### ISSUE TITLE
未识别的文件

### ISSUE THREAD

**Issue by zxb7500644** [pofey/movie_robot#1]
未识别的文件：
2022/02/11 18:08:19 - MainThread - ERROR: 识别不到影视信息，无法处理 查询词:["Ha
       rry Potter 1 Harry Potter and the Sorcerer's Stone", "Harry Potter 1 Harry Potte
       r and the Sorcerer's Stone", "Harry Potter 1 Harry Potter and the Sorcerer's Sto
       ne"] src: /nas/video/哈利波特1-8合集.Harry.Potter.8-Film.Collection.BluRay.2160p
       .HDR.x265.mUHD-FRDS/[Harry.Potter.1].Harry.Potter.and.the.Sorcerer's.Stone.2001.
       BluRay.2160p.HDR.x265.5Audios.mUHD-FRDS.mkv

2022/02/11 18:04:41 - MainThread - ERROR: 识别不到影视信息，无法处理 查询词:['Detective Conan Movie 01 The Time Bomb Skyscraper', 'Detective Conan Movie 01 TheTime Bomb Skyscraper', 'Detective Conan Movie 01 The Time Bomb Skyscraper'] src:                                                       /nas/video/Detective.Conan.Movie.22nd.Anniversary.Pack.1080p.BluRay.x265.10bit.TrueHD5.1EDW/Detective.Conan.Movie.01.The.Time.Bomb.Skyscraper.1997.1080p.BluRay.x265.10bit.TrueHD5.1-EDW.mkv

2022/02/11 18:04:46 - MainThread - ERROR: 识别不到影视信息，无法处理 查询词:['Detective Conan Movie 05 Count Down to Heaven', 'Detective Conan Movie 05 Count Down to Heaven', 'Detective Conan Movie 05 Count Down to Heaven'] src: /nas/video/                                                      Detective.Conan.Movie.22nd.Anniversary.Pack.1080p.BluRay.x265.10bit.TrueHD5.1-ED                                              W/Detective.Conan.Movie.05.Count.Down.to.Heaven.2001.1080p.BluRay.x265.10bit.TrueHD5.1-EDW.mkv

2022/02/11 18:05:00 - MainThread - ERROR: 识别不到影视信息，无法处理 查询词:['Detective Conan Movie 18 The Sniper from Another Dimension', 'Detective Conan Movie 18 The Sniper from Another Dimension', 'Detective Conan Movie 18 The Sniper fr                                                      om Another Dimension'] src: /nas/video/Detective.Conan.Movie.22nd.Anniversary.Pa                                                   ck.1080p.BluRay.x265.10bit.TrueHD5.1-EDW/Detective.Conan.Movie.18.The.Sniper.fro                                              m.Another.Dimension.2014.1080p.BluRay.x265.10bit.TrueHD5.1-EDW.mkv

2022/02/11 18:09:48 - MainThread - ERROR: 识别不到影视信息，无法处理 查询词:['Zack Snyders Justice League CD1', 'Zack Snyders Justice League CD1', 'Zack SnydersJustice League CD1'] src: /nas/video/Zack.Snyder's.Justice.League.2021.UHD.BluR                                                     ay.REMUX.2160p.HEVC.TrueHD7.1-HDS/Zack.Snyders.Justice.League.CD1.2021.UHD.BluRa                                                      y.REMUX.2160p.HEVC.TrueHD7.1-HDS.mkv

2022/02/11 18:09:49 - MainThread - ERROR: 识别不到影视信息，无法处理 查询词:['Zack Snyders Justice League CD2', 'Zack Snyders Justice League CD2', 'Zack SnydersJustice League CD2'] src: /nas/video/Zack.Snyder's.Justice.League.2021.UHD.BluR                                                      ay.REMUX.2160p.HEVC.TrueHD7.1-HDS/Zack.Snyders.Justice.League.CD2.2021.UHD.BluRa                                                      y.REMUX.2160p.HEVC.TrueHD7.1-HDS.mkv

2022/02/11 18:10:14 - MainThread - ERROR: 识别不到影视信息，无法处理 查询词:['ZOOTOPIA_', 'ZOOTOPIA_', 'ZOOTOPIA_'] src: /nas/video/疯狂动物城 Zootopia 2016 UHD Blu-ray 2160p HEVC TrueHD Atmos 7.1-Pete@HDSky/ZOOTOPIA_2016_UHD_BLU-RAY_2160.iso

2022/02/11 18:11:03 - MainThread - ERROR: 识别不到影视信息，无法处理 查询词:['Baby Drivers', 'Baby Drivers', 'Baby Drivers'] src: /nas/video/极盗车神.Baby.Drivers.2017.BluRay.2160p.x265.10bit.HDR.3Audio.mUHD-FRDS/Baby.Drivers.2017.BluRay.21                                                      60p.x265.10bit.HDR.3Audio.mUHD-FRDS.mkv

**Comment by zxb7500644** [comment]
碟中谍识别不准确::
2022/02/11 18:08:53 - MainThread - INFO: 已处理：碟中谍 (1996) 源路径: /nas/vide
       o/碟中谍.Mission.Impossible.BluRay.2160p.x265.10bit.HDR.mUHD-FRDS/碟中谍1.Missio
       n.Impossible.I.1996.BluRay.2160p.x265.10bit.HDR.2Audio.mUHD-FRDS/Mission.Impossi
       ble.1996.BluRay.2160p.x265.10bit.HDR.2Audios.mUHD-FRDS.mkv

022/02/11 18:08:55 - MainThread - INFO: 已处理：碟中谍 (1996) 源路径: /nas/vide
       o/碟中谍.Mission.Impossible.BluRay.2160p.x265.10bit.HDR.mUHD-FRDS/碟中谍2.Missio
       n.Impossible.II.2000.BluRay.2160p.x265.10bit.HDR.3Audio.mUHD-FRDS/Mission.Imposs
       ible.II.2000.BluRay.2160p.x265.10bit.HDR.3Audio.mUHD-FRDS.mkv

2022/02/11 18:08:57 - MainThread - INFO: 已处理：碟中谍2 (2000) 源路径: /nas/vid
       eo/碟中谍.Mission.Impossible.BluRay.2160p.x265.10bit.HDR.mUHD-FRDS/碟中谍3.Missi
       on.Impossible.III.2006.BluRay.2160p.x265.10bit.HDR.3Audio.mUHD-FRDS/Mission.Impo
       ssible.III.2006.BluRay.2160p.x265.10bit.HDR.3Audio.mUHD-FRDS.mkv

**Comment by zxb7500644** [comment]
电锯惊魂识别不准确::

2022/02/11 18:07:11 - MainThread - INFO: 已处理：电锯惊魂8：竖锯 (2017) 源路径:                                                                                                                                                                            /nas/video/Saw.2004 -2017.Collection.BluRay.1080p.x265.10bit.MNHD-FRDS/Jigsaw.20                                                                                                                                                                           17.BluRay.1080p.x265.10bit.MNHD-FRDS/Jigsaw.2017.BluRay.1080p.x265.10bit.MNHD-FR                                                                                                                                                                           DS.mkv
2022/02/11 18:07:16 - MainThread - INFO: 已处理：电锯惊魂 (2004) 源路径: /nas/vi                                                                                                                                                                           deo/Saw.2004 -2017.Collection.BluRay.1080p.x265.10bit.MNHD-FRDS/Saw.2004.BluRay.                                                                                                                                                                           1080p.x265.10bit.MNHD-FRDS/Saw.2004.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv
2022/02/11 18:07:21 - MainThread - INFO: 已处理：电锯惊魂 (2004) 源路径: /nas/vi                                                                                                                                                                           deo/Saw.2004 -2017.Collection.BluRay.1080p.x265.10bit.MNHD-FRDS/Saw.II.2005.BluR                                                                                                                                                                           ay.1080p.x265.10bit.MNHD-FRDS/Saw.II.2005.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv
2022/02/11 18:07:29 - MainThread - INFO: 已处理：电锯惊魂 (2004) 源路径: /nas/vi                                                                                                                                                                           deo/Saw.2004 -2017.Collection.BluRay.1080p.x265.10bit.MNHD-FRDS/Saw.III.2006.Blu                                                                                                                                                                           ray.1080p.x265.10bit.MNHD-FRDS/Saw.III.2006.Bluray.1080p.x265.10bit.MNHD-FRDS.mk                                                                                                                                                                           v
2022/02/11 18:07:38 - MainThread - INFO: 已处理：电锯惊魂 (2004) 源路径: /nas/vi                                                                                                                                                                           deo/Saw.2004 -2017.Collection.BluRay.1080p.x265.10bit.MNHD-FRDS/Saw.IV.2007.BluR                                                                                                                                                                           ay.1080p.x265.10bit.MNHD-FRDS/Saw.IV.2007.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv
2022/02/11 18:07:46 - MainThread - INFO: 已处理：电锯惊魂5 (2008) 源路径: /nas/v                                                                                                                                                                           ideo/Saw.2004 -2017.Collection.BluRay.1080p.x265.10bit.MNHD-FRDS/Saw.V.2008.BluR                                                                                                                                                                           ay.1080p.x265.10bit.MNHD-FRDS/Saw.V.2008.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv
2022/02/11 18:07:54 - MainThread - INFO: 已处理：电锯惊魂5 (2008) 源路径: /nas/v                                                                                                                                                                           ideo/Saw.2004 -2017.Collection.BluRay.1080p.x265.10bit.MNHD-FRDS/Saw.VI.2009.Blu                                                                                                                                                                           Ray.1080p.x265.10bit.MNHD-FRDS/Saw.VI.2009.BluRay.1080p.x265.10bit.MNHD-FRDS.mkv
2022/02/11 18:08:04 - MainThread - INFO: 已处理：电锯惊魂5 (2008) 源路径: /nas/v                                                                                                                                                                           ideo/Saw.2004 -2017.Collection.BluRay.1080p.x265.10bit.MNHD-FRDS/Saw.VII.2010.Bl                                                                                                                                                                           uRay.1080p.x265.10bit.MNHD-FRDS/Saw.VII.2010.BluRay.1080p.x265.10bit.MNHD-FRDS.m                                                                                                                                                                           kv

**Comment by zxb7500644** [comment]
已上只是部分，一个一个找太麻烦了。有的文件会直接跳过，既不显示处理 也不显示未处理的原因。最终320个文件成功识别240个。

**Comment by mjyhj** [comment]
> 已上只是部分，一个一个找太麻烦了。有的文件会直接跳过，既不显示处理 也不显示未处理的原因。最终320个文件成功识别240个。

最后全部错的发出来，让作者优化提高识别率

**Comment by suwill** [comment]
> 已上只是部分，一个一个找太麻烦了。有的文件会直接跳过，既不显示处理 也不显示未处理的原因。最终320个文件成功识别240个。

cat xxx.log | grep ERROR
