### ISSUE TITLE
是否提供1080P压制作品的筛选方案

### ISSUE THREAD

**Issue by Duan-rax** [pofey/movie_robot#1]
硬盘并不够大，另外emby对原盘支持并不是很好，因此问下作者是否提供1080P分辨率下，压制作品的筛选方案

**Comment by pofey** [comment]
可以通过调整torrent_scoring.py的类型分值，设定加权关键字，可以调出符合你期望的最佳种子。

**Comment by jsdfhasuh** [comment]
作者现在拥有什么邀请了，需要柠檬邀请吗
