### ISSUE TITLE
从hdchina无法筛选出种子，即使有很多符合的，最终筛选不出来

### ISSUE THREAD

**Issue by icefire61** [pofey/movie_robot#10]
剧集方面：
手动搜索国王排名：
![image](https://user-images.githubusercontent.com/56681195/153882424-8487c756-05a0-438a-af3b-16938b0af167.png)
结果有很多个，而且剧集从第1集到17集齐全，但是下载时却是从另外两个网站下载的，并且最终第14/15集没有下载到；
![国王排名](https://user-images.githubusercontent.com/56681195/153883151-dd3102a7-9347-4096-ad28-3fe682b872ce.png)

电影方面：
手动搜索新生化危机：
![生化](https://user-images.githubusercontent.com/56681195/153883361-61e8a0aa-13a8-416b-82e2-e9cb3a96a36b.png)
可以看到资源也是挺多的，当时经过机器人筛选后1个都没下载
![筛选后](https://user-images.githubusercontent.com/56681195/153883544-a1748b59-4d4d-4e58-96ab-e5feb7c52e9e.png)

以上使用的都是默认选种规则compress

**Comment by pofey** [comment]
升级到最新的216V6版本试一下

**Comment by pofey** [comment]
升级217v8吧，新版优先使用imdbid在pt站搜索，会忽略掉年份校验
