### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by ciweiyoushang** [pofey/movie_robot#102]
目前在机器人下载记录里面删除下载视频后，会同时删除种子原文件，和硬链接文件，emby媒体库文件
问题是下载视频多了以后，删除之前下载的视频在机器人下载记录就非常不好找。
需求:如果可以主动删除emby视频，随后同时删除原种子文件和硬链接文件就更加方便了
这样更符合日常删除文件的习惯

**Comment by pofey** [comment]
emby删除，整理硬链接后的文件自己会没的。
种子文件想删，定时清理也解决需求。
