### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by IvanSolis1989** [pofey/movie_robot#103]
当前版本：0.8.5
当前删除硬连接和qb及订阅必须在机器人操作。这个比较反常规使用习惯。
根据用户使用习惯及更加方便的考虑，建议增加媒体服务器（emby、jellyfin、plex）端内删除影片，机器人联动删除订阅和源QB种子及下载文件。看到一个很垃圾的片想立马删了，竟然还要跳到另一个app去删除。是不是很气气？

**Comment by pofey** [comment]
重复问题
