### ISSUE TITLE
日志报错，0.8.5版本，Docker安装

### ISSUE THREAD

**Issue by starkiller43** [pofey/movie_robot#104]
s2022/05/11 09:01:02 - ThreadPoolExecutor-0_0 - INFO: 有3个免费种子需要下载，开始提交到下载器。
]2022/05/11 09:01:02 - ThreadPoolExecutor-0_0 - INFO: 免费种子提交下载队列完成。
�2022/05/11 09:01:02 - DownloadConsumer - INFO: 开始处理免费种子下载任务: [hddolby]Sheng Sheng Bu xi 2022 S01E03 1080p WEB-DL AVC AAC-QHstudIo
�2022/05/11 09:01:03 - DownloadConsumer - INFO: 开始处理免费种子下载任务: [hddolby]Slmmer Down 2022 S01E30-E32.1080p WEB-DL AVC AAC-QHstudIo
�2022/05/11 09:01:08 - SubConsumer - ERROR: 处理订阅消息出错：RetryError[]
#Traceback (most recent call last):
C  File "/dependencies/tenacity/__init__.py", line 407, in __call__
!    result = fn(*args, **kwargs)
`  File "yee/consumer/subconsumer.py", line 285, in yee.consumer.subconsumer.SubConsumer.get_sub
f  File "yee/models/subscribemodel.py", line 82, in yee.models.subscribemodel.SubscribeModel.get_by_id
D  File "/dependencies/sqlalchemy/orm/query.py", line 2819, in first
)    return self.limit(1)._iter().first()
D  File "/dependencies/sqlalchemy/orm/query.py", line 2903, in _iter
#    result = self.session.execute(
H  File "/dependencies/sqlalchemy/orm/session.py", line 1695, in execute
+    conn = self._connection_for_bind(bind)
U  File "/dependencies/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind
3    return self._transaction._connection_for_bind(
T  File "/dependencies/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
N  File "/dependencies/sqlalchemy/orm/session.py", line 601, in _assert_active
'    raise sa_exc.PendingRollbackError(
usqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: UPDATE statement on table 'subscribe' expected to update 1 row(s); 0 were matched. (Background on this error at: https://sqlalche.me/e/14/7s2a)

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
\  File "yee/consumer/subconsumer.py", line 291, in yee.consumer.subconsumer.SubConsumer.run
D  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
     return self(f, *args, **kw)
C  File "/dependencies/tenacity/__init__.py", line 404, in __call__
,    do = self.iter(retry_state=retry_state)
?  File "/dependencies/tenacity/__init__.py", line 361, in iter
)    raise retry_exc from fut.exception()
gtenacity.RetryError: RetryError[]
�2022/05/11 09:01:14 - SubConsumer - ERROR: 处理订阅消息出错：RetryError[]
#Traceback (most recent call last):
C  File "/dependencies/tenacity/__init__.py", line 407, in __call__
!    result = fn(*args, **kwargs)
`  File "yee/consumer/subconsumer.py", line 285, in yee.consumer.subconsumer.SubConsumer.get_sub
f  File "yee/models/subscribemodel.py", line 82, in yee.models.subscribemodel.SubscribeModel.get_by_id
D  File "/dependencies/sqlalchemy/orm/query.py", line 2819, in first
)    return self.limit(1)._iter().first()
D  File "/dependencies/sqlalchemy/orm/query.py", line 2903, in _iter
#    result = self.session.execute(
H  File "/dependencies/sqlalchemy/orm/session.py", line 1695, in execute
+    conn = self._connection_for_bind(bind)
U  File "/dependencies/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind
3    return self._transaction._connection_for_bind(
T  File "/dependencies/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
N  File "/dependencies/sqlalchemy/orm/session.py", line 601, in _assert_active
'    raise sa_exc.PendingRollbackError(
usqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: UPDATE statement on table 'subscribe' expected to update 1 row(s); 0 were matched. (Background on this error at: https://sqlalche.me/e/14/7s2a)

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
\  File "yee/consumer/subconsumer.py", line 291, in yee.consumer.subconsumer.SubConsumer.run
D  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
     return self(f, *args, **kw)
C  File "/dependencies/tenacity/__init__.py", line 404, in __call__
,    do = self.iter(retry_state=retry_state)
?  File "/dependencies/tenacity/__init__.py", line 361, in iter
)    raise retry_exc from fut.exception()
gtenacity.RetryError: RetryError[]
�2022/05/11 09:01:20 - SubConsumer - ERROR: 处理订阅消息出错：RetryError[]
#Traceback (most recent call last):
C  File "/dependencies/tenacity/__init__.py", line 407, in __call__
!    result = fn(*args, **kwargs)
`  File "yee/consumer/subconsumer.py", line 285, in yee.consumer.subconsumer.SubConsumer.get_sub
f  File "yee/models/subscribemodel.py", line 82, in yee.models.subscribemodel.SubscribeModel.get_by_id
D  File "/dependencies/sqlalchemy/orm/query.py", line 2819, in first
)    return self.limit(1)._iter().first()
D  File "/dependencies/sqlalchemy/orm/query.py", line 2903, in _iter
#    result = self.session.execute(
H  File "/dependencies/sqlalchemy/orm/session.py", line 1695, in execute
+    conn = self._connection_for_bind(bind)
U  File "/dependencies/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind
3    return self._transaction._connection_for_bind(
T  File "/dependencies/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
N  File "/dependencies/sqlalchemy/orm/session.py", line 601, in _assert_active
'    raise sa_exc.PendingRollbackError(
usqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: UPDATE statement on table 'subscribe' expected to update 1 row(s); 0 were matched. (Background on this error at: https://sqlalche.me/e/14/7s2a)

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
\  File "yee/consumer/subconsumer.py", line 291, in yee.consumer.subconsumer.SubConsumer.run
D  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
     return self(f, *args, **kw)
C  File "/dependencies/tenacity/__init__.py", line 404, in __call__
,    do = self.iter(retry_state=retry_state)
?  File "/dependencies/tenacity/__init__.py", line 361, in iter
)    raise retry_exc from fut.exception()
gtenacity.RetryError: RetryError[]
�2022/05/11 09:01:26 - SubConsumer - ERROR: 处理订阅消息出错：RetryError[]
#Traceback (most recent call last):
C  File "/dependencies/tenacity/__init__.py", line 407, in __call__
!    result = fn(*args, **kwargs)
`  File "yee/consumer/subconsumer.py", line 285, in yee.consumer.subconsumer.SubConsumer.get_sub
f  File "yee/models/subscribemodel.py", line 82, in yee.models.subscribemodel.SubscribeModel.get_by_id
D  File "/dependencies/sqlalchemy/orm/query.py", line 2819, in first
)    return self.limit(1)._iter().first()
D  File "/dependencies/sqlalchemy/orm/query.py", line 2903, in _iter
#    result = self.session.execute(
H  File "/dependencies/sqlalchemy/orm/session.py", line 1695, in execute
+    conn = self._connection_for_bind(bind)
U  File "/dependencies/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind
3    return self._transaction._connection_for_bind(
T  File "/dependencies/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
N  File "/dependencies/sqlalchemy/orm/session.py", line 601, in _assert_active
'    raise sa_exc.PendingRollbackError(
usqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: UPDATE statement on table 'subscribe' expected to update 1 row(s); 0 were matched. (Background on this error at: https://sqlalche.me/e/14/7s2a)

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
\  File "yee/consumer/subconsumer.py", line 291, in yee.consumer.subconsumer.SubConsumer.run
D  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
     return self(f, *args, **kw)
C  File "/dependencies/tenacity/__init__.py", line 404, in __call__
,    do = self.iter(retry_state=retry_state)
?  File "/dependencies/tenacity/__init__.py", line 361, in iter
)    raise retry_exc from fut.exception()
gtenacity.RetryError: RetryError[]
�2022/05/11 09:01:32 - SubConsumer - ERROR: 处理订阅消息出错：RetryError[]
#Traceback (most recent call last):
C  File "/dependencies/tenacity/__init__.py", line 407, in __call__
!    result = fn(*args, **kwargs)
`  File "yee/consumer/subconsumer.py", line 285, in yee.consumer.subconsumer.SubConsumer.get_sub
f  File "yee/models/subscribemodel.py", line 82, in yee.models.subscribemodel.SubscribeModel.get_by_id
D  File "/dependencies/sqlalchemy/orm/query.py", line 2819, in first
)    return self.limit(1)._iter().first()
D  File "/dependencies/sqlalchemy/orm/query.py", line 2903, in _iter
#    result = self.session.execute(
H  File "/dependencies/sqlalchemy/orm/session.py", line 1695, in execute
+    conn = self._connection_for_bind(bind)
U  File "/dependencies/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind
3    return self._transaction._connection_for_bind(
T  File "/dependencies/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
N  File "/dependencies/sqlalchemy/orm/session.py", line 601, in _assert_active
'    raise sa_exc.PendingRollbackError(
usqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: UPDATE statement on table 'subscribe' expected to update 1 row(s); 0 were matched. (Background on this error at: https://sqlalche.me/e/14/7s2a)

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
\  File "yee/consumer/subconsumer.py", line 291, in yee.consumer.subconsumer.SubConsumer.run
D  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
     return self(f, *args, **kw)
C  File "/dependencies/tenacity/__init__.py", line 404, in __call__
,    do = self.iter(retry_state=retry_state)
?  File "/dependencies/tenacity/__init__.py", line 361, in iter
)    raise retry_exc from fut.exception()
gtenacity.RetryError: RetryError[]
�2022/05/11 09:01:38 - SubConsumer - ERROR: 处理订阅消息出错：RetryError[]
#Traceback (most recent call last):
C  File "/dependencies/tenacity/__init__.py", line 407, in __call__
!    result = fn(*args, **kwargs)
`  File "yee/consumer/subconsumer.py", line 285, in yee.consumer.subconsumer.SubConsumer.get_sub
f  File "yee/models/subscribemodel.py", line 82, in yee.models.subscribemodel.SubscribeModel.get_by_id
D  File "/dependencies/sqlalchemy/orm/query.py", line 2819, in first
)    return self.limit(1)._iter().first()
D  File "/dependencies/sqlalchemy/orm/query.py", line 2903, in _iter
#    result = self.session.execute(
H  File "/dependencies/sqlalchemy/orm/session.py", line 1695, in execute
+    conn = self._connection_for_bind(bind)
U  File "/dependencies/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind
3    return self._transaction._connection_for_bind(
T  File "/dependencies/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
N  File "/dependencies/sqlalchemy/orm/session.py", line 601, in _assert_active
'    raise sa_exc.PendingRollbackError(
usqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: UPDATE statement on table 'subscribe' expected to update 1 row(s); 0 were matched. (Background on this error at: https://sqlalche.me/e/14/7s2a)

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
\  File "yee/consumer/subconsumer.py", line 291, in yee.consumer.subconsumer.SubConsumer.run
D  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
     return self(f, *args, **kw)
C  File "/dependencies/tenacity/__init__.py", line 404, in __call__
,    do = self.iter(retry_state=retry_state)
?  File "/dependencies/tenacity/__init__.py", line 361, in iter
)    raise retry_exc from fut.exception()
gtenacity.RetryError: RetryError[]
�2022/05/11 09:01:44 - SubConsumer - ERROR: 处理订阅消息出错：RetryError[]
#Traceback (most recent call last):
C  File "/dependencies/tenacity/__init__.py", line 407, in __call__
!    result = fn(*args, **kwargs)
`  File "yee/consumer/subconsumer.py", line 285, in yee.consumer.subconsumer.SubConsumer.get_sub
f  File "yee/models/subscribemodel.py", line 82, in yee.models.subscribemodel.SubscribeModel.get_by_id
D  File "/dependencies/sqlalchemy/orm/query.py", line 2819, in first
)    return self.limit(1)._iter().first()
D  File "/dependencies/sqlalchemy/orm/query.py", line 2903, in _iter
#    result = self.session.execute(
H  File "/dependencies/sqlalchemy/orm/session.py", line 1695, in execute
+    conn = self._connection_for_bind(bind)
U  File "/dependencies/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind
3    return self._transaction._connection_for_bind(
T  File "/dependencies/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
N  File "/dependencies/sqlalchemy/orm/session.py", line 601, in _assert_active
'    raise sa_exc.PendingRollbackError(
usqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: UPDATE statement on table 'subscribe' expected to update 1 row(s); 0 were matched. (Background on this error at: https://sqlalche.me/e/14/7s2a)

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
\  File "yee/consumer/subconsumer.py", line 291, in yee.consumer.subconsumer.SubConsumer.run
D  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
     return self(f, *args, **kw)
C  File "/dependencies/tenacity/__init__.py", line 404, in __call__
,    do = self.iter(retry_state=retry_state)
?  File "/dependencies/tenacity/__init__.py", line 361, in iter
)    raise retry_exc from fut.exception()
gtenacity.RetryError: RetryError[]
�2022/05/11 09:01:50 - SubConsumer - ERROR: 处理订阅消息出错：RetryError[]
#Traceback (most recent call last):
C  File "/dependencies/tenacity/__init__.py", line 407, in __call__
!    result = fn(*args, **kwargs)
`  File "yee/consumer/subconsumer.py", line 285, in yee.consumer.subconsumer.SubConsumer.get_sub
f  File "yee/models/subscribemodel.py", line 82, in yee.models.subscribemodel.SubscribeModel.get_by_id
D  File "/dependencies/sqlalchemy/orm/query.py", line 2819, in first
)    return self.limit(1)._iter().first()
D  File "/dependencies/sqlalchemy/orm/query.py", line 2903, in _iter
#    result = self.session.execute(
H  File "/dependencies/sqlalchemy/orm/session.py", line 1695, in execute
+    conn = self._connection_for_bind(bind)
U  File "/dependencies/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind
3    return self._transaction._connection_for_bind(
T  File "/dependencies/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
N  File "/dependencies/sqlalchemy/orm/session.py", line 601, in _assert_active
'    raise sa_exc.PendingRollbackError(
usqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: UPDATE statement on table 'subscribe' expected to update 1 row(s); 0 were matched. (Background on this error at: https://sqlalche.me/e/14/7s2a)

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
\  File "yee/consumer/subconsumer.py", line 291, in yee.consumer.subconsumer.SubConsumer.run
D  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
     return self(f, *args, **kw)
C  File "/dependencies/tenacity/__init__.py", line 404, in __call__
,    do = self.iter(retry_state=retry_state)
?  File "/dependencies/tenacity/__init__.py", line 361, in iter
)    raise retry_exc from fut.exception()
gtenacity.RetryError: RetryError[]
�2022/05/11 09:01:56 - SubConsumer - ERROR: 处理订阅消息出错：RetryError[]
#Traceback (most recent call last):
C  File "/dependencies/tenacity/__init__.py", line 407, in __call__
!    result = fn(*args, **kwargs)
`  File "yee/consumer/subconsumer.py", line 285, in yee.consumer.subconsumer.SubConsumer.get_sub
f  File "yee/models/subscribemodel.py", line 82, in yee.models.subscribemodel.SubscribeModel.get_by_id
D  File "/dependencies/sqlalchemy/orm/query.py", line 2819, in first
)    return self.limit(1)._iter().first()
D  File "/dependencies/sqlalchemy/orm/query.py", line 2903, in _iter
#    result = self.session.execute(
H  File "/dependencies/sqlalchemy/orm/session.py", line 1695, in execute
+    conn = self._connection_for_bind(bind)
U  File "/dependencies/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind
3    return self._transaction._connection_for_bind(
T  File "/dependencies/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
N  File "/dependencies/sqlalchemy/orm/session.py", line 601, in _assert_active
'    raise sa_exc.PendingRollbackError(
usqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: UPDATE statement on table 'subscribe' expected to update 1 row(s); 0 were matched. (Background on this error at: https://sqlalche.me/e/14/7s2a)

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
\  File "yee/consumer/subconsumer.py", line 291, in yee.consumer.subconsumer.SubConsumer.run
D  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
     return self(f, *args, **kw)
C  File "/dependencies/tenacity/__init__.py", line 404, in __call__
,    do = self.iter(retry_state=retry_state)
?  File "/dependencies/tenacity/__init__.py", line 361, in iter
)    raise retry_exc from fut.exception()
gtenacity.RetryError: RetryError[]
�2022/05/11 09:02:02 - SubConsumer - ERROR: 处理订阅消息出错：RetryError[]
#Traceback (most recent call last):
C  File "/dependencies/tenacity/__init__.py", line 407, in __call__
!    result = fn(*args, **kwargs)
`  File "yee/consumer/subconsumer.py", line 285, in yee.consumer.subconsumer.SubConsumer.get_sub
f  File "yee/models/subscribemodel.py", line 82, in yee.models.subscribemodel.SubscribeModel.get_by_id
D  File "/dependencies/sqlalchemy/orm/query.py", line 2819, in first
)    return self.limit(1)._iter().first()
D  File "/dependencies/sqlalchemy/orm/query.py", line 2903, in _iter
#    result = self.session.execute(
H  File "/dependencies/sqlalchemy/orm/session.py", line 1695, in execute
+    conn = self._connection_for_bind(bind)
U  File "/dependencies/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind
3    return self._transaction._connection_for_bind(
T  File "/dependencies/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
N  File "/dependencies/sqlalchemy/orm/session.py", line 601, in _assert_active
'    raise sa_exc.PendingRollbackError(
usqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: UPDATE statement on table 'subscribe' expected to update 1 row(s); 0 were matched. (Background on this error at: https://sqlalche.me/e/14/7s2a)

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
\  File "yee/consumer/subconsumer.py", line 291, in yee.consumer.subconsumer.SubConsumer.run
D  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
     return self(f, *args, **kw)
C  File "/dependencies/tenacity/__init__.py", line 404, in __call__
,    do = self.iter(retry_state=retry_state)
?  File "/dependencies/tenacity/__init__.py", line 361, in iter
)    raise retry_exc from fut.exception()
gtenacity.RetryError: RetryError[]
�2022/05/11 09:02:08 - SubConsumer - ERROR: 处理订阅消息出错：RetryError[]
#Traceback (most recent call last):
C  File "/dependencies/tenacity/__init__.py", line 407, in __call__
!    result = fn(*args, **kwargs)
`  File "yee/consumer/subconsumer.py", line 285, in yee.consumer.subconsumer.SubConsumer.get_sub
f  File "yee/models/subscribemodel.py", line 82, in yee.models.subscribemodel.SubscribeModel.get_by_id
D  File "/dependencies/sqlalchemy/orm/query.py", line 2819, in first
)    return self.limit(1)._iter().first()
D  File "/dependencies/sqlalchemy/orm/query.py", line 2903, in _iter
#    result = self.session.execute(
H  File "/dependencies/sqlalchemy/orm/session.py", line 1695, in execute
+    conn = self._connection_for_bind(bind)
U  File "/dependencies/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind
3    return self._transaction._connection_for_bind(
T  File "/dependencies/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
N  File "/dependencies/sqlalchemy/orm/session.py", line 601, in _assert_active
'    raise sa_exc.PendingRollbackError(
usqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: UPDATE statement on table 'subscribe' expected to update 1 row(s); 0 were matched. (Background on this error at: https://sqlalche.me/e/14/7s2a)

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
\  File "yee/consumer/subconsumer.py", line 291, in yee.consumer.subconsumer.SubConsumer.run
D  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
     return self(f, *args, **kw)
C  File "/dependencies/tenacity/__init__.py", line 404, in __call__
,    do = self.iter(retry_state=retry_state)
?  File "/dependencies/tenacity/__init__.py", line 361, in iter
)    raise retry_exc from fut.exception()
gtenacity.RetryError: RetryError[]
�2022/05/11 09:02:14 - SubConsumer - ERROR: 处理订阅消息出错：RetryError[]
#Traceback (most recent call last):
C  File "/dependencies/tenacity/__init__.py", line 407, in __call__
!    result = fn(*args, **kwargs)
`  File "yee/consumer/subconsumer.py", line 285, in yee.consumer.subconsumer.SubConsumer.get_sub
f  File "yee/models/subscribemodel.py", line 82, in yee.models.subscribemodel.SubscribeModel.get_by_id
D  File "/dependencies/sqlalchemy/orm/query.py", line 2819, in first
)    return self.limit(1)._iter().first()
D  File "/dependencies/sqlalchemy/orm/query.py", line 2903, in _iter
#    result = self.session.execute(
H  File "/dependencies/sqlalchemy/orm/session.py", line 1695, in execute
+    conn = self._connection_for_bind(bind)
U  File "/dependencies/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind
3    return self._transaction._connection_for_bind(
T  File "/dependencies/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
N  File "/dependencies/sqlalchemy/orm/session.py", line 601, in _assert_active
'    raise sa_exc.PendingRollbackError(
usqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: UPDATE statement on table 'subscribe' expected to update 1 row(s); 0 were matched. (Background on this error at: https://sqlalche.me/e/14/7s2a)

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
\  File "yee/consumer/subconsumer.py", line 291, in yee.consumer.subconsumer.SubConsumer.run
D  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
     return self(f, *args, **kw)
C  File "/dependencies/tenacity/__init__.py", line 404, in __call__
,    do = self.iter(retry_state=retry_state)
?  File "/dependencies/tenacity/__init__.py", line 361, in iter
)    raise retry_exc from fut.exception()
gtenacity.RetryError: RetryError[]
�2022/05/11 09:02:20 - SubConsumer - ERROR: 处理订阅消息出错：RetryError[]
#Traceback (most recent call last):
C  File "/dependencies/tenacity/__init__.py", line 407, in __call__
!    result = fn(*args, **kwargs)
`  File "yee/consumer/subconsumer.py", line 285, in yee.consumer.subconsumer.SubConsumer.get_sub
f  File "yee/models/subscribemodel.py", line 82, in yee.models.subscribemodel.SubscribeModel.get_by_id
D  File "/dependencies/sqlalchemy/orm/query.py", line 2819, in first
)    return self.limit(1)._iter().first()
D  File "/dependencies/sqlalchemy/orm/query.py", line 2903, in _iter
#    result = self.session.execute(
H  File "/dependencies/sqlalchemy/orm/session.py", line 1695, in execute
+    conn = self._connection_for_bind(bind)
U  File "/dependencies/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind
3    return self._transaction._connection_for_bind(
T  File "/dependencies/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
N  File "/dependencies/sqlalchemy/orm/session.py", line 601, in _assert_active
'    raise sa_exc.PendingRollbackError(
usqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: UPDATE statement on table 'subscribe' expected to update 1 row(s); 0 were matched. (Background on this error at: https://sqlalche.me/e/14/7s2a)

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
\  File "yee/consumer/subconsumer.py", line 291, in yee.consumer.subconsumer.SubConsumer.run
D  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
     return self(f, *args, **kw)
C  File "/dependencies/tenacity/__init__.py", line 404, in __call__
,    do = self.iter(retry_state=retry_state)
?  File "/dependencies/tenacity/__init__.py", line 361, in iter
)    raise retry_exc from fut.exception()
gtenacity.RetryError: RetryError[]
�2022/05/11 09:02:26 - SubConsumer - ERROR: 处理订阅消息出错：RetryError[]
#Traceback (most recent call last):
C  File "/dependencies/tenacity/__init__.py", line 407, in __call__
!    result = fn(*args, **kwargs)
`  File "yee/consumer/subconsumer.py", line 285, in yee.consumer.subconsumer.SubConsumer.get_sub
f  File "yee/models/subscribemodel.py", line 82, in yee.models.subscribemodel.SubscribeModel.get_by_id
D  File "/dependencies/sqlalchemy/orm/query.py", line 2819, in first
)    return self.limit(1)._iter().first()
D  File "/dependencies/sqlalchemy/orm/query.py", line 2903, in _iter
#    result = self.session.execute(
H  File "/dependencies/sqlalchemy/orm/session.py", line 1695, in execute
+    conn = self._connection_for_bind(bind)
U  File "/dependencies/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind
3    return self._transaction._connection_for_bind(
T  File "/dependencies/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
N  File "/dependencies/sqlalchemy/orm/session.py", line 601, in _assert_active
'    raise sa_exc.PendingRollbackError(
usqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: UPDATE statement on table 'subscribe' expected to update 1 row(s); 0 were matched. (Background on this error at: https://sqlalche.me/e/14/7s2a)

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
\  File "yee/consumer/subconsumer.py", line 291, in yee.consumer.subconsumer.SubConsumer.run
D  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
     return self(f, *args, **kw)
C  File "/dependencies/tenacity/__init__.py", line 404, in __call__
,    do = self.iter(retry_state=retry_state)
?  File "/dependencies/tenacity/__init__.py", line 361, in iter
)    raise retry_exc from fut.exception()
gtenacity.RetryError: RetryError[]
�2022/05/11 09:02:32 - SubConsumer - ERROR: 处理订阅消息出错：RetryError[]
#Traceback (most recent call last):
C  File "/dependencies/tenacity/__init__.py", line 407, in __call__
!    result = fn(*args, **kwargs)
`  File "yee/consumer/subconsumer.py", line 285, in yee.consumer.subconsumer.SubConsumer.get_sub
f  File "yee/models/subscribemodel.py", line 82, in yee.models.subscribemodel.SubscribeModel.get_by_id
D  File "/dependencies/sqlalchemy/orm/query.py", line 2819, in first
)    return self.limit(1)._iter().first()
D  File "/dependencies/sqlalchemy/orm/query.py", line 2903, in _iter
#    result = self.session.execute(
H  File "/dependencies/sqlalchemy/orm/session.py", line 1695, in execute
+    conn = self._connection_for_bind(bind)
U  File "/dependencies/sqlalchemy/orm/session.py", line 1536, in _connection_for_bind
3    return self._transaction._connection_for_bind(
T  File "/dependencies/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
N  File "/dependencies/sqlalchemy/orm/session.py", line 601, in _assert_active
'    raise sa_exc.PendingRollbackError(
usqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: UPDATE statement on table 'subscribe' expected to update 1 row(s); 0 were matched. (Background on this error at: https://sqlalche.me/e/14/7s2a)

EThe above exception was the direct cause of the following exception:

#Traceback (most recent call last):
\  File "yee/consumer/subconsumer.py", line 291, in yee.consumer.subconsumer.SubConsumer.run
D  File "/dependencies/tenacity/__init__.py", line 324, in wrapped_f
     return self(f, *args, **kw)
C  File "/dependencies/tenacity/__init__.py", line 404, in __call__
,    do = self.iter(retry_state=retry_state)
?  File "/dependencies/tenacity/__init__.py", line 361, in iter
)    raise retry_exc from fut.exception()
gtenacity.RetryError: RetryError[]

**Comment by pofey** [comment]
卡io导致本地数据库操作失败，把机器人配置目录换到io稳定的存储区吧，ssd最好
