### ISSUE TITLE
【需求】不可说添加失败，希望增加皇后站，谢谢

### ISSUE THREAD

**Issue by Potato501** [pofey/movie_robot#106]
大神您好，请教一下：

1、我用edge浏览器在控制台输入 `document.cookie` 得到的“不可说”站点的cookie，无法在软件内成功添加该站点，提示“信息配置出错”，也没有看到有效的log，目前是最新的0.8.5版本，请教这个是软件本身问题还是我获取到的cookie信息不对，现在得到的cookie是类似这样的：

__utmz=37122914.1621340222.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmc=37122914; __utma=37122914.207223334.1651820222.1652212390.1652287293.8; __utmb=37122914.9.10.168548793

2、同时也希望增加皇后的支持

最后，感谢开发好用的工具。

**Comment by pofey** [comment]
还是按wiki中给出的方法，或网上的教程，获得ck

**Comment by Potato501** [comment]
手动拼接SPRINGID=xxxx好了，谢谢大神回复。
