### ISSUE TITLE
剧名部分匹配导致匹配错误

### ISSUE THREAD

**Issue by Skyline0503** [pofey/movie_robot#11]
豆瓣标记：鬼灭之刃 游郭篇(https://movie.douban.com/subject/34813210)
PLEX内已下载：鬼灭之刃 （https://movie.douban.com/subject/30210221）
movie_robot判断剧集已存在跳过了下载
INFO: 鬼灭之刃(2021)在影视库为剧集，总共11集全部存在

推测文件名部分包含了鬼灭之刃，模糊搜索导致可以被匹配上。同时PLEX获取到的年份也是错误的，PLEX内查看鬼灭之刃的年份是2019，INFO显示是2021.

**Comment by mjyhj** [comment]
> 豆瓣标记：鬼灭之刃 游郭篇(https://movie.douban.com/subject/34813210) PLEX内已下载：鬼灭之刃 （[https://movie.douban.com/subject/30210221）](https://movie.douban.com/subject/30210221%EF%BC%89) movie_robot判断剧集已存在跳过了下载 INFO: 鬼灭之刃(2021)在影视库为剧集，总共11集全部存在
> 
> 推测文件名部分包含了鬼灭之刃，模糊搜索导致可以被匹配上。同时PLEX获取到的年份也是错误的，PLEX内查看鬼灭之刃的年份是2019，INFO显示是2021.

这里的2021 是 游郭篇这一季的，而父路径那里只会用第一季来命名整理

**Comment by Skyline0503** [comment]
> > 豆瓣标记：鬼灭之刃 游郭篇(https://movie.douban.com/subject/34813210) PLEX内已下载：鬼灭之刃 （[https://movie.douban.com/subject/30210221）](https://movie.douban.com/subject/30210221%EF%BC%89) movie_robot判断剧集已存在跳过了下载 INFO: 鬼灭之刃(2021)在影视库为剧集，总共11集全部存在
> > 推测文件名部分包含了鬼灭之刃，模糊搜索导致可以被匹配上。同时PLEX获取到的年份也是错误的，PLEX内查看鬼灭之刃的年份是2019，INFO显示是2021.
> 
> 这里的2021 是 游郭篇这一季的，而父路径那里只会用第一季来命名整理

是否可以通过tmdb先进行季的匹配，比如鬼灭之刃 游郭篇在tmdb是可以对应到相应的季的（https://www.themoviedb.org/tv/85937/seasons/3）
