### ISSUE TITLE
关于养站的想法

### ISSUE THREAD

**Issue by clouis414** [pofey/movie_robot#114]
首先我理解作者只做少部分pt站点的适配，首先我手头上站点不多（馒头，葡萄，天空，阿童木，我堡，彩虹岛，学校，高清杜比，以及一些小站），开启使用养站功能后，只有少部分小站（高清杜比，阿童木）能拉取到资源，进行上传养站，大站可以说能养的微乎其微。既然有养站这种好功能，个人认为，多支持一些小站点，也不是未尝不可。更希望是作者制作出是配的文件，毕竟不是每个人都是大佬，可以肆意下载馒头，彩虹岛，天空这些资源。毕竟订阅的影视大多都来自这些站点下载，然而养站对这些大站并不友好。个人一些想法，作者看过后麻烦不要嫌弃，也是自己使用下来的感受。

**Comment by pofey** [comment]
![6D7B753A-034C-4499-AF62-D6BA72A74F1F](https://user-images.githubusercontent.com/1396975/168240178-cdbe34f1-9eac-4dc0-baca-42694b59f560.jpeg)
我的使用感受与你不同 反而大站养的最欢
