### ISSUE TITLE
【BUG】过滤器保留关键字或排除关键字不生效

### ISSUE THREAD

**Issue by neroxps** [pofey/movie_robot#115]
# 环境概述
- **movie_robot 版本**：0.9.3
- **部署方式**：OpenMediAvault(debian 11) + Docker 部署
- **TMDB 链接情况**：可用
- **默认智能下载的选种策略**：compress
- **链接的 PT 站点**：
  - 馒头
  - 听歌歌

# 故障描述
我期望订阅《声生不息》（湖南卫视版本）操作如下
1. 搜索获得《声生不息》
2. 点击【订阅】
3. 选择【独立设置过滤器】
4. 点击【更多过滤规则】
5. 在【保留包含特定关键字的结果】输入 【HNTV】
6. 【保留包含特定关键字的结果】还尝试过以下关键字
    - HNTV
    - 湖南卫视
7. 也尝试过清除【保留包含特定关键字的结果】，设置【排除包含特定关键字的结果】为以下关键字：
    - TVB
    - 翡翠台

以上配置均无法过滤到有效的下载内容

## 过滤器配置截图
![过滤器截图1](https://user-images.githubusercontent.com/8503224/168231579-469b816f-f198-4a23-a60c-cd1a1a2d1603.png)
![过滤器截图2](https://user-images.githubusercontent.com/8503224/168231646-6c2bb3fb-27e0-4de2-b23b-9fd049c02ba3.png)

## 日志内容
```
movie-robot    | 2022/05/13 15:11:26 - SubRequestConsumer - INFO: 声生不息(2022) 设置了独立的过滤规则，可以在我的订阅中查看和修改。
movie-robot    | 2022/05/13 15:11:26 - SubRequestConsumer - INFO: 新增来自admin的订阅: 声生不息(2022)
movie-robot    | 2022/05/13 15:11:26 - SubConsumer - INFO: 已经开始在站点: 馒头,听听歌 搜索: Infinity and Beyond,声生不息
movie-robot    | 2022/05/13 15:11:26 - SubConsumer - INFO: 已开启网络异常重试机制，最多可能等待15分钟。
movie-robot    | 2022/05/13 15:11:41 - SubConsumer - INFO: 共在2个站点搜索到15条结果，其中听听歌最慢，耗费14.39秒
movie-robot    | 2022/05/13 15:11:41 - SubConsumer - INFO: 声生不息(2022) 已经有搜索结果，但经过你设定的过滤器后，无任何结果。
```

### 馒头搜索截图
![image](https://user-images.githubusercontent.com/8503224/168231876-879eea7f-a046-45a8-813b-e592617a945a.png)
### 听歌歌搜索截图
![image](https://user-images.githubusercontent.com/8503224/168231939-5061fcd2-25d9-4077-9641-a1b7f5eb11c7.png)

# 需求
期望将规则过滤的逻辑在日志中打印出来，好排查到底是什么问题导致选种失败。

**Comment by pofey** [comment]
系统有一个内置名称分析过滤器来负责查找资源名与你想要的节目是一致的，这种你不必加HNTV，让系统自己去分析就好了。你这个截图结果以馒头为例子，我估计只有5、6行资源能过掉这个过滤器，其他几个全因为首个词xx台干扰了，这个我优化一下词表，提高解析能力

**Comment by neroxps** [comment]
抱歉，我没有太明白是什么意思。

因为 声生不息 是有TVB版本和湖南卫视版本。所以我现在需要下载湖南卫视版本应该怎么做？

**Comment by pofey** [comment]
> 抱歉，我没有太明白是什么意思。
> 
> 因为 声生不息 是有TVB版本和湖南卫视版本。所以我现在需要下载湖南卫视版本应该怎么做？

不需要设置任何过滤器，把过滤条件都给删了

**Comment by neroxps** [comment]
删除了他就下载 TVB 版本。这并不是我预期的。

**Comment by pofey** [comment]
> 删除了他就下载 TVB 版本。这并不是我预期的。

那你就先保留着，等我下一版做些无效词升级，看能不能解析几个乱七八糟名字的剧

**Comment by neroxps** [comment]
好的，辛苦肝帝了。

**Comment by neroxps** [comment]
或者等到把自定义内置规则的版本也行。

**Comment by pofey** [comment]
你再升级最新试一下
