### ISSUE TITLE
【BUG】路径错误导致下载不成功。订阅列表却显示下载完成

### ISSUE THREAD

**Issue by AdoShan** [pofey/movie_robot#117]
首先，修改了路径之后web界面是正常的，但是日志里面路径还是之前的。
![image](https://user-images.githubusercontent.com/44154107/168406385-e9a82973-afdd-4619-a9bf-4ae7537498f8.png)
其次，显示提交成功，但是mr以及qb里面并没有这条记录
最后，希望订阅状态可以增加一个下载中的中间态，优化一下逻辑，而不是一提交就直接标记下载完成，增加这个状态也可以解决下载不成功需要重新下载的问题。

mr：0.9.4

**Comment by pofey** [comment]
配置正常不会出这种问题

**Comment by AdoShan** [comment]
> 配置正常不会出这种问题

配置正常确实不会出现。但是我是修改了保存路径的，页面也是修改后大的路径，但是机器人未应用修改后的路径。当时确定点了保存，并且刷新之后也是修改后的路径

**Comment by pofey** [comment]
> > 配置正常不会出这种问题
> 
> 配置正常确实不会出现。但是我是修改了保存路径的，页面也是修改后大的路径，但是机器人未应用修改后的路径。当时确定点了保存，并且刷新之后也是修改后的路径

你qbit曾经的种子路径，该机器人有什么用？

**Comment by AdoShan** [comment]
> > > 配置正常不会出这种问题
> > 
> > 
> > 配置正常确实不会出现。但是我是修改了保存路径的，页面也是修改后大的路径，但是机器人未应用修改后的路径。当时确定点了保存，并且刷新之后也是修改后的路径
> 
> 你qbit曾经的种子路径，改机器人有什么用？

大佬，真的不是我故意找茬，我是真的发现好像修改了配置是没生效的，而且我刚刚还升级了0.9.5B，绝对重启了好多次。
![image](https://user-images.githubusercontent.com/44154107/168459889-bc80dafa-e298-493e-84a0-a3c7f4d052cc.png)
不知道为啥就是读取到了之前的配置而且一直没有更新保存路径

**Comment by pofey** [comment]
> > > > 配置正常不会出这种问题
> > > 
> > > 
> > > 配置正常确实不会出现。但是我是修改了保存路径的，页面也是修改后大的路径，但是机器人未应用修改后的路径。当时确定点了保存，并且刷新之后也是修改后的路径
> > 
> > 
> > 你qbit曾经的种子路径，改机器人有什么用？
> 
> 大佬，真的不是我故意找茬，我是真的发现好像修改了配置是没生效的，而且我刚刚还升级了0.9.5B，绝对重启了好多次。 ![image](https://user-images.githubusercontent.com/44154107/168459889-bc80dafa-e298-493e-84a0-a3c7f4d052cc.png) 不知道为啥就是读取到了之前的配置而且一直没有更新保存路径 这个问题应该就是对文件夹不区分大小写的问题导致的(有的系统和应用确实是有这个Bug，直接重命名会提示文件夹已存在)。我把Movierobot改成了MovieRobot 订阅状态也还是变成了下载完成。这个时候不应该是下载失败嘛

还有一个概念叫，下载保存路径，在配置文件 smart_download-download_paths，页面豆瓣想看，你变更路径，这一处不会自动同步的，你只能删除重加

**Comment by AdoShan** [comment]
对了。就是因为豆瓣想看里面的下载保存规则是空的。改一下这个bug吧。人傻了。万一真的改了保存路径的话到处都要改，不太符合逻辑，太复杂了。

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
