### ISSUE TITLE
剧集优先匹配全集字样存在失误

### ISSUE THREAD

**Issue by BruceSuen720** [pofey/movie_robot#118]
0.9.4版本，剧集在站点搜索中，发现全集字样则优先下载，完成后则标记订阅完成，不再继续订阅，实际种子文件并非全集种子，导致订阅失败，实测不止一个站点会存在这种命名问题；尝试拉黑种子，举报种子没有实质性效果；洗版也只会搜索全集进行洗版，未更新完的剧集短时间不存在全集资源。
`2022/05/14 10:20:46 - SubConsumer - INFO: 已经开始在站点:  搜索: Who Rules The World,且试天下
2022/05/14 10:20:46 - SubConsumer - INFO: 已开启网络异常重试机制，最多可能等待15分钟。
2022/05/14 10:21:12 - SubConsumer - INFO: 共在17个站点搜索到265条结果，其中瓷器最慢，耗费26.41秒
2022/05/14 10:21:12 - SubConsumer - INFO: 且试天下(2022) 第1季 正在洗版，只会找完整整季合格资源下载。
2022/05/14 10:21:12 - SubConsumer - INFO: 且试天下(2022) 第1季 全集 品质：WEB-DL 2160p H.265 资源: https://pt.sjtu.edu.cn/details.php?id=201504&hit=1&hitfrom=firstpage 已经提交下载。
2022/05/14 10:21:12 - DownloadConsumer - INFO: 开始处理来自订阅的下载: [putao][且试天下]Who Rules the World 2022 S01 2160p WEB-DL H265 AAC-LeagueWEB
2022/05/14 10:21:12 - SubConsumer - INFO: 且试天下(2022) 第1季 本次下载的种子中，包含有全集字样信息，将默认本剧完结，停止订阅不再智能下载。
2022/05/14 10:21:14 - DownloadConsumer - INFO: 下载器存在这个任务：且试天下.Who.Rules.the.World.2022.S01.2160p.WEB-DL.H265.AAC-LeagueWEB
2022/05/14 10:21:14 - DownloadConsumer - INFO: [putao][且试天下]Who Rules the World 2022 S01 2160p WEB-DL H265 AAC-LeagueWEB提交下载失败
2022/05/14 10:25:00 - Thread-413 - INFO: 且试天下.Who.Rules.the.World.2022.S01.2160p.WEB-DL.H265.AAC-LeagueWEB已经被列入黑名单。
2022/05/14 10:25:00 - Thread-413 - INFO: 且试天下.Who.Rules.the.World.2022.S01.2160p.WEB-DL.H265.AAC-LeagueWEB已经从下载器中被删除。
2022/05/14 10:26:20 - ThreadPoolExecutor-0_1 - INFO: 开始同步站点资源信息...
2022/05/14 10:28:21 - ThreadPoolExecutor-0_1 - INFO: 所有站点资源信息已经更新完毕。
2022/05/14 10:28:21 - ThreadPoolExecutor-0_1 - INFO: 没有配置或开启流量管理设置，不会开始运行：{'available_space': 1000, 'avg_statistics_period': 5, 'enable': False, 'save_path': '/downloads/刷流', 'upload_mbps_maximum': 20}
2022/05/14 10:28:41 - SubConsumer - INFO: 已经开始在站点:  搜索: Who Rules The World,且试天下
2022/05/14 10:28:41 - SubConsumer - INFO: 已开启网络异常重试机制，最多可能等待15分钟。
2022/05/14 10:29:02 - SubConsumer - INFO: 共在17个站点搜索到265条结果，其中瓷器最慢，耗费21.65秒
2022/05/14 10:29:02 - SubConsumer - ERROR: [putao]201504是黑名单中的种子，跳过。
2022/05/14 10:29:03 - SubConsumer - INFO: 且试天下(2022) 第1季 正在洗版，只会找完整整季合格资源下载。`
要精确匹配是否为全集资源，可能还是需要在提交到下载器后，查询下载器解析过的文件列表进行判断，集数是否可以与数据库中的资源信息匹配

**Comment by pofey** [comment]
非bug 不修复
