### ISSUE TITLE
【需求】多用户订阅同一资源的通知推送

### ISSUE THREAD

**Issue by zwf19870623** [pofey/movie_robot#119]
目前逻辑是谁订阅通知谁很合理，不过如果同一个剧有第二个人订阅时会提示已经订阅过，这样有多个用户都想追同一个剧的时候，只有第一个订阅的人能收到通知。

您看改成如果有其他用户也要订阅的时候，就把这个用户也加到通知用户列表中是不是会好一点。

**Comment by pofey** [comment]
和列表中另一个通知需求其实是一回事了，这个关了。
