### ISSUE TITLE
译名不同导致识别有误

### ISSUE THREAD

**Issue by Skyline0503** [pofey/movie_robot#12]
豆瓣标记剧名：奇巧计程车（https://movie.douban.com/subject/35332568/）
PLEX内包含剧名：奇巧出租车 （该剧名和tmdb一致 https://www.themoviedb.org/tv/116727）

movie_robot识别为剧集不存在，导致重新下载
INFO: 奇巧计程车(2021)需要下载，需要在mteam寻找最佳种子

建议豆瓣的剧名可以在tmdb进行一次匹配，以tmdb的译名为基准在plex/emby上搜索，可以防止此类问题

**Comment by pofey** [comment]
本地媒体服务器的搜索做的确实特别差，如果去拿一次tmdb的数据，代价很高。不过现在本地有sqlite存储，应该也不会重复下载豆瓣想看的同一部资源了。

**Comment by pofey** [comment]
已经改为用tmdb信息检索
