### ISSUE TITLE
[疑问]关于已下载资源清理策略的问题

### ISSUE THREAD

**Issue by broven** [pofey/movie_robot#120]
Hi, 感谢做出这么好的工具, 有一个行为想确认下, 
比如我下载了一个电影, 
1. 在开启复制模式时, 那么在下载路径的文件什么情况下会被清理掉呢?
2. 硬链接模式下, 清理的策略又是什么样的呢?
3. 站点的养护设置会影响到这个行为吗?

**Comment by pofey** [comment]
现在没有任何主动清理原始文件的行为。

**Comment by broven** [comment]
那这块有啥最佳实践么, 我是希望买一个然后部署在父母家中, 配置好后, 尽量减少远程去帮他们运维的操作
有一个想法, 在开启复制模式时, 完成复制刮削后的文件和用来刷上传的做种文件一同对待, 根据相同的规则判断去留?

资源盘他们通过emby前端维护删除就好了
下载盘通过movie-robot来维护? 这样合适不

**Comment by pofey** [comment]
下载器7天自动删除
