### ISSUE TITLE
【建议】针对刷流种子淘汰提个小建议

### ISSUE THREAD

**Issue by AdoShan** [pofey/movie_robot#122]
刷流有的种子上传始终维持在300B/s或者3-4KB/s的种子应该也给他舍弃掉吧。要不然这种种子留着也没多大的上传。检测时间可以稍微长一点，但是如果长期(比如半小时或者在下次获取新种子的时候)把处于这种半死不活的种子舍弃掉换入新种子刷流效果会不会好点

**Comment by pofey** [comment]
0.9.6 优化了一下 平均每分钟上传超过100KB则保留
