### ISSUE TITLE
免费种子删除问题

### ISSUE THREAD

**Issue by LuXun1974** [pofey/movie_robot#123]
qb中手滑把免费种子删了，然后现在日志里一直报错，请问这怎么解决？
<img width="743" alt="image" src="https://user-images.githubusercontent.com/28734748/168455652-ad962c86-0023-42b8-af70-ced4b509f7e4.png">

**Comment by pofey** [comment]
这错误和删种子没关系，你把提示的那个种子删了没准就好了
