### ISSUE TITLE
【BUG】RARBG下载完毕后没有自动刮削及存放到新目录

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#124]
RARBG下载完毕后没有自动刮削及存放到新目录，也没有报错信息，请问是什么情况？谢谢

**Comment by elic6699** [comment]
下载完城后统计数据也没有显示，我试用trasmission，下载完成后状态为seeding不是finished，会不会是这个原因

**Comment by elic6699** [comment]
将trasmission任务seeding终止，状态更改为finished，movie-robot这边任务状态仍旧为下载中

**Comment by elic6699** [comment]
<img width="539" alt="截屏2022-05-15 12 24 46" src="https://user-images.githubusercontent.com/105474506/168457226-b1242668-edc2-493b-9f54-4269adef
<img width="656" alt="截屏2022-05-15 12 24 30" src="https://user-images.githubusercontent.com/105474506/168457228-c10771eb-9c55-4cdf-82a4-905ec3084cf8.png">
27ef.png">

**Comment by elic6699** [comment]
<img width="656" alt="截屏2022-05-15 12 24 30" src="https://user-images.githubusercontent.com/105474506/168457246-99cc4640-395e-441f-95e9-2c9a92f0f1b3.png">

**Comment by elic6699** [comment]
重启了一下服务，状态都变成“下载完成”了

**Comment by pofey** [comment]
应该有报错，把完整日志贴出来看看

**Comment by elic6699** [comment]
`2022/05/15 11:07:18 - DownloadConsumer - INFO: 开始处理来自订阅的下载: [rarbg]Better.Call.Saul.S06E05.Black.And.Blue.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv]
 2022/05/15 11:07:18 - SubConsumer - INFO: 风骚律师(2015) 第6季 第[4]?{? 品质：WEB-DL 1080p H.264 资源: https://torrentapi.org/redirect_to_info.php?token=0uk78negba&p=2_7_7_3_8_0_2__7f7eb87f7a 已经提交下载。
 2022/05/15 11:07:18 - SubConsumer - INFO: 风骚律师(2015) 第6季 第[1]?{? 品质：WEB-DL 1080p H.264 资源: https://torrentapi.org/redirect_to_info.php?token=0uk78negba&p=2_7_6_3_2_7_5__d59f3d4513 已经提交下载。
 2022/05/15 11:07:18 - SubConsumer - INFO: 风骚律师(2015) 第6季 第[2]?{? 品质：WEB-DL 1080p H.264 资源: https://torrentapi.org/redirect_to_info.php?token=0uk78negba&p=2_7_6_3_3_0_7__f6da4234b6 已经提交下载。
 2022/05/15 11:07:18 - SubConsumer - INFO: 风骚律师(2015) 第6季 第[3]?{? 品质：WEB-DL 1080p H.264 资源: https://torrentapi.org/redirect_to_info.php?token=0uk78negba&p=2_7_6_8_4_6_1__626ced0d69 已经提交下载。
 2022/05/15 11:07:22 - DownloadConsumer - INFO: [rarbg]Better.Call.Saul.S06E05.Black.And.Blue.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv]已经开始下载,路径：/share/Movie/电视剧 分类：未设置 
 2022/05/15 11:07:22 - DownloadConsumer - INFO: 开始处理来自订阅的下载: [rarbg]Better.Call.Saul.S06E04.1080p.WEB.H264-CAKES[rartv]
 2022/05/15 11:12:31 - DownloadConsumer - INFO: [rarbg]Better.Call.Saul.S06E04.1080p.WEB.H264-CAKES[rartv]已经开始下载,路径：/share/Movie/电视剧 分类：未设置 
 2022/05/15 11:12:31 - DownloadConsumer - INFO: 开始处理来自订阅的下载: [rarbg]Better.Call.Saul.S06E01.1080p.WEB.H264-GLHF[rartv]
 2022/05/15 11:16:02 - DownloadConsumer - INFO: [rarbg]Better.Call.Saul.S06E01.1080p.WEB.H264-GLHF[rartv]已经开始下载,路径：/share/Movie/电视剧 分类：未设置 
 2022/05/15 11:16:02 - DownloadConsumer - INFO: 开始处理来自订阅的下载: [rarbg]Better.Call.Saul.S06E02.1080p.WEB.H264-GLHF[rartv]
 2022/05/15 11:19:31 - DownloadConsumer - INFO: [rarbg]Better.Call.Saul.S06E02.1080p.WEB.H264-GLHF[rartv]已经开始下载,路径：/share/Movie/电视剧 分类：未设置 
 2022/05/15 11:19:31 - DownloadConsumer - INFO: 开始处理来自订阅的下载: [rarbg]Better.Call.Saul.S06E03.1080p.WEB.H264-CAKES[rartv]
 2022/05/15 11:22:01 - DownloadConsumer - INFO: [rarbg]Better.Call.Saul.S06E03.1080p.WEB.H264-CAKES[rartv]已经开始下载,路径：/share/Movie/电视剧 分类：未设置 
 2022/05/15 11:30:00 - ThreadPoolExecutor-0_0 - INFO: 开始获取14****853(do) 365天内的电影
 2022/05/15 11:30:00 - ThreadPoolExecutor-0_0 - INFO: 开始获取14****853(wish) 365天内的电影
 2022/05/15 11:30:00 - ThreadPoolExecutor-0_0 - INFO: 豆瓣用户145549853的想看列表开始同步到订阅记录。 
 2022/05/15 11:30:00 - ThreadPoolExecutor-0_0 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
 2022/05/15 11:37:59 - Thread-1654 - INFO: 来自Overseerr的订阅，请求参数: {'notification_type': 'MEDIA_AUTO_APPROVED', 'subject': 'The Grandmother (2022)', 'message': 'A Paris model must return to Madrid where her grandmother, who raised her, has had a stroke. But spending just a few days with this relative turns into an unexpected nightmare.', 'image': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/eIUixNvox4U4f
oL5Z9KbN9HXYSM.jpg', 'email': '', 'username': '', 'avatar': '', 'media': {'media_type': 'movie', 'tmdbId': '661791', 'imdbId': '', 'tvdbId': '', 'status': 'PENDING', 'status4k': 'UNKNOWN'}, 'extra': [], 'request': {'request_id': '8', 'requestedBy_email': 'lee.elic@gmail.com', 'requestedBy_username': 'lee.elic@gmail.com', 'requestedBy_avatar': '/os_logo_square.png'}}
 2022/05/15 11:38:02 - Thread-1654 - INFO: La abuela(2022) 选用过滤器：4k蓝光265电影 排序规则：collection
 2022/05/15 11:38:02 - Thread-1654 - INFO: La abuela(2022) 订阅成功
 2022/05/15 11:38:02 - SubConsumer - INFO: 已经开始在站点: RARBG 搜索: La abuela,The Grandmother
 2022/05/15 11:38:02 - SubConsumer - INFO: 已开启网络异常重试机制，最多可能等待15分钟。
 2022/05/15 11:38:33 - SubConsumer - INFO: 共在1个站点搜索到16条结果，其中RARBG最慢，耗费30.71秒
 2022/05/15 11:40:16 - Thread-1728 - INFO: 已经开始在站点: RARBG 搜索: La abuela
 2022/05/15 11:40:16 - Thread-1728 - INFO: 共在1个站点搜索到1条结果，其中RARBG最慢，耗费0.66秒
 2022/05/15 11:40:43 - Thread-1735 - INFO: 已经开始在站点: RARBG 搜索: gradmother 2022
 2022/05/15 11:41:06 - rarbg-search - ERROR: 从RARBG搜索gradmother 2022失败了，错误信息: 
 2022/05/15 11:41:06 - Thread-1735 - INFO: 共在1个站点搜索到0条结果，其中RARBG最慢，耗费22.59秒
 2022/05/15 11:41:40 - Thread-1746 - INFO: 已经开始在站点: RARBG 搜索: 661791
 2022/05/15 11:42:03 - rarbg-search - ERROR: 从RARBG搜索661791失败了，错误信息: 
 2022/05/15 11:42:03 - Thread-1746 - INFO: 共在1个站点搜索到0条结果，其中RARBG最慢，耗费22.61秒
 2022/05/15 11:42:41 - SubConsumer - INFO: 已经开始在站点: RARBG 搜索: La abuela,The Grandmother
 2022/05/15 11:42:41 - SubConsumer - INFO: 已开启网络异常重试机制，最多可能等待15分钟。
 2022/05/15 11:43:01 - SubConsumer - INFO: 共在1个站点搜索到16条结果，其中RARBG最慢，耗费19.9秒
 2022/05/15 11:51:58 - SubRequestConsumer - ERROR: 没有在影视库找到需要删除的信息tmdb: 661791
 2022/05/15 12:00:00 - ThreadPoolExecutor-0_0 - INFO: 开始获取14****853(do) 365天内的电影
 2022/05/15 12:00:00 - ThreadPoolExecutor-0_0 - INFO: 开始获取14****853(wish) 365天内的电影
 2022/05/15 12:00:00 - ThreadPoolExecutor-0_0 - INFO: 豆瓣用户145549853的想看列表开始同步到订阅记录。 
 2022/05/15 12:00:00 - ThreadPoolExecutor-0_0 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
 2022/05/15 12:05:08 - Thread-2621 - INFO: 开始连接Transmission Host: 192.168.0.202 port：49092
 2022/05/15 12:05:08 - Thread-2621 - INFO: 新增任务：同步豆瓣想看到订阅列表
 2022/05/15 12:30:00 - ThreadPoolExecutor-0_1 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
 2022/05/15 12:48:33 - MainThread - INFO: Jellyfin连接正常，9918610a33e0版本为10.7.7
 2022/05/15 12:48:33 - MainThread - INFO: 开始连接Transmission Host: 192.168.0.202 port：49092
 2022/05/15 12:48:34 - MainThread - INFO: 新增任务：PT站点登陆有效性检查及分享数据?{?新任务
 2022/05/15 12:48:34 - MainThread - INFO: 新增任务：免费下载种子?{?测任务
 2022/05/15 12:48:34 - MainThread - INFO: 新增任务：站点资源同步任务
 2022/05/15 12:48:34 - MainThread - INFO: 新增任务：同步豆瓣想看到订阅列表
 2022/05/15 12:48:34 - MainThread - INFO: 新增任务：自定义任务调度
 2022/05/15 12:48:34 - MainThread - INFO: 未开启?{?控所有渠道提交到下载器的种子
 2022/05/15 12:48:34 - MainThread - INFO: 新增任务：?{?听下载客户端下载状态
 2022/05/15 12:48:34 - MainThread - INFO: Jellyfin连接正常，9918610a33e0版本为10.7.7
 2022/05/15 12:48:34 - MainThread - INFO: 已经启动字幕下载处理任务。
 2022/05/15 12:48:34 - MainThread - INFO: 当前版本: 0.9.5
 2022/05/15 12:49:00 - ThreadPoolExecutor-0_0 - INFO: 开始为剧?{? 风骚律师 (2015)做文件转移 源路径：/video/电视剧/Better.Call.Saul.S06E02.1080p.WEB.H264-GLHF[rarbg] 链接路径：/video/电视剧-jellyfin
 2022/05/15 12:49:00 - ThreadPoolExecutor-0_0 - ERROR: 未识别的文件类型：/video/电视剧/Better.Call.Saul.S06E02.1080p.WEB.H264-GLHF[rarbg]/RARBG_DO_NOT_MIRROR.exe
 2022/05/15 12:49:00 - ThreadPoolExecutor-0_0 - INFO: 已处理：风骚律师 (2015) 第6季 源路径: /video/电视剧/Better.Call.Saul.S06E02.1080p.WEB.H264-GLHF[rarbg]/better.call.saul.s06e02.1080p.web.h264-glhf.mkv, ?{?的路径: /video/电视剧-jellyfin/风骚律师 (2015) [tmdbid=60059]/Season 6/风骚律师 S06E02 - 1080p H264.mkv
 2022/05/15 12:49:00 - ThreadPoolExecutor-0_0 - INFO: 风骚律师 第6季(2022) 第2?{?字幕下载 任务已经?{建。
 2022/05/15 12:49:01 - ThreadPoolExecutor-0_0 - INFO: Better.Call.Saul.S06E02.1080p.WEB.H264-GLHF[rarbg]处理完毕。
 2022/05/15 12:50:00 - ThreadPoolExecutor-0_0 - INFO: 风骚律师 第6季(2022) 第2?{?字幕下载已经提交启动。
 2022/05/15 12:50:00 - SubRequestConsumer - INFO: 风骚律师 第6季(2022) 第2?{?字幕下载 下次运行时间：2022-05-15 12:51:00
 2022/05/15 12:51:00 - ThreadPoolExecutor-0_1 - INFO: 风骚律师 第6季(2022) 第2?{?字幕下载已经提交启动。
 2022/05/15 12:51:00 - SubRequestConsumer - INFO: 风骚律师 第6季(2022) 第2?{?字幕下载 下次运行时间：2022-05-15 12:52:00
 2022/05/15 12:51:00 - ThreadPoolExecutor-0_0 - INFO: 开始为剧?{? 风骚律师 (2015)做文件转移 源路径：/video/电视剧/Better.Call.Saul.S06E05.Black.And.Blue.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg] 链接路径：/video/电视剧-jellyfin
 2022/05/15 12:51:00 - ThreadPoolExecutor-0_0 - INFO: 已处理：风骚律师 (2015) 第6季 源路径: /video/电视剧/Better.Call.Saul.S06E05.Black.And.Blue.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg]/Better.Call.Saul.S06E05.Black.And.Blue.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv, ?{?的路径: /video/电视剧-jellyfin/风骚律师 (2015) [tmdbid=60059]/Season 6/风骚律师 S06E05 - 1080p H264 DDP5.1.mkv
 2022/05/15 12:51:00 - ThreadPoolExecutor-0_0 - ERROR: 未识别的文件类型：/video/电视剧/Better.Call.Saul.S06E05.Black.And.Blue.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg]/RARBG_DO_NOT_MIRROR.exe
 2022/05/15 12:51:00 - ThreadPoolExecutor-0_0 - ERROR: /video/电视剧/Better.Call.Saul.S06E05.Black.And.Blue.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg]/.@__thumb/a100Better.Call.Saul.S06E05.Black.And.Blue.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv to /video/电视剧-jellyfin/风骚律师 (2015) [tmdbid=60059]/Season 6/风骚律师 S06E05 - 1080p H264 DDP5.1.mkv 硬链接失败，请检查源?{?录和?{?标?{?录是否跨?{?符?
???{?多硬链接知识请自行Google！
 2022/05/15 12:51:00 - ThreadPoolExecutor-0_0 - INFO: 已处理：风骚律师 (2015) 第6季 源路径: /video/电视剧/Better.Call.Saul.S06E05.Black.And.Blue.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg]/.@__thumb, ?{?的路径: /video/电视剧-jellyfin/风骚律师 (2015) [tmdbid=60059]/Season 6
 2022/05/15 12:51:00 - ThreadPoolExecutor-0_0 - INFO: 风骚律师 第6季(2022) 第5?{?字幕下载 任务已经?{建。
 2022/05/15 12:51:00 - ThreadPoolExecutor-0_0 - INFO: Better.Call.Saul.S06E05.Black.And.Blue.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg]处理完毕。
 2022/05/15 12:51:00 - ThreadPoolExecutor-0_0 - INFO: 开始为剧?{? 风骚律师 (2015)做文件转移 源路径：/video/电视剧/Better.Call.Saul.S06E04.1080p.WEB.H264-CAKES[rarbg] 链接路径：/video/电视剧-jellyfin
 2022/05/15 12:51:00 - ThreadPoolExecutor-0_0 - ERROR: 未识别的文件类型：/video/电视剧/Better.Call.Saul.S06E04.1080p.WEB.H264-CAKES[rarbg]/RARBG_DO_NOT_MIRROR.exe
 2022/05/15 12:51:00 - ThreadPoolExecutor-0_0 - INFO: 已处理：风骚律师 (2015) 第6季 源路径: /video/电视剧/Better.Call.Saul.S06E04.1080p.WEB.H264-CAKES[rarbg]/better.call.saul.s06e04.1080p.web.h264-cakes.mkv, ?{?的路径: /video/电视剧-jellyfin/风骚律师 (2015) [tmdbid=60059]/Season 6/风骚律师 S06E04 - 1080p H264.mkv
 2022/05/15 12:51:00 - ThreadPoolExecutor-0_0 - ERROR: /video/电视剧/Better.Call.Saul.S06E04.1080p.WEB.H264-CAKES[rarbg]/.@__thumb/a100better.call.saul.s06e04.1080p.web.h264-cakes.mkv to /video/电视剧-jellyfin/风骚律师 (2015) [tmdbid=60059]/Season 6/风骚律师 S06E04 - 1080p H264.mkv 硬链接失败，请检查源?{?录和?{?标?{?录是否跨?{?符，?{?多硬链接知识请自行Google！
 2022/05/15 12:51:00 - ThreadPoolExecutor-0_0 - INFO: 已处理：风骚律师 (2015) 第6季 源路径: /video/电视剧/Better.Call.Saul.S06E04.1080p.WEB.H264-CAKES[rarbg]/.@__thumb, ?{?的路径: /video/电视剧-jellyfin/风骚律师 (2015) [tmdbid=60059]/Season 6
 2022/05/15 12:51:00 - ThreadPoolExecutor-0_0 - INFO: 风骚律师 第6季(2022) 第4?{?字幕下载 任务已经?{建。
 2022/05/15 12:51:01 - ThreadPoolExecutor-0_0 - INFO: Better.Call.Saul.S06E04.1080p.WEB.H264-CAKES[rarbg]处理完毕。
 2022/05/15 12:51:01 - ThreadPoolExecutor-0_0 - INFO: 开始为剧?{? 风骚律师 (2015)做文件转移 源路径：/video/电视剧/Better.Call.Saul.S06E01.1080p.WEB.H264-GLHF[rarbg] 链接路径：/video/电视剧-jellyfin
 2022/05/15 12:51:01 - ThreadPoolExecutor-0_0 - INFO: 已处理：风骚律师 (2015) 第6季 源路径: /video/电视剧/Better.Call.Saul.S06E01.1080p.WEB.H264-GLHF[rarbg]/better.call.saul.s06e01.1080p.web.h264-glhf.mkv, ?{?的路径: /video/电视剧-jellyfin/风骚律师 (2015) [tmdbid=60059]/Season 6/风骚律师 S06E01 - 1080p H264.mkv
 2022/05/15 12:51:01 - ThreadPoolExecutor-0_0 - INFO: 风骚律师 第6季(2022) 第1?{?字幕下载 任务已经?{建。
 2022/05/15 12:51:01 - ThreadPoolExecutor-0_0 - INFO: Better.Call.Saul.S06E01.1080p.WEB.H264-GLHF[rarbg]处理完毕。
 2022/05/15 12:51:01 - ThreadPoolExecutor-0_0 - INFO: 开始为剧?{? 风骚律师 (2015)做文件转移 源路径：/video/电视剧/Better.Call.Saul.S06E03.1080p.WEB.H264-CAKES[rarbg] 链接路径：/video/电视剧-jellyfin
 2022/05/15 12:51:01 - ThreadPoolExecutor-0_0 - ERROR: 未识别的文件类型：/video/电视剧/Better.Call.Saul.S06E03.1080p.WEB.H264-CAKES[rarbg]/RARBG_DO_NOT_MIRROR.exe
 2022/05/15 12:51:01 - ThreadPoolExecutor-0_0 - INFO: 已处理：风骚律师 (2015) 第6季 源路径: /video/电视剧/Better.Call.Saul.S06E03.1080p.WEB.H264-CAKES[rarbg]/better.call.saul.s06e03.1080p.web.h264-cakes.mkv, ?{?的路径: /video/电视剧-jellyfin/风骚律师 (2015) [tmdbid=60059]/Season 6/风骚律师 S06E03 - 1080p H264.mkv
 2022/05/15 12:51:01 - ThreadPoolExecutor-0_0 - INFO: 风骚律师 第6季(2022) 第3?{?字幕下载 任务已经?{建。
 2022/05/15 12:51:01 - ThreadPoolExecutor-0_0 - INFO: Better.Call.Saul.S06E03.1080p.WEB.H264-CAKES[rarbg]处理完毕。`

**Comment by elic6699** [comment]
可以看到12:48重启前下载早就好了，但是只有能重启后才开始做重链接

**Comment by elic6699** [comment]
还有第四第五集硬链接失败了，也不知什么原因

**Comment by pofey** [comment]
除了第四集失败是个问题，其他没看出问题，你再遇到能重现再说吧。第四集那个源路径看起来有点奇怪，建议你自己硬链接命令挂一下看看能不能成功。

**Comment by elic6699** [comment]
看了一下文件系统，好像是没有下载完就做链接了，
lrwxrwxrwx 2 admin administrators  155 2022-05-15 11:28 风骚律师 S06E04 - 1080p H264.mkv -> /share/CACHEDEV2_DATA/Movie/电视剧/Better.Call.Saul.S06E04.1080p.WEB.H264-CAKES[rarbg]/.@__thumb/defaultbetter.call.saul.s06e04.1080p.web.h264-cakes.mkv

**Comment by elic6699** [comment]
手动硬链接是成功的
