### ISSUE TITLE
[Bug] Bark推送配置不生效

### ISSUE THREAD

**Issue by xuewy** [pofey/movie_robot#126]
测试Bark时搭建了自己的Bark服务器，在MR的web上配置了，后来改回默认的api.day.app,在web配置保存并测试成功，但实际上智能下载成功后无法接收到Bark推送的消息。查看base-config，配置确实已保存，再查看日志，有报错信息如下：

**_2022/05/15 12:40:06 - ThreadPoolExecutor-0_1 - INFO: 黑水(2007)字幕下载 任务已经创建。
 2022/05/15 12:40:10 - ThreadPoolExecutor-0_1 - INFO: bark 推送失败 **http://flextiger.top:5588/dnGNHmVWYnEh2UtBWC8Uek/%E9%BB%91%E6%B0%B4+%282007%29+%E8%AF%84%E5%88%86%3A5.9/TigerXue%E6%B7%BB%E5%8A%A0%E7%9A%84%E7%94%B5%E5%BD%B1+%E9%BB%91%E6%B0%B4%282007%29%E5%B7%B2%E4%B8%8B%E8%BD%BD%E5%AE%8C%E6%AF%95?isArchive=1&sound=chime&group=电影机器人&icon=https://yee-1254270141.cos.ap-beijing.myqcloud.com/movie_robot/icon.jpg_**

> 发现MR还是用的我以前配的自建的Bark服务器的配置，但由于该服务器已取消，所以推送失败。貌似web以及base-config里的配置未被调用，请帮忙解决。

**Comment by pofey** [comment]
在配置已经保存成功的情况下，重启后依然不生效就自己找原因吧。
