### ISSUE TITLE
[需求]优化资源搜索功能

### ISSUE THREAD

**Issue by Decade1993** [pofey/movie_robot#129]
目前：手动搜索种子的时候，偶尔会因为某个站点响应慢而导致整个搜索页面空白。
需求：能否像ptpp那样搜索的时候只要有站点返回结果了就在列表里展示出来，而不是等所有站点都有结果了再一起展示。

**Comment by pofey** [comment]
现在的搜索结果是按自己偏好排序的，逐个显示会影响排序使用体检。

**Comment by Decade1993** [comment]
也不必实时刷新，可以每10s刷新一下现有搜索结果的排序结果进行展示
