### ISSUE TITLE
后期是否会增加下载后移至目标路径的功能？

### ISSUE THREAD

**Issue by kolicime** [pofey/movie_robot#13]
我的媒体系统是部署在租来的服务器上的，用google drive来存储文件。目前使用的sonarr可以在下载完成后将文件移动到我google drive挂载至本地的目录，而本地的文件会在做种若干小时后自动删除，以避免硬盘被塞爆。我看了movie_robot的文档，似乎没有提到这个功能，不知道后期是否会添加？如果有这个功能，应该能帮助不少人摆脱sonarr这一套臃肿的追剧系统

**Comment by pofey** [comment]
下载就支持的，下载完成后可以自动识别并硬链接或者copy到新目录，并且以标准的电影名命名
