### ISSUE TITLE
【需求】rarbg订阅时支持imdbid搜索

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#130]
订阅智能下载不启动，日志里也没有报错信息，就这么停着
2022/05/15 17:00:28 - Thread-1188 - INFO: 来自Overseerr的订阅，请求参数: {'notification_type': 'MEDIA_AUTO_APPROVED', 'subject': 'Dark (2017)', 'message': 'A missing child causes four families to help each other for answers. What they could not imagine is that this mystery would be connected to innumerable other secrets of the small town.', 'image': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/apbrbWs8M9lyOpJY
U5WXrpFbk1Z.jpg', 'email': '', 'username': '', 'avatar': '', 'media': {'media_type': 'tv', 'tmdbId': '70523', 'imdbId': '', 'tvdbId': '334824', 'status': 'PENDING', 'status4k': 'UNKNOWN'}, 'extra': [{'name': 'Seasons', 'value': '1, 2, 3'}], 'request': {'request_id': '16', 'requestedBy_email': 'lee.elic@gmail.com', 'requestedBy_username': 'lee.elic@gmail.com', 'requestedBy_avatar': '/os_logo_square.png'}}
 2022/05/15 17:00:31 - Thread-1188 - INFO: 暗黑(2017) 选用过滤器：1080p电视剧 排序规则：collection
 2022/05/15 17:00:31 - Thread-1188 - INFO: 暗黑(2017) 第1季 订阅成功
 2022/05/15 17:00:31 - SubConsumer - INFO: 已经开始在站点: RARBG 搜索: Dark,暗黑
 2022/05/15 17:00:31 - SubConsumer - INFO: 已开启网络异常重试机制，最多可能等待15分钟。
 2022/05/15 17:00:31 - Thread-1188 - INFO: 暗黑(2017) 选用过滤器：1080p电视剧 排序规则：collection
 2022/05/15 17:00:31 - Thread-1188 - INFO: 暗黑(2017) 第2季 订阅成功
 2022/05/15 17:00:31 - Thread-1188 - INFO: 暗黑(2017) 选用过滤器：1080p电视剧 排序规则：collection
 2022/05/15 17:00:31 - Thread-1188 - INFO: 暗黑(2017) 第3季 订阅成功
 2022/05/15 17:00:42 - SubConsumer - INFO: 共在1个站点搜索到99条结果，其中RARBG最慢，耗费10.95秒
 2022/05/15 17:00:42 - SubConsumer - INFO: 已经开始在站点: RARBG 搜索: Dark,暗黑
 2022/05/15 17:00:42 - SubConsumer - INFO: 已开启网络异常重试机制，最多可能等待15分钟。
 2022/05/15 17:00:52 - SubConsumer - INFO: 共在1个站点搜索到99条结果，其中RARBG最慢，耗费10.61秒
 2022/05/15 17:00:52 - SubConsumer - INFO: 已经开始在站点: RARBG 搜索: Dark,暗黑
 2022/05/15 17:00:52 - SubConsumer - INFO: 已开启网络异常重试机制，最多可能等待15分钟。
 2022/05/15 17:01:03 - SubConsumer - INFO: 共在1个站点搜索到99条结果，其中RARBG最慢，耗费10.66秒
 2022/05/15 17:15:04 - ThreadPoolExecutor-0_2 - INFO: 开始同步站点资源信息...
 2022/05/15 17:15:07 - ThreadPoolExecutor-0_2 - INFO: 所有站点资源信息已经?{?新完毕。
 2022/05/15 17:15:07 - ThreadPoolExecutor-0_2 - INFO: 没有配置或开启流量管理设置，不会开始运行：{'avg_statistics_period': 5, 'enable': False}
 2022/05/15 17:30:00 - ThreadPoolExecutor-0_1 - INFO: 开始获取14****853(do) 365天内的电影
 2022/05/15 17:30:00 - ThreadPoolExecutor-0_1 - INFO: 开始获取14****853(wish) 365天内的电影
 2022/05/15 17:30:00 - ThreadPoolExecutor-0_1 - INFO: 豆瓣用户145549853的想看列表开始同步到订阅记录。 
 2022/05/15 17:30:00 - ThreadPoolExecutor-0_1 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
 2022/05/15 17:33:29 - SubRequestConsumer - INFO: 风骚律师(2015) 选用过滤器：1080p电视剧 排序规则：collection
 2022/05/15 17:33:29 - SubRequestConsumer - INFO: 新增来自admin的订阅: 风骚律师(2015)
 2022/05/15 17:33:29 - SubConsumer - INFO: 已经开始在站点: RARBG 搜索: Better Call Saul,风骚律师
 2022/05/15 17:33:29 - SubConsumer - INFO: 已开启网络异常重试机制，最多可能等待15分钟。
 2022/05/15 17:33:54 - rarbg-search - ERROR: 从RARBG搜索Better Call Saul失败了，错误信息: 
 2022/05/15 17:33:54 - SubConsumer - INFO: 共在1个站点搜索到0条结果，其中RARBG最慢，耗费24.52秒
 2022/05/15 17:34:07 - SubRequestConsumer - ERROR: 没有在影视库找到需要删除的信息tmdb: 661231
 2022/05/15 17:40:35 - ThreadPoolExecutor-0_0 - INFO: 开始同步站点资源信息...
 2022/05/15 17:40:36 - ThreadPoolExecutor-0_0 - INFO: 所有站点资源信息已经?{?新完毕。
 2022/05/15 17:40:36 - ThreadPoolExecutor-0_0 - INFO: 没有配置或开启流量管理设置，不会开始运行：{'avg_statistics_period': 5, 'enable': False}
 2022/05/15 18:00:00 - ThreadPoolExecutor-0_2 - INFO: 开始获取14****853(do) 365天内的电影
 2022/05/15 18:00:00 - ThreadPoolExecutor-0_2 - INFO: 开始获取14****853(wish) 365天内的电影
 2022/05/15 18:00:00 - ThreadPoolExecutor-0_2 - INFO: 豆瓣用户145549853的想看列表开始同步到订阅记录。 
 2022/05/15 18:00:00 - ThreadPoolExecutor-0_2 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
 2022/05/15 18:06:06 - ThreadPoolExecutor-0_0 - INFO: 开始同步站点资源信息...
 2022/05/15 18:06:09 - ThreadPoolExecutor-0_0 - INFO: 所有站点资源信息已经?{?新完毕。
 2022/05/15 18:06:09 - ThreadPoolExecutor-0_0 - INFO: 没有配置或开启流量管理设置，不会开始运行：{'avg_statistics_period': 5, 'enable': False}
 2022/05/15 18:30:00 - ThreadPoolExecutor-0_2 - INFO: 开始获取14****853(do) 365天内的电影
 2022/05/15 18:30:00 - ThreadPoolExecutor-0_2 - INFO: 开始获取14****853(wish) 365天内的电影
 2022/05/15 18:30:00 - ThreadPoolExecutor-0_2 - INFO: 豆瓣用户145549853的想看列表开始同步到订阅记录。 
 2022/05/15 18:30:00 - ThreadPoolExecutor-0_2 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
<img width="972" alt="截屏2022-05-15 18 55 05" src="https://user-images.githubusercontent.com/105474506/168469269-8d57feee-25bf-4fb7-a3df-72ec665bd988.png">

**Comment by pofey** [comment]
贴rarbg你认为应该去下载的搜索结果

**Comment by elic6699** [comment]
搜索是正常的
<img width="879" alt="截屏2022-05-15 19 45 01" src="https://user-images.githubusercontent.com/105474506/168471130-6058fadb-50da-42b3-9c3a-3fba0f6c8616.png">

**Comment by elic6699** [comment]
<img width="706" alt="截屏2022-05-15 19 52 30" src="https://user-images.githubusercontent.com/105474506/168471411-95275513-c1b0-4af1-8e55-9e3b49083de5.png">

**Comment by pofey** [comment]
1080p电视剧
看你这个过滤器设置的什么东西

**Comment by elic6699** [comment]
<img width="2160" alt="截屏2022-05-15 19 58 42" src="https://user-images.githubusercontent.com/105474506/168471595-3712808a-6e95-480a-96e9-6f2d4b7d06f0.png">

**Comment by pofey** [comment]
现在系统搜索信息是按PT站搜索质量调优的结果，采用剧的英文名+中文名双搜索结果去重分析，季度分析，综合得出订阅想看的到底是什么，搜索时为了尽可能多检索pt站结果，是不带季度的。以暗黑这部剧为例，已经开始在站点: RARBG 搜索: Dark，dark是tmdb这部剧英文名和搜索词，我试了下用这个搜rarbg，出来的结果相关性实在太差了，就算用dark s01去搜，相关性依然很差。所以目前这个问题应该无解，短时间不打算针对rarbg做特殊的搜索优化。

**Comment by pofey** [comment]
我又试了下pt站 dark的搜索结果，虽然结果也很多，但是至少还有
[暗黑 第一季/暗(港/台)/暗黑世界/黑暗世界/黑暗 全10集 | 类型：科幻/悬疑 主演：奥利弗·马苏奇/卡罗莉内·艾希霍恩/耶迪斯·特里贝尔 全音轨字幕 全10集](https://totheglory.im//t/476867/)
WEB-DL
1080p
H.264
[ttg]Dark 2017 S01 Complete V2 1080p NF WEB-DL H264 DDP 5.1-LeagueNF

**Comment by elic6699** [comment]
我试用jellyseerr订阅，可以获得imdb的id，而rarbg可以直接使用imdb id精确搜，这个是否可以优化呢？谢谢

**Comment by pofey** [comment]
> 我使用jellyseerr订阅，可以获得imdb的id，而rarbg可以直接使用imdb id精确搜，这个是否可以优化呢？谢谢

确实是可以的，我也适配好它这个接口了，不过针对站点的搜索词优化这个事，短时间我估计不会开始。

**Comment by pofey** [comment]
当然也许哪天心情好就把它优化了

**Comment by pofey** [comment]
0.9.6 已经改为imdbid搜索了
