### ISSUE TITLE
transmission下载完成后仍在movie-robot中显示下载中

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#132]
<img width="488" alt="截屏2022-05-16 08 44 13" src="https://user-images.githubusercontent.com/105474506/168502244-cc5fcd19-48ee-4d0a-806b-9d03aa706b73.png">
<img width="670" alt="截屏2022-05-16 08 43 49" src="https://user-images.githubusercontent.com/105474506/168502254-ff7c4773-00a1-4a7b-87a2-c813f8fc441b.png">
导致无法进行进行下一步文件整理刮削，无法jellyfin入库

**Comment by pofey** [comment]
现在完成时附近的日志呢

**Comment by elic6699** [comment]
看了一下movie-robot的log里面该任务除了开始下载这一条，后面就没有相关的了
2022/05/15 22:22:30 - DownloadConsumer - INFO: 开始处理来自Web的下载: [rarbg]Ozark.S01.1080p.WEBRip.x265-RARBG

**Comment by elic6699** [comment]
昨天相同情况是重启了一下就开始执行下去了

**Comment by elic6699** [comment]
<img width="779" alt="截屏2022-05-16 09 26 12" src="https://user-images.githubusercontent.com/105474506/168504674-dd70216c-0e6a-4ded-992c-de363d7aa676.png">

**Comment by pofey** [comment]
下次遇到下完没动静把日志贴出来

**Comment by elic6699** [comment]
没日志啊，有没有debug更详细日志可设置的？

**Comment by pofey** [comment]
如果完全没有日志说明你程序没启动监控种子的任务，这是不可能的，因为只要配置好了下载器，就一定会启动这个任务。启动时会有 新增任务：监听下载客户端下载状态

**Comment by elic6699** [comment]
只有第一季没有继续任务，我看了一下，第一季目前的状态是finished，其他成功的都是Seeding状态

**Comment by pofey** [comment]
我看了下tr，现在的代码，只要种子状态非'download pending', 'downloading', 'stopped' 这几个状态，就说明已经完成，就会走转移处理
