### ISSUE TITLE
希望继续支持【直接识别qb里添加的种子】的功能

### ISSUE THREAD

**Issue by kiteggboy** [pofey/movie_robot#134]
前几个版本还是支持的，就是直接拉取几个种子添加到qb里，然后机器人能自动识别（应该是直接识别的路径里的资源），下完后也能自动重命名硬链接。
但是最近更新添加字幕功能后，貌似就不支持了。现在只能识别从movie-robot里搜寻添加的种子。
希望老哥能继续加上这个功能，真的挺好用的，特别是大量搬种的时候。

**Comment by pofey** [comment]
默认关闭了，通过配置可以打开

**Comment by kiteggboy** [comment]
谢谢大佬解答，我去康康！
