### ISSUE TITLE
智能下载选种问题

### ISSUE THREAD

**Issue by phinleyfei** [pofey/movie_robot#137]
![44fcbb68d42e716932d9ab85df3c203](https://user-images.githubusercontent.com/105186845/168586549-03f72ccb-ac09-4883-b401-467e006d3e49.png)

选种策略-compress
版本：0.9.6b
站点管理-馒头，选择的是允许智能下载

web搜索如图可以看到有1080p的版本且上传下载数多于720p的版本，但机器人选择720p的下载。删除订阅再重新订阅，策略里面选1080p，机器人没启动下载。

日志见附件。
[movie-robot.csv](https://github.com/pofey/movie_robot/files/8699793/movie-robot.csv)

**Comment by pofey** [comment]
第一个结果的俄剧: 被筛掉了，这个种子也没英文名
