### ISSUE TITLE
自动搜与手动搜结果不一致

### ISSUE THREAD

**Issue by phinleyfei** [pofey/movie_robot#138]
![image](https://user-images.githubusercontent.com/105186845/168696034-f9b0c03c-e2ef-4039-a702-09ca3f217d82.png)

“母亲”这部电影，智能下载无结果（日志时间6：37；46），通过点击过滤提交的方式（过滤器为空），却有搜索结果（日志6：58：47），机器人版本0.9.7C

**Comment by phinleyfei** [comment]
另外，我订阅中有几十部，为何只有日志中的这5部在自动搜？

**Comment by pofey** [comment]
无效反馈 关闭了。认为该有结果的，至少贴出来手动搜索认为该下的结果。认为订阅不下的，至少贴出订阅信息截图，以及触发时日志对比。在这说一堆没信息就是在浪费时间。
