### ISSUE TITLE
过滤器匹配问题

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#139]
下载log中搜到14个结果，但是有效结果为0
2022/05/17 09:43:05 - SubConsumer - INFO: 共在1个站点搜索到14条结果，其中RARBG最慢，耗费51.81秒
2022/05/17 09:43:05 - SubConsumer - INFO: 上帝的驱魔(2022) 经过系统分析后，没有搜到有效结果。

使用的过滤器为，排序为compress
<img width="952" alt="截屏2022-05-17 09 44 39" src="https://user-images.githubusercontent.com/105474506/168710880-85f1c5f5-6c2f-4860-b19f-68c3b9ce3acb.png">

但是web搜索结果如下，是匹配过滤器的。试过不使用过滤器，同样报没有搜到有效结果
<img width="656" alt="截屏2022-05-17 09 46 22" src="https://user-images.githubusercontent.com/105474506/168711502-19ff577d-5b16-49f2-8102-0d59327c99ff.png">

**Comment by pofey** [comment]
种子2021 实际实际tmdb 2022，同时因为资源名没标季，无法推断合理性，认为年份不合格筛掉了

**Comment by elic6699** [comment]
imdbid应该是最准的，这种情况下是否可以忽略年份，或者扩大年份的区间？

**Comment by elic6699** [comment]
这个资源是电影，所以没有季

**Comment by pofey** [comment]
> imdbid应该是最准的，这种情况下是否可以忽略年份，或者扩大年份的区间？

针对rarbg这个渠道，确实可以考虑这样的优化。现在走的都是pt逻辑，没有针对rarbg做过什么优化。不过电影错年，更是小概率事件了吧，这种case不会很多

**Comment by elic6699** [comment]
就例如这个电影 上帝的驱魔
在imdb是2011年，tmdb是2022年，这种情况不知道多不多
<img width="785" alt="截屏2022-05-17 14 11 36" src="https://user-images.githubusercontent.com/105474506/168741280-97202d11-51b0-4fb4-b94e-4c236ce60ba3.png">
<img width="505" alt="截屏2022-05-17 14 11 25" src="https://user-images.githubusercontent.com/105474506/168741291-af58aa68-970d-4a7b-9f15-aae58a6f6074.png">

**Comment by elic6699** [comment]
可能是院线和流媒体渠道的区别
