### ISSUE TITLE
这个页面能加个字幕下载详情就更好了

### ISSUE THREAD

**Issue by lalasou** [pofey/movie_robot#141]
类似这种 ，或者就在这加个也行

![image](https://user-images.githubusercontent.com/7440313/168773608-f3a80240-5900-4926-b617-0cbdc850a12c.png)

类似这种

**Comment by pofey** [comment]
考虑到整体使用体验，还不能加在这个位置，等待吧，会有地方显示的

**Comment by lalasou** [comment]
确实 功能现在差不多了  就是得整合优化下  
本地媒体信息  movie自建数据库存吧  要不然 每次都请求 会很慢
