### ISSUE TITLE
建议：希望BT和PT支持不同的下载器

### ISSUE THREAD

**Issue by HisingX** [pofey/movie_robot#142]
比如rarbg用下载器1，PT用下载器2
主要是BT的下载完保种规则等与PT不一样，希望BT能单独选择下载器。或者是添加种子的时候支持分享率设置，比如设置分享率为1的时候停止做种。

**Comment by pofey** [comment]
0.9.21 提交到qbit的bt种子，上传自动限速为每秒1byte
