### ISSUE TITLE
豆瓣电影订阅时发生错误，原因不明。环境：群晖NAS docker中

### ISSUE THREAD

**Issue by sansiex** [pofey/movie_robot#146]
豆瓣电影订阅时发生错误，原因不明。环境：群晖NAS docker中错误日志如下：

<img width="981" alt="image" src="https://user-images.githubusercontent.com/2852016/168860318-3e9e75ed-6777-4455-a7ca-abb30e9c4b26.png">

**Comment by sansiex** [comment]
0.9.7

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/2852016/168861864-28c0697c-ff38-4165-a8ac-bae58ef0f48a.png">

**Comment by pofey** [comment]
> 0.9.7
> 
> <img alt="image" width="1061" src="https://user-images.githubusercontent.com/2852016/168861864-28c0697c-ff38-4165-a8ac-bae58ef0f48a.png">

你先升级然后安wiki配置好再说吧 你这豆瓣还没配完
