### ISSUE TITLE
【需求】能否增加站点 Mikanani 和 dmhy 的智能下载

### ISSUE THREAD

**Issue by Alano-i** [pofey/movie_robot#147]
有很多动漫在 PT 站点更新比较慢或者没有，这两个站更新快也比较齐全，用的人也比较多。
希望能加入到智能下载中去。感谢！
https://mikanani.me/
https://share.dmhy.org/

目前动漫用的这两个的rss订阅添加到 qb 自动下载，如果能加入到这个机器人就太好了！

**Comment by pofey** [comment]
动漫先不考虑，动漫的下载和识别问题都非常难处理，暂时没精力去专项优化
