### ISSUE TITLE
老大，提几个小需求和小优化，期待顺手满足一下hh

### ISSUE THREAD

**Issue by leverule** [pofey/movie_robot#148]
需求：
- 设置智能下载只下载免费种子，因为水管小…想安心地把新站开启智能下载
方案：
- - 智能下载添加“只下载免费种子”的按钮
- - 利用过滤器的优先级机制开启更高端的玩法！！多级过滤器！比如可以设置高优先过滤器为免费种和高质量，低优先过滤器只设置免费种，过滤器运行模式添加“向低优先级匹配”的模式，一直匹配到完全匹配再下载的过滤器。实现订阅自动降档匹配，升档洗版，甚至可以在不同优先级过滤器里实现多重洗版：一版给家人在线观看、一版收藏级品质好好欣赏，保存到不同的分类路径…哇好期待

- 过滤器的关键词，可以设置与或关系

- 可以尝试识别一下站免公告？然后推送站免的通知，上线，手动一键洗版，一气呵成。因为直接洗版remux太奢侈了…

优化：
- Web手动搜索后，把所有265、264编码类型整合为“x265编码”和“x264编码”，或者改为复选框，提升检索体验

- 把站点管理中的是/否设置，改为一键切换的按钮滑块，这样就能快速在站免的时候疯狂白嫖！哈哈

**Comment by pofey** [comment]
过滤器现在就能满足你的要求了，读 https://yee329.notion.site/12f6d44243194c8c96a7e000b9dde023

**Comment by leverule** [comment]
不是的噢，当前过滤器“先按排序下载随后再洗版”的模式，如果匹配不到指定质量的资源，会只按排序规则下载，这种情况下，一旦免费排在后面或者结果中无免费，那么会下载不免费的资源。

举个栗子哈

这是瞬息全宇宙的过滤器，设置了洗版模式，勾选了只下载免费：
![Snipaste_2022-05-18_13-31-24](https://user-images.githubusercontent.com/57491211/168965250-89097ce4-001d-403e-bdbb-0b24f5570111.png)

这是排序规则的搜索结果：
![Snipaste_2022-05-18_13-17-50](https://user-images.githubusercontent.com/57491211/168965282-8f51999c-a7ea-409a-b077-3bda19140951.png)

最终还是自动下载了不免费的资源，因为洗版模式下按照排序规则下载了，完全没有其他过滤：
![Snipaste_2022-05-18_13-28-52](https://user-images.githubusercontent.com/57491211/168965793-67ac627b-b080-4217-8665-e8a7a57cb5f4.png)

我的想法是，可以把智能下载的大前提设置为免费，免费种子里如果没有指定质量的，就在其他质量里按排序规则先下载一个，再洗版。所以多层过滤的机制应该会很好用，过滤器的优先级也会有真正意义

**Comment by pofey** [comment]
仔细研究排序规则的设计，以及配置文件，这是靠排序来解决的，而不是所谓的多级过滤器。只要你会玩，你自己通过自定义一份排序规则，就可以实现自己的需求了。

**Comment by leverule** [comment]
> 仔细研究排序规则的设计，以及配置文件，这是靠排序来解决的，而不是所谓的多级过滤器。只要你会玩，你自己通过自定义一份排序规则，就可以实现自己的需求了。

噢……问下哈，如果结果中没免费种子，再加上过滤免费种子不严格，无论怎么排序，下载的都是不免费的吧？难道可以通过调整排序规则来实现非免费不下载嘛

**Comment by pofey** [comment]
你在好好读读吧，如果你非免费不可，这叫过滤，如果你只是想免费绝对优先，这叫排序
