### ISSUE TITLE
plex下载字幕后未刷新元数据导致字幕不被识别。

### ISSUE THREAD

**Issue by HisingX** [pofey/movie_robot#149]
plex外挂字幕识别机制是对当前资源进行元数据刷新才可以识别到下载到影视同级目录的字幕文件，我发现字幕下载完成后plex不会对当前影视剧进行元数据刷新，导致无法识别获取的外部字幕文件。

这个功能建议**只对当前电影或者剧集进行指定元数据刷新**，**不要对整个目录刷新**，整个目录刷新的话会占用大量时间。

<img width="772" alt="image" src="https://user-images.githubusercontent.com/19724911/168937641-ff044a6e-51c0-4db9-b47f-796db7ce50ca.png">

**Comment by pofey** [comment]
现在plex接口好像变成了调用update，也就是扫描接口，刷新元数据是refresh操作吗。

**Comment by HisingX** [comment]
> 现在plex接口好像变成了调用update，也就是扫描接口，刷新元数据是refresh操作吗。

plex 扫描新数据用的update，执行后如果识别到新资源会自动对该资源进行元数据扫描，如果此时目录里有字幕文件会识别到。
如果是资源已经被plex扫描到，后来又补充字幕文件，需要对当前资源进行一次元数据更新才会识别后来新增的外部字幕。
————————————
另外最新版机器人，剧集下载完，PLEX好像没有执行update操作啊。还得手动去plex扫一下才行。

**Comment by pofey** [comment]
现在有触发update的，只是没日志提示而已，如果确定字幕是refresh，我后面考虑字幕完成走refresh接口

**Comment by HisingX** [comment]
> 现在有触发update的，只是没日志提示而已，如果确定字幕是refresh，我后面考虑字幕完成走refresh接口

能加上日志吗？方便我们用户看下什么时候执行的update，因为电影下载后媒体库会更新，剧集下载后就没更新。之前版本没有这个问题，测试有问题的版本是 **当前版本: 0.9.8C**

**Comment by pofey** [comment]
已经优化，并且加了日志，0.9.21 生效
