### ISSUE TITLE
【建议】不同站点相同资源优先下载免费资源

### ISSUE THREAD

**Issue by Alano-i** [pofey/movie_robot#150]
搜索到在不同站点有相同资源时，建议优先下载免费资源或更便宜的资源！

<img width="1603" alt="image" src="https://user-images.githubusercontent.com/68833595/168938442-12b3ce01-987d-45bc-b80e-25f855159c24.png">

**Comment by pofey** [comment]
现在排序规则可以解决，只是没开放配置，你姐的你会玩可以自己看看rule李配置文件
