### ISSUE TITLE
希望在下载记录里电视剧添加合集功能

### ISSUE THREAD

**Issue by sunsetz** [pofey/movie_robot#151]
现在想在机器人里完全删除一部电视剧，步骤是需要完全把下载记录的所下载所有的下载集数都删除，才可以完全删除一部电视剧。
如果在下载记录把下载的电视剧做一个合集，所有下载的集数都显示在这部电视剧下面，删除只需要删除这部电视剧合集就好了，跟删除电影一样步骤简化。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by pofey** [comment]
你直接去订阅里，深度删除，就会自动全干掉了
