### ISSUE TITLE
一个跟下载后复制文件相关的问题

### ISSUE THREAD

**Issue by lalakers1986** [pofey/movie_robot#154]
hi 您开发的movie_robot非常好用，首先表示感谢~
我常用的是Hetzner+GoogleDrive+Plex的组合.
昨晚想看新加入的瞬息全宇宙，但是只要走Plex看就放不出..
测试结果是，直接Plex不行，Infuse+Plex不行，Infuse+GDrive行，在GoogleDrive直接播放/下载也可…
然后我fclone手动传了一份到GDrive，这个版本Plex是可以播放的.
接着我测试了最近movie_robot自动整理的片子，发现几天前的Plex都可以正常播放，新加入的都无法播放...
（猜测是不是要经过一段时间？但搞不懂这个限制在哪...）
不知是否跟movie_robot的复制到挂载路径的方式有关？（因为挂载网盘所以我没有使用HardLink）
movie_robot的版本我是用watchtower一直自动更新的，昨晚是0.9.7C
昨晚用docker logs看了日志，显示一切正常...
ps. 昨晚瞬息全宇宙push说字幕已下好，上去也没看见...
然后我reset了一下，logs也不见了...先来问问看是否有类似情形...
感谢阅读 再次感谢您的开发~

**Comment by pofey** [comment]
#149 字幕不刷新跟这个反馈有关系
至于你上面说的一堆，我就不懂了，我没那么用过。但你检测的标准应该不是plex能不能播，而是看机器人复制过去的文件是否完整。

**Comment by lalakers1986** [comment]
感谢提醒，我去检查下复制的完整性～

**Comment by HisingX** [comment]
> 感谢提醒，我去检查下复制的完整性～

我也是hz + plex+ gdrive ，不过我上传文件用的是rclone挂载，plex播放挂的是plexdrive，因为这个实测比rclone块的多，但是不支持上传文件，只能读取。

我这边播放没问题，你播放不出来，你可以在plex里看一下 文件详细信息，看看文件状态对不对。

**Comment by lalakers1986** [comment]
> > 感谢提醒，我去检查下复制的完整性～
> 
> 我也是hz + plex+ gdrive ，不过我上传文件用的是rclone挂载，plex播放挂的是plexdrive，因为这个实测比rclone块的多，但是不支持上传文件，只能读取。
> 
> 我这边播放没问题，你播放不出来，你可以在plex里看一下 文件详细信息，看看文件状态对不对。

感谢回复～
我有空去试试看plexdrive来read～
这个情况超诡异，就是昨天下的那两部播不出，但文件没问题，直接gd里放是ok的，就是plex抽风。
我刚刚又测试了长泽新出的英雄篇，robot处理好以后plex又可以秒播正常……

**Comment by JackieDark** [comment]
问下rclone模式的话下载的文件是如何复制到云盘里面的，我看复制的很慢，不是rclone copy这种

**Comment by lalakers1986** [comment]
作者应该没有考虑rclone吧🤔
所以复制可能就是系统中的copy命令？（我的速度还行😆因为我每天用量不大
如果大量入库的话
建议你不要订阅，直接批量手动下载+fclone到gd，再用robot存量整理，现在存量整理有move了，以前只有hardlink和copy，用move整理比较快。

Cole ***@***.***>于2022年8月18日 周四10:16写道：

**Comment by JackieDark** [comment]
感谢回复，目前看确实就是系统的copy，这样就是copy进去的文件到云盘会出现播放不了，有时候会出现两份：服务器一份和云盘一份。希望后面支持云盘模式吧，只需要用rclone copy代替下

**Comment by lalakers1986** [comment]
播放不了是gd的问题 过一会应该就好了
有两份是指server端下载的文件吗？我是用autoremovetorrents处理的，基本上保留5-7days，看你服务器硬盘多大了。如果是vps那种只有80G的同时下好几个就比较麻烦😆

Cole ***@***.***>于2022年8月18日 周四10:23写道：
