### ISSUE TITLE
下载《美国恐怖故事》第二、第四、第九季出现问题

### ISSUE THREAD

**Issue by elle007011** [pofey/movie_robot#155]
其中第二、第四季都提示订阅失败，第九季会被认为是《鹿鼎记》第九季。Robot版本为0.9.8D

详细日志见后
<img width="1410" alt="WechatIMG221" src="https://user-images.githubusercontent.com/105756846/168958545-f9f545cd-149b-4fab-8a47-8ea5c96c4c42.png">
<img width="1416" alt="WechatIMG222" src="https://user-images.githubusercontent.com/105756846/168958579-072a1077-9e36-409e-ac4b-df03fc92f831.png">

**Comment by pofey** [comment]
<img width="461" alt="截屏2022-05-18 下午12 59 44" src="https://user-images.githubusercontent.com/1396975/168960550-3db0232b-4379-4ecd-a6e4-2e75154b590b.png">
1、美国恐怖故事与鹿鼎记无关，鹿鼎记你还要在看看怎么回事
2、这个报错是豆瓣处理的一个bug，已经修复，下个版本发布
