### ISSUE TITLE
希望能在页面上添加日志查看功能

### ISSUE THREAD

**Issue by Zayia** [pofey/movie_robot#156]
不然每次查看日志都只能去docker里面查看，非常麻烦

**Comment by pofey** [comment]
你有什么正常操作，是非要看日志才能完成的？

**Comment by Zayia** [comment]
正常操作还需要看日志？

**Comment by pofey** [comment]
不正常的异常，你需要看几次日志呢，分析问题的过程必须要开电脑，看日志，分析的呀。web看日志，就是伪需求。
