### ISSUE TITLE
【 讨论】关于WEB页面是否有必要显示日志的探讨

### ISSUE THREAD

**Issue by Alano-i** [pofey/movie_robot#162]
希望能增加实时日志显示，目前日志只能打开文件查看，有些不是很方便，经常会有一些需要查看日志定位问题什么的。
如果能在 web 端就能查看日志，那就太方便了。

顺手画了个图，大致如下，仅供参考，谢谢！
 
![image](https://user-images.githubusercontent.com/68833595/169101401-b56c889d-792c-4890-b40c-05e08e1fdb4f.png)
![image](https://user-images.githubusercontent.com/68833595/169103405-c2f7808c-0706-4256-a2f0-b998fe20a2b2.png)

**Comment by elecxwr** [comment]
因为目前还在快速开发迭代期，各种新特性带来的各种功能、问题都需要查排查日志。
另外，感觉软件目前实现功能的各种进度展现得还不够，推送通知都还略显不足，我也喜欢查看日志来掌握进度、实现情况。
所以其实现在对于我个人来说查看日志是个高频功能。感觉在当前状态下加上会方便很多。
当然，以后软件功能成熟稳定了，各种进度推送也比较完善，不用折腾了，这个功能也不那么需要了。

**Comment by Alano-i** [comment]
**_“稳定运行后，不用折腾，也就没有看日志的需求”_**

1. `十分同意这个观点，这是大多数软件一个比较理想的状态，毕竟对于用户而言看日志还是比较头疼的事。`
2. `但是对于我们这个机器人而言，认为并不是一个相对容易上手的应用，因为需要和其他多个应用进行联动交互，还需要特殊网络环境等等，总之相对来说比较复杂并不是“一个人吃饱全家不饿”的应用，任何一环都不能出问题。`
3. `能使用部署这个应用的人群，应该都是或多或少有一点点基础，喜欢折腾的人，而不仅仅是关心电影能不能看，初次接触这个的看wiki估计都看不懂，而这类人群，他们对于日志关注的 score 一定比较高。（仅仅关心电影能不能看的人是部署这个应用用户的家人或者朋友，而不是本人）`

  所以虽然已经有相对完善的wiki可以查阅指导，但是能一次就部署成功并在后期不需要折腾的情况目前看来是不太现实的（至少对于大多数人来说），正如 @elecxwr 所说，快速开发迭代期，各种新特性带来的各种功能、问题都需要查排查日志，每次使用电脑查看log, 还需要不断点刷新看日志实属不太方便。

以上是自己的一些浅薄想法，仅供大家参考。

**Comment by pofey** [comment]
> **_“稳定运行后，不用折腾，也就没有看日志的需求”_**
> 
> 1. `十分同意这个观点，这是大多数软件一个比较理想的状态，毕竟对于用户而言看日志还是比较头疼的事。`
> 2. `但是对于我们这个机器人而言，认为并不是一个相对容易上手的应用，因为需要和其他多个应用进行联动交互，还需要特殊网络环境等等，总之相对来说比较复杂并不是“一个人吃饱全家不饿”的应用，任何一环都不能出问题。`
> 3. `能使用部署这个应用的人群，应该都是或多或少有一点点基础，喜欢折腾的人，而不仅仅是关心电影能不能看，初次接触这个没有基础的看wiki估计都看不懂，而这类人群，他们对于日志关注的 score 一定比较高。（仅仅关心电影能不能看的人是部署这个应用用户的家人或者朋友，而不是本人）`
> 4. `心理上，能看到日志，知道系统正在做什么，有什么错误正在发生，有掌控全局的感觉有木有，哈哈哈（just kidding）`
> 
> 所以虽然已经有相对完善的wiki可以查阅指导，但是能一次就部署成功并在后期不需要折腾的情况目前看来是不太现实的（至少对于大多数人来说），正如 @elecxwr 所说，快速开发迭代期，各种新特性带来的各种功能、问题都需要查排查日志，每次使用电脑查看log, 还需要不断点刷新看日志实属不太方便。
> 
> 以上是自己的一些浅薄想法，仅供大家参考。

你总结的非常好。但是我认为解决这个需求的最终形态还是我上面提到的一个全局仪表盘，这个仪表盘包含所有依赖系统的健康状态检测，机器人自身任务运行情况，一个全面的dashboard，而不是log

**Comment by Alano-i** [comment]
没错，`全局 dashboard` 作为最终形态很不错，也是比log更加直观的数据可视化呈现形式，我觉得没有任何问题，比 log 更出色。

不过，产品都会不断迭代进化，直接使用最终目标来限定当前产品，难免有失偏颇。

当前产品开发阶段，个人觉得` log `也许更加适合这群喜欢折腾的小伙伴，开发难度或许也更低。都希望产品能越来越好。

最后，关于这些想法纯属个人的建议，作者有作者的考量，角度不同考虑不同。

以上。

**Comment by pofey** [comment]
> 没错，`全局 dashboard` 作为最终形态很不错，也是比log更加直观的数据可视化呈现形式，我觉得没有任何问题，比 log 更出色。
> 
> 不过，产品都会不断迭代进化，直接使用最终目标来限定当前产品，难免有失偏颇。
> 
> 当前产品开发阶段，个人觉得`log`也许更加适合这群喜欢折腾的小伙伴，开发难度或许也更低。都希望产品能越来越好。
> 
> 最后，关于这些想法纯属个人的建议，作者有作者的考量，角度不同考虑不同。
> 
> 以上。

主要是有太多更高优先级的事情还在慢慢优化中

**Comment by zsgcgrs** [comment]
需要web日志，因为我经常去Portainer去看日志，来查看运行状态

**Comment by dyg777** [comment]
确实需要,毕竟这个有的时候.更多联动太多.如站点.网络,等
