### ISSUE TITLE
挂载盘做片库出现复制文件的问题

### ISSUE THREAD

**Issue by axunrun** [pofey/movie_robot#165]
我是用115云盘做片库的，需求是下载完成后复制到115的挂载盘，系统是UNRAID。目前出现问题时会重复复制多份文件到目标目录，这个有没有相关的设置进行处理？有以下的报错，事实上是上传成功了，只是上传了两次，有两份片源在整理路径里面。
2022/05/19 20:47:11 - ThreadPoolExecutor-1_0 - INFO: 已处理：刺猬索尼克2 (2022) 源路径: /video/disk1/download/dy/Sonic.the.Hedgehog.2.2022.1080p.WEBRip.AAC2.0.x264-SHITBOX/Sonic.the.Hedgehog.2.2022.1080p.WEBRip.AAC2.0.x264-SHITBOX.mp4, 目的路径: /video/disk2/media/115/filmguodu/刺猬索尼克2 (2022) [tmdbid=675353]/刺猬索尼克2 (2022) [tmdbid=675353] - 1080p x264 AAC.mp4
2022/05/19 20:47:11 - ThreadPoolExecutor-1_0 - ERROR: TMDB ID: 675353没有找到在影音库的对应媒体库，路径: /video/disk2/media/115/filmguodu

**Comment by pofey** [comment]
不解决此类问题，自己探索办法。机器人底层就目前支持系统硬链接和copy模式的文件整理，你需要再次逻辑之上，优化自己的方案。
