### ISSUE TITLE
请问有没有支持迅雷远程下载的计划

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#170]
请问有没有支持迅雷远程下载的计划，对于不玩PT的来说迅雷下载的速度还是很快的

**Comment by pofey** [comment]
这拨人不是本产品用户群

**Comment by elic6699** [comment]
玩PT门槛高，毕竟算小众。就是提个建议，别介意。

**Comment by pofey** [comment]
小众正是发展理念，不走大众化路线。功能的拓展，围绕着更好的体验向前走，而不是更多的人可以用，或者更低的门槛。
