### ISSUE TITLE
关于综艺的订阅问题

### ISSUE THREAD

**Issue by leo8912** [pofey/movie_robot#176]
订阅了几个综艺，今天有空准备看一看，结果发现集数乱七八糟，很多错的少的。
鉴于综艺现在的命名，什么超前版，先导版，上，下，partA,partB，与tmdb跟豆瓣都对不上信息，很难解决刮削问题。
所以是否可以加个设置，订阅综艺时硬链只硬链到正确综艺名的目录下，不刮削改名具体的的每一集，按照原文件名全部直接硬链到同一综艺名的文件夹下。这样视频都在，每个综艺的照片墙也没问题。
真人看到综艺名称也是能看懂先后顺序与集数，不会影响观看

**Comment by pofey** [comment]
发一些综艺的例子看看

**Comment by leo8912** [comment]
> 发一些综艺的例子看看

现在只看了声生不息，明星大侦探。这两个集数都是乱的。
后来手动搜了声生不息，发现是有先导版，纯享版，超前营业。。。![Screenshot_2022-05-20-22-17-33-121_com.kiwibrowser.browser.png](https://user-images.githubusercontent.com/22719866/169547805-30ec0c8a-f7cf-4cac-99da-8974f40ba575.png)
手动搜了大侦探，是按故事区分集数，命名上中下分级。
![Screenshot_2022-05-20-22-18-47-548-edit_com.kiwibrowser.browser.jpg](https://user-images.githubusercontent.com/22719866/169547900-97379f87-d5c9-4afe-bd94-77ebc7cf4926.jpg)
个人觉得这其实pt站的命名还是比较合理的，tmdb添加综艺时是只能添加第几集，其实没有种子命名合理。
如果因为跟tmdb对不上，导致追剧下载识别不到缺的集数，可以只下最先发第一集的站的资源。（同一个站的命名也会比较统一）硬链改名的时候只需要识别到分季就可以

**Comment by leo8912** [comment]
硬链刮削命名的时候可以保留这部分，这样文件夹也是会比较整洁的。
![IMG_20220520_222804.jpg](https://user-images.githubusercontent.com/22719866/169549830-68149f2d-649d-453d-81cb-21ff80ef97dc.jpg)

**Comment by pofey** [comment]
这种国产综艺还是直接看视频平台就好了吧，为什么要追这些，我以为是海外的

**Comment by leo8912** [comment]
> 这种国产综艺还是直接看视频平台就好了吧，为什么要追这些，我以为是海外的

这个跟订阅电视剧的需求一样啊，而且emby是能区分partAB的，如果放弃这个，那自动化的意义不就只剩订阅未出的电影了么。。

**Comment by pofey** [comment]
那你还不是本产品用户，建议弃用，如果付费了找我退款
