### ISSUE TITLE
订阅与下载出错

### ISSUE THREAD

**Issue by axunrun** [pofey/movie_robot#179]
图中一部分通过豆瓣想看，一部分通过jellyseer请求，都出现下图中问题，搭建测试的时候是成功的，并非全部出错，也正常下载了一些电影。
![微信图片_20220520224010](https://user-images.githubusercontent.com/97007105/169552191-6344b3b5-0cfc-49cb-87a2-c02cec0a602d.png)

**Comment by pofey** [comment]
检查自己网络访问tmdb的可靠性
