### ISSUE TITLE
获取种子hash失败

### ISSUE THREAD

**Issue by axunrun** [pofey/movie_robot#180]
2022/05/21 02:49:16 - ThreadPoolExecutor-1_0 - INFO: 开始同步站点资源信息...
2022/05/21 02:49:22 - ThreadPoolExecutor-1_0 - INFO: RARBG最新种子同步完成。
2022/05/21 02:49:23 - ThreadPoolExecutor-1_0 - INFO: pt时间最新种子同步完成。
2022/05/21 02:49:23 - ThreadPoolExecutor-1_0 - INFO: 所有站点资源信息已经更新完毕。
2022/05/21 02:49:24 - ThreadPoolExecutor-1_0 - INFO: 开始筛选免费种子。
2022/05/21 02:49:24 - ThreadPoolExecutor-1_0 - INFO: 有1个免费种子需要下载，开始提交到下载器。
2022/05/21 02:49:24 - ThreadPoolExecutor-1_0 - INFO: 免费种子提交下载队列完成。
2022/05/21 02:49:24 - DownloadConsumer - INFO: 开始处理免费种子下载任务: [pttime]Love.Death.and.Robots.S03.1080p.NF.WEBRip.DDP5.1.Atmos.x264-SMURF[rartv]
2022/05/21 02:49:24 - DownloadConsumer - ERROR: 获取种子hash失败：/data/torrent/a81319a8b1bf283654acd843ec787851.torrent

2022/05/21 02:49:24 - DownloadConsumer - ERROR: 处理下载任务失败：

2022/05/21 01:58:21 - ThreadPoolExecutor-1_1 - INFO: 开始筛选免费种子。
2022/05/21 01:58:21 - ThreadPoolExecutor-1_1 - INFO: 有1个免费种子需要下载，开始提交到下载器。
2022/05/21 01:58:21 - ThreadPoolExecutor-1_1 - INFO: 免费种子提交下载队列完成。
2022/05/21 01:58:21 - DownloadConsumer - INFO: 开始处理免费种子下载任务: [pttime]Halo S01 2160p WEB-DL H265 HDR DDP5.1 Atmos
2022/05/21 01:58:21 - DownloadConsumer - ERROR: 获取种子hash失败：/data/torrent/8ab2177bfb9917ce68301c19d4d78f6d.torrent

2022/05/21 01:58:21 - DownloadConsumer - ERROR: 处理下载任务失败：

**Comment by pofey** [comment]
自己记事本打开这种看看怎么回事
