### ISSUE TITLE
下了十几部电影，到目前为止没有任何一部下载字幕成功

### ISSUE THREAD

**Issue by axunrun** [pofey/movie_robot#181]
Traceback (most recent call last):
File "yee/consumer/downloadconsumer.py", line 39, in yee.consumer.downloadconsumer.DownloadConsumer.run
File "yee/service/downloadservice.py", line 503, in yee.service.downloadservice.DownloadService.download_to_free_record
File "yee/core/downloadclient.py", line 108, in yee.core.downloadclient.DownloadClient.info_hash
File "yee/core/downloadclient.py", line 102, in yee.core.downloadclient.DownloadClient.info_hash
File "yee/core/downloadclient.py", line 103, in yee.core.downloadclient.DownloadClient.info_hash
File "/dependencies/bencoder.py", line 93, in decode
ret, rest = decode_first(s)
File "/dependencies/bencoder.py", line 88, in decode_first
assert False
AssertionError
2022/05/21 01:33:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:33:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:34:00
2022/05/21 01:34:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:34:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:35:00
2022/05/21 01:35:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:35:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:36:00
2022/05/21 01:36:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:36:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:37:00
2022/05/21 01:37:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:37:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:38:00
2022/05/21 01:38:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:38:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:39:00
2022/05/21 01:39:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:39:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:40:00
2022/05/21 01:40:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:40:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:41:00
2022/05/21 01:41:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:41:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:42:00
2022/05/21 01:42:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:42:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:43:00
2022/05/21 01:43:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:43:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:44:00
2022/05/21 01:44:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:44:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:45:00
2022/05/21 01:45:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:45:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:46:00
2022/05/21 01:46:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:46:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:47:00
2022/05/21 01:47:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:47:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:48:00
2022/05/21 01:48:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:48:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:49:00
2022/05/21 01:49:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:49:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:50:00
2022/05/21 01:50:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:50:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:51:00
2022/05/21 01:51:00 - ThreadPoolExecutor-1_3 - INFO: 魔法满屋(2021)字幕下载已经提交启动。
2022/05/21 01:51:00 - SubRequestConsumer - INFO: 魔法满屋(2021)字幕下载 下次运行时间：2022-05-21 01:52:00
2022/05/21 01:57:54 - ThreadPoolExecutor-1_1 - INFO: 开始同步站点资源信息...
2022/05/21 01:58:17 - ThreadPoolExecutor-1_1 - INFO: RARBG最新种子同步完成。
2022/05/21 01:58:18 - ThreadPoolExecutor-1_1 - INFO: pt时间最新种子同步完成。
2022/05/21 01:58:18 - ThreadPoolExecutor-1_1 - INFO: 所有站点资源信息已经更新完毕。
2022/05/21 01:58:20 - SubConsumer - INFO: 星际迷航：奇异新世界(2022) 没有搜索到缺失的[4, 5]集
2022/05/21 01:58:21 - ThreadPoolExecutor-1_1 - INFO: 开始筛选免费种子。
2022/05/21 01:58:21 - ThreadPoolExecutor-1_1 - INFO: 有1个免费种子需要下载，开始提交到下载器。
2022/05/21 01:58:21 - ThreadPoolExecutor-1_1 - INFO: 免费种子提交下载队列完成。
2022/05/21 01:58:21 - DownloadConsumer - INFO: 开始处理免费种子下载任务: [pttime]Halo S01 2160p WEB-DL H265 HDR DDP5.1 Atmos
2022/05/21 01:58:21 - DownloadConsumer - ERROR: 获取种子hash失败：/data/torrent/8ab2177bfb9917ce68301c19d4d78f6d.torrent

2022/05/21 01:58:21 - DownloadConsumer - ERROR: 处理下载任务失败：

**Comment by pofey** [comment]
版本号 以及证明你媒体服务器需要下字幕的影片刮削正常
