### ISSUE TITLE
【BUG】rarbg api搜索结果和站点结果不同步

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#184]
rarbg视频下载似乎无法检索到4K，如 记忆,Memory,tt11827628 ，我第一条规则是
<img width="2606" alt="截屏2022-05-21 18 00 03" src="https://user-images.githubusercontent.com/105474506/169646457-f4b14702-5da3-4559-9f06-9f8a3af82425.png">
手动检索有以下种子，共10条记录
<img width="609" alt="截屏2022-05-21 18 01 11" src="https://user-images.githubusercontent.com/105474506/169646479-e01318c5-1c2a-4bf5-8ebc-cd8315e50654.png">
但是最终下载的是 Memory.2022.1080p.WEBRip.DD5.1.x264-NOGRP，没有匹配到4K
查看log，系统只检索到7条记录
 2022/05/21 17:47:08 - SubConsumer - INFO: 已经开始在站点: RARBG 搜索: 记忆,Memory,tt11827628
 2022/05/21 17:47:12 - SubConsumer - INFO: 共在1个站点搜索到7条结果，其中RARBG最慢，耗费3.62秒

搜不到4K的
<img width="582" alt="截屏2022-05-21 19 18 20" src="https://user-images.githubusercontent.com/105474506/169649354-e9a4e6aa-dc57-46a3-a61f-79d844aba1f1.png">

**Comment by pofey** [comment]
我看了下这个问题似乎无解，用rarbg的api搜索就是没有这个结果，无论imdbid还是关键词搜索

**Comment by elic6699** [comment]
请问这个问题是否能解决？jackett的搜索结果就是全的
![image](https://user-images.githubusercontent.com/105474506/171003231-a53abf63-c264-48be-89a6-a1899839b6b0.png)

**Comment by pofey** [comment]
APP_ID = "m-bot"
    ENDPOINT = 'http://torrentapi.org/pubapi_v2.php'

这是在用的rarbg api，应该和jackett是一样的吧

**Comment by elic6699** [comment]
jackett我试了很多片子都是全的，它用的什么api就不太清楚了

**Comment by pofey** [comment]
我看了下jackett的源码：https://github.com/Jackett/Jackett/blob/861b71034611039bb171cfc32fa39cfe42a8e843/src/Jackett.Common/Indexers/RarBG.cs
用了和他一摸一样的参数和接口，就是不出来俩视频，你自己也可以试试
https://torrentapi.org/pubapi_v2.php?format=json_extended&limit=100&search_imdb=tt11827628&token=ms5jgkx7ce&app_id=m-bot&mode=search&ranked=0

**Comment by pofey** [comment]
无法修复先关闭了

**Comment by elic6699** [comment]
好的，幸苦了

**Comment by elic6699** [comment]
观察了一下，好像是所有265编码的都没有，看看对你排查有没有帮助

**Comment by pofey** [comment]
这个非常诡异了 因为访问的就是原始接口 都没有经过程序 浏览器直接访问

**Comment by elic6699** [comment]
https://torrentapi.org/pubapi_v2.php?token=w8xv6a3rs0&format=json_extended&app_id=jackett_v0.20.1125&limit=100&ranked=0&sort=last&mode=search&search_imdb=tt11827628&category=14%3B17%3B18%3B23%3B25%3B27%3B28%3B32%3B33%3B40%3B41%3B42%3B44%3B45%3B46%3B47%3B48%3B49%3B50%3B51%3B52%3B53%3B54

**Comment by elic6699** [comment]
这个能搜到，你试试

**Comment by elic6699** [comment]
![image](https://user-images.githubusercontent.com/105474506/171342476-579485f4-8116-458b-b2a9-4b71de910abc.png)

**Comment by elic6699** [comment]
去掉category就不行了

**Comment by elic6699** [comment]
有需求就有动力，哈哈

**Comment by pofey** [comment]
> tt11827628

6666 带上所有分类查询，出来了，下一个版本上线
