### ISSUE TITLE
能否适配一下HDSky的TV命名规则

### ISSUE THREAD

**Issue by MyFaith** [pofey/movie_robot#185]
![image](https://user-images.githubusercontent.com/8826441/169654181-2f02b0e3-a840-41c9-b225-b6f58da17f44.png)

**Comment by pofey** [comment]
这是要干啥

**Comment by MyFaith** [comment]
手动下载和订阅无法对这种命名规则的正常解析

**Comment by pofey** [comment]
有几个因素不准备优化国产综艺识别了，外国的会优化
1、国内视频网站活得不容易，这种资源部鼓励用机器人追
2、tmdb上数据标准和pt站点的综艺数据标准有差异，tmdb也不及时，所以这块识别不好
