### ISSUE TITLE
【优化】网页订阅时去掉确认框，默认自动

### ISSUE THREAD

**Issue by elle007011** [pofey/movie_robot#187]
比如订阅页面，剧集以一个海报图片展现，默认订阅为全季，如果要订阅单季，可以在二级页面（或点击展开各季海报）单独点击订阅？

洗版以集为单位，比如目前风骚律师第六季，只有6集，还没有完结，但已经有2160P的更好版本，可以替换之前下载的1080P版本了，能否自动开始洗版？

最后是老生常谈的过滤器使用需求，就是如果设置好过滤器及其优先级，可以自动按照过滤器结果进行订阅，不再弹出对话框确认是否使用默认过滤器来下载

**Comment by pofey** [comment]
剧集单集洗版当初没做我有几个考虑，1）电视剧这东西看完重复在看的概率非常低，我好像几乎没有，那么肯定是想等到品质更好的出了在看；2）当时的架构，单集替换还比较复杂；
订阅弹框的问题也想过，没去掉是因为有些剧的品质无法确定，确实会想为某部剧独立设置一个过滤器，如果一刀切不弹窗，就很难交互了。

**Comment by elle007011** [comment]
> 剧集单集洗版当初没做我有几个考虑，1）电视剧这东西看完重复在看的概率非常低，我好像几乎没有，那么肯定是想等到品质更好的出了在看；2）当时的架构，单集替换还比较复杂；
> 订阅弹框的问题也想过，没去掉是因为有些剧的品质无法确定，确实会想为某部剧独立设置一个过滤器，如果一刀切不弹窗，就很难交互了。

一点意见，供群主参考。

其实有了机器人之后，看和保存就是两件事了。是不是可以支持一个策略，就是先看再洗？第一时间跟得上最新的电影/剧集。看过之后机器人自动洗版，建立保存一个最新、最好版本的影音库？再看的时候，洗版还会给一个惊喜。

过滤器也是一样，99.9%的时候根据IFTTT的过滤器设置进行下载，需要手动的时候再进行手动设置。在这时候，是否可以考虑前面99.9%的状况可以无需弹窗。

谢谢群主的回复

**Comment by pofey** [comment]
电影支持先看再洗，剧集后面肯定也会支持。但是不选过滤器的交互，还是没想清楚

**Comment by elle007011** [comment]
> 电影支持先看再洗，剧集后面肯定也会支持。但是不选过滤器的交互，还是没想清楚

简单的办法是开一个手动二次确认的选项。点上这个选项就每次都需要交互，不点这个选项就直接按照设置好的过滤器来做过滤

**Comment by pofey** [comment]
偶尔想手动 还要去打开开关

**Comment by elle007011** [comment]
> 偶尔想手动 还要去打开开关

是啊，我觉得偶尔手动，打开开关，比每次都交互一下更有效率

**Comment by pofey** [comment]
偶尔打开一下，感觉还是很不麻烦，有没有更好的办法？

**Comment by elle007011** [comment]
> 偶尔打开一下，感觉还是很不麻烦，有没有更好的办法？

我能想到的，就是在订阅页面手动设置，今后洗版按照个性化需求进行。但是如果想一次搞定，这个我也真想不出什么好办法来
