### ISSUE TITLE
【问题】部分影片字幕无法下载

### ISSUE THREAD

**Issue by Jim-CN** [pofey/movie_robot#193]
刚刚付费转投robot，感谢大佬写了这么好的应用！
试用1周，发现部分影片无法下载字幕：
1、巨星嫁到
<img width="869" alt="1653294049" src="https://user-images.githubusercontent.com/86034975/169777032-d060835d-f156-43ec-b3ea-58b4cc2f9ab6.png">
<img width="571" alt="1653294049(3)" src="https://user-images.githubusercontent.com/86034975/169777045-e26b918a-c749-416d-acb2-527265efa712.png">
<img width="856" alt="1653294049(1)" src="https://user-images.githubusercontent.com/86034975/169777064-390800ff-4fbe-47aa-823a-e29baf8d55b0.png">
<img width="1030" alt="1653294049(2)" src="https://user-images.githubusercontent.com/86034975/169777090-cc5f4608-800e-4bbd-ab25-8c845013d151.png">
2、健听女孩
<img width="901" alt="1653294060(1)" src="https://user-images.githubusercontent.com/86034975/169777167-ebf57203-623c-4263-911d-45a227a074d8.png">

**Comment by pofey** [comment]
等下个版本加日志以及观察新下的情况吧
