### ISSUE TITLE
希望增加海胆站点

### ISSUE THREAD

**Issue by jinfeng1985** [pofey/movie_robot#194]
目前好像还没有。

**Comment by pofey** [comment]
我已经不在适配站点了 都是网友热心贡献 想要你可以自己研究下

**Comment by pofey** [comment]
配置目录 sites文件夹 全是站点适配文件

**Comment by jinfeng1985** [comment]
> 配置目录 sites文件夹 全是站点适配文件

试着研究了几天，太菜了，搞不定，请问如果付费了，有群什么，请教其他大神的？

**Comment by pofey** [comment]
有群 但是大家对这个站可能已经没什么兴趣了 估计没人去适配，这个站魔改了很多东西，得到的价值远大于定制化适配的成本。
