### ISSUE TITLE
【求助】m-team站点无法添加

### ISSUE THREAD

**Issue by Sizukaze** [pofey/movie_robot#195]
测试过网站访问正常，之前一直在做种连接正常。
可以直接访问网站无需代理。
![M-Team - TP  用戶詳情 - Sizukaze - Powered by NexusPHP_2022-05-23_21-33-13](https://user-images.githubusercontent.com/53135795/169831865-c668ca75-2407-44c5-be70-e9ae7a775a22.png)

但是在Movie-Robot里面添加馒头，一直添加失败。
浏览器里获取的cookie格式是**cf_clearance=XXXXXXXXX;tp=XXXXXXXX;**
添加进去直接报错。后台显示
![2022-05-23_21-34-57](https://user-images.githubusercontent.com/53135795/169831932-4e1af594-b6d5-4c85-a81e-9ec6bc48488e.png)
![2022-05-23_21-35-30](https://user-images.githubusercontent.com/53135795/169831977-4875b7e0-a461-4e51-ac1e-7d99f04bfcd4.png)
用另一个浏览器插件提取的cookie格式是**tp:XXXXXXXX;cf_clearance:XXXXXXXXX;**
添加进去无限五秒盾,馒头注销重新登录再次获取还是一样，重试多次都是一样。
![2022-05-23_21-41-39](https://user-images.githubusercontent.com/53135795/169832922-ff2b4ad6-3de2-470e-988e-e3eb006a22ae.png)
![2022-05-23_21-41-55](https://user-images.githubusercontent.com/53135795/169832936-f1c5c3cf-cad1-4aa3-9d45-96f9adba5258.png)

按照提示刷新网页，重新登录多次都是一样，用PT助手插件访问馒头数据是正常的

**Comment by pofey** [comment]
开了二级验证？

**Comment by Sizukaze** [comment]
> 开了二级验证？

。。。确实，刚才试了下关闭二级验证之后就可以了。
谢谢！
