### ISSUE TITLE
【需求】能否添加Telegram推送?

### ISSUE THREAD

**Issue by WuhanSy** [pofey/movie_robot#197]
telegram推送有计划去开发这个功能吗?

**Comment by pofey** [comment]
这个倒是没什么难度，但是我实在想不到有什么必要去用tg通知的场景，体验上我也觉得不会有什么提升

**Comment by onmpen** [comment]
> 这个倒是没什么难度，但是我实在想不到有什么必要去用tg通知的场景，体验上我也觉得不会有什么提升

主要是应该习惯了用 telegram 而且对使用者来说，设置上可能更简单

**Comment by pofey** [comment]
> > 这个倒是没什么难度，但是我实在想不到有什么必要去用tg通知的场景，体验上我也觉得不会有什么提升
> 
> 主要是应该习惯了用 telegram 而且对使用者来说，设置上可能更简单

pushdeer bark其实是最简单的

**Comment by WuhanSy** [comment]
最好把企业微信上的搜索和订阅功能都加上。

**Comment by pofey** [comment]
先关了 感受不到tg体验有啥优势
