### ISSUE TITLE
下载目录变更导致订阅下载失败

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#198]
由于下载器从套件换成docker，所以目录链接也相对更换了，已经在mr中对应修改，但是订阅的电视剧似乎仍旧使用原先设置的目录链接，导致下载失败。使用web搜索后手动下载是正常的。log如下
2022/05/24 10:54:40 - DownloadConsumer - INFO: 开始处理来自订阅的下载: [rarbg]Better.Call.Saul.S06E07.1080p.WEB.H264-CAKES[rartv]
2022/05/24 10:54:40 - DownloadConsumer - ERROR: 找不到/share/Movie/电视剧对应的媒体路径设置，请检查基础设置-存储路径设置，以及思考你是否变更过设置。 
2022/05/24 11:06:32 - Thread-384 - INFO: 已经开始在站点: RARBG,pt时间 搜索: Better.Call.Saul.S06E07
2022/05/24 11:06:34 - Thread-384 - INFO: 共在2个站点搜索到5条结果，其中pt时间最慢，耗费2.2秒
2022/05/24 11:07:07 - DownloadConsumer - INFO: 开始处理来自Web的下载: [rarbg]Better.Call.Saul.S06E07.1080p.WEB.H264-CAKES[rartv]

**Comment by pofey** [comment]
把配置文件里所有的目录都换成新的

**Comment by elic6699** [comment]
就是因为改了还出错我才发的，现在我把目录设置全部删除重建再观察一下

**Comment by pofey** [comment]
改之前下的就没辙了 改之后重启新下的肯定不会有问题

**Comment by elic6699** [comment]
我是说订阅电视剧，这一季还没下完，删除重新订阅的话会把所有原先下的视频文件都给删了吧

**Comment by elic6699** [comment]
知道了，深度删除不打勾，谢谢了
