### ISSUE TITLE
【BUG】一个剧集存在PARTA、PARTB时PARTB不会硬链接

### ISSUE THREAD

**Issue by happyhaha1** [pofey/movie_robot#199]
movie-robot version：0.9.24
剧集为乘风破浪的姐姐第三季
S03E01 存在PARTA、PARTB
硬链接只PARTA

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/10184254/169945882-84d28de2-6dde-4916-9cfa-858e3b373a5a.png">
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/10184254/169945933-0dfa66c7-91f9-4505-b71f-7f80ccb1c9e2.png">

**Comment by pofey** [comment]
是的 现在不支持part 未来也不一定会支持
