### ISSUE TITLE
反馈一些提交识别错误，和识别不了的，建议专门建立2个issues，让大家统一反馈

### ISSUE THREAD

**Issue by mjyhj** [pofey/movie_robot#2]
识别不了： 
ERROR: 识别不到影视信息，无法处理 查询词:['倚天屠龙记之圣火雄风 New Kung Fu Cult Master Ⅱ'] src: /download2/电影/倚天屠龙记之圣火雄风.New.Kung.Fu.Cult.Master.Ⅱ.2022.60fps.2160p.WEB-DL.AAC.H265.2Audio-HDSWEB/倚天屠龙记之圣火雄风.New.Kung.Fu.Cult.Master.Ⅱ.2022.60fps.2160p.WEB-DL.AAC.H265.2Audio-HDSWEB.mkv

ERROR: 识别不到影视信息，无法处理 查询词:['倚天屠龙记之九阳神功 New Kung Fu Cult Master Ⅰ'] src: /download2/电影/倚天屠龙记之九阳神功.New.Kung.Fu.Cult.Master.Ⅰ.2022.60fps.2160p.WEB-DL.AAC.H265.2Audio-HDSWEB/倚天屠龙记之九阳神功.New.Kung.Fu.Cult.Master.Ⅰ.2022.60fps.2160p.WEB-DL.AAC.H265.2Audio-HDSWEB.mkv

多了，New Kung Fu Cult Master Ⅰ和Ⅱ

识别其它的：
INFO: 已处理：误杀 (2019) 源路径: /download2/电影/误杀2.Fireflies.in.the.Sun.2021.2160p.WEB-DL.DDP5.1 AAC2.0.H265-HDSWEB/误杀2.Fireflies.in.the.Sun.2021.2160p.WEB-DL.DDP5.1 AAC2.0.H265-HDSWEB.mkv

误杀2变成误杀1

**Comment by pofey** [comment]
双字节中日韩文字识别改出BUG了，已经修复等发布
