### ISSUE TITLE
RARBG站点上传限制导致下载没有速度

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#210]
由于新版本RARBG上传限制在1Kbyte，导致下载速度只能在几十K，每次任务生成了只能手动去调整，请问是否能够放开？
此外RARBG部分4k种子搜索不到是否能够解决？如果暂时解决不了的话能否开放上传种子文件下载？谢谢

**Comment by pofey** [comment]
我好像听到很多人说这个问题了。但是想请教下原理，这个限速机制是如何做的，谁做的？

**Comment by elic6699** [comment]
不清楚原因啊，我也是小白

**Comment by elic6699** [comment]
看看这个？ https://www.reddit.com/r/torrents/comments/7zqq5h/qbittorrent_limiting_upload_speed_also_lowers/

**Comment by pofey** [comment]
后面改独立下载器了

**Comment by pofey** [comment]
0.9.36 支持aria2了，这个上传限制取消了
