### ISSUE TITLE
建议增加手动下载字幕功能

### ISSUE THREAD

**Issue by LeeHK1989** [pofey/movie_robot#211]
现在只能通过自动下载，3天后不下载。但有时候3天内没有出字幕，或者出的字幕不够精校。
建议增加一个单部电影或剧集的手动启动下载字幕功能。

**Comment by pofey** [comment]
后面要有专门页面的 要1.0之后了

**Comment by horseytr** [comment]
这个正是我想提的，现在是可以先试emby存在的剧集或则电视，需求单独对某一或某一集电视剧，手动下载字幕

**Comment by pofey** [comment]
想清楚的需求和场景，就会开放出来，没想清楚，不会草率的去加功能。私有化部署的产品，旧升新，代价比较大，使用习惯的变化也会很不适应。更重要的是没想清楚随便加的功能也不好用。

**Comment by pofey** [comment]
索索到本地媒体库资源时已经可以直接发起字幕下载任务了
