### ISSUE TITLE
订阅了一堆电影剧集为什么只检索几部？

### ISSUE THREAD

**Issue by LeeHK1989** [pofey/movie_robot#214]
<img width="1640" alt="iShot_2022-05-27_14 12 06" src="https://user-images.githubusercontent.com/106141368/170641406-91b7607c-5ddc-415e-a6d0-6c2e5b637ab3.png">
<img width="781" alt="iShot_2022-05-27_14 12 27" src="https://user-images.githubusercontent.com/106141368/170641423-7d5f6605-925c-463f-8b19-814aa0de23ae.png">

一开始我以为是即将开播才会搜索，但是今天欧比旺开播了，网上已经有资源了，程序还是没有开始搜索，我明明订阅了 这是为什么啊？

**Comment by pofey** [comment]
一个问题一个问题聊。就先说欧比旺，你截下欧比旺的订阅图，我看看右上角是什么状态，你这太多，我看不出来是哪个。另外，你也手动搜索一下，贴一下你期望下载的资源是什么。
