### ISSUE TITLE
字幕下载提示媒体库还没刮好

### ISSUE THREAD

**Issue by jinfeng1985** [pofey/movie_robot#215]
我所有下载的，下载完成后，都提示媒体库还没刮好，等会儿再试。重复几遍后就提示请求数量满了，就完全停止下载字幕了。请问这是我哪里设置不对吗？

**Comment by pofey** [comment]
发版本号，和日志，以及本地媒体库确实刮好的记录截图看看

**Comment by jinfeng1985** [comment]
> 发版本号，和日志，以及本地媒体库确实刮好的记录截图看看

麻烦问下，本地媒体库确实刮好的记录  这是在哪里的？是jellyfin里面？

**Comment by pofey** [comment]
> > 发版本号，和日志，以及本地媒体库确实刮好的记录截图看看
> 
> 麻烦问下，本地媒体库确实刮好的记录 这是在哪里的？是jellyfin里面？

你用的哪个媒体服务器，就截你认为已经在jellyfin里能看到的那部片子

**Comment by jinfeng1985** [comment]
> > > 发版本号，和日志，以及本地媒体库确实刮好的记录截图看看
> > 
> > 
> > 麻烦问下，本地媒体库确实刮好的记录 这是在哪里的？是jellyfin里面？
> 
> 你用的哪个媒体服务器，就截你认为已经在jellyfin里能看到的那部片子

不好意思，原来是我媒体的文件夹弄错了，怪不得…现在好了
