### ISSUE TITLE
提一些小小的建议😁

### ISSUE THREAD

**Issue by miniers** [pofey/movie_robot#22]
1.抓取豆瓣详情页的视频数据可以存到数据库，记录个缓存时间，一定期限内不再去豆瓣抓
2.可以配置多个豆瓣id和对应cookie,这样豆瓣想看中的视频成功找到并下载后，就可以把该视频设置为在看，避免想看列表过长，抓取时间过长
3.豆瓣想看列表是按照加入时间顺序排列的，抓取后可以记录最新一条的时间，这样下次抓取只用抓取这个时间后的就行了，就不用遍历所有页了（如果实现这一条的话，第二条就没啥必要做了😆）
4.日志文件可以按天切片存，存一个文件过大不好翻😂
5.因为剧集好多PT站都没有年份信息，能否可以给个 配置项 可以让剧集不用强制匹配年份呢？或者给年份也作为为权重配置
6.增加手动执行的任务的cli命令或者api接口，这样就可以加入豆瓣想看后，通过ios的快捷指令来触发任务了😂不用非得等到定时时间

再次感谢大佬开发的这么好用的工具🤓

**Comment by kingswon** [comment]
第6条 或者大佬能不能给个容器内手动执行任务的命令  想测试的话  直接使用cli命令触发方式

**Comment by pofey** [comment]
0.1 版本已经完全重写了豆瓣数据获取部分代码，同时增加了自动管理标签的能力，现在速度已经非常快了。
