### ISSUE TITLE
升级到0.9.35后无法使用存量视频整理

### ISSUE THREAD

**Issue by LeeHK1989** [pofey/movie_robot#223]
![WX20220528-213804](https://user-images.githubusercontent.com/106141368/170828006-ba68aa05-3d3d-4b2d-900b-9f414153dee1.png)

机器人订阅的下载下来是可以自动归类硬链接的，但是存量视频不行。之前用0.9.24版本是可以的

**Comment by pofey** [comment]
这不是很清晰的错误了 tmdb访问失败

**Comment by LeeHK1989** [comment]
> 这不是很清晰的错误了 tmdb访问失败

但是我用订阅TMDB不会失败啊  可以正常订阅正常改名。为什么只有存量整理会失败
