### ISSUE TITLE
自动打标签

### ISSUE THREAD

**Issue by zjgithub413** [pofey/movie_robot#224]
建议：通过MR下载的种子能在qb里自动打个标签（无论是自己下载的还是养站自动下载的），标签显示的下载站的名称。现在MR是可以在qb自动分类。虽然可以挨个点tracker查看，但是在保种量大的情况下不太方便，如果能自动添加下载站的标签，可以比较直观方便的管理种子。

**Comment by pofey** [comment]
短时间不会考虑去解决种子管理领域的需求
