### ISSUE TITLE
手动添加到媒体目录的同名字幕文件，硬链时可以一并改名复制过去吗

### ISSUE THREAD

**Issue by leverule** [pofey/movie_robot#225]
某剧集种子详情页，其他人上传的处理好且改好名字的中英双语字幕文件，添加到硬链接媒体库还需要手动改名...
自动搜索字幕固然很强，但手动添加的字幕值得被珍视！

**Comment by pofey** [comment]
说的是存量字幕直接链接过去对吧？

**Comment by leverule** [comment]
> 说的是存量字幕直接链接过去对吧？

是的~

**Comment by pofey** [comment]
那这个就关了，和 #99 是同一回事
