### ISSUE TITLE
请问如何指定 UPID 与 UGID

### ISSUE THREAD

**Issue by mrLann** [pofey/movie_robot#228]
现在的情况是，qB 与 Plex 都运行在普通用户下，只有 robot 运行在 root 权限下，导致 Plex 无法在 Web 删除硬链之后的资源，只能 SSH 上去敲命令删除。

**Comment by pofey** [comment]
下个版本支持吧

**Comment by pofey** [comment]
0.9.49 已经可以通过PUID、PGID环境变量指定了
