### ISSUE TITLE
每次升级TMDB

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#229]

**Comment by elic6699** [comment]
每次升级TMDB FANart 代理设置都丢失，需要手工再次添加

**Comment by pofey** [comment]
好像没这回事 头一回听说

**Comment by elic6699** [comment]
我升了两个版本都碰到了

**Comment by pofey** [comment]
发出来你的操作步骤以及配置变化

**Comment by elic6699** [comment]
正常通过watchtower升级，升级完以下代理配置就空了
![image](https://user-images.githubusercontent.com/105474506/170899991-c1645cf0-20e7-4cf8-b312-0654091c402f.png)
Fanart那里也是一样
我是在升级完后后台log看见tmdb连接报错才发现的，两次升级都这样

**Comment by pofey** [comment]
确实，我重现了

**Comment by pofey** [comment]
下个版本修复上去
