### ISSUE TITLE
自由下载指定目录错误后，程序报错后不能继续处理其他内容

### ISSUE THREAD

**Issue by BruceSuen720** [pofey/movie_robot#23]
自由下载的时候，如果一不小心放错目录了之后（比如  把电影不小心放到了电视剧的目录） 程序无法识别处理，会报错，提示监控种子出现错误，但不影响下一次运行，此时程序会一直循环在这个错误里，其他自由下载的正确的任务也不会处理了。
是否可以在出现这种错误时，跳过硬链接，并继续处理其他任务

**Comment by pofey** [comment]
版本号是多少
