### ISSUE TITLE
多个下载器支持导致下载目录不统一

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#230]
由于新版本支持了多个下载器，而我目前qbit使用docker版，aria2使用的是套件，导致下载目录无法一致，请问能否将下载目录优化至各个下载器页面分开设置？谢谢

**Comment by pofey** [comment]
为何不能一致 一定是可以的

**Comment by elic6699** [comment]
好的，自己通过修改挂载目录解决了
