### ISSUE TITLE
下面的支付宝二维码只显示了一半，我换了台电脑依旧这样，怎么弄呢？

### ISSUE THREAD

**Issue by axunrun** [pofey/movie_robot#233]

**Comment by axunrun** [comment]
![图片](https://user-images.githubusercontent.com/97007105/170915308-52d1bf88-47b2-4aa4-9434-4526400ec9cb.png)

**Comment by pofey** [comment]
https://yee-1254270141.cos.ap-beijing.myqcloud.com/movie_robot/alipay.jpg
这个能直接打开
