### ISSUE TITLE
Aria2下载器下载rarbg问题

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#235]
使用aria2下载rarbg，下载开始了一会儿就在mr端显示下载完成，但是实际aria2还在下载中，
![image](https://user-images.githubusercontent.com/105474506/170922209-34f86046-c624-42fe-b6bb-115bc9885978.png)
![image](https://user-images.githubusercontent.com/105474506/170922277-f6a8b2d2-895e-4cbc-9069-7ac799aeba4d.png)

log如下：

2022/05/30 13:01:36 - DownloadConsumer - INFO: 开始处理来自订阅的下载: [rarbg]Inland.Empire.2006.1080p.BluRay.H264.AAC-RARBG
2022/05/30 13:01:36 - DownloadConsumer - INFO: [rarbg]Inland.Empire.2006.1080p.BluRay.H264.AAC-RARBG已经开始下载,路径：/share/Movie/电影 分类：未设置 
2022/05/30 13:03:00 - ThreadPoolExecutor-3_1 - INFO: 开始为电影 内陆帝国 (2006)做文件转移 源路径：/video/电影/[METADATA]Inland.Empire.2006.1080p.BluRay.H264.AAC-RARBG 链接路径：/video/电影-jellyfin
2022/05/30 13:03:00 - ThreadPoolExecutor-3_1 - ERROR: 需要处理的路径不存在或无法访问：/video/电影/[METADATA]Inland.Empire.2006.1080p.BluRay.H264.AAC-RARBG
2022/05/30 13:03:00 - ThreadPoolExecutor-3_1 - ERROR: 找不到内陆帝国(2006)的内容存放路径。

 我看了一下实际目录应该是、/video/电影/Inland.Empire.2006.1080p.BluRay.H264.AAC-RARBG] ,不知道为什么前面加了个 [METADATA]，

**Comment by pofey** [comment]
提交到aria2的种子好像一个infohash被拆成了两个任务，一个metadata下载，一个实际文件下载。优化了一下对metadata任务的排除，下个版本尝试修复。0.9.41
