### ISSUE TITLE
[Bug]monitor_all_torrent 设定为 false 时，MR 依旧监控下载器的手动种子添加(辅种)

### ISSUE THREAD

**Issue by mrLann** [pofey/movie_robot#237]
复现版本：0.9.36 - 0.9.46
下载器：qBittorrent 4.3.9
相关信息：
<img width="1232" alt="Snipaste_2022-05-31_02-52-16" src="https://user-images.githubusercontent.com/7830924/171047422-3bad622d-97cc-4849-8990-174ffcae7eb7.png">
![image](https://user-images.githubusercontent.com/7830924/171048495-ec15817a-e44b-41b7-a8ff-49d038de8dbd.png)

**Comment by mrLann** [comment]
目前执行辅种操作的时候，先暂时关掉MR。

**Comment by pofey** [comment]
你只有一个下载器对么

**Comment by mrLann** [comment]
> 你只有一个下载器对么

是的，只有一个qBit客户端

**Comment by pofey** [comment]
> > 你只有一个下载器对么
> 
> 是的，只有一个qBit客户端

升级一下 已经修复了
