### ISSUE TITLE
订阅失败

### ISSUE THREAD

**Issue by w905581962** [pofey/movie_robot#239]
版本为：0.9.46
错误日志：
![image](https://user-images.githubusercontent.com/40052692/171095069-353e1d3a-088d-4c31-84db-9c6e782d3558.png)
MR界面，我的订阅为空

豆瓣想看配置：
![image](https://user-images.githubusercontent.com/40052692/171095380-096ebbf0-890a-44fc-9238-95dddd316e52.png)

保存路径测试没有问题
![image](https://user-images.githubusercontent.com/40052692/171095466-01ecbac8-9282-49de-8e7e-446bf8b8f4bf.png)

**Comment by pofey** [comment]
你的媒体服务器挂了没连上，重启吧

**Comment by w905581962** [comment]
一定要连媒体服务器吗？，之前是想就做一个下载窗口使用的。

**Comment by pofey** [comment]
必须连，不连怎么去重，怎么解析字幕，怎么联动
