### ISSUE TITLE
剧集的新集数种子选择错误（选到了整季）

### ISSUE THREAD

**Issue by jsl9208** [pofey/movie_robot#24]
2022/02/23 11:31:11 - ThreadPoolExecutor-0_1 - INFO: 绿色星球(2022)在影视库存在，但缺少第[6]集
2022/02/23 11:31:33 - ThreadPoolExecutor-0_1 - INFO: 绿色星球(2022)使用compress策略选种
2022/02/23 11:31:33 - ThreadPoolExecutor-0_1 - INFO: 绿色星球(2022)共有1个最佳种子需要下载
2022/02/23 11:31:46 - ThreadPoolExecutor-0_1 - INFO: 绿色星球 The Green Planet (2022) | 主演: 大卫·爱登堡 | 类型: 纪录片(mteam)已经开始下载,保存分类：documentary 路径：None

选择到的种子是前五集的集合
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/4048787/155260436-dfb96c63-24e8-4b95-9cb8-cf1f0d5003a5.png">

**Comment by pofey** [comment]
豆瓣之前绿色星球集数错误，我编辑过来了。
