### ISSUE TITLE
剧集订阅的下载机制是就这样设计的还是bug呢？

### ISSUE THREAD

**Issue by GodD6366** [pofey/movie_robot#243]
Emby中已经存在1-6集了，但是检测到全集时，还是会下载完整剧集包，为什么不是只下载第七集？

![image](https://user-images.githubusercontent.com/17250383/171198804-8b4b5a26-934e-4f62-b101-ac1e78b2358e.png)

**Comment by pofey** [comment]
那个种子名有问题，拉黑吧
