### ISSUE TITLE
流量管理能否增加限速开关

### ISSUE THREAD

**Issue by 1pondog** [pofey/movie_robot#245]
目前流量管理和订阅下载用的同一个下载器，刷流是一直进行的所以我限速了10MB，不想把带宽跑满，但是订阅下载时又想满速下载，所以能否在流量管理界面增加一个限速，就像自己手动提交种子时可以选择单种的上下行速度限制一样，把整个刷流进行一个限速而又不限速订阅下载。

**Comment by pofey** [comment]
难以控制，暂时不打算去解决这个问题
