### ISSUE TITLE
阿童木不能自动养站，和其他站设置一样。

### ISSUE THREAD

**Issue by axunrun** [pofey/movie_robot#246]
2022/05/31 23:02:14 - ThreadPoolExecutor-3_2 - INFO: pt时间最新种子同步完成。
2022/05/31 23:02:16 - ThreadPoolExecutor-3_2 - INFO: RARBG最新种子同步完成。
2022/05/31 23:02:17 - ThreadPoolExecutor-3_2 - INFO: 家园最新种子同步完成。
2022/05/31 23:02:18 - ThreadPoolExecutor-3_2 - INFO: 阿童木最新种子同步完成。
2022/05/31 23:02:18 - ThreadPoolExecutor-3_2 - INFO: 所有站点资源信息已经更新完毕。
2022/05/31 23:02:20 - ThreadPoolExecutor-3_2 - INFO: 开始筛选免费种子。
2022/05/31 23:02:20 - ThreadPoolExecutor-3_2 - INFO: 有4个免费种子需要下载，开始提交到下载器。
2022/05/31 23:02:20 - ThreadPoolExecutor-3_2 - INFO: 免费种子提交下载队列完成。
2022/05/31 23:02:20 - DownloadConsumer - INFO: 开始处理免费种子下载任务: [HDHome]The Killer's Shopping List S01 1080p WEB-DL H.265 AAC-ADWeb
2022/05/31 23:02:31 - DownloadConsumer - INFO: 开始处理免费种子下载任务: [HDHome]The Avengers Earth's Mightiest Heroes S01 1080p DSNP WEB-DL DDP5.1 H.264-playWEB
2022/05/31 23:03:24 - DownloadConsumer - INFO: 开始处理免费种子下载任务: [HDHome]Bizarre Foods Delicious Destinations S02 1080p WEB-DL DDP5.1 H.264-squalor
2022/05/31 23:04:13 - DownloadConsumer - INFO: 开始处理免费种子下载任务: [HDHome]Introduction 2021 BluRay 1080p DD2.0 x264-BMD
![image](https://user-images.githubusercontent.com/97007105/171225930-0f27a8f8-e0a9-46fc-8d54-0f2da8533b92.png)

**Comment by axunrun** [comment]
今天刚注册的，想养一下上传再使用，难道是因为分享率显示无限造成的？
![image](https://user-images.githubusercontent.com/97007105/171229035-a3632023-b60e-4b1e-9813-62d0d55da7f0.png)
![image](https://user-images.githubusercontent.com/97007105/171229120-026cf127-96b5-489e-ac52-a2b2431acda1.png)
![image](https://user-images.githubusercontent.com/97007105/171229338-4e95a0ba-6901-4c73-ab84-3bf1c9354434.png)

**Comment by axunrun** [comment]
今天刚注册的，想养一下上传再使用，难道是因为分享率显示无限造成的？
![image](https://user-images.githubusercontent.com/97007105/171229035-a3632023-b60e-4b1e-9813-62d0d55da7f0.png)
![image](https://user-images.githubusercontent.com/97007105/171229120-026cf127-96b5-489e-ac52-a2b2431acda1.png)
![image](https://user-images.githubusercontent.com/97007105/171229338-4e95a0ba-6901-4c73-ab84-3bf1c9354434.png)

**Comment by pofey** [comment]
没什么问题，这些种子上传几百，下载中多为位个位数，进去就是炮灰，不会去下的。
