### ISSUE TITLE
不管选哪个排序规则，都会选用compress

### ISSUE THREAD

**Issue by phinleyfei** [pofey/movie_robot#251]
三个都试过了，但是订阅电影后日志都会提示使用compress，应用也重启过。

需要什么信息你说，我再上传。

![image](https://user-images.githubusercontent.com/105186845/171402573-6548eb55-f85d-4e36-bb65-8d0940f982d7.png)

**Comment by pofey** [comment]
三个都试过了是在哪设置的？

**Comment by pofey** [comment]
这里的设置好像失效了没有去掉，是跟随用户的，在用户管理中可以调
