### ISSUE TITLE
订阅失败

### ISSUE THREAD

**Issue by Ignatius-Ye** [pofey/movie_robot#254]
![Screenshot_20220602_170807](https://user-images.githubusercontent.com/37823715/171604266-34d89213-04f8-4afb-a570-b5a85f5e33e6.jpg)
![Screenshot_20220602_174857](https://user-images.githubusercontent.com/37823715/171604298-0ac64b3f-a399-4f3c-b87a-5c295222694c.jpg)

导致订阅失败

**Comment by pofey** [comment]
日志只有一半看不出来是访问什么失败 检查自己网络稳定性吧
