### ISSUE TITLE
【优化】能推出一个查看所有已下载文件的页面（包括web搜索下载及订阅智能下载）

### ISSUE THREAD

**Issue by zjgithub413** [pofey/movie_robot#255]
近期使用时发现emby中有一部通过web搜索下载电影识别错误，想进MR中修改，却发现在“近期下载”中只能显示一部分电影，前面的电影无法显示，因此没法修改识别。建议能在MR中增加一个页面，里面能显示所有已下载的电影（包括web搜索下载的、订阅智能下载的及后期可能会推出的通过MR整理硬链接的存量电影）方便进行媒体库的统一管理。

**Comment by zjgithub413** [comment]
另，如果增加了这个页面，便可以在这个页面中显示所有的已下载电影，不仅可以用来修改识别问题，同时也可以通过这个页面进行字幕及洗版的管理。

**Comment by pofey** [comment]
下一版开放本地资源整理页面
