### ISSUE TITLE
【BUG】剧集不知道该保存到哪

### ISSUE THREAD

**Issue by AAlexDing** [pofey/movie_robot#256]
版本：0.9.49
系统：UNRAID 5.9.2

测试保存规则后提示：剧集 史前星球(分类：纪录 区域：美国,英国)不知道该保存到哪，请检查保存规则
剧集豆瓣ID：34603375

保存规则配置：
![image](https://user-images.githubusercontent.com/30212143/171648447-d026907b-3f8b-4298-ba72-6ff55048ee89.png)
![image](https://user-images.githubusercontent.com/30212143/171648492-624a7099-dda4-4edb-98b9-62d520fbdd52.png)

另外有一个疑问：下载保存规则1,2,3,4.....是否有优先级考虑？如果有的话能否加个功能，让它直接拖动改变优先级？

**Comment by pofey** [comment]
https://yee329.notion.site/5-745da2776daa4fc7b5e2ddb3170aa11a
看wiki吧 不想解释这种配置问题了
