### ISSUE TITLE
存量片库识别的问题汇总-雅木专用

### ISSUE THREAD

**Issue by leming1982** [pofey/movie_robot#257]
**文件名特殊符号识别问题**

> 2022/06/03 10:10:42 - MainThread - INFO: 开始处理电影目录 /电影/保种/中国/香港/其他/[怒火·重案].Raging.Fire.2021.GBR.UHD.BluRay.2160p.x265.10bit.HDR.DTS-HD.MA.7.1.2Audios-CMCT 目标目录：/电影/Emby硬链/台湾
> 2022/06/03 10:11:23 - MainThread - INFO: 已处理：怒火难平 (2021) 源路径: /电影/保种/中国/香港/其他/[怒火·重案].Raging.Fire.2021.GBR.UHD.BluRay.2160p.x265.10bit.HDR.DTS-HD.MA.7.1.2Audios-CMCT/[怒火·重案].Raging.Fire.2021.GBR.UHD.BluRay.2160p.x265.10bit.HDR.DTS-HD.MA.7.1.2Audios-CMCT.mkv, 目的路径: /电影/Emby硬链/台湾/怒火难平 (2021) [tmdbid=753946]/怒火难平 (2021) [tmdbid=753946] - 2160p x265 HDR 10bit DTS-HD.mkv 

以这一段为例，tmdb 信息为：
[怒火·重案](https://www.themoviedb.org/movie/513692) (2021)
疑似在识别文件名带有特殊符号"·"时，未进行正确处理导致

**文件夹内电影同年份识别问题**

> root@yipengfei-movie-robot:/app# python commandapp.py -w=/data -a=moviesmanager --source-type=movie --source-dir=/电影/保种/中国/香港/其他/Infernal.Affairs.Trilogy.2002-2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD/Infernal.Affairs.3.2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD --target-dir=/电影/Emby硬链/香港 --file-mode=link
> 2022/06/03 10:15:49 - MainThread - INFO: 开始处理电影目录 /电影/保种/中国/香港/其他/Infernal.Affairs.Trilogy.2002-2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD/Infernal.Affairs.3.2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD 目标目录：/电影/Emby硬链/香港
> 2022/06/03 10:15:52 - MainThread - INFO: 已处理：无间道2 (2003) 源路径: /电影/保种/中国/香港/其他/Infernal.Affairs.Trilogy.2002-2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD/Infernal.Affairs.3.2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD/Infernal.Affairs.3.2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD.mkv, 目的路径: /电影/Emby硬链/香港/无间道2 (2003) [tmdbid=11647]/无间道2 (2003) [tmdbid=11647] - 1080p x264 DTS-HD.mkv 

以此段为例，CHD 无间道包中含3个文件夹，分别为
Infernal.Affairs.2002.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD
Infernal.Affairs.3.2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD
Infernal.Affairs.2.2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD
识别结果为
无间道 (2002) [tmdbid=10775]
无间道2 (2003) [tmdbid=11647]
少了一个文件

**Comment by leming1982** [comment]
经过再次确认，应该是无间道3识别成了2
Infernal.Affairs.3.2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD

> root@yipengfei-movie-robot:/app# python commandapp.py -w=/data -a=moviesmanager --source-type=movie --source-dir=/电影/保种/中国/香港/其他/Infernal.Affairs.Trilogy.2002-2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD/Infernal.Affairs.3.2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD --target-dir=/电影/Emby硬链/香港 --file-mode=link
> 2022/06/03 10:30:34 - MainThread - INFO: 开始处理电影目录 /电影/保种/中国/香港/其他/Infernal.Affairs.Trilogy.2002-2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD/Infernal.Affairs.3.2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD 目标目录：/电影/Emby硬链/香港
> 2022/06/03 10:30:47 - MainThread - INFO: 已处理：无间道2 (2003) 源路径: /电影/保种/中国/香港/其他/Infernal.Affairs.Trilogy.2002-2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD/Infernal.Affairs.3.2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD/Infernal.Affairs.3.2003.BluRay.1080p.DTS-HDMA7.1.2Audio.x264-CHD.mkv, 目的路径: /电影/Emby硬链/香港/无间道2 (2003) [tmdbid=11647]/无间道2 (2003) [tmdbid=11647] - 1080p x264 DTS-HD.mkv

**Comment by leming1982** [comment]
关于繁体中文与老电影的识别问题

> 2022/06/03 09:30:07 - MainThread - ERROR: 识别不到电影信息，无法处理 查询词:['mu qin 30sui'] 路径: /电影/保种/中国/台湾/其他/母親三十歲.The.Story.of.Mother.1973.1080p-iLoveTV/Mu.Qin.30Sui.1973.1080p.HDTV.H264.MPEG-iLoveTV.ts

可以看到，对于
母親三十歲 1973，因tmdb缺少简体中文信息，但繁体是有的，无法识别

**Comment by pofey** [comment]
合集包一直是不处理的
