### ISSUE TITLE
建议增加“只下载整季”选项

### ISSUE THREAD

**Issue by LeeHK1989** [pofey/movie_robot#258]
现在只能单集下载，但是到了最后一集，PT站通吃只提供整季打包下载。这样就导致前面的集数都会重新下载一遍，浪费容量也浪费带宽。
能否实现只提取整季种子里的最后一集下载呢？
如果不能的话能否提供一个只下载整季的功能，没有完结的时候就不下载了。

**Comment by pofey** [comment]
这个问题后续会解决，但是解法不一定是你建议的这样，所以这个帖子先关了
