### ISSUE TITLE
建议：馒头pt站开了二级不能登陆，建议能否优化下，谢谢！

### ISSUE THREAD

**Issue by yzbleaf** [pofey/movie_robot#259]
建议：馒头pt站(kp.m-team.cc)开启了二级验证后在站点管理不能登陆，取消二级验证后才能登陆成功，为了安全和隐私，建议能否优化下在开了二级验证的情况下也能登陆，我试了使用chrome的扩展PT助手（即PT-Plugin-Plus），在开启二级验证的情况下，该扩展是可以正常获取cookie正常登陆的，谢谢！
技术方面我不懂，不知道这个实现的难度是怎样的，只是希望该项目能越来越好，辛苦了。

**Comment by yzbleaf** [comment]
> 建议：馒头pt站(https://kp.m-team.cc)开启了二级验证后在站点管理不能登陆，取消二级验证后才能登陆成功，为了安全和隐私，建议能否优化下在开了二级验证的情况下也能登陆，我试了使用chrome的扩展PT助手（即PT-Plugin-Plus），在开启二级验证的情况下，该扩展是可以正常获取cookie正常登陆的，谢谢！
> 技术方面我不懂，不知道这个实现的难度是怎样的，只是希望该项目能越来越好，辛苦了。

**Comment by pofey** [comment]
你试试获取cookie时顺便把useragent也填进去是否可以，如果不行就没办法了

**Comment by yzbleaf** [comment]
已尝试同时也填写useragent，在二级验证下，仍然不能登陆

**Comment by pofey** [comment]
> 已尝试同时也填写useragent，在二级验证下，仍然不能登陆

那暂时就没戏了
