### ISSUE TITLE
我的订阅删除风骚律师问题

### ISSUE THREAD

**Issue by crashdada** [pofey/movie_robot#260]
### 背景

- 已分别下载了风骚律师（1-5），是手动搜索下载的
- 之后订阅风骚律师（6），设置了过滤器（x265），可能一直没资源，未开始下载
- MR版本 0.9.49
### 操作

- 进入我的订阅，删除订阅风骚律师（6），默认选择了深度删除
- 之后选择了过滤器，重新进行了风骚律师（6）的订阅
### 问题

- 现在发现风骚律师（1-5）被删除，回收站中只有硬链目录下的风骚律师（1-5），原下载文件已经没了。

**Comment by pofey** [comment]
需要提供日志和你期望下载的资源
