### ISSUE TITLE
剧集识别问题

### ISSUE THREAD

**Issue by mymoonyue** [pofey/movie_robot#262]
订阅自动下载的，如果tmdb有多版本会有个问题。

比如西游记，tmdb上其中一个版本是包含了第一部和续集，另一个是把续集单独分出来了。

当做种人的意思是想用前者，并且把续集命名了S02，而mr识别的是后者，就会新建一个“西游记续集”的文件夹而不是找原来的“西游记”，并且他会根据种子文件的S02命名Season 02而不是Season 01

正确的应该是“西游记/Season 02”或者“西游记续集/Season 01”，现在变成了“西游记续集/Season 02”

由于国产大多都只有单季，有第二季的就会有两个版本。如果不容易解决的话，能否加一个手动修改匹配。

**Comment by pofey** [comment]
没完全听懂但是感觉很特殊不是一个普遍性问题，这种极其特别的就手动处理好了吧

**Comment by mymoonyue** [comment]
手动修改Season的话，后续更新就有问题啦
