### ISSUE TITLE
洗版问题

### ISSUE THREAD

**Issue by phinleyfei** [pofey/movie_robot#263]
碰到一部电影，虽然选种是compact，但是洗了一部蓝光出来，经搜索该电影有非常多的非蓝光版本，考虑是否因为：

经过以下操作后，洗版是否还使用最初的compress标准来洗？
1、用户管理-选种设置为compress
2、订阅电影
3、用户管理-选种设置改为compact

![image](https://user-images.githubusercontent.com/105186845/172029458-9610bcb9-12a1-4af6-8b2c-49b6659f6707.png)
![image](https://user-images.githubusercontent.com/105186845/172029468-18a7accc-5043-41dc-85a9-7eb054ff3f91.png)

**Comment by pofey** [comment]
提前进入洗版状态的设置不会因后期调整而发生改变
