### ISSUE TITLE
集名因为视频编码引发的emby识别错误

### ISSUE THREAD

**Issue by wxg1015** [pofey/movie_robot#265]
目前集名就是
剧名+季号+集号+分辨率+视频编码+其他
但是有时候会得不到分辨率
导致集号挨着视频编码  
就会出现这种错误
![photo_2022-06-05_12-17-12](https://user-images.githubusercontent.com/44153358/172034823-7743adc4-03e8-4b5c-87c3-26c2a5f51da1.jpg)

**Comment by pofey** [comment]
现在这个个试试emby自己的 应该不至于

**Comment by pofey** [comment]
而且这个问题没啥优化空间了，想调整你可以把硬连接文件名格式的version去掉，干干净净的只保留集数信息
