### ISSUE TITLE
【优化】站点vip将所有种子自动标记为免费

### ISSUE THREAD

**Issue by mymoonyue** [pofey/movie_robot#266]
如果过滤规则勾选了“**只要不计下载量的种子**”或“**排除需要HR考核的种子**”，貌似**不会去下载不free但是有vip的站**？

**Comment by pofey** [comment]
那个站

**Comment by mymoonyue** [comment]
我试了chdbits和hdsky都是这样。

我是想既然站点管理那里面可以识别添加的PT站是否有VIP，是不是可以把VIP站的种子都标记为FREE。

**Comment by pofey** [comment]
嗯 下个版本把这几个站vip 全free

**Comment by mymoonyue** [comment]
好的谢谢

**Comment by pofey** [comment]
这个事情最近一段时间觉得做了没有意义，这个需求看起来你核心想要的是vip站点优先，这用排序就解决了，而不必破坏原始数据

**Comment by pofey** [comment]
> 那如果vip站靠前了，他的种子并没有其他站的资源好呢。
> 另外就是如果有短期vip的，想在vip期间内养站，本可以下所有的种子（vip不计下载）来刷上传，但是现在也只能刷free的种，那么就跟非vip一样啦

这个逻辑不对，如果vip变为免费后还想去养站，毁出问题的，基本上会把所有种子都拉下来但很快淘汰掉是没有意义的。
