### ISSUE TITLE
可以让plex刮削，mr直接拿来用吗

### ISSUE THREAD

**Issue by leverule** [pofey/movie_robot#267]
mr做管理做同步就好，让plex干活，经过长时间的配合使用，发现它可以胜任。

有以下好处：

1. 有多源刮削，tmdb没有的信息也能搞来，如现在爱死机tmdb无中文标题
2. 能识别合集，包括TOP250这种大包
3. 刮削对网络要求更友好
4. 手动处理的存量识别错了可修正
5. 省心省力，不用mr、plex识别两次，环保，干净又卫生

请衣总考虑，需要plex账号我可以提供

**Comment by leverule** [comment]
简单点，可以在这里加一个“硬链接到目标路径（按文件原名称）”的选项，核心需求是想用plex做识别。
![image](https://user-images.githubusercontent.com/57491211/172036771-f43011b4-8f37-4c40-bd4d-fe29dbd1a70a.png)

**Comment by pofey** [comment]
不做强制硬链接处理 后续字幕下载等很多功能现在都不可用

**Comment by leverule** [comment]
> 不做强制硬链接处理 后续字幕下载等很多功能现在都不可用

明白，那么plex进行预识别，再根据结果硬链接可行吗？
存量识别修正可以等存量管理的功能，但合集识别不了不好操作

**Comment by leverule** [comment]
就是给用户一个选择，用mr的识别，还是用媒体库的识别。Emby更需要mr识别，而plex已经能单飞了233
