### ISSUE TITLE
深度删除未能删除Aria2中的任务

### ISSUE THREAD

**Issue by zjgithub413** [pofey/movie_robot#268]
设置用QB下载PT站，Aria2下载RARBG。在一次使用时订阅了一部剧“狄更斯世界”，发现剧集一部分从馒头中抓取的资源，一部分从RARBG中抓取的资源。因为RARBG没有下载速度，便从“我的订阅”中删除了剧集的订阅（点了深度删除），准备先关闭RARBG，重新订阅，但发现QB中的任务已删除，Aria2中的下载任务还在，需要手动删除任务。

**Comment by pofey** [comment]
删肯定是能删的 物理文件能不能删掉 就看自己aria配置了

**Comment by zjgithub413** [comment]
您好，您的邮件我已收到，我会尽快回复Hello, I have received your mail, and I will reply as soon as possible

**Comment by zjgithub413** [comment]
当时的截图还在，确实没能删除aria2中的文件，qb中的倒是删除了
![dc74c98ad6f7ab412ebf96ed1e025e2](https://user-images.githubusercontent.com/106440008/172341031-6c9872db-7328-4a44-b3dc-e09383c54fde.png)
![f06a44a62d525263e86fcf4bd6156de](https://user-images.githubusercontent.com/106440008/172341036-2b132509-8156-4545-893f-ebb67f06b07d.png)
。

**Comment by pofey** [comment]
aria2的删除需要自己配置下aria2服务

**Comment by zjgithub413** [comment]
您好，您的邮件我已收到，我会尽快回复Hello, I have received your mail, and I will reply as soon as possible
