### ISSUE TITLE
字幕问题

### ISSUE THREAD

**Issue by ciweiyoushang** [pofey/movie_robot#269]
<img width="685" alt="CDAB285C-F974-484E-A803-8005AA03D4F7" src="https://user-images.githubusercontent.com/54163329/172086742-c2bcd5ed-631b-4836-afb1-ec9a486bdbe8.png">
<img width="1269" alt="5B921F7C-7B41-496E-A9E7-4E642947F0F4" src="https://user-images.githubusercontent.com/54163329/172086746-d753aac1-e9be-4c28-9bb4-2c89473d4dbb.png">
字幕库有字幕 但是机器人不下载 
不知道啥原因

**Comment by pofey** [comment]
字幕库名称第一季没带s，被过滤了，0.9.50 兼容修复
