### ISSUE TITLE
【优化】VIP站点的下载不做种增加删除策略

### ISSUE THREAD

**Issue by mymoonyue** [pofey/movie_robot#270]
从 **VIP站点** 下载的种子可以 **不要上传** 吗，或者自动在qb里面限制一个 **特别小的上传速度**。避免占用带宽，把上传留给需要养的站点。

或者可以自己 **手动设置** 哪些站点不要上传也行，因为有些站的 **短期vip** 还是需要养。

**Comment by mymoonyue** [comment]
或者可以自己 **手动设置** 哪些站点不要上传也行，因为有些站的 **短期vip** 还是需要养

**Comment by pofey** [comment]
vip的设置等统一规划开放配置吧
