### ISSUE TITLE
0.9.50字幕问题

### ISSUE THREAD

**Issue by ciweiyoushang** [pofey/movie_robot#272]
日志如下，依然下载错误
![5DDA1B21-CA6D-48D5-BD62-FA3FADE2409E](https://user-images.githubusercontent.com/54163329/172270100-3336f0a7-9b8f-4cb9-9ee2-6d940e1c55f5.png)
![65CB550C-3089-433E-AC78-5DA227FA7240](https://user-images.githubusercontent.com/54163329/172270105-a469f590-8be6-4430-8356-730001b14978.png)

**Comment by ciweiyoushang** [comment]
sub字幕下载错误，不会继续选择字幕库继续下载

**Comment by pofey** [comment]
errno 111 connection refused 这种就检查你自己的网络吧，以及你是不是被subhd ban了，我这搜索正
<img width="900" alt="截屏2022-06-07 上午9 10 02" src="https://user-images.githubusercontent.com/1396975/172274562-1d59fc0d-2033-4fce-8143-2d70dba11c89.png">
常

**Comment by pofey** [comment]
后续再优化站点屏蔽和资源跳过能力
