### ISSUE TITLE
【BUG】下载的字幕压缩包中如果还存在压缩包，无法处理

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#274]
开始下载9号秘事 第7季 第5集字幕: 9号秘事 第七季第五集 Inside.No.9.S07E05.720p iPlayer bilibili官方字幕
字幕保存路径：/data/subtitle/[zmk.pw]Inside.No.9.S07E05.720p.iP.WEBRip.AAC2.0.x264.zip
9号秘事 第7季 第5集 字幕开始复制到影片内容路径: /video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7
字幕时间轴同步成功 视频文件：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7/9号秘事 S07E05 - 1080p H264.mkv 调整后字幕：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season
字幕时间轴同步成功 视频文件：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7/9号秘事 S07E05 - 1080p H264.mkv 调整后字幕：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season
字幕时间轴同步成功 视频文件：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7/9号秘事 S07E05 - 1080p H264.mkv 调整后字幕：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season
字幕时间轴同步成功 视频文件：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7/9号秘事 S07E05 - 1080p H264.mkv 调整后字幕：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season
字幕时间轴同步成功 视频文件：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7/9号秘事 S07E05 - 1080p H264.mkv 调整后字幕：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season
字幕时间轴同步成功 视频文件：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7/9号秘事 S07E05 - 1080p H264.mkv 调整后字幕：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season
字幕时间轴同步成功 视频文件：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7/9号秘事 S07E05 - 1080p H264.mkv 调整后字幕：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season
字幕时间轴同步成功 视频文件：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7/9号秘事 S07E05 - 1080p H264.mkv 调整后字幕：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season
字幕同步成功 视频文件：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7/9号秘事 S07E05 - 1080p H264.mkv 字幕文件：/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7/9号秘
收到字幕处理消息：{'task_id': 109, 'content_path': '/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7', 'media_info': {'tmdb_id': 61746, 'type': 'TV', 'name': '9号秘事', 'year': 2014,
Zimuku存在9号秘事 第七季缓存，直接读取。
Subhd存在9号秘事 第七季缓存，直接读取。
搜索到14条字幕信息
开始下载9号秘事 第7季 第6集字幕: 9号秘事 第七季第六集 Inside.No.9.S07E06.720p/1080p iPlayer/HDTV bilibili官方字幕（无删减）[本季终]
字幕保存路径：/data/subtitle/[zmk.pw]9号秘事 第七集第六集.zip
9号秘事 第7季 第6集 字幕开始复制到影片内容路径: /video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7
收到字幕处理消息：{'task_id': 110, 'content_path': '/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7', 'media_info': {'tmdb_id': 61746, 'type': 'TV', 'name': '9号秘事', 'year': 2014,
9号秘事 第7季 (2022) 第{4}集 已经有中文字幕，不再下载。
收到字幕处理消息：{'task_id': 111, 'content_path': '/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7', 'media_info': {'tmdb_id': 61746, 'type': 'TV', 'name': '9号秘事', 'year': 2014,
9号秘事 第7季 (2022) 第{3}集 已经有中文字幕，不再下载。
收到字幕处理消息：{'task_id': 112, 'content_path': '/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7', 'media_info': {'tmdb_id': 61746, 'type': 'TV', 'name': '9号秘事', 'year': 2014,
Zimuku存在9号秘事 第七季缓存，直接读取。
Subhd存在9号秘事 第七季缓存，直接读取。
搜索到14条字幕信息
开始下载9号秘事 第7季 第1集字幕: 9号秘事 第七季第一集 Inside.No.9.S07E01.720p / 1080p iPlayer/HDTV bilibili官方字幕
字幕保存路径：/data/subtitle/[zmk.pw]Inside.No.9.S07E01.zip
9号秘事 第7季 第1集 字幕开始复制到影片内容路径: /video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7
收到字幕处理消息：{'task_id': 113, 'content_path': '/video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7', 'media_info': {'tmdb_id': 61746, 'type': 'TV', 'name': '9号秘事', 'year': 2014,
Zimuku存在9号秘事 第七季缓存，直接读取。
Subhd存在9号秘事 第七季缓存，直接读取。
搜索到14条字幕信息
开始下载9号秘事 第7季 第2集字幕: 9号秘事 第七季第二集 Inside.No.9.S07E02.720p / 1080p iPlayer/HDTV bilibili官方字幕（无删减）
字幕保存路径：/data/subtitle/[zmk.pw]inside no.9 s07e02.zip
9号秘事 第7季 第2集 字幕开始复制到影片内容路径: /video2/电视剧-jellyfin/9号秘事 (2014) [tmdbid=61746]/Season 7

搜到推送是1、2、5、6完成字幕下载，但是实际情况目录中只有第5集有字幕
![image](https://user-images.githubusercontent.com/105474506/172296784-1f0e73d6-9f9d-4e50-9238-706c04b835ee.png)
查看下载目录，1、2、5、6字幕下载是成功的，但是没有成功复制到最终目录
![image](https://user-images.githubusercontent.com/105474506/172296908-9bcf14fd-6663-4b40-90c5-90a475c43988.png)

**Comment by elic6699** [comment]
另外log中说 3、4已有中文字幕，不再下载，实际是只有英文字幕

**Comment by elic6699** [comment]
手动再次提交字幕下载，这次3、4字幕下载完成，但是仍未复制到最终目录
![image](https://user-images.githubusercontent.com/105474506/172298097-76bf8574-c404-43f3-a9bc-7f92ef04a5b3.png)
发现除了成功的第五集，目录下是最终解压的srt ass文件，其他几个都是尚未解压的zip包
![image](https://user-images.githubusercontent.com/105474506/172298320-b1f5d9a3-6bea-405d-92b5-029ec10e9a88.png)

**Comment by pofey** [comment]
你最后一条信息的意思是说，字幕包解压缩后文件内还有压缩包？

**Comment by elic6699** [comment]
是的

**Comment by pofey** [comment]
这种文件现在没有处理 是个新坑

**Comment by pofey** [comment]
再发布了，0.9.53解决这个嵌套压缩包的问题
