### ISSUE TITLE
不能自动追的动漫问题集中收集贴

### ISSUE THREAD

**Issue by pofey** [pofey/movie_robot#275]
反馈动漫不能追的问题，需要提供几类信息辅助分析。
1、这部动漫的名称及豆瓣对应的访问地址，带上豆瓣截图，最好也带上tmdb的信息，季度，名称之类，加快分析效率。
2、你认为应该下载，但是无法自动下载的搜索种子列表截图，重点表现种子名称及种子中文标题。能复制点文字出来最佳。
就先提供这两类信息吧，其他想到再补充。
集中收集一波动漫追番问题，思考解决方案。

**Comment by pofey** [comment]
> 番名：骸骨骑士大人异世界冒险中 [https://movie.douban.com/subject/35438178/](url) [https://www.themoviedb.org/tv/123528?language=zh-CN](url)
> 
> 应该是12集完结，不知道为什么搜索页面显示9集完结
> 
> <img alt="image" width="1100" src="https://user-images.githubusercontent.com/29762822/172335767-ce7bf1b0-9c35-431c-97d5-16a4ccc5245f.png">
> 
> <img alt="image" width="959" src="https://user-images.githubusercontent.com/29762822/172336437-13569dcc-2500-4e1e-96ee-2bacf4491b9f.png">

升级到最新版 删了重订阅 然后再试试

**Comment by pofey** [comment]
> 动漫名称：RPG不动产 [https://movie.douban.com/subject/35382420/](url) TMDB：[https://www.themoviedb.org/tv/119631-rpg?language=zh-CN](url)
> 
> 版本号: 0.9.52
> 
> 订阅RPG不动产出错，日志如下：
> 
> > `2022/06/07 16:06:01 - ThreadPoolExecutor-0_15 - ERROR: 从RARBG搜索['rpg 不动产']失败了 错误：
> 
> > 2022/06/07 16:06:04 - Thread-111 - INFO: 共在23个站点搜索到55条结果，其中我堡最慢，耗费4.4秒
> > 2022/06/07 16:06:31 - SubRequestConsumer - INFO: 正直不动产(2022) 选用过滤器：（默认）新国外剧中文字幕（自动洗版） 排序规则：me
> > 2022/06/07 16:06:31 - SubRequestConsumer - INFO: 新增来自彦祖的订阅: 正直不动产(2022) 选用过滤器：（默认）新国外剧中文字幕（自动洗版） 排序规则：me
> > 2022/06/07 16:07:36 - Thread-136 - INFO: 已经开始在站点: 馒头,天空,北洋园,不可说,彩虹岛,朋友,猫站,我堡,铂金家,柠檬,备胎,烧包乐园,家园,观众,高清杜比,吐鲁番,聆音,瓷器,听听歌,学校,红豆饭,白兔,RARBG 搜索: rpg不动产
> > 2022/06/07 16:07:37 - ThreadPoolExecutor-0_9 - ERROR: uid解析出错 values: {} tag: None
> > Traceback (most recent call last):
> > File "yee/site/htmlparser.py", line 177, in yee.site.htmlparser.HtmlParser.parse_item_fields
> > AttributeError: 'NoneType' object has no attribute 'select_one'
> > 2022/06/07 16:07:37 - ThreadPoolExecutor-0_9 - ERROR: user_group解析出错 values: {} tag: None
> > Traceback (most recent call last):
> > File "yee/site/htmlparser.py", line 177, in yee.site.htmlparser.HtmlParser.parse_item_fields
> > AttributeError: 'NoneType' object has no attribute 'select_one'
> > 2022/06/07 16:07:37 - ThreadPoolExecutor-0_9 - ERROR: username解析出错 values: {} tag: None
> > Traceback (most recent call last):
> > File "yee/site/htmlparser.py", line 177, in yee.site.htmlparser.HtmlParser.parse_item_fields
> > AttributeError: 'NoneType' object has no attribute 'select_one'
> > 2022/06/07 16:07:37 - ThreadPoolExecutor-0_9 - ERROR: share_ratio解析出错 values: {} tag: None
> > Traceback (most recent call last):
> > File "yee/site/htmlparser.py", line 177, in yee.site.htmlparser.HtmlParser.parse_item_fields
> > AttributeError: 'NoneType' object has no attribute 'select_one'
> > 2022/06/07 16:07:37 - ThreadPoolExecutor-0_9 - ERROR: uploaded解析出错 values: {} tag: None
> > Traceback (most recent call last):
> > File "yee/site/htmlparser.py", line 177, in yee.site.htmlparser.HtmlParser.parse_item_fields
> > AttributeError: 'NoneType' object has no attribute 'select_one'
> > 2022/06/07 16:07:37 - ThreadPoolExecutor-0_9 - ERROR: downloaded解析出错 values: {} tag: None
> > Traceback (most recent call last):
> > File "yee/site/htmlparser.py", line 177, in yee.site.htmlparser.HtmlParser.parse_item_fields
> > AttributeError: 'NoneType' object has no attribute 'select_one'
> > 2022/06/07 16:07:37 - ThreadPoolExecutor-0_9 - ERROR: seeding解析出错 values: {} tag: None
> > Traceback (most recent call last):
> > File "yee/site/htmlparser.py", line 177, in yee.site.htmlparser.HtmlParser.parse_item_fields
> > AttributeError: 'NoneType' object has no attribute 'select_one'
> > 2022/06/07 16:07:37 - ThreadPoolExecutor-0_9 - ERROR: leeching解析出错 values: {} tag: None
> > Traceback (most recent call last):
> > File "yee/site/htmlparser.py", line 177, in yee.site.htmlparser.HtmlParser.parse_item_fields
> > AttributeError: 'NoneType' object has no attribute 'select_one'
> > 2022/06/07 16:07:37 - ThreadPoolExecutor-0_9 - ERROR: vip_group解析出错 values: {} tag: None
> > Traceback (most recent call last):
> > File "yee/site/htmlparser.py", line 189, in yee.site.htmlparser.HtmlParser.parse_item_fields
> > File "yee/site/htmlparser.py", line 145, in yee.site.htmlparser.HtmlParser.**case_value**
> > AttributeError: 'NoneType' object has no attribute 'select_one'
> > 2022/06/07 16:07:37 - ThreadPoolExecutor-0_21 - ERROR: 从RARBG搜索['rpg不动产']失败了 错误：
> > 2022/06/07 16:07:42 - Thread-136 - INFO: 共在23个站点搜索到55条结果，其中观众最慢，耗费5.1秒`
> 
> 订阅列表新增 <img alt="image" width="229" src="https://user-images.githubusercontent.com/29762822/172330751-b8722c93-1bbe-4fa0-aa01-fa7f5d9aaaad.png">
> 
> 正直不动产是我订阅的一部日剧，不知道为什么会跑出来。另外这个新出现的订阅名字虽然是正直不动产，但是海报上面的介绍是RPG不动产的.
> 
> <img alt="image" width="739" src="https://user-images.githubusercontent.com/29762822/172332185-50242d96-229d-4ec2-a187-b955f543b46a.png">
> 
> 可以看到搜索界面是能正常搜到的，也显示了已经订阅
> 
> <img alt="image" width="1093" src="https://user-images.githubusercontent.com/29762822/172332496-9b667110-9fba-414f-aee3-a5b3e1fe1dad.png">
> 
> 标题：[2022年4月新番] RPG不动产 / RPG不動産 第09集 内封中字 官方中字]

rpg不动产的问题，0.9.53修复

**Comment by brucetangian** [comment]
动漫名称：身为女主角！~讨厌的女主角与秘密的工作~(2022) 
豆瓣：[https://movie.douban.com/subject/35579469/](url)
[TMDB：] https://www.themoviedb.org/tv/132213
版本号: 0.9.53
2022/06/08 05:48:38 - SubRequestConsumer - INFO: 新增来自bruce的订阅: 身为女主角！~讨厌的女主角与秘密的工作~(2022) 选用过滤器：電視劇 排序规则：compress
2022/06/08 05:48:38 - SubConsumer - INFO: 已经开始在站点: 馒头,听听歌,彩虹岛,猫站,柠檬,天空,我堡 搜索: 身为女主角！~讨厌的女主角与秘密的工作~,Heroines Run the Show,tt19801014
2022/06/08 05:48:42 - SubConsumer - INFO: 共在7个站点搜索到1条结果，其中柠檬最慢，耗费3.32秒
2022/06/08 05:48:42 - SubConsumer - INFO: 身为女主角！~讨厌的女主角与秘密的工作~(2022) 第1季 第[7]集 品质：WEB-DL 1080p H.264 资源: https://kp.m-team.cc/details.php?id=577268&hit=1 已经提交下载。
2022/06/08 05:48:42 - DownloadConsumer - INFO: 开始处理来自订阅的下载: [mteam]Heroines Run the Show S01E07 1080p WEB H.264-SENPAI
2022/06/08 05:48:43 - DownloadConsumer - INFO: [mteam]Heroines Run the Show S01E07 1080p WEB H.264-SENPAI已经开始下载,路径：/share/綜合/anime/anime-robot 分类：動漫 

CHD有7集，但是搜不到，抱歉不会贴图

**Comment by u93724** [comment]
经测在版本0.9.53中，该问题仍然存在https://github.com/pofey/movie_robot/issues/216

**Comment by brucetangian** [comment]
动漫名称：约会大作战 第四季
豆瓣：https://movie.douban.com/subject/35002367/
[TMDB：] https://www.themoviedb.org/tv/46004-d-to-a-raibu/season/4

2022/06/10 02:58:04 - Thread-1427 - INFO: 已经开始在站点: 我堡,馒头,听听歌,备胎,彩虹岛,猫站,观众,柠檬,天空 搜索: 约会大作战
2022/06/10 02:58:04 - ThreadPoolExecutor-0_4 - ERROR: 从听听歌搜索['约会大作战']失败了 错误：EOF occurred in violation of protocol (_ssl.c:1125)
2022/06/10 02:58:10 - Thread-1427 - INFO: 共在9个站点搜索到124条结果，其中柠檬最慢，耗费6.04秒
2022/06/10 02:58:23 - SubRequestConsumer - INFO: 约会大作战(2013) 选用过滤器：電視劇 排序规则：compress
2022/06/10 02:58:23 - SubRequestConsumer - INFO: 新增来自bruce的订阅: 约会大作战(2013) 选用过滤器：電視劇 排序规则：compress
2022/06/10 02:58:24 - SubConsumer - INFO: 已经开始在站点: 我堡,馒头,听听歌,彩虹岛,猫站,柠檬,天空 搜索: 约会大作战,Date a Live,tt2575684
2022/06/10 02:58:44 - SubConsumer - INFO: 共在7个站点搜索到99条结果，其中馒头最慢，耗费20.44秒
2022/06/10 02:58:44 - SubConsumer - INFO: 约会大作战(2013) 第1季 全集 品质：WEB-DL 1080p H.264 资源: https://ourbits.club/details.php?id=99116&hit=1 已经提交下载。
2022/06/10 02:58:44 - DownloadConsumer - INFO: 开始处理来自订阅的下载: [ourbits]Date A Live S03 1080p KKTV WEB-DL AAC2.0 H264-Ao
2022/06/10 02:58:44 - SubConsumer - INFO: 约会大作战(2013) 第1季 本次下载的种子中，包含有全集字样信息，将默认本剧完结，停止订阅不再智能下载。
2022/06/10 02:58:46 - DownloadConsumer - INFO: [ourbits]Date A Live S03 1080p KKTV WEB-DL AAC2.0 H264-Ao已经开始下载,路径：/share/綜合/anime/anime-robot 分类：動漫

订阅的是第一次季，搜到的却是第一季

**Comment by brucetangian** [comment]
动漫名称：约会大作战 第四季
豆瓣：https://movie.douban.com/subject/35002367/
[TMDB：] https://www.themoviedb.org/tv/46004-d-to-a-raibu/season/4

2022/06/10 02:58:04 - Thread-1427 - INFO: 已经开始在站点: 我堡,馒头,听听歌,备胎,彩虹岛,猫站,观众,柠檬,天空 搜索: 约会大作战
2022/06/10 02:58:04 - ThreadPoolExecutor-0_4 - ERROR: 从听听歌搜索['约会大作战']失败了 错误：EOF occurred in violation of protocol (_ssl.c:1125)
2022/06/10 02:58:10 - Thread-1427 - INFO: 共在9个站点搜索到124条结果，其中柠檬最慢，耗费6.04秒
2022/06/10 02:58:23 - SubRequestConsumer - INFO: 约会大作战(2013) 选用过滤器：電視劇 排序规则：compress
2022/06/10 02:58:23 - SubRequestConsumer - INFO: 新增来自bruce的订阅: 约会大作战(2013) 选用过滤器：電視劇 排序规则：compress
2022/06/10 02:58:24 - SubConsumer - INFO: 已经开始在站点: 我堡,馒头,听听歌,彩虹岛,猫站,柠檬,天空 搜索: 约会大作战,Date a Live,tt2575684
2022/06/10 02:58:44 - SubConsumer - INFO: 共在7个站点搜索到99条结果，其中馒头最慢，耗费20.44秒
2022/06/10 02:58:44 - SubConsumer - INFO: 约会大作战(2013) 第1季 全集 品质：WEB-DL 1080p H.264 资源: https://ourbits.club/details.php?id=99116&hit=1 已经提交下载。
2022/06/10 02:58:44 - DownloadConsumer - INFO: 开始处理来自订阅的下载: [ourbits]Date A Live S03 1080p KKTV WEB-DL AAC2.0 H264-Ao
2022/06/10 02:58:44 - SubConsumer - INFO: 约会大作战(2013) 第1季 本次下载的种子中，包含有全集字样信息，将默认本剧完结，停止订阅不再智能下载。
2022/06/10 02:58:46 - DownloadConsumer - INFO: [ourbits]Date A Live S03 1080p KKTV WEB-DL AAC2.0 H264-Ao已经开始下载,路径：/share/綜合/anime/anime-robot 分类：動漫

订阅的是第四季，下载的却是第3季

**Comment by pofey** [comment]
> 动漫名称：爱、死亡 & 机器人 第三季 豆瓣：https://movie.douban.com/subject/35436582/ [TMDB：] https://www.themoviedb.org/tv/86831-love-death-robots/season/3 2022/06/10 03:13:47 - SubRequestConsumer - INFO: 爱，死亡和机器人(2019) 已经在影视库，不再进行订阅！
> 
> 相同的季识别问题，订阅的是第3季，EMBY中有第1，2季却识别有第3季取消订阅
> 
> ![image](https://user-images.githubusercontent.com/100015276/172927809-9c613ee1-c1bb-4e9e-8ca2-00cdf2baaad6.png)

发emby里搜索结果截图看看，另外这是动漫吗？

**Comment by qianxia1983** [comment]
动漫名称:https://movie.douban.com/subject/35312003/
TMDB:https://www.themoviedb.org/tv/124003
完美世界(2021) 第1季 全集 品质：WEB-DL 1080p H.264 资源: https://pthome.net/details.php?id=124330&hit=1 已经提交下载。
2022/06/11 23:21:23 - DownloadConsumer - INFO: 开始处理来自订阅的下载: [pthome]Perfect World 2021 WEB-DL 1080p H264 AAC-PTHweb
2022/06/11 23:21:23 - SubConsumer - INFO: 完美世界(2021) 第1季 本次下载的种子中，包含有全集字样信息，将默认本剧完结，停止订阅不再智能下载。
2022/06/11 23:21:26 - DownloadConsumer - INFO: [pthome]Perfect World 2021 WEB-DL 1080p H264 AAC-PTHweb已经开始下载,路径：/media/国内/anime 分类：国内动漫 
种子名称 :
下载 | [PTHOME].完美世界.Perfect World.2021.WEB-DL.1080p.H264.AAC-PTHweb.torrent    
副标题 | 完美世界 第一季 全30集
但这个一季有78集 我下了2个种子 都会停止订阅
![完美世界](https://user-images.githubusercontent.com/71596976/173194430-861e66c0-e2b6-4847-a603-721631151c3f.png)

**Comment by pofey** [comment]
> 完美世界

你看看这种子标题，假种子，test版已经修复这个问题了

**Comment by brucetangian** [comment]
> > 动漫名称：爱、死亡 & 机器人 第三季 豆瓣：https://movie.douban.com/subject/35436582/ [TMDB：] https://www.themoviedb.org/tv/86831-love-death-robots/season/3 2022/06/10 03:13:47 - SubRequestConsumer - INFO: 爱，死亡和机器人(2019) 已经在影视库，不再进行订阅！
> 
> > 
> 
> > 相同的季识别问题，订阅的是第3季，EMBY中有第1，2季却识别有第3季取消订阅
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/100015276/172927809-9c613ee1-c1bb-4e9e-8ca2-00cdf2baaad6.png)
> 
> 
> 
> 发emby里搜索结果截图看看，另外这是动漫吗？

这个分类也有动画 算是个外国动画吧 Emby中只有两季
![image](https://user-images.githubusercontent.com/100015276/173200469-f6b8f6a5-9892-40af-87af-971d2e9bdbb2.png)

**Comment by Migflyway** [comment]
海贼王订阅后只有924集； 柯南订阅后也只有109集

**Comment by leverule** [comment]
无法订阅斗罗大陆，未完结的动漫，每周一次更新

豆瓣上集数完全不对(https://movie.douban.com/subject/27040807/)，订阅会提示全集已下载，实际已有二百多集
![image](https://user-images.githubusercontent.com/57491211/173230580-3516243d-bcaf-468f-bef4-fbdb1af7f5bb.png)

tmdb上集数对，但无法通过imdbid订到正确的集数
IMDB---https://www.imdb.com/title/tt8948436/?ref_=fn_al_tt_1
TMDB---https://www.themoviedb.org/tv/76572-2018

目前只能通过qb的RSS来解决订阅问题，我的qb还是4.2.5快检版，设置rss要通过备用WEBUI，很不方便
![image](https://user-images.githubusercontent.com/57491211/173231138-8d37b9d4-ccef-48e3-8d51-fb0dadd7dfb9.png)

真心希望RSS能做的事情，强大的MR也能做

**Comment by qianxia1983** [comment]
动漫名称 凡人修仙传
豆瓣：https://movie.douban.com/subject/35882624/
TMDB; https://www.themoviedb.org/tv/106449
豆瓣分三季 TMDB 只有1季
订阅出错
2022/06/16 00:18:57 - Thread-655 - INFO: 已经开始在站点: 备胎,红豆饭,馒头,猫站,铂金家,烧包乐园,北洋园,听听歌,阿童木,高清时间,丐帮,朋友,白兔,iptorrents,马杀鸡,艾薇 搜索: 凡人修仙传
2022/06/16 00:19:02 - ThreadPoolExecutor-0_8 - ERROR: 从猫站搜索['凡人修仙传']失败了 错误：EOF occurred in violation of protocol (_ssl.c:1125)
2022/06/16 00:19:11 - ThreadPoolExecutor-0_6 - ERROR: 从备胎搜索['凡人修仙传']失败了 错误：The read operation timed out
2022/06/16 00:19:16 - Thread-655 - INFO: 共在16个站点搜索到145条结果，其中馒头最慢，耗费19.08秒
2022/06/16 00:20:16 - SubRequestConsumer - ERROR: douban_id: 35882624 订阅失败，请查看日志分析原因。
Traceback (most recent call last):
  File "yee/service/smartdownloadservice.py", line 261, in yee.service.smartdownloadservice.SmartDownloadService.sub_from_douban
  File "yee/service/smartdownloadservice.py", line 40, in yee.service.smartdownloadservice.SmartDownloadService.exists
TypeError: object of type 'NoneType' has no len()
2022/06/16 00:20:17 - SubRequestConsumer - ERROR: douban_id: 35882624 订阅失败，请查看日志分析原因。

**Comment by pofey** [comment]
时间截止，最近做了一大波关于硬链接和识别的优化，同时还开放了自定义订阅。反馈问题的同学可以再最新版重新感受一下，如有问题，来这里回复我再继续排查。
