### ISSUE TITLE
下载记录剧集展示是否可以优化

### ISSUE THREAD

**Issue by jinfeng1985** [pofey/movie_robot#276]
目前订阅的剧集，每周下载会有一个新的下载记录，这样就有好多同样封面的下载记录，是否可以优化合并成一个。
![C73B15E4-2120-4DA6-A1AC-30AEC90F4D19](https://user-images.githubusercontent.com/22148953/172317588-aa3aa1a4-b75e-472e-bae0-0a43086245f2.jpeg)

**Comment by pofey** [comment]
先不合并 下一版剧集增加集号显示
