### ISSUE TITLE
字幕下载就没成功过，是我的配置问题吗？

### ISSUE THREAD

**Issue by guoshuhuang** [pofey/movie_robot#278]
<img width="1108" alt="截屏2022-06-07 20 29 05" src="https://user-images.githubusercontent.com/31760242/172379674-1c570a4e-58ff-49cc-aaa9-f2ffc85aac7c.png">

<img width="1255" alt="截屏2022-06-07 20 30 51" src="https://user-images.githubusercontent.com/31760242/172379737-2a0cae36-d80f-46b7-b1bf-d676451f78a6.png">

版本号：最新

**Comment by pofey** [comment]
得看logs task subtitle日志

**Comment by guoshuhuang** [comment]
> 

<img width="644" alt="image" src="https://user-images.githubusercontent.com/31760242/172395044-8e38e362-2c63-4aee-8aa9-365d894e481c.png">

好像是网络问题，能加个代理的配置吗

**Comment by pofey** [comment]
这俩网站怎么会有网络问题呢 你是被ban了吗
