### ISSUE TITLE
有可能是逻辑错误 自动分类出了问题

### ISSUE THREAD

**Issue by DaBo0219** [pofey/movie_robot#280]
![image](https://user-images.githubusercontent.com/62327176/172401549-2bbca7e3-0fe2-49b8-9900-5bcfa4ab9c1b.jpeg)![image](https://user-images.githubusercontent.com/62327176/172401587-0f785e6e-383a-4884-8696-5a2eab71acba.png) 电影名称：越狱兄弟3 豆瓣ID：35908037 豆瓣地址：https://m.douban.com/movie/subject/35908037/
这部电影的豆瓣地区是香港但没有正确分类到正确的文件夹 我的逻辑是 规则1 类型为动画  规则2 地区包括 中国 中国香港 中国台湾 规则3 类型和地区不限制用来保底包含任何地区影片 在订阅越狱兄弟3时 规则2没有起到作用进入了规则3 请大佬们帮忙看看

**Comment by pofey** [comment]
<img width="1443" alt="截屏2022-06-07 下午10 41 16" src="https://user-images.githubusercontent.com/1396975/172408952-c6359dfa-fb0b-4d27-8505-2eb306c83b9f.png">
这片子zhi pian制片地区在tmdb是空，测试那块显示其他，所以没啥错误，我帮给这条tmdb数据加了个香港，应该好了

**Comment by DaBo0219** [comment]
> <img width="1443" alt="截屏2022-06-07 下午10 41 16" src="https://user-images.githubusercontent.com/1396975/172408952-c6359dfa-fb0b-4d27-8505-2eb306c83b9f.png">
> 
> 这片子zhi pian制片地区在tmdb是空，测试那块显示其他，所以没啥错误，我帮给这条tmdb数据加了个香港，应该好了

感谢衣总
