### ISSUE TITLE
激活码未发送咨询。

### ISSUE THREAD

**Issue by ShellMonster** [pofey/movie_robot#281]
你好，激活码还没有发到邮箱，支付宝订单号2022053022001419651416756409。

**Comment by pofey** [comment]
> > 查到了 备注没留邮箱 你在这给我个邮箱
> 
> [ctrlf4@yeah.net](mailto:ctrlf4@yeah.net)，谢谢。

不对劲我查了一下你这个530已经发过了

**Comment by ShellMonster** [comment]
> > > 查到了 备注没留邮箱 你在这给我个邮箱
> > 
> > 
> > [ctrlf4@yeah.net](mailto:ctrlf4@yeah.net)，谢谢。
> 
> 不对劲我查了一下你这个530已经发过了

我看了收件箱和垃圾箱，都没有；我从邮箱后台重新复制了下邮箱，Ctrlf4@yeah.net  (和手输的一致啊😯)

**Comment by pofey** [comment]
yipengfei329加我微信
