### ISSUE TITLE
【求助】无法建立硬链接

### ISSUE THREAD

**Issue by haha6311** [pofey/movie_robot#283]
版 本：latest 0.9.52
媒体库：PLEX
运行环境：OPENWRT-by FLIPPY docker arm64 
说 明：源目录和目标目录未跨盘符 挂载的非媒体目录下（如/data）硬链接未报错

![image](https://user-images.githubusercontent.com/36618980/172505644-ea45e9e0-c124-408c-97cb-e0fca3cbf364.png)

{"log":"2022-06-08 07:20:05,359 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.\r\n","stream":"stdout","time":"2022-06-07T23:20:05.360014476Z"}
{"log":"2022-06-08 07:20:05,370 INFO supervisord started with pid 35\r\n","stream":"stdout","time":"2022-06-07T23:20:05.371443492Z"}

硬盘的分区信息和挂载信息
![image](https://user-images.githubusercontent.com/36618980/172504817-8397a9d5-a746-4e72-9e92-0c555ea2374c.png)
![image](https://user-images.githubusercontent.com/36618980/172504905-9b705bd9-b032-4b19-be93-815b39f36d9f.png)
![image](https://user-images.githubusercontent.com/36618980/172505222-8096569a-fc31-4b95-bc7f-210388ff0c83.png)

**Comment by pofey** [comment]
这个在docker文件系统上好像还是算跨了
