### ISSUE TITLE
【BUG】字幕下载到错误路径

### ISSUE THREAD

**Issue by jayling1111** [pofey/movie_robot#284]
手机反馈不方便复制，直接整理到备忘录。

![Screenshot_20220608_025401](https://user-images.githubusercontent.com/84979549/172525972-fccb6114-d80d-44cc-91f1-7a791b2ee136.jpg)

**Comment by jayling1111** [comment]
版本为0.9.53

**Comment by pofey** [comment]
这可能还真是个bug 晚上看看代码

**Comment by pofey** [comment]
等新版修复了

**Comment by pofey** [comment]
同名前缀的问题已经修复掉了
