### ISSUE TITLE
【！！严重BUG】机器人深度删除剧集某季，导致通过机器人下载的剧集全剧删除。

### ISSUE THREAD

**Issue by jayling1111** [pofey/movie_robot#285]
机器人深度删除剧集中某季的时候，会直接把剧集全剧删除。

比如库内有权游S01到S08整八季，都是从机器人下载的。
现对S02资源不满意，针对S02执行深度删除，结果机器人把权游全剧S01到S08一并删除，包括源文件，硬链接。

求问这个是属于程序正常逻辑还是错误删除，
该情况在0.9.53版本仍可复现。

**Comment by pofey** [comment]
1、你从哪个操作触发的删除 订阅还是下载记录
2、整8季是分开下载还是合集包

**Comment by jayling1111** [comment]
> 

1.从订阅界面，已完成那里选择深度删除。
2.非集合大包，全剧都是分开，即S01到S08分别为8个不同的种子任务。

**Comment by jayling1111** [comment]
补充一下，在订阅界面仅对S02执行取消订阅，并执行深度删除，其他季没有操作。

**Comment by pofey** [comment]
翻了一下代码，这里还真是个bug，下一版修复，抱歉了。。。

**Comment by pofey** [comment]
test版已经修复
