### ISSUE TITLE
动漫剧集下载 ，文件名识别错误

### ISSUE THREAD

**Issue by zxq321zxq** [pofey/movie_robot#286]
![CBB3F6C7-EEE2-408C-B8ED-206D34429738](https://user-images.githubusercontent.com/50660883/172540649-3ce2bf2b-8e91-4167-86f5-9b3dcbf0e261.png)

**Comment by zxq321zxq** [comment]
![8A0397C2-A0FD-40E8-B44E-3038B91BA149](https://user-images.githubusercontent.com/50660883/172540823-cccba00e-cbd7-405f-b750-aaf2caa55644.jpeg)
第08集识别成10集了

**Comment by pofey** [comment]
动漫问题按规格合到另外一个帖子去
