### ISSUE TITLE
【BUG】BDMV硬链接不全

### ISSUE THREAD

**Issue by zjgithub413** [pofey/movie_robot#291]
最近发现有十多部BDMV无法播放，查看后发现硬链接过去的文件不全，缺失了一部分。图片左边为原来的文件，右边为硬链接后的文件。照理来说硬链接后的文件被emby刮削过，里面包含的文件应该比原文件还要多几个的。
![微信截图_20220609224534](https://user-images.githubusercontent.com/106440008/172877263-6d639054-3b19-4976-a625-078531ac340a.png)
![微信截图_20220609224826](https://user-images.githubusercontent.com/106440008/172877334-f2934a05-7222-446c-80a8-fa8ae5901853.png)

**Comment by zjgithub413** [comment]
如过排查后真的是MR的BUG，会不会在下一版修复？有没有方式能让机器人把之前的硬链接再自动再重新刷新链接一遍？因为不确定媒体库中还有多少BDMV有问题，且如果不能自动重新链接，还需要挨个手动排查，排查后要删除文件，重新下载，进行硬链接。

**Comment by pofey** [comment]
现有所有版本的硬链接功能不修复不发布了，已经完全重写这部分代码了。现存的bug应该是原盘忽略掉了一些xml txt文件导致出的问题，新版出来重跑就好了
