### ISSUE TITLE
【BUG】订阅剧集错误

### ISSUE THREAD

**Issue by qiuwei0209** [pofey/movie_robot#293]
从”机器人“里面直接搜索”纸钞屋“，然后订阅”纸钞屋 第二季“，查看已订阅是”纸钞屋（韩版） 第二季“。

另外用Overseerr订阅的”纸房子 第一季“、”纸房子 第二季“、”纸房子 第三季“。和”纸钞屋“命名不同，好像不能触发下载。

比较坑的是”纸钞屋“在豆瓣有五季，而在TMDB只有三季。

**Comment by pofey** [comment]
这个剧手动处理吧 当前模式无法解决
