### ISSUE TITLE
Jellyfin接口问题导致硬链接删除文件失败

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#296]
2022/06/09 22:58:42 - Thread-1377 - INFO: No.Country.for.Old.Men.2007.1080p.BluRay.REMUX.AVC.LPCM.5.1-FGT已经从下载器中被删除。
 2022/06/09 22:58:42 - Thread-1377 - ERROR: 没有在影视库找到需要删除的信息tmdb: 6977

同样的在jellyfin库中 6977是有的，刮削已经完成

**Comment by pofey** [comment]
你能让我连你服务器调试这个问题么

**Comment by elic6699** [comment]
在衣总指导下调整了一下，后期再观察

**Comment by elic6699** [comment]
发现搜不到可能是媒体库刮削的时候刮削到了除tmdb外的其他数据源的元信息，比如imdb和tvdb，唯独缺tmdb的id，导致搜不到，建议是否可以在没有tmdb id的情况下增加imdb的匹配，豆瓣是直接有imdb信息的
