### ISSUE TITLE
是否考虑加入其他清单

### ISSUE THREAD

**Issue by qcgzxw** [pofey/movie_robot#3]
因为本人用豆瓣比较少，都是在letterboxd twitter看别人推荐和最近比较火的电影。
是否有考虑加入其他清单识别
- trakt watchlist
- imdb watchlist
- letterboxd watchlist
- etc.

另外 既然不开源了 是否考虑开放出一个http 接口
这样方便传入imdb id调用下载pt 扩展性就更强了

**Comment by pofey** [comment]
建议很好，imdb watchlist和豆瓣id、imdbid、tmdbid调用后下载的接口也会推出
