### ISSUE TITLE
阿童木养站无法触发

### ISSUE THREAD

**Issue by ibowennn** [pofey/movie_robot#301]
movie_robot版本： 0.9.53
相同设置下，阿童木的养站功能始终无法触发，一直提示找不到合适的种子。而后面添加的铂金站则可以触发养站功能，自动下载种子。
养站功能配置如下：
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/51699450/173188663-9628c41d-f489-42b2-b441-c29305959037.png">
日志如下：
<img width="748" alt="image" src="https://user-images.githubusercontent.com/51699450/173188596-eef88c96-8606-4556-9cc3-496149a0732c.png">
<img width="633" alt="image" src="https://user-images.githubusercontent.com/51699450/173188600-3483fe7f-417b-4ad2-80bc-a39c71c442f3.png">

**Comment by pofey** [comment]
都已经提示你没有合适的种子了，那就没什么问题
