### ISSUE TITLE
【求助】ERROR: 需要处理的路径不存在或无法访问

### ISSUE THREAD

**Issue by haha6311** [pofey/movie_robot#308]
版 本：latest 0.9.53
媒体库：PLEX
运行环境：OPENWRT-by FLIPPY docker arm64
说 明：源目录和目标目录未跨盘符 硬链接测试依然提示“源路径不存在或无法访问” 已root权限运行
```
2022/06/14 09:31:00 - ThreadPoolExecutor-3_1 - INFO: 开始为电影 青春派 (2013)做文件转移 源路径：/video/Downloads/Movie/青春派.Young.Style.2013.2160p.WEB-DL.AAC.H265-OurTV 链接路径：/video/电影
 2022/06/14 09:31:00 - ThreadPoolExecutor-3_1 - ERROR: 需要处理的路径不存在或无法访问：/video/Downloads/Movie/青春派.Young.Style.2013.2160p.WEB-DL.AAC.H265-OurTV
```
![image](https://user-images.githubusercontent.com/36618980/173478454-37bc64ab-db67-44c5-a6ef-68cfde640c3a.png)

**Comment by haha6311** [comment]
重启大法好，不过这也算是个bug吧

**Comment by pofey** [comment]
这种自己的环境问题的如果想让帮忙排查 就得把所有挂载和配置信息都贴出来 不然能看啥？

**Comment by haha6311** [comment]
不好意思，我可以补充下信息在贴一个嘛
