### ISSUE TITLE
ERROR: 需要处理的路径不存在或无法访问

### ISSUE THREAD

**Issue by haha6311** [pofey/movie_robot#311]
**根据衣总的要求补充了一下信息，不知道对不对。**

版 本：`latest 0.9.53`
媒体库：`PLEX`
运行环境：`OPENWRT docker arm64`
说 明：**源目录和目标目录未跨盘符 硬链接测试依然提示“源路径不存在或无法访问” 已root权限运行 重启容器后恢复** 

相关报错信息：
`2022/06/14 09:31:00 - ThreadPoolExecutor-3_1 - INFO: 开始为电影 青春派 (2013)做文件转移 源路径：/video/Downloads/Movie/青春派.Young.Style.2013.2160p.WEB-DL.AAC.H265-OurTV 链接路径：/video/电影
 2022/06/14 09:31:00 - ThreadPoolExecutor-3_1 - ERROR: 需要处理的路径不存在或无法访问：/video/Downloads/Movie/青春派.Young.Style.2013.2160p.WEB-DL.AAC.H265-OurTV`

文件权限信息：
![image](https://user-images.githubusercontent.com/36618980/173478454-37bc64ab-db67-44c5-a6ef-68cfde640c3a.png)
mr配置信息：
![XB9 VN`0EV)I4W(@T4~%J47](https://user-images.githubusercontent.com/36618980/173504060-b54dc63d-98db-4bb9-801f-a199f8c83182.png)
宿主机分区挂载信息：
![image](https://user-images.githubusercontent.com/36618980/173504423-adc9b4a3-dc6b-441c-adbe-b6c47af250da.png)
docker配置信息：
![image](https://user-images.githubusercontent.com/36618980/173504575-d7726da7-559b-4b2f-b02e-fbe5fc31e9dd.png)

**Comment by pofey** [comment]
你的激活码泄漏了

**Comment by pofey** [comment]
另外你别在宿主机ls 要去容器内已puid和pgid为0的权限去ls 这个issue我关闭了 程序没啥优化空间 那个地方是os api

**Comment by haha6311** [comment]
> 另外你别在宿主机ls 要去容器内已puid和pgid为0的权限去ls 这个issue我关闭了 程序没啥优化空间 那个地方是os api

好滴 刚才看了下容器内的 和宿主机的一样

![image](https://user-images.githubusercontent.com/36618980/173521051-d7f5cc70-436e-4be0-94d7-713b75ffff0d.png)

**Comment by pofey** [comment]
你这命令行还是root openwrt？

**Comment by haha6311** [comment]
> 你这命令行还是root openwrt？看着不像容器 如果是容器那这个问题就查不下去了

是容器，可以通过输入uid以uid身份进入容器的bash或sh
![image](https://user-images.githubusercontent.com/36618980/173565185-d0866903-abf6-4828-bc70-cdef6b78cc9e.png)

反正现在是没有这个问题了，哈哈
