### ISSUE TITLE
【提交bug】自动分析假全集功能将BDMV剧集视为内含0集的假剧集

### ISSUE THREAD

**Issue by Lava-delta** [pofey/movie_robot#316]
![image](https://user-images.githubusercontent.com/61100224/173985711-e6ff4989-086c-44d8-bf37-389b3fdeb5e9.png)
![image](https://user-images.githubusercontent.com/61100224/173985735-87317b27-4f30-4705-ad37-08b445c82cd8.png)

**Comment by pofey** [comment]
0.9.91 修复
