### ISSUE TITLE
鬼刃之灭硬链接错误(0.9.74)

### ISSUE THREAD

**Issue by Turbo6666** [pofey/movie_robot#320]
订阅了第一季的鬼灭之刃 完成后硬链接识别成第四季 且手动修改也无法改变 #

![DWM` SY{%ZOF311PYBCMS(C](https://user-images.githubusercontent.com/105849652/174064667-07db927f-bf85-421a-a5c6-ebcd7e8f827b.png)
![屏幕截图 2022-06-16 194445](https://user-images.githubusercontent.com/105849652/174064673-b0545d8a-5ba0-4241-87d7-5cb2033b8d7a.png)
![屏幕截图 2022-06-16 194620](https://user-images.githubusercontent.com/105849652/174064681-97d48eec-ec4f-46a1-b3e2-29a4e0569575.png)

**Comment by pofey** [comment]
我去tmdb看了下 这东西在tmdb季度数据标的不是数字，是个中文

**Comment by Turbo6666** [comment]
> 我去tmdb看了下 这东西在tmdb季度数据标的不是数字，是个中文

我后来又下载了第三季做对比 是没有出现问题的 不知道是不是个例问题 我已经手动更改文件夹了

**Comment by Turbo6666** [comment]
> 我去tmdb看了下 这东西在tmdb季度数据标的不是数字，是个中文

我刚刚又下载了一部鱿鱼游戏 个人觉得这应该不是个例了 鱿鱼游戏只有一季他也整理成s2了
![屏幕截图 2022-06-16 224612](https://user-images.githubusercontent.com/105849652/174096851-c2962c01-f413-43fa-9532-48b4b2cc6d1f.png)

**Comment by mymoonyue** [comment]
哈哈鬼灭之刃我昨天也是S01识别成S04

**Comment by mymoonyue** [comment]
> 我去tmdb看了下 这东西在tmdb季度数据标的不是数字，是个中文

不管是不是中文，原名已经就是S01，咋的也不应该硬给改成S04吧

**Comment by pofey** [comment]
这里好像确实是出问题了 今晚查

**Comment by Turbo6666** [comment]
> 这里好像确实是出问题了 今晚查

有劳衣总～

**Comment by pofey** [comment]
976修复了
