### ISSUE TITLE
【问题】修改过滤规则后，曾经设置过该规则的订阅全部自动洗版

### ISSUE THREAD

**Issue by haha6311** [pofey/movie_robot#322]
需求：

增加时间判定，修改后的过滤规则只对之后的订阅或手动洗版操作生效，此前的设置了该规则的订阅如果没有手动操作不会自动按照新规则洗版。

或者确认修改时，弹出对话框，让我们决定是否对之前的这些订阅自动洗版

**Comment by pofey** [comment]
其实订阅时选过滤器 并非就绑定了那个过滤器 每一部订阅都是独立的，所以改过滤器行为是不会作用于订阅的。
