### ISSUE TITLE
下载记录集数显示错误

### ISSUE THREAD

**Issue by BruceSuen720** [pofey/movie_robot#324]
![4725fd1261bce9c85c926e193dc5df7](https://user-images.githubusercontent.com/85166199/174280173-2f77b03d-7fba-4678-b581-564b83f25900.png)
![080966126ad818549c7206e03a65491](https://user-images.githubusercontent.com/85166199/174280244-ce68941a-ad4a-4776-bb3b-88f66197a6a5.png)
怪奇物语将年限信息显示识别为集数

**Comment by pofey** [comment]
怪奇物语.S02.2017.全9集.1080p  解析结果{'start': 9, 'end': None, 'text': '9集'}
没法重现呢
