### ISSUE TITLE
订阅BUG

### ISSUE THREAD

**Issue by mymoonyue** [pofey/movie_robot#329]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/60549575/174465234-f4a34857-9ffe-4031-a633-87a3861641c7.png">

首先我库里没有这些，其次它的年份也不对。群里很多人遇到了。

**Comment by pofey** [comment]
对应时间日志
以及你用的什么媒体服务器，对应媒体服务器截图
还有版本号

**Comment by mymoonyue** [comment]
> 对应时间日志 以及你用的什么媒体服务器，对应媒体服务器截图 还有版本号

<img width="495" alt="image" src="https://user-images.githubusercontent.com/60549575/174467308-ce09c148-a8f0-4e5e-b2be-b552574e903c.png">

emby-4.7.1   movierobot-0.9.76

日志只有说已存在，而且这个bot说的名字跟年份完全对不上。

出问题的似乎都是剧集，我电影订阅的少，不知道其他人有没有遇到电影出问题。

**Comment by pofey** [comment]
![76EA35C5-1316-402E-9E3D-271A734001F2](https://user-images.githubusercontent.com/1396975/174468631-a38db347-2740-4926-ae93-f76228f5fd4a.png)
![7ACF7ADA-677F-467D-8A4E-5A128D77077E](https://user-images.githubusercontent.com/1396975/174468634-ff39a837-93d4-4dbe-b040-1e95eb8a5d75.jpeg)
用你真是个天才订阅试了一下，没什么问题 无法重现
