### ISSUE TITLE
宇宙探索编辑部 订阅搜索错误

### ISSUE THREAD

**Issue by AlanLang** [pofey/movie_robot#330]
订阅电影 宇宙探索编辑部 https://movie.douban.com/subject/34941536/
会自动按以下搜索条件搜索：宇宙探索编辑部,Journey to the West,tt15072612
但是当以 Journey to the West 进行搜索的时候，就会搜索到西游记红孩儿的资源：https://movie.douban.com/subject/35613319/
可能是因为二者年份相同，英文名也相同。
错误资源的标题：
Journey to the West Red boy 2021 2160p WEB-DL HEVC DDP5.1 QHstudio

**Comment by pofey** [comment]
那这种无解 手动下这个吧
