### ISSUE TITLE
豆瓣cookie

### ISSUE THREAD

**Issue by mymoonyue** [pofey/movie_robot#331]
豆瓣cookie经常用着好好的就失效了（表现为搜索结果没有豆瓣电影信息），然后去豆瓣cookie设置里面点保存提示 “豆瓣cookie有问题，请检查有效性”。

100%确认cookie无问题，也尝试各种办法重新获取甚至注册了新账号，还是保存失败。

**最迷的是有时候那个“有问题的cookie”不管他自己又好了**。可能是什么问题？据我所知最少三人中招了。

**Comment by AlanLang** [comment]
我这边也有同样的问题

**Comment by pofey** [comment]
把你获取cookie的过程截图，关键信息打码 发出来看看

**Comment by mymoonyue** [comment]
> 把你获取cookie的过程截图，关键信息打码 发出来看看
<img width="1268" alt="屏幕截图 2022-06-19 131933" src="https://user-images.githubusercontent.com/60549575/174467077-06d86160-a343-4cd6-b498-8a1889b12c40.png">

<img width="761" alt="屏幕截图 2022-06-19 132231" src="https://user-images.githubusercontent.com/60549575/174467128-7f981b19-f392-4ea0-bb71-56344a5a77ad.png">

豆瓣首页和豆瓣电影的cookie都试了，cookie应该没问题，我都用了几天之后才抽风的

**Comment by pofey** [comment]
有没有试过把豆瓣账号退出重新登陆

**Comment by mymoonyue** [comment]
> 有没有试过把豆瓣账号退出重新登陆

退出重登，无痕模式，换浏览器，注册新账号都试过了

**Comment by pofey** [comment]
我刚才拿了个新cookie试了下没什么问题，另外截图看，你的cookie比我的短好多。
https://movie.douban.com/
你通过这个域名获取ck试试吧，我是用豆瓣电影页面的ck

**Comment by mymoonyue** [comment]
> 我刚才拿了个新cookie试了下没什么问题，另外截图看，你的cookie比我的短好多。 https://movie.douban.com/ 你通过这个域名获取ck试试吧，我是用豆瓣电影页面的ck

豆瓣首页和豆瓣电影我都试过的，一开始提到了

<img width="1050" alt="屏幕截图 2022-06-20 072406" src="https://user-images.githubusercontent.com/60549575/174504163-7dbd5aee-f246-4193-bafe-98f878aaf3d4.png">

**Comment by pofey** [comment]
把你ck 发给我测试。我的一个疑问是，为什么你的ck这么短，我的内容值比你多知少三倍。

**Comment by mymoonyue** [comment]
> 把你ck 发给我测试。我的一个疑问是，为什么你的ck这么短，我的内容值比你多知少三倍。

好的，微信私发您了。

其他人长度不清楚，但是我的获取cookie方式应该没问题吧。edge和chrome都是一样的。
