### ISSUE TITLE
启动字幕下载任务提示错误

### ISSUE THREAD

**Issue by miniers** [pofey/movie_robot#332]
突然发现从6月13日以来就没有触发过字幕下载任务
尝试手动搜索电影触发下载时提示 “在媒体路径配置的路径中，找不到这部影片 天才不能承受之重(2022) tmdb_id: 648579“ ，我可以肯定在 媒体路径配置 已经配置了该目录
<img width="929" alt="iShot_2022-06-19_13 53 39" src="https://user-images.githubusercontent.com/2039910/174467864-a9b697f9-6970-46aa-8be4-0dc17094d9c9.png">
尝试 从下载记录中触发重新识别，日志提示 ： ERROR: 找不到天才不能承受之重(2022)的内容存放路径。
<img width="864" alt="iShot_2022-06-19_13 54 20" src="https://user-images.githubusercontent.com/2039910/174467896-29fb8659-0ea2-45bf-ab16-0ba6eca4b76f.png">
日志目录中，task_subtitle.log 最后更新时间也为13日，后续再无更新
<img width="557" alt="iShot_2022-06-19_13 57 54" src="https://user-images.githubusercontent.com/2039910/174467927-7dd44cdd-32eb-470f-85bf-7d6f46ca4696.png">
MR版本为：0.9.76

**Comment by pofey** [comment]
可以肯定已经配置 就把配置 和目录里这电影文件夹发出来看看？

**Comment by miniers** [comment]
<img width="946" alt="iShot_2022-06-19_14 14 04" src="https://user-images.githubusercontent.com/2039910/174468352-6f65297e-b347-4b7d-ad2c-7508abc76134.png">
上边这个是下载目录和硬链后目录内容
<img width="526" alt="iShot_2022-06-19_14 14 37" src="https://user-images.githubusercontent.com/2039910/174468367-d044f1d8-5ecb-45ee-9a32-ec0ef0e9a8ce.png">
上边这个是媒体目录配置

**Comment by pofey** [comment]
if filename.find('tmdbid=%s' % tmdb_id) != -1:
                return content_path
            if filename.startswith('%s(%s)' % (media_name, year)):
                return content_path

第一个查找 tmdb- 搜不到
第二个查找你文件夹名的那个括号是个中文括号么 如果是 估计也导致查找不到

**Comment by pofey** [comment]
应该是自定义format之后导致的，我看看这里怎么优化下

**Comment by miniers** [comment]
<img width="1011" alt="iShot_2022-06-19_14 47 14" src="https://user-images.githubusercontent.com/2039910/174469278-78f50947-f462-43e4-bd85-838db8bcd4e6.png">
是的，确实是自定义文件名，括号是英文的

**Comment by miniers** [comment]
暂时先把括号前后的空格取消就可以启动字幕下载任务了

**Comment by pofey** [comment]
不用，我改成正则查找了，下一版发
