### ISSUE TITLE
【提交bug】种子目录下面存在sample只硬链接了sample

### ISSUE THREAD

**Issue by happyhaha1** [pofey/movie_robot#333]
版本：0.9.76
种子目录
![image](https://user-images.githubusercontent.com/10184254/174482816-ffb42bc2-bc72-4bee-923b-e44f91098350.png)
硬链接目录，只硬链接了133.98m的sample
![image](https://user-images.githubusercontent.com/10184254/174483079-129af6e7-9ecd-4d4f-8760-98b0983c1fe9.png)
日志
![image](https://user-images.githubusercontent.com/10184254/174483104-546b6ae0-b008-4138-9324-9bed30b43d06.png)

**Comment by pofey** [comment]
确定是新版硬链接的bug 抽空修

**Comment by pofey** [comment]
0.9.78修复 等发布
