### ISSUE TITLE
升级最新0.9.77后rarbg种子拉取失败

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#334]
升级最新0.9.77后rarbg种子拉取失败，升级前无此问题
 2022/06/20 09:31:44 - ThreadPoolExecutor-3_0 - INFO: RARBG拉取种子超时，请耐心等待...
 2022/06/20 09:32:44 - ThreadPoolExecutor-3_0 - INFO: RARBG拉取种子超时，请耐心等待...
 2022/06/20 09:47:11 - ThreadPoolExecutor-4_2 - ERROR: 访问RARBG失败: RetryError[<Future at 0x7fc220267520 state=finished raised AttributeError>]
 2022/06/20 09:47:11 - ThreadPoolExecutor-3_0 - INFO: 所有站点资源信息已经更新完毕。
 2022/06/20 09:47:11 - ThreadPoolExecutor-3_0 - INFO: 没有任何需要养护的站点，停止免费任务获取。
 2022/06/20 09:47:12 - SubConsumer - INFO: 黑袍纠察队(2019) 已经有搜索结果，但经过你设定的过滤器后，无任何结果。
 2022/06/20 09:47:23 - SubConsumer - INFO: 已经开始在站点: pt时间,馒头,RARBG 搜索: 香水,Perfume: The Story of a Murderer,tt0396171
 2022/06/20 09:47:29 - ThreadPoolExecutor-0_2 - ERROR: 从RARBG搜索 ['tt0396171'] 失败了，错误信息: 'Rarbg' object has no attribute 'ACTION_PRE_REQUEST_TIME'
 2022/06/20 09:47:56 - ThreadPoolExecutor-0_2 - ERROR: 从RARBG搜索 ['tt0396171'] 失败了，错误信息: 'Rarbg' object has no attribute 'ACTION_PRE_REQUEST_TIME'
 2022/06/20 09:48:22 - ThreadPoolExecutor-0_2 - ERROR: 从RARBG搜索 ['tt0396171'] 失败了，错误信息: 'Rarbg' object has no attribute 'ACTION_PRE_REQUEST_TIME'
 2022/06/20 09:48:48 - ThreadPoolExecutor-0_2 - ERROR: 从RARBG搜索 ['tt0396171'] 失败了，错误信息: 'Rarbg' object has no attribute 'ACTION_PRE_REQUEST_TIME'
 2022/06/20 09:49:14 - ThreadPoolExecutor-0_2 - ERROR: 从RARBG搜索 ['tt0396171'] 失败了，错误信息: 'Rarbg' object has no attribute 'ACTION_PRE_REQUEST_TIME'
使用的是设置中的sock5代理，本地使用代理访问rarbg正常，猜想是否站点代理设置失效？

**Comment by pofey** [comment]
可能是个bug 晚上修
