### ISSUE TITLE
更新75版本后订阅电视剧一直报错

### ISSUE THREAD

**Issue by vickychien0114** [pofey/movie_robot#335]
之前一直用53版本，订阅电视剧都正常，自从更新75之后，一直报错
![image](https://user-images.githubusercontent.com/101592714/174512507-1e549ad4-c118-4f05-847c-0164753f5ef2.png)
![image](https://user-images.githubusercontent.com/101592714/174512553-09e652ed-ff1a-4c53-819c-3d9478f31930.png)
![image](https://user-images.githubusercontent.com/101592714/174512589-0c6c1d3d-d81f-4bca-ae11-7e8a6892e5ab.png)
已经删除原有订阅，重新订阅过，仍然报错，且没有添加任何订阅规则

**Comment by pofey** [comment]
报错给出的原因很清晰了，访问你自己那个域名端口超时，那应该是媒体服务器？
