### ISSUE TITLE
洗版无法删除老版资源，已经给了最高权限

### ISSUE THREAD

**Issue by zzj6666** [pofey/movie_robot#336]
![image](https://user-images.githubusercontent.com/101039599/174515044-f110ba93-b219-4f51-83ee-2a18bc96246d.png)
![image](https://user-images.githubusercontent.com/101039599/174515090-88c97c99-05a2-485c-a57c-22c2702628e3.png)

**Comment by pofey** [comment]
看报错，没什么问题很正常。现在的删除功能是联动媒体服务器去做的，所以能不能删，取决于你媒体服务器给机器人那个token有没有权限删。
