### ISSUE TITLE
[缺陷]: 自定义订阅是否可以自动使用原来的下载分类而不是预先指定下载分类？制作组可否允许输入关键字匹配？

### ISSUE THREAD

**Issue by elle007011** [pofey/movie_robot#338]
### 当前程序版本

0.9.77

### 问题描述

假设我只想从彩虹岛拉取SGNB制作组制作的蓝光原盘，需要预先指定下载至/movie或是其他分类。可否在成功订阅后走订阅流程，自动分拣到下载类别里？

第二，现在制作组就很多了，滚轮选取很麻烦，可否改成输入自动提示符合条件的制作组？比如输入sg，自动提示sgnb？

最后还有个小问题，我现在选择了sgnb，保存后再进入编辑，sgnb就没有了

### 重现步骤

我现在选择了sgnb，保存后再进入编辑，sgnb就没有了
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/105756846/174535139-c7a2f1a0-359a-4007-bb55-7b02b873031f.png">
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/105756846/174535160-3f7d2ee0-8492-427a-adf0-9348ac5d821c.png">

**Comment by pofey** [comment]
读取制作组的页面bug我知道；
关于自定义订阅这个路径选择，我也再考虑走智能那套规则，动态去分析，后面应该会开放选项出来。
制作组选择那块优化，我现在前端水平有限还不能做出更好的交互，我也还不是很满意。等等吧，现在输入首字母应该可以定位到附近。

**Comment by elle007011** [comment]
> 读取制作组的页面bug我知道；
> 关于自定义订阅这个路径选择，我也在考虑走智能那套规则，动态去分析，后面应该会开放选项出来。
> 制作组选择那块优化，我现在前端水平有限还不能做出更好的交互，我也还不是很满意。等等吧，现在输入首字母应该可以定位到附近。

收到，期待

**Comment by pofey** [comment]
制作组显示bug0.9.78修复 等发布
