### ISSUE TITLE
[优化]: 能否适配一下站点上传或下载限速

### ISSUE THREAD

**Issue by AdoShan** [pofey/movie_robot#339]
### 当前现状

现在没办法将自动添加的种子设置下载或上传限速。虽然大部分人的家宽可能达不到站点的上限。但是有一小部分人的带宽可以达到吧。例如某些站点上传限制12MB/s,12.5MB/s,25MB/s

### 你的建议

适配一下按照站点设置上传或下载限速

### 优先级

非常高

### 受众范围

一般

**Comment by pofey** [comment]
你这是刷流用吧，从正常家庭使用，观影问题这个范畴，是不会考虑去解决这个问题的。

**Comment by AdoShan** [comment]
> 你这是刷流用吧，从正常家庭使用，观影问题这个范畴，是不会考虑去解决这个问题的。

主要是刷流用。一半下载没限速。上传有，但是我记得好像有几个站点也是有下载限速

**Comment by pofey** [comment]
> > 你这是刷流用吧，从正常家庭使用，观影问题这个范畴，是不会考虑去解决这个问题的。
> 
> 主要是刷流用。一般下载没限速。上传有，但是我记得好像有几个站点也是有下载限速

目前还不想去优化专业刷流场景的功能，这不是常态性的功能，用同类一些专门刷流工具去解决吧。

**Comment by AdoShan** [comment]
> > > 你这是刷流用吧，从正常家庭使用，观影问题这个范畴，是不会考虑去解决这个问题的。
> > 
> > 
> > 主要是刷流用。一般下载没限速。上传有，但是我记得好像有几个站点也是有下载限速
> 
> 目前还不想去优化专业刷流场景的功能，这不是常态性的功能，用同类一些专门刷流工具去解决吧。

万一超前订阅的影片出了，下载之后还是有可能会超速

**Comment by pofey** [comment]
> > > > 你这是刷流用吧，从正常家庭使用，观影问题这个范畴，是不会考虑去解决这个问题的。
> > > 
> > > 
> > > 主要是刷流用。一般下载没限速。上传有，但是我记得好像有几个站点也是有下载限速
> > 
> > 
> > 目前还不想去优化专业刷流场景的功能，这不是常态性的功能，用同类一些专门刷流工具去解决吧。
> 
> 万一超前订阅的影片出了，下载之后还是有可能会超速

80%的用户是30M小水管，200M跑满也就16M左右，这个单种上传速率还不会超pt限制。再往上，正常用户在国内基本没有了。

**Comment by AdoShan** [comment]
> 80%的用户是30M小水管，200M跑满也就16M左右，这个单种上传速率还不会超pt限制。再往上，正常用户在国内基本没有了。

有俩站分别限速12MB/s，12.5MB/s，家园限制25MB/s。我这学校机房1G对等很容易超速，家园上传挺凶的。

**Comment by pofey** [comment]
> > 80%的用户是30M小水管，200M跑满也就16M左右，这个单种上传速率还不会超pt限制。再往上，正常用户在国内基本没有了。
> 
> 有俩站分别限速12MB/s，12.5MB/s，家园限制25MB/s。我这学校机房1G对等（过段时间如果重新搞了硬件的话带宽就更高了，目前是硬件问题导致只有1G带宽）很容易超速，家园上传挺凶的。

这种case 不用自动化工具时 你是怎么避免被封的呢？

**Comment by AdoShan** [comment]
> > > 80%的用户是30M小水管，200M跑满也就16M左右，这个单种上传速率还不会超pt限制。再往上，正常用户在国内基本没有了。
> > 
> > 
> > 有俩站分别限速12MB/s，12.5MB/s，家园限制25MB/s。我这学校机房1G对等（过段时间如果重新搞了硬件的话带宽就更高了，目前是硬件问题导致只有1G带宽）很容易超速，家园上传挺凶的。
> 
> 这种case 不用自动化工具时 你是怎么避免被封的呢？

手动限速。直接选中qb左侧的tracker然后全选种子限制上传速率
