### ISSUE TITLE
[优化]: 重新识别，结果继承+删旧硬链

### ISSUE THREAD

**Issue by leverule** [pofey/movie_robot#340]
### 当前现状

1. 剧集识别错误，手动重新识别，之后订阅（自由下载）到的同目录下追更剧集依然会识别错，并且会把整个目录再次错误硬链。
![Snipaste_2022-06-20_20-27-29](https://user-images.githubusercontent.com/57491211/174604588-5a5d9c08-a6ea-4c6b-8593-5e1f27bfd0b0.png)
添加追更剧集后：
![image](https://user-images.githubusercontent.com/57491211/174604081-899e40f8-2c16-4518-8e37-02ade39012a6.png)
![Snipaste_2022-06-20_19-48-09](https://user-images.githubusercontent.com/57491211/174604481-027ba8dd-d864-4edf-909a-42f88f537164.png)
![image](https://user-images.githubusercontent.com/57491211/174606867-a389ae27-9ceb-4c3e-bfc9-e5f2fdc5eb54.png)

2. 重新识别后，之前错误的硬链接未自动删除。已排除权限问题。

### 你的建议

1. 剧集重新识别后，之后同目录下的追更剧集自动继承重新识别的结果。
2. 重新识别后，自动删除之前错误的硬链接。

### 优先级

非常高

### 受众范围

很多人需要

**Comment by pofey** [comment]
1、错误的这部剧，原始文件名和上级文件夹名称复制出来。
2、手动你重新识别输入了什么它正常的，直接给tmdbid吗

**Comment by leverule** [comment]
斗罗大陆.Dou Luo Da Lu.2020.S01.1080p.WEB-DL.H264.AAC-PTerWEB\
斗罗大陆.Dou Luo Da Lu.2020.S01E174.1080p.WEB-DL.H264.AAC-PTerWEB.mp4

种子文件名里的年份有问题，应该是2018而不是2020，所以识别错了我觉得还好...

重新识别输入了这个
![image](https://user-images.githubusercontent.com/57491211/174609825-7e44f973-d942-4a2d-923b-283ac50290d2.png)
