### ISSUE TITLE
[优化]: 资源整理支持按照影视类型或区域进行分类

### ISSUE THREAD

**Issue by yoball** [pofey/movie_robot#341]
### 当前现状

根据目前MR的使用, 资源整理已经可以很方便的解决错误识别的问题了. 但是只能将电影或是剧集从一个下载路径下整理至另一个另一个下载路径下. 无法进行分类

如果已经有下载好的大包资源, 或是之前只配置了简单的电影剧集下载规则, 后期如果希望按照影视类型或者区域进行分类(类似于智能下载保存规则里面一样) 好像只能手动进行分类

### 你的建议

首先不太清楚目前是否已经有办法解决这种需求哈. 这里有几个建议:
1. 希望可以在资源整理页面添加两列, 一列是影视类型, 一列是区域. 这样就可以半自动化的进行整理. 
![ScreenShot-2022-06-21-01-12-56](https://user-images.githubusercontent.com/13519297/174651196-38d916fd-6855-41cb-bcd3-4195b7c3c9e8.png)
2. 可以直接根据在智能下载保存规则里面设定好的规则对于下载的文件进行自动分类.

### 优先级

一般

### 受众范围

不确定

**Comment by pofey** [comment]
这个数据现在都是有的。表格加个数据筛选，然后整理目标路径改成点整理在选，选中不同资源可以对应到不同目标路径，应该就可以灵活整理了。不过这个事不痛不痒，先留着吧。

**Comment by pofey** [comment]
关了这个，现在已经支持自动分类了
