### ISSUE TITLE
[缺陷]: 订阅的剧集自己变成电影了

### ISSUE THREAD

**Issue by mymoonyue** [pofey/movie_robot#346]
### 当前程序版本

0.9.78

### 问题描述

之前订阅的剧集，并且一直在上新中，突然发现它自己变成电影了。如图，**订阅时都是剧集形式，现在变成电影**

![image](https://user-images.githubusercontent.com/60549575/174725240-a805ad0c-8158-448b-8636-abbc50ac5526.png)

这或许是之前反馈的一直“**订阅已存在”的问题？**如图，这些都是剧集，如果库里已存在，正确提示应该是**某剧全多少集已存在**，现在它的提示是电影格式

![image](https://user-images.githubusercontent.com/60549575/174725418-7d516540-0eab-4da1-8e93-80375c28cd88.png)

### 重现步骤

没法具体让他重现。。。因为我也不知道是什么问题

**Comment by pofey** [comment]
没法重现也没有日志 让我看什么呢？

**Comment by mymoonyue** [comment]
> 没法重现也没有日志 让我看什么呢？

这怎么重现啊，我哪里知道它怎么变的？首先不是人为的，至于它怎么从剧集就变成电影了并没有日志体现。提示影视库已存在这个，比如正义的算法，你可以看看二十分钟前后的日志

<img width="584" alt="image" src="https://user-images.githubusercontent.com/60549575/174727960-62d6b790-579d-41bb-a719-f0adc0f53223.png">

<img width="427" alt="image" src="https://user-images.githubusercontent.com/60549575/174728046-79860422-6ad7-41b4-97a1-50fa5124c678.png">

**Comment by pofey** [comment]
那没法分析啊，我这也没问题，查不下去的。不然你就把有问题的都删了重新订阅吧
