### ISSUE TITLE
[缺陷]: 搜索报错

### ISSUE THREAD

**Issue by Ignatius-Ye** [pofey/movie_robot#348]
### 当前程序版本

0.9.78

### 问题描述

![Uploading Screenshot_20220621_220511.jpg…]()

### 重现步骤

正常搜索时报错

**Comment by pofey** [comment]
这个图没传完我看不到 另外把日志补一下

**Comment by Ignatius-Ye** [comment]
[Uploading movie-robot-beta.html…]()

**Comment by pofey** [comment]
日志断了没看到错误 大概率是你容器网络问题
