### ISSUE TITLE
[优化]: 能否在传统过滤器内加入自定义订阅的优先级偏好内容

### ISSUE THREAD

**Issue by elle007011** [pofey/movie_robot#350]
### 当前现状

当前只能选择规则，没有单独的优先级权重设置

### 你的建议

提供选项，允许优先（限制）下载某个站点、某个制作组。将传统过滤器与自定义订阅体验统一化

### 优先级

一般

### 受众范围

不确定

**Comment by elle007011** [comment]
> 我没有完全看懂 配点图示范说明一下是什么功能

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/105756846/174950247-3dd9522b-c3a9-4e18-9580-cc6e44e7d40c.png">
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/105756846/174950307-7c37917d-e618-4c0c-ae5f-d03fb2b664db.png">
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/105756846/174950337-e3365ea4-f6ae-415b-bb27-2e6824ebae14.png">
其实就是把过滤器和自定义订阅规则两者融合，使得过滤器可以优先下载某个站点、某个制作组、其他某个维度评价的种子

**Comment by pofey** [comment]
订阅过滤器和自定义那个规则同步？

**Comment by elle007011** [comment]
> 订阅过滤器和自定义那个规则同步？

倒没必要同步，但是将所有自定义订阅里可选择的项都开放给订阅过滤器，允许它做优先（或是降低权重）

**Comment by pofey** [comment]
你谈到优先这个字我就看不懂了

**Comment by elle007011** [comment]
> 你谈到优先这个字我就看不懂了

我表述的问题，优先我的意思是增加权重

**Comment by pofey** [comment]
影片订阅，现在是支持排序规则的，只是没开放给用户配置
