### ISSUE TITLE
[求助]: 微信下载完成无法推送，请求帮助。

### ISSUE THREAD

**Issue by icinessx** [pofey/movie_robot#356]
### 当前程序版本

0.9.78

### 问题描述

企业微信搜索和订阅剧集都可以推送，唯独下载完成无法推送。

### 重现步骤

企业微信输入电影名字，然后订阅都有发送消息，
![image](https://user-images.githubusercontent.com/7602422/174936847-db3b9cfc-33d9-4286-9faf-1d005dcac515.png)
，
![image](https://user-images.githubusercontent.com/7602422/174937038-a11bff36-6643-4495-9032-14383b6789c7.png)
就是没有下载完成提示，使用下载器是qBittorrent。

**Comment by pofey** [comment]
日志呢

**Comment by icinessx** [comment]
2022/06/22 15:22:11 - SubConsumer - INFO: 共在2个站点搜索到40条结果，其中馒头最慢，耗费18.95秒            
2022/06/22 15:22:11 - SubConsumer - INFO: 天才不能承受之重(2022) 当前最佳选择: Blu-ray 2160p Remux 资源：h
ttps://hdsky.me/details.php?id=243753&hit=1 已经提交下载。                                                
2022/06/22 15:22:11 - hdsky-downloader - INFO: 开始处理来自订阅的下载: [hdsky]The Unbearable Weight of Mas
sive Talent 2022 UHD BluRay REMUX 2160p HEVC TrueHD7.1 Atmos-HDS                                          
2022/06/22 15:22:22 - hdsky-downloader - INFO: [hdsky]The Unbearable Weight of Massive Talent 2022 UHD Blu
Ray REMUX 2160p HEVC TrueHD7.1 Atmos-HDS已经开始下载,路径：/downloads/ 分类：未设置   

![image](https://user-images.githubusercontent.com/7602422/174969098-cfc857a6-27dd-401f-80f6-b229292ff90f.png)

Robot消息里面也没下载完成的通知。

**Comment by pofey** [comment]
要看下载完成时的日志有什么报错
