### ISSUE TITLE
[缺陷]: 资源整理目录识别问题

### ISSUE THREAD

**Issue by cdjjustin** [pofey/movie_robot#361]
### 当前程序版本

0.9.82

### 问题描述

![image](https://user-images.githubusercontent.com/5894665/175035808-c47f8cfa-7f58-47e7-b6d3-eb4362ba1a15.png)
![image](https://user-images.githubusercontent.com/5894665/175035931-e5706e59-e2b6-483a-9307-bb8b686512ad.png)
![image](https://user-images.githubusercontent.com/5894665/175036004-15acd12b-aa28-4c3e-85ed-3affedab9126.png)
如上几图，实际目录下是有多个视频文件，在选择媒体路径时，该目录不会展开，选择后出现的媒体资源只有一个目录名的

### 重现步骤

如上

**Comment by pofey** [comment]
这个问题是什么？只显示一个目录是符合预期的

**Comment by cdjjustin** [comment]
> 

资源整理的时候，目录里边的视频文件没有显示在页面上，进行资源整理后，只硬连了一个文件
