### ISSUE TITLE
[优化]: 能否添加一个企业微信手动选择下载种子的功能

### ISSUE THREAD

**Issue by skypjsfly** [pofey/movie_robot#364]
### 当前现状

目前企业微信远程控制都只能订阅然后优选下载，个人不太喜欢优选，还是喜欢手动选择，请问有没有考虑过添加这个功能

### 你的建议

添加远程手动选择种子功能

### 优先级

不着急

### 受众范围

一般

**Comment by pofey** [comment]
不考虑，完全的伪需求。直接手机端开网页就可以选了。
