### ISSUE TITLE
[缺陷]: 搜索影片时，搜索不到结果，结果为0

### ISSUE THREAD

**Issue by iniwex5** [pofey/movie_robot#365]
### 当前程序版本

0.9.85

### 问题描述

> 搜索影片时，搜索不到结果，结果为0，显示：在1个站点搜索到0条结果，其中pt时间最慢，耗费0秒。前天0.9.75版本还是正常可以搜索到的。

### 重现步骤

![微信截图_20220623115957](https://user-images.githubusercontent.com/35565716/175206823-c6bacdeb-c7e0-414f-bcbc-18201da4e2c9.png)

### 发生问题时系统日志

```shell
2022/06/23 12:00:19 - Thread-709 - INFO: 已经开始在站点: pt时间 搜索: 加勒比海盗1
2022/06/23 12:00:19 - Thread-709 - INFO: 共在1个站点搜索到0条结果，其中pt时间最慢，耗费0.0秒
2022/06/23 12:01:07 - Thread-717 - INFO: 已经开始在站点: pt时间 搜索: 加勒比海盗1
2022/06/23 12:01:07 - Thread-717 - INFO: 共在1个站点搜索到0条结果，其中pt时间最慢，耗费0.0秒
```

### 其他信息

![image](https://user-images.githubusercontent.com/35565716/175206665-9919eb8e-ecb9-4ecc-88ce-0fd22c2964c4.png)

**Comment by iniwex5** [comment]
重新设置站点 也是没有用的
![image](https://user-images.githubusercontent.com/35565716/175206937-5fc29369-29e2-4df8-bbba-d7a74ad56908.png)

**Comment by pofey** [comment]
应该是站点适配文件有缺陷，这个问题其实我不管了，仅此一次吧，我没这个站。我帮你看了下民间版pttime，应该是path的分类设定错了，你自己打开文件改一下吧。
paths:
    - path: torrents.php
      categories: [ "!", 440, 441, 442, 443, 444, 445, 446, 447, 448 ]

 找到你那个适配文件，把配置改成这样再重启试试吧。你用的版本可能把所有分类都排除掉了，前面叹号就是非的意思
