### ISSUE TITLE
[缺陷]: 剧集集数识别错误

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#368]
### 当前程序版本

0.9.85

### 问题描述

旺达幻视通过微信订阅，识别错误

### 重现步骤

![image](https://user-images.githubusercontent.com/105474506/175296298-8dfbff7e-d538-4b37-9973-2c047eef8493.png)
整季识别为第九集

### 发生问题时系统日志

2022/06/23 18:36:42 - qywx-search - INFO: 旺达幻视(2021) 选用过滤器：欧美电视剧4k 排序规则：compress
 2022/06/23 18:36:44 - SubConsumer - INFO: 已经开始在站点: RARBG,pt时间 搜索: 旺达幻视,WandaVision,tt9140560
 2022/06/23 18:36:58 - SubConsumer - INFO: 旺达幻视(2021) 第1季 第[4]集 品质：WEB-DL 2160p x265 资源: https://www.pttime.org/details.php?id=3472&hit=1 已经提交下载。
 2022/06/23 18:36:58 - SubConsumer - INFO: 旺达幻视(2021) 第1季 第[5]集 品质：WEB-DL 2160p H.265 资源: https://www.pttime.org/details.php?id=3591&hit=1 已经提交下载。
 2022/06/23 18:36:58 - SubConsumer - INFO: 旺达幻视(2021) 第1季 第[9]集 品质：WEB-DL 2160p x265 资源: https://www.pttime.org/details.php?id=4132&hit=1 已经提交下载。
 2022/06/23 18:36:58 - SubConsumer - INFO: 旺达幻视(2021) 第1季 第[1]集 品质：WEB-Rip 2160p x265 资源: https://torrentapi.org/redirect_to_info.php?token=wpqi1g98nz&p=2_4_0_2_0_3_8__640ea43

**Comment by pofey** [comment]
下载记录里的显示是从种子标题抽的，要看种子标题叫什么

**Comment by elic6699** [comment]
WandaVision.S01.2160p.DSNP.WEB-DL.DDP.5.1.HDR.x265-TOMMY

**Comment by pofey** [comment]
这也无所谓 做硬链接处理就是根据实际ep分析了
