### ISSUE TITLE
[提问]: 无法硬链

### ISSUE THREAD

**Issue by oreme2** [pofey/movie_robot#370]
### 当前程序版本

0.9.53

### 问题

无法硬链
- 日志如图
![Snipaste_2022-06-23_19-34-13](https://user-images.githubusercontent.com/38098761/175318431-9a5b4366-4afd-4b6e-bffe-5ae721283526.jpg)

- docker映射
![Snipaste_2022-06-23_19-36-52](https://user-images.githubusercontent.com/38098761/175319056-f0b6ea4f-ce29-4e3b-afca-6f572fa4b6ab.jpg)
![Snipaste_2022-06-23_19-37-15](https://user-images.githubusercontent.com/38098761/175319068-bae2d04e-12fb-477c-b165-e9fd5a325ceb.jpg)

- 相应的文件系统：源文件已下载
![Snipaste_2022-06-23_19-35-31](https://user-images.githubusercontent.com/38098761/175319395-0fb2d09f-da1b-42dc-8150-27ad5205bd6b.jpg)
![Snipaste_2022-06-23_19-36-05](https://user-images.githubusercontent.com/38098761/175319470-ef0ca7b8-34a5-4280-a0b8-64890b41efc4.jpg)
![Snipaste_2022-06-23_19-36-22](https://user-images.githubusercontent.com/38098761/175319513-b96cea43-abcf-4d38-9efa-b493bfd1654a.jpg)

- 机器人硬链设置
![Snipaste_2022-06-23_19-37-44](https://user-images.githubusercontent.com/38098761/175319567-3d2944f1-6c21-423c-9d04-1cc4a0e2954d.jpg)

**Comment by pofey** [comment]
先升级再试
