### ISSUE TITLE
[优化]: 剧集名称过长导致下载记录的集数显示不完整

### ISSUE THREAD

**Issue by Xxx00xxX33** [pofey/movie_robot#373]
### 当前现状

在日剧/日漫中经常会出现名字太长的情况，这样会导致集数/季数显示不完全（我是macbook13寸小屏，不知道在大屏上是不是也这样），下载记录还有在订阅的时候会有看不到第几季第几集的情况，如图所示

<img width="271" alt="image" src="https://user-images.githubusercontent.com/29762822/175464971-c0212c6e-b8d5-4de9-8ced-7e3a17bb7e3c.png">

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/29762822/175465571-55b3dad5-123a-4c04-a1fb-e30bc60bccf4.png">
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/29762822/175465932-5d9ef9ad-4564-42aa-8c44-78eeb691ce68.png">

### 你的建议

- 季和集数的显示放在海报右上角或其他地方

- 用SxxExx替代第x季第x集

### 优先级

一般

### 受众范围

一般

**Comment by pofey** [comment]
短期先不改这个了，等下次下载记录页面大重构，再优化
