### ISSUE TITLE
[缺陷]: ttg过滤器不生效

### ISSUE THREAD

**Issue by FaintGhost** [pofey/movie_robot#376]
### 当前程序版本

0.9.86

### 问题描述

过滤器配置的选择 `只要不计下载量的种子` 和 `保留包含特定关键字的结果` 不生效。特意去网站上看了只有唯一一个free并且包含关键字的种子存在，但是程序自动选择了另一个没有free也没有关键字的种子。使用的是完全匹配。

### 重现步骤

选择过滤器，点击订阅。三种组合都试过，只要free，包含关键字，free和包含关键字。三次都选的同一个种子

### 发生问题时系统日志

```shell
movie-robot    | 2022/06/24 10:08:04 - SubRequestConsumer - INFO: 黑匣子(2021)$ 设置了独立的过滤规则，可以在我的订阅中查看和修改。
movie-robot    | 2022/06/24 10:08:04 - SubRequestConsumer - INFO: 新增来自admin的订阅: 黑匣子(2021) 设置了独立的过滤规则，可以在我的订阅中查看和修改。
movie-robot    | 2022/06/24 10:08:04 - SubConsumer - INFO: 已经开始在站点: 幼儿园,听听歌 搜索: 黑匣子,Black Box,tt10341034
movie-robot    | 2022/06/24 10:08:16 - SubConsumer - INFO: 共在2个站点搜索到31条结果，其中听听歌最慢，耗费11.73秒
movie-robot    | 2022/06/24 10:08:16 - SubConsumer - INFO: 黑匣子(2021) 已经有搜索结果，但目前为严格过滤模式，经过你设定的过滤器后，无任何结果。
movie-robot    | 2022/06/24 10:08:39 - SubConsumer - INFO: 已经开始在站点: 幼儿园,听听歌 搜索: 黑匣子,Black Box,tt10341034
movie-robot    | 2022/06/24 10:08:49 - SubConsumer - INFO: 共在2个站点搜索到31条结果，其中听听歌最慢，耗费10.44秒
movie-robot    | 2022/06/24 10:08:49 - SubConsumer - INFO: 黑匣子(2021) 没有找到符合过滤结果的资源，先下Blu-ray 2160p Remux 等到更好的资源会自动下载。
movie-robot    | 2022/06/24 10:08:49 - SubConsumer - INFO: 黑匣子(2021) 当前最佳选择: Blu-ray 2160p Remux 资源：https://totheglory.im//t/558465/ 已经提交下载。
movie-robot    | 2022/06/24 10:08:49 - ttg-downloader - INFO: 开始处理来自订阅的下载: [ttg]Black Box AKA Boîte noire 2021 UHD BluRay REMUX 2160p HEVC TrueHD7 1 Atmos-HDS
movie-robot    | 2022/06/24 10:08:50 - ttg-downloader - INFO: [ttg]Black Box AKA Boîte noire 2021 UHD BluRay REMUX 2160p HEVC TrueHD7 1 Atmos-HDS已经开始下载,路径：/downloads/movie/ 分类：电影 
movie-robot    | 2022/06/24 10:10:15 - SubRequestConsumer - ERROR: 没有在影视库找到需要删除的信息tmdb: 663260
movie-robot    | 2022/06/24 10:13:21 - SubRequestConsumer - INFO: 黑匣子(2021) 选用过滤器：Any-Free 排序规则：compress
movie-robot    | 2022/06/24 10:13:22 - SubRequestConsumer - INFO: 新增来自admin的订阅: 黑匣子(2021) 选用过滤器：Any-Free 排序规则：compress
movie-robot    | 2022/06/24 10:13:43 - SubConsumer - INFO: 已经开始在站点: 幼儿园,听听歌 搜索: 黑匣子,Black Box,tt10341034
movie-robot    | 2022/06/24 10:13:54 - SubConsumer - INFO: 共在2个站点搜索到31条结果，其中听听歌最慢，耗费11.09秒
movie-robot    | 2022/06/24 10:13:54 - SubConsumer - INFO: 黑匣子(2021) 没有找到符合过滤结果的资源，先下Blu-ray 2160p Remux 等到更好的资源会自动下载。
movie-robot    | 2022/06/24 10:13:54 - SubConsumer - INFO: 黑匣子(2021) 当前最佳选择: Blu-ray 2160p Remux 资源：https://totheglory.im//t/558465/ 已经提交下载。
movie-robot    | 2022/06/24 10:13:54 - ttg-downloader - INFO: 开始处理来自订阅的下载: [ttg]Black Box AKA Boîte noire 2021 UHD BluRay REMUX 2160p HEVC TrueHD7 1 Atmos-HDS
movie-robot    | 2022/06/24 10:13:54 - ttg-downloader - INFO: [ttg]Black Box AKA Boîte noire 2021 UHD BluRay REMUX 2160p HEVC TrueHD7 1 Atmos-HDS已经开始下载,路径：/downloads/movie/ 分类：电影 
movie-robot    | 2022/06/24 10:14:18 - SubRequestConsumer - ERROR: 没有在影视库找到需要删除的信息tmdb: 663260
movie-robot    | 2022/06/24 10:16:15 - Thread-240 - INFO: 已经开始在站点: 幼儿园,听听歌 搜索: 黑匣子
movie-robot    | 2022/06/24 10:16:16 - Thread-240 - INFO: 共在2个站点搜索到15条结果，其中听听歌最慢，耗费1.28秒
movie-robot    | 2022/06/24 10:17:47 - SubRequestConsumer - INFO: 黑匣子(2021)$ 设置了独立的过滤规则，可以在我的订阅中查看和修改。
movie-robot    | 2022/06/24 10:17:47 - SubRequestConsumer - INFO: 新增来自admin的订阅: 黑匣子(2021) 设置了独立的过滤规则，可以在我的订阅中查看和修改。
movie-robot    | 2022/06/24 10:18:16 - SubConsumer - INFO: 已经开始在站点: 幼儿园,听听歌 搜索: 黑匣子,Black Box,tt10341034
movie-robot    | 2022/06/24 10:18:27 - SubConsumer - INFO: 共在2个站点搜索到31条结果，其中听听歌最慢，耗费11.26秒
movie-robot    | 2022/06/24 10:18:27 - SubConsumer - INFO: 黑匣子(2021) 没有找到符合过滤结果的资源，先下Blu-ray 2160p Remux 等到更好的资源会自动下载。
movie-robot    | 2022/06/24 10:18:27 - SubConsumer - INFO: 黑匣子(2021) 当前最佳选择: Blu-ray 2160p Remux 资源：https://totheglory.im//t/558465/ 已经提交下载。
movie-robot    | 2022/06/24 10:18:27 - ttg-downloader - INFO: 开始处理来自订阅的下载: [ttg]Black Box AKA Boîte noire 2021 UHD BluRay REMUX 2160p HEVC TrueHD7 1 Atmos-HDS
movie-robot    | 2022/06/24 10:18:27 - ttg-downloader - INFO: [ttg]Black Box AKA Boîte noire 2021 UHD BluRay REMUX 2160p HEVC TrueHD7 1 Atmos-HDS已经开始下载,路径：/downloads/movie/ 分类：电影
```

### 其他信息

![1656059298409](https://user-images.githubusercontent.com/17885196/175496132-22456ec8-31a6-4a04-bcdf-25cea33537da.jpg)

**Comment by pofey** [comment]
没有找到符合过滤结果的资源
你使用了先下后洗，逻辑没什么问题，好好看看文档 
https://yee329.notion.site/12f6d44243194c8c96a7e000b9dde023

**Comment by FaintGhost** [comment]
> 没有找到符合过滤结果的资源 你使用了先下后洗，逻辑没什么问题，好好看看文档 [yee329.notion.site/12f6d44243194c8c96a7e000b9dde023](https://yee329.notion.site/12f6d44243194c8c96a7e000b9dde023)

我没有使用先下后洗 我说了我选择的完全符合

**Comment by FaintGhost** [comment]
第一次实验
过滤器所有条件都是空的，只有free搜索结果只有唯一free种子，使用完全符合还是选择其他种子
第二次实验
所有过滤器为空，匹配关键字，匹配的关键字也只有唯一结果，使用完全符合还是选择其他种子

**Comment by M-chacha** [comment]
> > 没有找到符合过滤结果的资源 你使用了先下后洗，逻辑没什么问题，好好看看文档 [yee329.notion.site/12f6d44243194c8c96a7e000b9dde023](https://yee329.notion.site/12f6d44243194c8c96a7e000b9dde023)
> 
> 我没有使用先下后洗 我说了我选择的完全符合 <img alt="image" width="373" src="https://user-images.githubusercontent.com/17885196/175528199-e010b5df-6035-49b0-ae14-9e30e35a04f7.png">

黑匣子(2021) 没有找到符合过滤结果的资源，先下Blu-ray 2160p Remux 等到更好的资源会自动下载。
这不就是吗 自己好好看看吧

**Comment by FaintGhost** [comment]
> > > 没有找到符合过滤结果的资源 你使用了先下后洗，逻辑没什么问题，好好看看文档 [yee329.notion.site/12f6d44243194c8c96a7e000b9dde023](https://yee329.notion.site/12f6d44243194c8c96a7e000b9dde023)
> > 
> > 
> > 我没有使用先下后洗 我说了我选择的完全符合 <img alt="image" width="373" src="https://user-images.githubusercontent.com/17885196/175528199-e010b5df-6035-49b0-ae14-9e30e35a04f7.png">
> 
> 黑匣子(2021) 没有找到符合过滤结果的资源，先下Blu-ray 2160p Remux 等到更好的资源会自动下载。 这不就是吗 自己好好看看吧

这就是我奇怪的地方，因为我选的就是完全匹配，但是还会下载，这就是我提的问题啊？

**Comment by FaintGhost** [comment]
开着完全匹配并且符合条件种子存在的情况下不仅不下载符合的种子，还去下别的种子。

**Comment by pofey** [comment]
> > 没有找到符合过滤结果的资源 你使用了先下后洗，逻辑没什么问题，好好看看文档 [yee329.notion.site/12f6d44243194c8c96a7e000b9dde023](https://yee329.notion.site/12f6d44243194c8c96a7e000b9dde023)
> 
> 我没有使用先下后洗 我说了我选择的完全符合 <img alt="image" width="373" src="https://user-images.githubusercontent.com/17885196/175528199-e010b5df-6035-49b0-ae14-9e30e35a04f7.png">

要去看，你订阅里的过滤条件是什么，截个图？

**Comment by FaintGhost** [comment]
> > > 没有找到符合过滤结果的资源 你使用了先下后洗，逻辑没什么问题，好好看看文档 [yee329.notion.site/12f6d44243194c8c96a7e000b9dde023](https://yee329.notion.site/12f6d44243194c8c96a7e000b9dde023)
> > 
> > 
> > 我没有使用先下后洗 我说了我选择的完全符合 <img alt="image" width="373" src="https://user-images.githubusercontent.com/17885196/175528199-e010b5df-6035-49b0-ae14-9e30e35a04f7.png">
> 
> 要去看，你订阅里的过滤条件是什么，截个图？ 再我的订阅，找到这个影片，点他的过滤就能看到详情
![1](https://user-images.githubusercontent.com/17885196/175564413-0ee70201-ccd1-40cb-9cc3-9d2950161a2f.jpg)
![2](https://user-images.githubusercontent.com/17885196/175564430-7bc5a653-0d53-43da-a717-cfa3922b5873.jpg)
![3](https://user-images.githubusercontent.com/17885196/175564439-2cae72c2-e4ac-440b-b49a-fe38cb4b10ed.jpg)

我的订阅规则基本都是留空，只要是free的就行
刚才又测试了一下没有下载其他种子了，但是全场唯一的free他也识别不到
```
2022/06/24 17:05:56 - SubRequestConsumer - INFO: 黑匣子(2021) 选用过滤器：Any-Free 排序规则：compress
2022/06/24 17:05:56 - SubRequestConsumer - INFO: 新增来自admin的订阅: 黑匣子(2021) 选用过滤器：Any-Free 排序规则：compress
2022/06/24 17:08:18 - ThreadPoolExecutor-3_2 - INFO: 开始同步站点资源信息...
2022/06/24 17:08:19 - ThreadPoolExecutor-3_2 - INFO: 幼儿园最新种子同步完成。
2022/06/24 17:08:20 - ThreadPoolExecutor-3_2 - INFO: 听听歌最新种子同步完成。
2022/06/24 17:08:20 - ThreadPoolExecutor-3_2 - INFO: 所有站点资源信息已经更新完毕。
2022/06/24 17:08:20 - ThreadPoolExecutor-3_2 - INFO: 开始筛选免费种子。
2022/06/24 17:08:20 - ThreadPoolExecutor-3_2 - INFO: 有1个免费种子需要下载，开始提交到下载器。
2022/06/24 17:08:20 - ThreadPoolExecutor-3_2 - INFO: 免费种子提交下载队列完成。
2022/06/24 17:08:20 - ttg-downloader - INFO: 开始处理免费种子下载任务: [ttg]The Public 2018 Blu-ray 1080p AVC DTS-HD MA5.1-DIY@TTG「DIY 官譯繁简中字」
2022/06/24 17:08:20 - SubConsumer - INFO: 已经开始在站点: 幼儿园,听听歌 搜索: 黑匣子,Black Box,tt10341034
2022/06/24 17:08:31 - SubConsumer - INFO: 共在2个站点搜索到31条结果，其中听听歌最慢，耗费11.15秒
2022/06/24 17:08:31 - SubConsumer - INFO: 黑匣子(2021) 已经有搜索结果，但目前为严格过滤模式，经过你设定的过滤器后，无任何结果。
```

**Comment by FaintGhost** [comment]
> 黑匣子(2021) 已经有搜索结果，但目前为严格过滤模式，经过你设定的过滤器后，无任何结果。 这回是严格过滤了，你到底要问题什么？

他应该有结果的啊，是有一个免费的种子他为什么不抓取呢？其他条件留空的只选free的意思应该就是free就会下载我没理解错误吧？

**Comment by FaintGhost** [comment]
我的目标：下载 `free` 的黑匣子，不管什么版本
现状：ttg有唯一一个 `free` 的版本，但是mr并不下载
我的问题很难理解吗？

**Comment by pofey** [comment]
> 我的目标：下载 `free` 的黑匣子，不管什么版本 现状：ttg有唯一一个 `free` 的版本，但是mr并不下载 我的问题很难理解吗？

你开贴的问题是，完全匹配过滤不生效，现在就问问你，生效了没

**Comment by pofey** [comment]
> > 
> 
> 不生效，生效他是不是应该把那个 `free` 的种子给我下载了？

黑匣子(2021) 已经有搜索结果，但目前为严格过滤模式，经过你设定的过滤器后，无任何结果。

日志显示，严格模式生效，这个帖子，结了，无效问题，无需修复。
如果你还有其他问题，描述清楚问题现象，附带详细信息，再去提。
