### ISSUE TITLE
[提问]: 扫码了支付宝并付款没有收到激活码

### ISSUE THREAD

**Issue by lxhj** [pofey/movie_robot#379]
### 当前程序版本

least

### 问题

mail:79492103@qq.com

**Comment by pofey** [comment]
哈哈哈 人工的 你也太早了

**Comment by lxhj** [comment]
![1656119521(1)](https://user-images.githubusercontent.com/5977779/175752635-3fe1b8e9-cd3d-4ce9-9440-ee28319ba01b.png)

不好意思啊，昨晚折腾半天，请问这个问题如何解决
