### ISSUE TITLE
[提问]: 

### ISSUE THREAD

**Issue by lxhj** [pofey/movie_robot#380]
### 当前程序版本

least

### 问题

【bug】无法选择PT站点
![1656125241(1)](https://user-images.githubusercontent.com/5977779/175755391-f659d1ce-dc22-4b7c-91fd-07c8be427d79.png)

请问不能新增站点的话，怎么下载呢？阻塞在这一步了

**Comment by pofey** [comment]
https://t.me/aimovierobot/117
我记得wiki写了
