### ISSUE TITLE
一个订阅生成了4个下载记录[缺陷]: 

### ISSUE THREAD

**Issue by sinosofti** [pofey/movie_robot#381]
### 当前程序版本

v1

### 问题描述
1、搜索纸钞屋
2、订阅纸钞屋
一个订阅生成了4个下载记录 并且转移到emby的文件夹名字不对
![image](https://user-images.githubusercontent.com/38282416/175760448-c20526a2-45d1-4244-909b-dea312fac382.png)
![image](https://user-images.githubusercontent.com/38282416/175760505-c9665ed5-2ae2-44e8-852d-c027b871d3f3.png)

### 重现步骤

v1

### 发生问题时系统日志
没截取到实时日志
_No response_

**Comment by pofey** [comment]
处理过程的日志发一下

**Comment by pofey** [comment]
还有你程序的版本号呢？

**Comment by pofey** [comment]
无人回复，关了
