### ISSUE TITLE
[缺陷]: 纪录片不下载元数据

### ISSUE THREAD

**Issue by oreme2** [pofey/movie_robot#382]
### 当前程序版本

0.9.86

### 问题描述

识别为纪录的TV不下载元数据
普通TV正常
如图
**TV**
![Snipaste_2022-06-25_19-11-05](https://user-images.githubusercontent.com/38098761/175771061-e1f7e938-1e56-464d-b942-be560edf1966.jpg)
![Snipaste_2022-06-25_19-10-17](https://user-images.githubusercontent.com/38098761/175771058-de217396-5b71-434e-b057-08421a916a6a.jpg)
**纪录片**
![Snipaste_2022-06-25_19-10-40](https://user-images.githubusercontent.com/38098761/175771059-498a1bee-2899-49d3-a56b-1974d5c4659e.jpg)
![Snipaste_2022-06-25_19-10-50](https://user-images.githubusercontent.com/38098761/175771060-4b84794c-b6d7-4116-b05c-adbfd9b2b0fe.jpg)

**纪录片正常识别tmdbid和改名**

这是分流规则
![Snipaste_2022-06-25_19-09-12](https://user-images.githubusercontent.com/38098761/175771099-78a3759b-4f35-4f56-9110-4e864fda10ed.jpg)

### 重现步骤

相同操作
普通TV正常
纪录片TV不下载元数据，正常识别和改名

### 发生问题时系统日志

```shell
日志无error
```

**Comment by pofey** [comment]
产品从来都不会下载元数据，目前版本任何资源也没下过
