### ISSUE TITLE
[提问]: 订阅剧集重复提示下载，0.9.87版本

### ISSUE THREAD

**Issue by vickychien0114** [pofey/movie_robot#383]
### 当前程序版本

0.9.87

### 问题

[订阅了梦华录一直提示下载重复的，日志里显示的存储路径找不到，但是存储路径从未变更过，之前一直正常订阅下载的
![image](https://user-images.githubusercontent.com/101592714/175771140-174498e4-acaf-4864-91be-15c3fdeedcaf.png)

![image](https://user-images.githubusercontent.com/101592714/175771151-11706324-6719-4e2e-9914-401af83b86a2.png)

![image](https://user-images.githubusercontent.com/101592714/175771157-1ba06aaa-ef9d-4fe3-b8af-7d6d1aa074a6.png)
![image](https://user-images.githubusercontent.com/101592714/175771210-aec3db1a-4d64-42ae-b3fc-d894315e7e11.png)
![image](https://user-images.githubusercontent.com/101592714/175771774-16a59132-9bf3-4bae-b34a-6cf2254d9067.png)

此问题升级到87版本才遇到的，之前没有，整体网络环境都没变过存储路径什么的都没有调整

**Comment by vickychien0114** [comment]
后来发现是IYUU辅种的下载器导致此问题，但是问题在哪儿确实不知道，因为这个也挺奇怪，辅种理论上不影响的，因为辅种文件夹是源目录啊

**Comment by pofey** [comment]
程序错误提示清晰，没有改动空间，自己排查分析解决

**Comment by vickychien0114** [comment]
> 程序错误提示清晰，没有改动空间，自己排查分析解决

真的是如果辅种会造成重复提示，不知道你有没有用IYUU一类的

**Comment by pofey** [comment]
> > 程序错误提示清晰，没有改动空间，自己排查分析解决
> 
> 真的是如果辅种会造成重复提示，不知道你有没有用IYUU一类的

我不做种，好像群里辅种的人都是把下载器分开

**Comment by vickychien0114** [comment]
下载器是分开的，但是下载目录是一起的，监控了下载目录，目前我把辅种的下载器删除了，貌似之前的问题解决了部分但是有点类似的小问题，
![image](https://user-images.githubusercontent.com/101592714/175798639-bde390b9-d6a6-48b5-b725-e2702241ccc5.png)
五点钟正好是我z转种任务发生的时间，而我现在转种下载器已经删除了的，MR里面只有一个下载器，只下载，不养站
