### ISSUE TITLE
[缺陷]: 找到一个错误的全集种子后 不自动继续使用另外正确的种子

### ISSUE THREAD

**Issue by oreme2** [pofey/movie_robot#384]
### 当前程序版本

0.9.86

### 问题描述

找到一个错误的全集种子后 不继续使用其他正确的种子

### 重现步骤

找到一个错误的全集种子后 不继续使用其他正确的种子
如图
![image](https://user-images.githubusercontent.com/38098761/175786366-7ad1cc7a-2ff2-4d90-a467-54a9fea0a3e8.png)
总共有十个种子，非要用最下面错误的
![image](https://user-images.githubusercontent.com/38098761/175786505-990b702e-27af-48f3-866c-c367197f2eb0.png)

我使用过滤器想要过滤该HDTV结果，结果如图---无种子，但是明明有这么多webdl。
![image](https://user-images.githubusercontent.com/38098761/175786549-ba032407-87bb-4bf7-83a8-3c7035830f18.png)

![image](https://user-images.githubusercontent.com/38098761/175786440-e6c82a1c-e37d-489f-aba0-49e897d58828.png)

所以找到一个错误的全集种子后 不继续使用其他正确的种子原因：可能是和我手动操作的一样，没找到种子

**Comment by oreme2** [comment]
找到一点问题，我把mteam关了，发现没有有效结果
![image](https://user-images.githubusercontent.com/38098761/175786914-bf1c42b5-4d49-4591-a8e4-8cfced06d810.png)
而可能原因是tmdb显示其剧集为2014年。除了hdtv这个种子未写明年份外，其他种子标注的年份都是错误的。分析种子的时候可能直接排除了其他搜索结果。不知道是不是这样

**Comment by pofey** [comment]
没错 除了你的过滤器 内置还有一堆分析器用来分析种子的有效性。面对这种极端命名和错误元数据没什么好办法 只能手动下载
