### ISSUE TITLE
[优化]: 自定义订阅可否将历史种子纳入订阅，按照每日一定数量进行下载？

### ISSUE THREAD

**Issue by elle007011** [pofey/movie_robot#385]
### 当前现状

现在的自定义订阅仅针对新种子生效，对以往的无能为力，在群里讨论时，大佬们也提示说如果全空将会下载整个站的种子导致很多问题。

### 你的建议

可否考虑允许搜索过往种子，但是按照每日一定数量（比如10/20/50）进行下载？慢慢补全所有相关内容

### 优先级

一般

### 受众范围

不确定

**Comment by pofey** [comment]
不考虑历史全站。
