### ISSUE TITLE
6.23更新空的站点文件之后，刷流全部失败

### ISSUE THREAD

**Issue by chqchshj** [pofey/movie_robot#386]
### 当前程序版本

0.9.87

### 问题

6.23更新空的站点文件之后，刷流全部失败

2022/06/26 12:36:44 - hdsky-downloader - ERROR: 下载种子错误：https://hdsky.me/download.php?id=244783&t=1656215438&sign=fadce9b9ec9fd96c2a54b9f291677993
2022/06/26 12:36:44 - hdsky-downloader - ERROR: <h1>Not Found</h1>
<script async src='/cdn-cgi/challenge-platform/h/g/scripts/invisible.js?ts=1656216000'></script><script type="text/javascript">(function(){window['__CF$cv$params']={r:'72133e617ca13a37',m:'pl3qnkjzzfbVR4zuvgATVGjsuHdMr7Eg8KoZstq1rq8-1656218204-0-Ad/dZwAGt7rs4srYn5v1+CECISTCt0bxQR6aPErKxVKo2XMpH1KygxXAKQLGiXQL4Tnwr9p4L6pkzMRe+sZsfbxf3RasbKfeqUvxs5aApX0qMl1cjFKVQVM0hY1zxU7iU9xZ80wqKJ5W9XSv08jk1gc28VOV/FdatTRPJnQkQf5AfyRd8ywmNbhy+QYBKpSl7P0kfPgq6EUrE+AvwY+bEWE=',s:[0x07024edee6,0x4f130aee45],u:'/cdn-cgi/challenge-platform/h/g'}})();</script>

2022/06/26 12:49:26 - hdsky-downloader - ERROR: 下载种子错误：https://hdsky.me/download.php?id=244785&t=1656215438&sign=bXXXXXXXXXX80605831f8
2022/06/26 12:49:26 - hdsky-downloader - ERROR: <h1>Not Found</h1>
<script async src='/cdn-cgi/challenge-platform/h/g/scripts/invisible.js?ts=1656216000'></script><script type="text/javascript">(function(){window['__CF$cv$params']={r:'721350fa3b08399c',m:'UmZZq0Vdh4pTHZYn8EZbbhOpjgxmMr4alRU6Xth0K4Y-1656218966-0-AWPevDdzHDkYEZyG2N1lZIM1uuZYLXmkFZyiWczi0tcwgcfD+g5Jy/IZHLBPwK6jrf2eZYyWrBkuZg20sp0qS/RkveyLd+d10YmxeK03RbbZXSqFK5qGY5REoKZxZH2scLYh8AwH97Z1bnMdFmRRI+m+fzEH2CFPJyD0jMD4ERzL12OruOG9vE24LcNwbZP/exNY2IDQhbWqTowU005iEo0=',s:[0x08985f79b2,0x42a233e1af],u:'/cdn-cgi/challenge-platform/h/g'}})();</script>
2022/06/26 12:49:58 - hdsky-downloader - ERROR: 下载种子错误：https://hdsky.me/download.php?id=244785&t=1656215438&sign=bXXXXXXXXXX80605831f8
2022/06/26 12:49:58 - hdsky-downloader - ERROR: <h1>Not Found</h1>
<script async src='/cdn-cgi/challenge-platform/h/g/scripts/invisible.js?ts=1656216000'></script><script type="text/javascript">(function(){window['__CF$cv$params']={r:'721351bf4da208a1',m:'62XVPzySTsXABQ5xOb0RMR5OSak1YdP9QNbU2fJzLG0-1656218998-0-ARh/yjXrkb+Dpi1K2sitGKxTj8/8pKH5mA+MBqPglK7LVsytoBvEddjc0cnkMnBj5NMI/xgALxAB0AaDt8M3m3U46ptmO1z8TnL+cSJh6mvYWUWY2DXMZflo2UsKjBI61dLGvuwckHp9LyX4c7MEvBQn3rvgml34rCSCMjIQ8Yrkf+tBCIcBc6/yPwneunqQfnpYiJGWLErFmtyOOBrlZTQ=',s:[0xceff524d6d,0x36aef5c964],u:'/cdn-cgi/challenge-platform/h/g'}})();</script>

**Comment by pofey** [comment]
站点配置文件发出来我试试

**Comment by chqchshj** [comment]
今天又更新了站点文件，刚才看已经正常了，但是刷流空间检测有点奇怪，我这边是一个2T的固态刷流，给机器人填写的是1t，目前磁盘只使用了200G，日志还会显示 ERROR: 剩余可用空间不足，停止下载，是否因为这个目录没有挂载给机器人的关系？
但是之前没挂载给机器人，刷流是正常的

2022/06/26 14:06:38 - ThreadPoolExecutor-4_0 - ERROR: 剩余可用空间不足，停止下载
2022/06/26 14:06:38 - hdsky-downloader - INFO: 开始处理免费种子下载任务: [hdsky]Everything Everywhere All at Once 2022 V3 BluRay 1080p AVC Atmos TrueHD7.1-AQLJ@HDSky
2022/06/26 14:06:38 - audiences-downloader - INFO: 开始处理免费种子下载任务: [audiences]Conspiracy S01 2020 1080p WEB-DL H265 AAC-ADWeb
2022/06/26 14:06:38 - ThreadPoolExecutor-4_0 - ERROR: 剩余可用空间不足，停止下载
2022/06/26 14:06:38 - ThreadPoolExecutor-4_0 - ERROR: 剩余可用空间不足，停止下载
2022/06/26 14:06:38 - ThreadPoolExecutor-4_0 - ERROR: 剩余可用空间不足，停止下载
2022/06/26 14:06:38 - ThreadPoolExecutor-4_0 - ERROR: 剩余可用空间不足，停止下载
2022/06/26 14:06:38 - ThreadPoolExecutor-4_0 - ERROR: 剩余可用空间不足，停止下载
2022/06/26 14:06:38 - ThreadPoolExecutor-4_0 - ERROR: 剩余可用空间不足，停止下载
2022/06/26 14:06:38 - ThreadPoolExecutor-4_0 - INFO: 免费种子提交下载队列完成。
2022/06/26 14:07:16 - hdsky-downloader - INFO: 开始处理免费种子下载任务: [hdsky]A Banquet 2021 1080p BluRay DTS x264-HDS
2022/06/26 14:08:41 - hdsky-downloader - INFO: 开始处理免费种子下载任务: [hdsky]Journey to the West-Conquering the Demons 2013 BluRay 1080p AVC Dolby TrueHD5.1-CHDBits
2022/06/26 14:10:05 - hdsky-downloader - INFO: 开始处理免费种子下载任务: [hdsky]Game of Thrones S06 2016 UHD BluRay REMUX 2160p HEVC TrueHD7.1 Atmos-HDS
2022/06/26 14:10:40 - hdsky-downloader - INFO: 开始处理免费种子下载任务: [hdsky]Love in a Fallen Ci

**Comment by chqchshj** [comment]
我再观察一两天看下…

**Comment by chqchshj** [comment]
中午更新站点文件后，刷流正常了一段时间，后续又开始了同样的报错
站点文件链接是这边下载的 
[https://github.com/M-chacha/movie_robot/releases/download/sync_sites-0625/sites.zip](url)

**Comment by pofey** [comment]
把梦华录看完了我测一下

**Comment by pofey** [comment]
我测试了一下，可以正常下载，你可以好好检查一下你本地hdsky的文件，是否为最新版。
最新版有一个配置特征：
download:
  method: POST
你可以搜一下
