### ISSUE TITLE
[缺陷]: 媒体文件夹下载路径与qb分类设置不同步

### ISSUE THREAD

**Issue by Alano-i** [pofey/movie_robot#387]
### 当前程序版本

0.9.87

### 问题描述

当同时设置好 `download_path` 和 `qbit_cate`, qb分类的默认保存路径没有自动同步设置为`download_path`设置的路径。
（如果不设置 `qbit_cate`似乎没有这个问题，在测试保存规则时也可以看到，如果同时设置`download_path` 和 `qbit_cate`，只会显示保存的qb分类，不显示实际保存的路径）
<img width="557" alt="image" src="https://user-images.githubusercontent.com/68833595/175803358-e19d86d7-1ca9-4d80-ae97-05fe1b46c1cd.png">

继续这个问题的描述，以下图中，国产剧为例。

<img width="366" alt="image" src="https://user-images.githubusercontent.com/68833595/175802288-00506076-f59a-4967-8e7b-ced5aec7be25.png">
假设，qb的默认保存路径为`/Media/downloads`，qb中未设置国产剧分类

在mr中提交订阅或者手动提交下载任务，qb中实际下载为：`/Media/downloads/国产剧` 而不是设置的`/Media/downloads/剧集/国产剧`
<img width="602" alt="image" src="https://user-images.githubusercontent.com/68833595/175802662-db2a6df0-26ac-480e-99a0-611376bd548f.png">

此时只有在qb分类中设置国产剧分类保存路径为`/Media/downloads/剧集/国产剧`，后续下载才会正常。

<img width="514" alt="image" src="https://user-images.githubusercontent.com/68833595/175802692-8ef10291-d2e3-4cc9-97bd-47317c1f0f39.png">

### 重现步骤

国产剧为例，

qb的默认保存路径为`downloads`，qb中未设置国产剧分类的保存路径，

mr下载路径设置时在 `downloads` 路径和`国产剧`之间再增加一级路径，比如 `downloads/剧集/国产剧`

### 发生问题时系统日志

```shell
ThreadPoolExecutor-4_3 - ERROR: 在存储路径设置的下载保存路径中，找不到此路径，请检查配置：/Media/downloads/国产剧 种子名: 梦华录.A.Dream.of.Splendor.S01.2022.2160p.WEB-DL.AAC.H265-HDSWEB hash: 8efb0f468af1261ce5fdbcfca8b5b69c563d9126
ThreadPoolExecutor-4_3 - INFO: 当前已配置的下载保存路径：dict_keys(['/Media/downloads/电影', '/Media/downloads/剧集/欧美剧', '/Media/downloads/动漫', '/Media/downloads/综艺', '/Media/downloads/剧集/国产剧', '/Media/downloads/剧集/港台剧'])
```

**Comment by M-chacha** [comment]
> ### 当前程序版本
> 0.9.87
> 
> ### 问题描述
> 当同时设置好 `download_path` 和 `qbit_cate`, qb分类的默认保存路径没有自动同步设置为`download_path`设置的路径。 （如果不设置 `qbit_cate`似乎没有这个问题，在测试保存规则时也可以看到，如果同时设置`download_path` 和 `qbit_cate`，只会显示保存的qb分类，不显示实际保存的路径） <img alt="image" width="557" src="https://user-images.githubusercontent.com/68833595/175803358-e19d86d7-1ca9-4d80-ae97-05fe1b46c1cd.png">
> 
> 继续这个问题的描述，以下图中，国产剧为例。
> 
> <img alt="image" width="366" src="https://user-images.githubusercontent.com/68833595/175802288-00506076-f59a-4967-8e7b-ced5aec7be25.png">
> 
> 假设，qb的默认保存路径为`/Media/downloads`，qb中未设置国产剧分类
> 在mr中提交订阅或者手动提交下载任务，qb中实际下载为：`/Media/downloads/国产剧` 而不是设置的`/Media/downloads/剧集/国产剧` <img alt="image" width="602" src="https://user-images.githubusercontent.com/68833595/175802662-db2a6df0-26ac-480e-99a0-611376bd548f.png">
> 
> 此时只有在qb分类中设置国产剧分类保存路径为`/Media/downloads/剧集/国产剧`，后续下载才会正常。
> 
> <img alt="image" width="514" src="https://user-images.githubusercontent.com/68833595/175802692-8ef10291-d2e3-4cc9-97bd-47317c1f0f39.png">
> 
> ### 重现步骤
> 国产剧为例，
> 
> qb的默认保存路径为`downloads`，qb中未设置国产剧分类的保存路径，
> 
> mr下载路径设置时在 `downloads` 路径和`国产剧`之间再增加一级路径，比如 `downloads/剧集/国产剧`
> 
> ### 发生问题时系统日志
> ```shell
> ThreadPoolExecutor-4_3 - ERROR: 在存储路径设置的下载保存路径中，找不到此路径，请检查配置：/Media/downloads/国产剧 种子名: 梦华录.A.Dream.of.Splendor.S01.2022.2160p.WEB-DL.AAC.H265-HDSWEB hash: 8efb0f468af1261ce5fdbcfca8b5b69c563d9126
> ThreadPoolExecutor-4_3 - INFO: 当前已配置的下载保存路径：dict_keys(['/Media/downloads/电影', '/Media/downloads/剧集/欧美剧', '/Media/downloads/动漫', '/Media/downloads/综艺', '/Media/downloads/剧集/国产剧', '/Media/downloads/剧集/港台剧'])
> ```
> 
> ### 其他信息
> _No response_

豆瓣想看的下载保存规则改了吗？

**Comment by Alano-i** [comment]
改了的
![1B8D8828-DB6F-45D1-80A1-488A09853465](https://user-images.githubusercontent.com/68833595/175810410-c7f04f95-2970-48db-9526-a89ba16ad968.png)

**Comment by pofey** [comment]
我仔细看了所有case，但似乎一切都符合预期逻辑。
1、带了cate提交到没设置cate的qbit，程序会传真实路径和分类给qbit，交由qbit自动管理。你测得qbit逻辑为无分类时自动在默认路径补分类文件夹，它的设计貌似没问题挺合理。
2、测试时有cate只提示cate，也是以前故意设计的，因为路径已经没有意义了。为了新用户友好，减少理解复杂度，现在新人应该已经没有qbit分类这个概念了。

**Comment by Alano-i** [comment]
> 我仔细看了所有case，但似乎一切都符合预期逻辑。 1、带了cate提交到没设置cate的qbit，程序会传真实路径和分类给qbit，交由qbit自动管理。你测得qbit逻辑为无分类时自动在默认路径补分类文件夹，它的设计貌似没问题挺合理。 2、测试时有cate只提示cate，也是以前故意设计的，因为路径已经没有意义了。为了新用户友好，减少理解复杂度，现在新人应该已经没有qbit分类这个概念了。

1、带了cate,提交到没有设置cate的qb, 但是实际只新建了分类，该分类保存路径并没有传过去，为空。
2、路径我认为是有意义的（虽说cate其实和路径指向的是同一个位置），种子越来越多，分类的意义在后期也就提现出来了。试想统一展示1000条种子记录，如果没有分类作为管理，我是看着有些头大的。
