### ISSUE TITLE
[优化]: 过滤器关键词建议

### ISSUE THREAD

**Issue by oreme2** [pofey/movie_robot#388]
### 当前现状

![image](https://user-images.githubusercontent.com/38098761/175815089-61c1dfac-4701-4d07-97a3-c42006935769.png)
如图排除种子的关键词用的逻辑是：有"A或B"，则排除
    选取种子的关键词用的逻辑是：有"A且B"，则选取

### 你的建议

我的希望可以"且"和"或"两个逻辑均有，在选取和排除时。

使用情景：
在动画剧集中，我们知道各个动画压制组并非如同电影电视压制组一样裸压。
他们会进行滤镜，修瑕等一些操作的bdrip。各个组的出产水平不一致，所以选取压制组的水平十分重要

比如我订阅一个动画，我想要的选取逻辑是“A压制组或B压制组”的作品。因为动画组往往不会撞车，这样的话A如果没压制的话，我就可以“或”选取B。
其实电影电视组也会有这样的问题，比如我想要WIKI组压制的，没有，就“或”CHD，这样就需要过滤器的设置为----如果关键字有"WIKI 或 CHD" ，则选取；而现在是有"WIKI 和 CHD"，才选取，显然无法满足需要。

### 优先级

非常高

### 受众范围

一般

**Comment by pofey** [comment]
现在这俩条件应该都是或

**Comment by pofey** [comment]
我认为你用现在的过滤器或，加排序规则的优先规则，就可以实现范围加优先过滤了
