### ISSUE TITLE
[优化]: 识别与整理设置

### ISSUE THREAD

**Issue by Jim-CN** [pofey/movie_robot#392]
### 当前现状

识别与整理设置中已可以通过配置的方式自定义命名格式，但修改后不直观，无法直接体现修改格式后的效果。对对自定义格式不十分清楚的普通用户不够友好。

### 你的建议

建议在修改命名格式配置的同时，能有一个样本媒体根据刚刚的自定义格式自动展示修改效果。

### 优先级

一般

### 受众范围

一般

**Comment by pofey** [comment]
挺好。但锦上添花，先放着吧。

**Comment by pofey** [comment]
https://yee329.notion.site/ed17e503e361449e8f364104d64ab150
通过在wiki中增加一些示范，来尝试解决这个问题吧，其实可选的样式就那么几种，是可枚举的，没必要增加复杂度折腾页面了。
