### ISSUE TITLE
[优化]: 希望webUI的搜索界面保持下载结果

### ISSUE THREAD

**Issue by haha6311** [pofey/movie_robot#393]
### 当前现状

因为家里网络环境没那么牛逼（我想有很多人跟我一样），大概得20秒出结果，这个等待时间我切到别的功能，再切回来就还要重新搜索。

### 你的建议

希望之后能加入会话监测机制（知道是那个浏览页面在开着）
搜索时，即使我切到别的功能，webui依然能让我知道搜索进程在进行（虽然看后台日志这个搜索进程确实是在进行的，但是能体现到界面上会更好）
还会为我保持搜索结果，即使我临时切到别的功能再切回来，依然能看到上一次搜索结果（除非我关掉浏览器一段时间，这个点我也不太会把握，不知道实现难度大不大）

### 优先级

一般

### 受众范围

一般

**Comment by pofey** [comment]
搜的慢还是要去分析自己连接pt站为什么慢，比如我把pt都代理掉就变快了。其次可以调整搜索超时的设置改进搜索体验。
关于这个优化本身，可能不用搞所谓搜索会话这么麻烦的改进。未来考虑开放搜索设定，对最近一瓷搜索加几分钟缓存就好了，这也可以让你离开页面甚至离开app，回来再搜同一个关键字可以瞬间加载

**Comment by haha6311** [comment]
![image](https://user-images.githubusercontent.com/36618980/175860079-5d8953db-23f5-4fac-aecf-70f32f9a22f2.png)
如果像这样搜索结果单拉个按钮放缓存结果可以嘛

**Comment by pofey** [comment]
关了，等待后期搜索条件优化，共同考虑这个问题
