### ISSUE TITLE
[提问]: 能否临时暂停养站任务

### ISSUE THREAD

**Issue by Alano-i** [pofey/movie_robot#394]
### 当前程序版本

0.9.88

### 问题

最近两天遇到一个场景，在外面远程观看影片时发现卡顿，查看后发现是养站任务占用了所有上传带宽。

能否有个临时关闭养站任务的开关（比如`临时暂停1小时`、`2小时`...`永久关闭`，类似这种）

这几天遇到了，只能干脆把 qb 停止运行了再观看影片，但是看完了又忘记重新打开qb, 第二天才发现才又去重新打开。

**Comment by pofey** [comment]
之前想过监听媒体服务器播放就自动限速 但是整体仍然觉得不优雅 没有更好的方案就先不做了

**Comment by leverule** [comment]
我在用爱快流控，外网看影片能把qb自动限速到100Kb/s，外网串流游戏也很舒服。这些活还是路由器来做最棒
![image](https://user-images.githubusercontent.com/57491211/175951224-f49976d7-ac52-4e38-ae61-8c46988ef314.png)
