### ISSUE TITLE
[优化]: 下载中途资源速度一直为0，希望智能更换种子重新下载

### ISSUE THREAD

**Issue by bobo0810** [pofey/movie_robot#395]
### 当前现状

使用过程中出现过几次：资源下载中途突然速度为0，卡在那，后续再没速度。

![I2022-06-26T+0800 下午7:30:44 066+0800](https://user-images.githubusercontent.com/26057879/175872731-ffa4bc06-7275-4048-bb50-f5c2716cc9a9.jpg)

### 你的建议

希望能监控下载过程，当种子下载速度为0的时间超过阈值时，智能更换种子重新下载该影片。

### 优先级

非常高

### 受众范围

很多人需要

**Comment by pofey** [comment]
这是一件很麻烦的事，策略极其难以定义，一个种子持续一段时间为0这种事情是综合因素导致的，单以这个策略去换种子，延伸出来要处理的细节非常多，完全没有必要。粗略的想一下，就要考虑手动的下载如何处理？如果丢弃换种，新种不合规矩甚至没有怎么办？有很多很多细节。
反而，你在过滤器把做种人数设置一定的保底，这个问题就不会出现了。
