### ISSUE TITLE
[优化]: 提供选项，仅将原盘资源的最大文件硬链接出来。

### ISSUE THREAD

**Issue by bobo0810** [pofey/movie_robot#396]
### 当前现状

当前设备：nas搭建MR，电视端是infuse、plex。
下载的原盘资源 文件太多，导致 硬链接后plex和infuse不能识别。
现象：MR通知下载完了，plex页面却没有该资源。需要手动把最大的文件剪切到 该影片根目录下才生效。

### 你的建议

提供一个选项：仅将原盘资源的最大文件硬链接出来即可。

### 优先级

非常高

### 受众范围

一般

**Comment by pofey** [comment]
这个事情有好多人提过。但是仍然不打算去以破坏原始文件的形式改进这个问题，你可以选择下remux。

**Comment by bobo0810** [comment]
> 这个事情有好多人提过。但是仍然不打算去以破坏原始文件的形式改进这个问题，你可以选择下remux。

1. 并不需要全局生效。 提供一个选项，需要的人再开启。
在yaml里配置也可以。
2. 我使用的是 自带collection，下载的原盘资源。

**Comment by pofey** [comment]
我用compress，现在只下remux。
当然我本地也有几十部BDMV，我用infuse播起来没什么问题

**Comment by bobo0810** [comment]
> 我用compress，现在只下remux。 当然我本地也有几十部BDMV，我用infuse播起来没什么问题

我用infuse播放也没问题。就是手动找到最大文件再转移路径 比较麻烦。

**Comment by pofey** [comment]
> > 我用compress，现在只下remux。 当然我本地也有几十部BDMV，我用infuse播起来没什么问题
> 
> 我用infuse播放也没问题。就是手动找到最大文件再转移路径 比较麻烦。

不用吧？我直接播的bdmv的文件夹

**Comment by bobo0810** [comment]
> 
是因为开启了这个选项吗？
![image](https://user-images.githubusercontent.com/26057879/175878757-73c9a9fc-ac0b-4aed-ad5d-66208adfbee1.png)

**Comment by pofey** [comment]
> 是因为开启了这个选项吗？
> ![image](https://user-images.githubusercontent.com/26057879/175878757-73c9a9fc-ac0b-4aed-ad5d-66208adfbee1.png)

不是 不过我是emby
