### ISSUE TITLE
[优化]: 能否优化上传量计算，目前上传量经常出错

### ISSUE THREAD

**Issue by AdoShan** [pofey/movie_robot#397]
### 当前现状

上传量出错目前发现两种情况。
一是今日上传计算错误，下方饼图并没有出错。
二是饼图计算错误，导致今日上传计算错误

目前观察到的两个可能导致错误的情况：
一：单纯的今日上传计算错误(目前不知道为啥会出这错误)，饼图正常
二：更新站点适配文件之后(或cookie失效后更新cookie后)直接将该站点的上传量全部计入今日上传

### 你的建议

可以尝试直接将前一日的上传量记录一下保存到数据库然后直接计算
或者有更好的方式也可以。不知道站点有没有对应的API

### 优先级

不着急

### 受众范围

不确定

**Comment by pofey** [comment]
发图和数据

**Comment by pofey** [comment]
> 是应该不至于更新个站点适配

这没啥错吧，第二天就好了，没什么问题

**Comment by AdoShan** [comment]
> > 是应该不至于更新个站点适配
> 
> 这没啥错吧，第二天就好了，没什么问题

但是第二天是好了，这不是因为当天更新站点适配文件之后就出问题了嘛，到了第二天那又是新的一天，当然得从新计算了，第二天错不错再另说。
另外有时候就算没更新站点适配文件和cookie还是会出现`问题一`描述的情况（就是上面那个数值大的离谱，然后下面的饼图看起来挺正常的，简单来说就算数值比饼图显示的数值大得多）。

**Comment by pofey** [comment]
当天新加计入，这个是统计口径的设计，这不能算是个“缺陷”

**Comment by AdoShan** [comment]
> 当天新加计入，这个是统计口径的设计，这不能算是个“缺陷”

站点不是当天新加哇。而且就算是新加，那也不能算作今日上传吧。😅

**Comment by AdoShan** [comment]
> > > 当天新加计入，这个是统计口径的设计，这不能算是个“缺陷”
> > 
> > 
> > 但是站点不是当天新加哇，只是更新了适配文件而已，如果这样的话柠檬也更新了，但是柠檬就没把全部的上传量算作今日上传，而是正常的计量。而且就算是新加，那也不能算作今日上传吧。😅
> 
> 那也许是站点适配文件之前版本解析有错，更新正常出来了

今天遇到了第一种状况：今日上传计算错误，下方饼图并没有出错。 0.9.93
![image](https://user-images.githubusercontent.com/44154107/177990389-cb334a42-7d9d-4d7c-afc2-5eb6035977da.png)
