### ISSUE TITLE
建议增加多种消息通知渠道

### ISSUE THREAD

**Issue by charmingYouYou** [pofey/movie_robot#4]
如果是python, 建议参考[sendNotify.py](https://github.com/bullfly666/percollect/blob/main/sendNotify.py)
如果是node, 建议参考[sendNotify.js](https://github.com/bullfly666/percollect/blob/main/sendNotify.js)

**Comment by pofey** [comment]
扩展通知渠道是低优先级需求，延缓后面再说吧
