### ISSUE TITLE
[提问]: 下载到qb的分类一直对不上

### ISSUE THREAD

**Issue by sinosofti** [pofey/movie_robot#401]
### 当前程序版本

 latest

### 问题

本人设置如图
![image](https://user-images.githubusercontent.com/38282416/175962010-36cd4ea5-2cd9-4b3d-a739-3cb68a75b244.png)
![image](https://user-images.githubusercontent.com/38282416/175962053-6327c7dd-27ba-4301-9521-274e1648ee43.png)
qb版本 linuxserver/qb latest
qb设置分类如图
![image](https://user-images.githubusercontent.com/38282416/175962651-e6994aee-4ef8-4ddc-901c-261220df6b86.png)

当时日志如图
![image](https://user-images.githubusercontent.com/38282416/175962860-6239e7be-869f-4725-a51b-7783e5f57ceb.png)

**Comment by pofey** [comment]
现在的程序提交时不会提交分类名称的，直接提交一个路径

**Comment by sinosofti** [comment]
![image](https://user-images.githubusercontent.com/38282416/176178321-44bc2922-ef78-4918-b54d-5e9f65cc1366.png)
那这里还需要创建分类吗？
还有映射到具体的美剧、韩剧 一个tv可以映射多个emby 美剧、韩剧文件夹吗？

**Comment by pofey** [comment]
> ![image](https://user-images.githubusercontent.com/38282416/176178321-44bc2922-ef78-4918-b54d-5e9f65cc1366.png) 那这里还需要创建分类吗？ 还有映射到具体的美剧、韩剧 一个tv可以映射多个emby 美剧、韩剧文件夹吗？

你如果没强迫症一定要分类，那就可以不建立了，下半句没看懂

**Comment by sinosofti** [comment]
就是机器人把美剧韩剧全部下载到tv文件夹，然后emby映射可以分别映射到embytv/美剧 embytv/韩剧 文件夹吗？建议加上分类 比较强迫症
