### ISSUE TITLE
[优化]: 订阅“已完成”页面可否将【电影】和【电视节目】区分开，同时允许一键更新同类订阅所使用的过滤器？

### ISSUE THREAD

**Issue by elle007011** [pofey/movie_robot#402]
### 你的建议

目前都是海报墙，只能一个一个来更改使用的过滤器。能否考虑将【电影】和【电视节目】区分开，并允许一键更新所使用的过滤器？

如果考虑的更细一些，就是允许在分类页面里用列表形式，通过勾选订阅实现一次多个订阅使用同一个过滤器

另外能否考虑给过滤器内【想要的分辨率】里增加一个永远都达不到的分辨率？比如说100K？这样只要选这一个分辨率，就能一直自动洗版了

### 优先级

一般

### 受众范围

不确定

**Comment by pofey** [comment]
比如说100K？这样只要选这一个分辨率，就能一直自动洗版了
这目的是要一层一层出好的就往上升么？

**Comment by elle007011** [comment]
> 比如说100K？这样只要选这一个分辨率，就能一直自动洗版了
> 这目的是要一层一层出好的就往上升么？

是的，出了更好的版本永远自动洗

**Comment by pofey** [comment]
> > 比如说100K？这样只要选这一个分辨率，就能一直自动洗版了
> > 这目的是要一层一层出好的就往上升么？
> 
> 是的，出了更好的版本永远自动洗

可是在实际需求层面，你应该不会每个版本都去看，只会看一个最快的，和一个符合口味的啊？中间过程的那么多有啥用

**Comment by elle007011** [comment]
其实影音库就是松鼠症嘛，最新、最全、最好，包括刮削，都是为了让这个影音库看起来更完备更专业，倒不是主要为了都看。另外自动洗版的目标就是“ready to go”，永远保持最好的状态> > > 比如说100K？这样只要选这一个分辨率，就能一直自动洗版了
> 
> > > 这目的是要一层一层出好的就往上升么？
> 
> > 
> 
> > 是的，出了更好的版本永远自动洗
> 
> 
> 
> 可是在实际需求层面，你应该不会每个版本都去看，只会看一个最快的，和一个符合口味的啊？中间过程的那么多有啥用

**Comment by pofey** [comment]
我能理解递进去洗的逻辑，我只是怀疑这个功能的实际作用。

**Comment by elle007011** [comment]
> 我能理解递进去洗的逻辑，我只是怀疑这个功能的实际作用。

如果不复杂的话，能否考虑做出来让大家试试？嘿嘿
