### ISSUE TITLE
[优化]: 过滤器（以及自定义过滤器）的几点小建议

### ISSUE THREAD

**Issue by leverule** [pofey/movie_robot#403]
### 当前现状

1. 选择制作组不太方便，因为组多（只有PC端可以输入首字母快速定位）。
![Snipaste_2022-06-27_21-41-42](https://user-images.githubusercontent.com/57491211/175958380-b89c697a-f52b-449e-a32f-dcd640be9576.png)
希望移动端也支持输入，快速定位制作组

2. 站点及制作组筛选功能，自定义有，而普通过滤器没有，体验不一致

3. 关键词开放“和”的逻辑，https://github.com/pofey/movie_robot/issues/388#issuecomment-1167354106
![Snipaste_2022-06-27_21-43-06](https://user-images.githubusercontent.com/57491211/175958449-765dbfe7-21f8-4784-8e37-a78363f5095b.png)

### 你的建议

如上，请衣总考虑

### 优先级

非常高

### 受众范围

一般

**Comment by pofey** [comment]
下一个版本过滤器和自定义过滤器条件同步，制作组改为可搜索。条件and与or 再等等吧

**Comment by leverule** [comment]
> 下一个版本过滤器和自定义过滤器条件同步，制作组改为可搜索。条件and与or 再等等吧

好耶
