### ISSUE TITLE
[优化]: 国产综艺的硬链接问题

### ISSUE THREAD

**Issue by bobo0810** [pofey/movie_robot#404]
### 当前现状

国产综艺的问题
1. 每期分上下两部分、甚至有上中下三部分。 而MR每期仅硬链接一个。
2. 存在很多版本。比如同一期内容有正常版、会员尊享版。

![image](https://user-images.githubusercontent.com/26057879/176337931-0bbfa005-2eda-481c-b749-16f89e69e6a8.png)

### 你的建议

Plex是可以识别PartA、PartB是同一期的，MR硬链接时带上Part应该就可以。

### 优先级

非常高

### 受众范围

很多人需要

**Comment by pofey** [comment]
下个版本支持，但是要手动改一下剧集的模版，先看文档吧https://yee329.notion.site/ed17e503e361449e8f364104d64ab150

**Comment by pofey** [comment]
> > 下个版本支持，但是要手动改一下剧集的模版，先看文档吧https://yee329.notion.site/ed17e503e361449e8f364104d64ab150
> 
> 如果更新了下一个版本，用户还需要手动改剧集模板吗？

按需，因为我不确定媒体服务器所需的part格式是什么，需要自己改
