### ISSUE TITLE
[缺陷]: 剧集 科幻（Sci-Fi&Fantasy） 无法正确识别保存

### ISSUE THREAD

**Issue by ShakeChanDev** [pofey/movie_robot#407]
### 当前程序版本

0.9.90

### 问题描述

TMDB 的剧集分类不含“科幻”，而是采用“Sci-Fi&Fantasy”，导致所有科幻的剧集无法正确归类到科幻上

### 重现步骤

《黑镜》《苍穹浩瀚》

**Comment by pofey** [comment]
确定过所有的Sci-Fi&Fantasy 都是科幻么？如果是，晚上我把这个标签翻译一下。

**Comment by ShakeChanDev** [comment]
确定，这个锅其实算tmdb的，tmdb剧集分类把“科幻和奇幻”并在一起并命名为“Sci-Fi&Fantasy”

<img width="557" alt="image" src="https://user-images.githubusercontent.com/2718231/176577099-fb0ab148-f4ba-4e66-8e39-40f69041533d.png">

**Comment by pofey** [comment]
晚上把这个sf替换成科幻

**Comment by pofey** [comment]
不用管测试，测试这个地方应该没改
