### ISSUE TITLE
[优化]: 希望普通用户订阅后需要管理员允许才进行下载

### ISSUE THREAD

**Issue by ericlokz** [pofey/movie_robot#413]
### 当前现状

此功能在jellyseerr(overseerr)也有,如果不是这个功能我已经完全弃用jellyseer了.
现MR版本是普通用户可以无任何限制的进行订阅,或者是直接搜索资源进行下载,而不担心PT站的各项数据是否允许进行大量的下载任务.

### 你的建议

希望可以增加类似jellyseer的权限管理,例如:
1.普通用户可以提交下载电视剧、电影的订阅申请，管理员收到推送通知后,确认审核后MR再启动任务.
2.增加普通用户能否直接使用"立即搜索资源"功能的开关.

附上jellyseerr关于订阅请求页面图:

![微信截图_20220701182645](https://user-images.githubusercontent.com/30315596/176877631-dc726d00-0ea3-4f7f-bd9f-b6ed45cf4fc8.png)
![微信截图_20220701182856](https://user-images.githubusercontent.com/30315596/176877658-808886e5-6a58-4133-a820-8e1573c4faef.png)

### 优先级

非常高

### 受众范围

很多人需要

**Comment by pofey** [comment]
多用户能力强化，应该会是1.0后的一个优化方向的，但是避免被提前抄袭，就不多介绍了
