### ISSUE TITLE
[优化]: 在自定义条件中添加RSS订阅地址

### ISSUE THREAD

**Issue by u93724** [pofey/movie_robot#418]
### 当前现状

我看了issue中其他几个关于RSS追番的反馈，作者提到了可以使用qb内置的订阅然后下载到指定的文件夹中解决，我实测了一下发现识别有错误 rss地址：https://mikanani.me/RSS/Search?searchstr=%E9%97%B4%E8%B0%8D%E8%BF%87%E5%AE%B6%E5%AE%B6&subgroupid=562&page=1
![chrome_sD4ke4us3F](https://user-images.githubusercontent.com/57604382/176992337-ceac8e54-ff84-4584-95b7-475dcd2ca354.png)上图是在bt站点rss订阅标题，下图是在qb中实际下载的种子标题
![chrome_o8yLZGQPxH](https://user-images.githubusercontent.com/57604382/176992355-73fc4116-e73a-4c08-a765-b032441447fd.png)
可以看出有的种子中文名，有的种子英文名，实测中文名可以识别但英文名无法识别，在资源整理中手动添加tmdb链接识别成功

### 你的建议

可以在自定义订阅中添加rss地址，并可以指定tmdb链接地址，增强识别的准确度。直接在MR中添加RSS订阅，也可以直接读取RSS内容，在RSS中都是中文标题并没有存在中英混杂的情况。

### 优先级

非常高

### 受众范围

不确定

**Comment by pofey** [comment]
看标题应该是nc-raws不认识，加个无效词就可以了。
rss不会再支持了，自定义订阅的体系比rss更高级，可用过滤项目更多。但是自定义订阅绑定一个固定的tmdbid，这个不排除可以支持
