### ISSUE TITLE
[提问]: 微信推送通知能否增加 {file_size} 程序变量

### ISSUE THREAD

**Issue by Alano-i** [pofey/movie_robot#422]
### 当前程序版本

0.9.93

### 问题

微信推送通知能否增加 `{file_size}` 程序变量
目前通知中没有文件大小的变量可调用，无法知道当前下载的种子的大小。

<img width="878" alt="image" src="https://user-images.githubusercontent.com/68833595/177081287-a371a448-3b71-4d00-a182-fb882d917ae0.png">

如果能有大小就太好了。

![image](https://user-images.githubusercontent.com/68833595/177081239-a55b8d47-9f78-463e-bf2c-20079c8d9234.png)

**Comment by pofey** [comment]
关心文件大小的作用是？

**Comment by Alano-i** [comment]
对下载资源的关注度我目前关注的有个点无非就是品质，目前通知只有名称这种基本信息，并没有品质。
即使都是4k,我会下载比对之后下载文件大小更大的（多数情况下）。
过滤器、排序规则已经可很细致的筛选了。有时候还是会下载到一些资源并不是想要的比如订阅的4k，若没有4k，会先按排序规则下个1080的。若强制只下4k，又会漏掉很多资源。所以我会比较在意这个资源的大小。
