### ISSUE TITLE
[优化]: 在【搜索栏】页面，为【已完成】的影片：添加【洗版】按钮

### ISSUE THREAD

**Issue by Howardnm** [pofey/movie_robot#424]
### 当前现状

- 目前，已经【已完成】的影片要重新洗版的话，要到【下载记录】慢慢找到【洗版】按钮，太麻烦了
- 最好是，直接搜索影片，就能看到【洗版】按钮。

### 你的建议

- 可以直接搜索影片，点击洗版，这个操作很方便
- 这样就可以不用到【下载记录】去慢慢找了
- 建议：在下面图片加上【洗版】按钮
![image](https://user-images.githubusercontent.com/55622355/177108549-849ab94f-fd92-4e1c-9667-63eb58640f6d.png)

### 优先级

一般

### 受众范围

不确定

**Comment by pofey** [comment]
你如果习惯搜索入口洗，那你搜到那条订阅记录，就可以直接洗了
