### ISSUE TITLE
[优化]: 建议搜索资源时候增加高级模式

### ISSUE THREAD

**Issue by jinfeng1985** [pofey/movie_robot#426]
### 当前现状

目前搜索内容时候是全站点搜索（配置允许web搜索的站点）

### 你的建议

希望可以根据自己的需求，添加高级搜索（当我只想在某个站点搜索时），可以只搜索单个站点的内容。目前，只能在站点管理中进行修改，但站点多了，临时修改还是比较麻烦的。

### 优先级

非常高

### 受众范围

很多人需要

**Comment by htnanako** [comment]
> ### 当前现状
> 目前搜索内容时候是全站点搜索（配置允许web搜索的站点）
> 
> ### 你的建议
> 希望可以根据自己的需求，添加高级搜索（当我只想在某个站点搜索时），可以只搜索单个站点的内容。目前，只能在站点管理中进行修改，但站点多了，临时修改还是比较麻烦的。
> 
> ### 优先级
> 非常高
> 
> ### 受众范围
> 很多人需要

搜完出结果筛选站点不就好了。

**Comment by pofey** [comment]
1.0之后是有一个搜索条件的改造 但不是什么所谓的高级模式，就是简单的把站点、分类，开放选择

**Comment by pofey** [comment]
已经发布了
