### ISSUE TITLE
[缺陷]: 动画标题解析貌似有问题没识别正确

### ISSUE THREAD

**Issue by zoooo0** [pofey/movie_robot#427]
### 当前程序版本

0.9.93

### 问题描述

因标题解析有误无法正常追更

pt站标题：[2022年7月新番] 欢迎来到实力至上主义的教室 第二季 / ようこそ実力至上主義の教室へ 2nd Season 第01集 内封中字
种子文件名：Youkoso.Jitsuryoku.Shijou.Shugi.no.Kyoushitsu.e.S02E01.1080p.Crunchyroll.WEB-DL.H264.AAC-CHDWEB.mkv

### 重现步骤

订阅欢迎来到实力至上主义的教室 第二季 

### 发生问题时系统日志

```shell
2022/07/05 11:59:53 - SubConsumer - INFO: [chdbits]Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e S02E01 1080p Crunchyroll WEB-DL H264 AAC-CHDWEB [2022年7月新番] 欢迎来到实力至上主义的教室 第二季 / ようこそ実力至上主義の教室へ 2nd Season 第01.. 官方中字是个全集种子，需要预分析可靠性...
2022/07/05 11:59:53 - SubConsumer - ERROR: [chdbits]Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e S02E01 1080p Crunchyroll WEB-DL H264 AAC-CHDWEB [2022年7月新番] 欢迎来到实力至上主义的教室 第二季 / ようこそ実力至上主義の教室へ 2nd Season 第01.. 官方中字是一个假全集种子，种子内共0集，实际全13集。 种子链接：https://chdbits.co/details.php?id=193390&hit=1
2022/07/05 11:59:53 - SubConsumer - INFO: 欢迎来到实力至上主义的教室(2017) 没有搜索到缺失的[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]集
```

**Comment by pofey** [comment]
日志不是提示种子假全集而被pass？实际种子文件有什么呢

**Comment by zoooo0** [comment]
> 日志不是提示种子假全集而被pass？实际种子文件有什么呢

就一个单文件啊
Youkoso.Jitsuryoku.Shijou.Shugi.no.Kyoushitsu.e.S02E01.1080p.Crunchyroll.WEB-DL.H264.AAC-CHDWEB.mkv
这个第二季的第一集

**Comment by zoooo0** [comment]
2022/07/05 20:02:00 - DownlaodCommander - INFO: 开始处理来自下载器的手动下载记录: Youkoso.Jitsuryoku.Shijou.Shugi.no.Kyoushitsu.e.S02E01.1080p.Crunchyroll.WEB-DL.H264.AAC-CHDWEB.mkv
2022/07/05 20:02:01 - DownlaodCommander - INFO: 识别到新的剧集下载任务，Youkoso.Jitsuryoku.Shijou.Shugi.no.Kyoushitsu.e.S02E01.1080p.Crunchyroll.WEB-DL.H264.AAC-CHDWEB.mkv已被纳入监控
![image](https://user-images.githubusercontent.com/62314432/177323250-8852e576-6628-49e5-820a-98cccde80f39.png)
手动提交倒是可以成功识别到。可能还是pt站标题问题？

**Comment by pofey** [comment]
这个标题太特殊了，不好定向去优化，先这么着吧
