### ISSUE TITLE
[优化]: 自动辅种（类似IYUU）

### ISSUE THREAD

**Issue by ShakeChanDev** [pofey/movie_robot#428]
### 你的建议

养站越往后发展可能会发生过度拟合的情况，自动辅种能更好地维护社区的生态

### 优先级

一般

### 受众范围

不确定

**Comment by pofey** [comment]
iyuu不好用么

**Comment by ShakeChanDev** [comment]
iyuu是一个粗糙且丑陋的工具。。
辅种功能在mr上能很优雅的结合，并不会感觉是硬塞

**Comment by ShakeChanDev** [comment]
嗯嗯，也是

**Comment by pofey** [comment]
> 嗯嗯，也是

还有一个最严重我的问题，为了解决种子检索的，不得不弄台服务器给大家作为检索源。这就意味着要自己弄个服务保存pt站所有种子信息在服务器，我是不太想干这个事的，这无异于自己再帮助配合传播维护盗版内容，触犯刑法，难脱从犯的嫌疑😅

**Comment by leverule** [comment]
> 辅种这个功能对pt圈生态确实是良性的，但我们的用户有多少愿意去为这个良性复出代价我是不确定的。从功能来说，就算它是个“粗糙丑陋”的工具，它应该还是可以独立很好的去解决辅种这个问题的吧，应该不至于不能用？如果他能用，并且这件事没什么变更好的可能了，那就没必要去卷它啊。

衣总抽空完善下对辅种的支持好啵，比如辅种重复通知，深度删除支持删辅种。

虽然开第二qb来辅种能解决重复通知，但深度删除不删第二qb的辅种，仍为做种状态（只有重启qb才显示文件丢失，停止做种），但文件已经没了，有被判做假种ban号的风险。尤其是硬盘满了整理影片，要大量删的时候

**Comment by leverule** [comment]
另外辅种对用户的代价其实很小噢，一份文件传多个站，省空间。辅种多了甚至不需要刻意刷流，比如我的辅种流量直接跑满带宽了，除非哪个站需要单独照顾一下。就是管理稍微麻烦点，比如删除这方面。好在有各种自动化工具
