### ISSUE TITLE
[缺陷]: 删除一个下载工具后在核心依赖健康状态依然可以看到这个下载工具的健康状态

### ISSUE THREAD

**Issue by Zayia** [pofey/movie_robot#429]
### 当前程序版本

0.9.93

### 问题描述

之前用的QBittorrent下载工具，后来删除了这个下载工具，改为使用Transmission
但是在核心依赖健康状态页面依然可以看到QB的健康状态
![image](https://user-images.githubusercontent.com/35530837/177296585-b470a0e7-b851-41d5-b809-8f553b81423e.png)

### 重现步骤

未重复操作

**Comment by pofey** [comment]
过24小时就没了
