### ISSUE TITLE
[缺陷]: 安娜 2022 无法下载

### ISSUE THREAD

**Issue by tianjian110** [pofey/movie_robot#430]
### 当前程序版本

最新

### 问题描述

安娜 2022 明明有资源，也无法下载

### 重现步骤

安娜 2022 明明有资源，也无法下载

**Comment by pofey** [comment]
选择过程的日志

**Comment by tianjian110** [comment]
![Uploading 4E20F98B-1945-45DD-AA69-6966D7FE297B.png…]()选错种子了

**Comment by tianjian110** [comment]
英文标题：Hanna S01 2160p AMZN WEBRip DDP 5.1 x264-AJP69
附标题：汉娜 第一季

**Comment by pofey** [comment]
以前的系统内置名称分析器，会按名称相似度，相似度高就给放过了，这个英文相似度太高了。
下一版做了一个危险的优化，把名称分析器变的更严格
