### ISSUE TITLE
[缺陷]: 最新版本在arm架构下启动可能报错

### ISSUE THREAD

**Issue by ibowennn** [pofey/movie_robot#431]
### 当前程序版本

0.9.91

### 问题描述

使用watchtower从80升到0.9.91后，docker提示standard_init_linux.go:228: exec user process caused: exec format error。
更新过程如下：
docker run --rm --name watchtower -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --cleanup --run-once movie-robot
time="2022-07-05T14:18:45Z" level=info msg="Watchtower 1.4.0"
time="2022-07-05T14:18:45Z" level=info msg="Using no notifications"
time="2022-07-05T14:18:45Z" level=info msg="Only checking containers with name \"movie-robot\""
time="2022-07-05T14:18:45Z" level=info msg="Running a one time update."
time="2022-07-05T14:18:45Z" level=info msg="Session done" Failed=0 Scanned=0 Updated=0 notify=no
time="2022-07-05T14:18:45Z" level=info msg="Waiting for the notification goroutine to finish" notify=no

更新完成后，docker无法启动，手动启动提示：
standard_init_linux.go:228: exec user process caused: exec format error

### 重现步骤

1.80版本使用watchtower更新至最新版；
2.更新后无法自动启动，手动启动MR失败。

### 发生问题时系统日志

```shell
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by pofey** [comment]
这日志不属于本程序

**Comment by ibowennn** [comment]
> 
自动更新后，在container station里面就显示这个
<img width="752" alt="image" src="https://user-images.githubusercontent.com/51699450/177353861-35c9880a-de03-4a87-a4a1-7a961908e1ec.png">

**Comment by pofey** [comment]
启动就这样，你是如何确定版本号的？现在应该是993了

**Comment by pofey** [comment]
> 自动更新后，在container station里面就显示这个
> <img alt="image" width="752" src="https://user-images.githubusercontent.com/51699450/177353861-35c9880a-de03-4a87-a4a1-7a961908e1ec.png">

这看起来像是docker层面的启动错误，还没进入到应用

**Comment by ibowennn** [comment]
> > 自动更新后，在container station里面就显示这个
> > <img alt="image" width="752" src="https://user-images.githubusercontent.com/51699450/177353861-35c9880a-de03-4a87-a4a1-7a961908e1ec.png">
> 
> 这看起来像是docker层面的启动错误，还没进入到应用



> > 自动更新后，在container station里面就显示这个
> > <img alt="image" width="752" src="https://user-images.githubusercontent.com/51699450/177353861-35c9880a-de03-4a87-a4a1-7a961908e1ec.png">
> 
> 这看起来像是docker层面的启动错误，还没进入到应用

我在notion看到日志是0.9.91，以为最新版就是91。
更新之前是正常运作的。根据notion的教程，使用watchtower进行更新，然后就无法启动了。
此外，上两个星期是成功使用watchtower更新到80的。

**Comment by ibowennn** [comment]
> 

是的，ARM。是新版本没支持这个架构吗？

**Comment by ibowennn** [comment]
> > 是的，ARM。是新版本没支持这个架构吗？
> 
> 嗯，最新版为了解决hdc 免费种子状态获取的问题，不得不引入Google chrome，而chrome就只有x86编译版本。 这个问题确实需要解决，我有两个优化方向 1、找到多平台架构兼容的浏览器模拟方案 2、回滚到之前的镜像基础，当hdc刷流开启时，验证cpu架构，自动在x86架构动态安装chrome 这两个改动都需要点时间，你手里没有x86架构的设备可用了么？

暂时没有了，那我先退回到以前的版本吧。

**Comment by ibowennn** [comment]
> > 是的，ARM。是新版本没支持这个架构吗？
> 
> 嗯，最新版为了解决hdc 免费种子状态获取的问题，不得不引入Google chrome，而chrome就只有x86编译版本。 这个问题确实需要解决，我有两个优化方向 1、找到多平台架构兼容的浏览器模拟方案 2、回滚到之前的镜像基础，当hdc刷流开启时，验证cpu架构，自动在x86架构动态安装chrome 这两个改动都需要点时间，你手里没有x86架构的设备可用了么？

请问是从哪个版本开始不支持arm的呢？

**Comment by pofey** [comment]
> > > 是的，ARM。是新版本没支持这个架构吗？
> > 
> > 
> > 嗯，最新版为了解决hdc 免费种子状态获取的问题，不得不引入Google chrome，而chrome就只有x86编译版本。 这个问题确实需要解决，我有两个优化方向 1、找到多平台架构兼容的浏览器模拟方案 2、回滚到之前的镜像基础，当hdc刷流开启时，验证cpu架构，自动在x86架构动态安装chrome 这两个改动都需要点时间，你手里没有x86架构的设备可用了么？
> 
> 暂时没有了，那我先退回到以前的版本吧。

嗯 向上一个版本程序应该是一样的，最新版只解决了一个hdc刷流问题

**Comment by ibowennn** [comment]
> > > > 是的，ARM。是新版本没支持这个架构吗？
> > > 
> > > 
> > > 嗯，最新版为了解决hdc 免费种子状态获取的问题，不得不引入Google chrome，而chrome就只有x86编译版本。 这个问题确实需要解决，我有两个优化方向 1、找到多平台架构兼容的浏览器模拟方案 2、回滚到之前的镜像基础，当hdc刷流开启时，验证cpu架构，自动在x86架构动态安装chrome 这两个改动都需要点时间，你手里没有x86架构的设备可用了么？
> > 
> > 
> > 请问是从哪个版本开始不支持arm的呢？
> 
> 去docker hub那个页面能看到

好的，谢谢。
