### ISSUE TITLE
[优化]: 建议支持通过宽容度筛选下载

### ISSUE THREAD

**Issue by sanpao-hu** [pofey/movie_robot#435]
### 当前现状

现在可以根据编码格式筛选种子。

### 你的建议

能否加入通过HDR/杜比视界及声音编码进行筛选。建议设立优先级。同时在重命名部分也添加播放宽容度标识。

### 优先级

非常高

### 受众范围

很多人需要

**Comment by sanpao-hu** [comment]
radaar采用的是自定义命名格式打分

**Comment by pofey** [comment]
之前观察过，媒体中音频质量不稳定 所以没有把音频作为标准选项开放出来，过滤用关键字可解

**Comment by sanpao-hu** [comment]
至少在规则里是有帮助的，场景如我需要最终需要的是2160p的杜比世界，但资源只有2160p的hdr和2160的sdr。

**Comment by pofey** [comment]
> 至少在规则里是有帮助的，场景如我需要最终需要的是2160p的杜比世界，但资源只有2160p的hdr和2160的sdr。

你会自己编辑那个规则文件也可以了
