### ISSUE TITLE
[缺陷]: 资源整理选择目录不显示里面的内容

### ISSUE THREAD

**Issue by Kev1nT** [pofey/movie_robot#441]
### 当前程序版本

0.9.94

### 问题描述

0.9.93之前正常，更新0.9.93-Beta后出现问题
且有的目录不能识别，有的目录可以识别
https://s3.bmp.ovh/imgs/2022/07/09/df9f5bb6eb4a58d2.jpeg

### 重现步骤

资源整理选择目录不显示里面的内容

**Comment by pofey** [comment]
把剧集的文件夹里边东西再截图一下看看

**Comment by Kev1nT** [comment]
https://s3.bmp.ovh/imgs/2022/07/09/cd0ebe9e3a119e0f.jpeg
https://s3.bmp.ovh/imgs/2022/07/09/83b872691bfd8593.jpeg
https://s3.bmp.ovh/imgs/2022/07/09/178a3d02b1f027e6.jpeg
比如选择Movie文件夹就可以识别到，选择TV或者动漫就没有，
群里有其他人也反馈这个问题，应该不是个例

**Comment by pofey** [comment]
你用个其他文件夹，打开直接看吧，别用这个选择，看看里面实际有什么，不应该

**Comment by pofey** [comment]
升级一下看看，昨天有bug

**Comment by Kev1nT** [comment]
感谢跟进，目前已更新到0.9.97，但问题依旧存在
看了下目录下的文件，除了影视文件外，还有一些metadata文件，尝试删除后问题依旧，
期间尝试过重新给目录权限，重启容器和NAS，但并没有解决问题

但此之外机器人其他功能均无问题

大佬看下我需要提供什么信息给你进行问题排查

**Comment by pofey** [comment]
> 感谢跟进，目前已更新到0.9.97，但问题依旧存在 看了下目录下的文件，除了影视文件外，还有一些metadata文件，尝试删除后问题依旧， 期间尝试过重新给目录权限，重启容器和NAS，但并没有解决问题
> 
> 但此之外机器人其他功能均无问题
> 
> 大佬看下我需要提供什么信息给你进行问题排查

现在main db sqlite 有个cache表 怀疑有缓存 有能力清空试试 不行就等后面出清缓存功能
