### ISSUE TITLE
[缺陷]: 监控种子任务出现错误：找不到目标链接路径或无权限访问：/downloads/电视剧

### ISSUE THREAD

**Issue by sinosofti** [pofey/movie_robot#444]
### 当前程序版本

 latest

### 问题描述

媒体文件夹删了这个硬链接之后

### 重现步骤

![image](https://user-images.githubusercontent.com/38282416/178134053-cca5a36b-a91c-43ec-8bc3-7abbfea58bf9.png)
![image](https://user-images.githubusercontent.com/38282416/178134152-fb06540d-9261-4a36-bba6-6f8d5debcfbb.png)

**Comment by pofey** [comment]
健康状态，以及你的配置信息和文件目录信息都发出来就明白了，程序以及提示的错误比较明确了
