### ISSUE TITLE
[缺陷]: 刷流量过程中，不会调用删除种子接口

### ISSUE THREAD

**Issue by OLOrz996** [pofey/movie_robot#447]
### 当前程序版本

0.9.93、0.9.97

### 问题描述

启动流量自动管理，发现免费种子永远不会被删除，但db文件内delete_status状态为0，抓包后发现，db内记录变化期间未曾调用qBittorrent删除种子api

### 重现步骤

1.检查qBittorrent免费种子情况，确实有大量未删除仍在做种，以其中一个种子为例
![image](https://user-images.githubusercontent.com/11268446/178152046-c0980be3-ddc9-48e1-8249-d2409736070b.png)
![image](https://user-images.githubusercontent.com/11268446/178152020-ce210f65-b2fe-4142-b363-39f21b67641e.png)

2.将db文件内所有记录都update为0
![image](https://user-images.githubusercontent.com/11268446/178152080-d34cd151-3e16-45b3-a5bd-3a8ea0438b27.png)

3.开启tcpdump抓包，等待db变化
![image](https://user-images.githubusercontent.com/11268446/178152107-0b1f91cc-9c4b-485b-9290-41ee33e10422.png)
![image](https://user-images.githubusercontent.com/11268446/178152112-eac51f85-65f4-4de3-9646-fc8c74ec3dce.png)

4.检查抓包情况，发现全程没有调用delete接口
![image](https://user-images.githubusercontent.com/11268446/178151821-616ea822-19b4-49e0-957c-4eeb70fbdc7a.png)

PS：作为对比，手动删除下载任务，qb能删除成功，抓包也能发现delete接口调用
![image](https://user-images.githubusercontent.com/11268446/178152192-9e7a3469-93e4-47db-82de-ed8ed9e6a6f1.png)

### 发生问题时系统日志

```shell
2022/07/10 23:47:53 - ttg-downloader - INFO: 开始处理免费种子下载任务: [ttg]NeZha 2021 1080p BluRay x265 10bit-WiKi  国粤双语 内封中字

2022/07/10 23:47:52 - ThreadPoolExecutor-4_2 - INFO: 彩虹岛最新种子同步完成。

2022/07/10 23:47:53 - ThreadPoolExecutor-4_2 - INFO: 免费种子提交下载队列完成。

2022/07/10 23:47:53 - ThreadPoolExecutor-4_2 - INFO: 开始筛选免费种子。

2022/07/10 23:47:53 - ThreadPoolExecutor-4_2 - INFO: 有1个免费种子需要下载，开始提交到下载器。

2022/07/10 23:47:52 - ThreadPoolExecutor-4_2 - INFO: 所有站点资源信息已经更新完毕。

2022/07/10 23:47:51 - ThreadPoolExecutor-4_2 - INFO: 馒头最新种子同步完成。

2022/07/10 23:47:31 - ThreadPoolExecutor-4_2 - INFO: 听听歌最新种子同步完成。

2022/07/10 23:47:26 - ThreadPoolExecutor-4_2 - INFO: 开始同步站点资源信息...

2022/07/10 23:30:00 - ThreadPoolExecutor-4_0 - INFO: 本次豆瓣想看同步到订阅任务已经完成。

2022/07/10 23:27:17 - ThreadPoolExecutor-4_4 - ERROR: 已经没有可用空间下载免费资源，总可用：1024.0 GB 当前已用：4148.838818359373 GB

2022/07/10 23:27:14 - ThreadPoolExecutor-4_4 - INFO: 彩虹岛最新种子同步完成。

2022/07/10 23:27:14 - ThreadPoolExecutor-4_4 - INFO: 所有站点资源信息已经更新完毕。

2022/07/10 23:27:12 - ThreadPoolExecutor-4_4 - INFO: 馒头最新种子同步完成。

2022/07/10 23:26:58 - ThreadPoolExecutor-4_4 - INFO: 听听歌最新种子同步完成。

2022/07/10 23:26:52 - ThreadPoolExecutor-4_4 - INFO: 开始同步站点资源信息...

2022/07/10 23:20:20 - SubRequestConsumer - INFO: 举起手来(2003)字幕下载到达限制，已经终止。启动至今：61分钟 运行次数：2

2022/07/10 23:20:00 - ThreadPoolExecutor-4_4 - INFO: 举起手来(2003)字幕下载已经提交启动。

2022/07/10 23:18:45 - Thread-5456 - INFO: 举起手来！Hands Up!2003.4K.WEB-DL.H265.AAC-PTerWEB已经从下载器中被删除。

2022/07/10 23:06:45 - ttg-downloader - INFO: 开始处理免费种子下载任务: [ttg]From Russia With Love 1963 1080p BluRay x264 DTS-WiKi

2022/07/10 23:06:43 - ttg-downloader - INFO: 开始处理免费种子下载任务: [ttg]NeZha 2021 1080p BluRay x264-WiKi  国粤双语 内封中字

2022/07/10 23:06:43 - ThreadPoolExecutor-4_0 - INFO: 开始筛选免费种子。

2022/07/10 23:06:43 - ThreadPoolExecutor-4_0 - INFO: 有2个免费种子需要下载，开始提交到下载器。

2022/07/10 23:06:43 - ThreadPoolExecutor-4_0 - INFO: 免费种子提交下载队列完成。

2022/07/10 23:06:42 - ThreadPoolExecutor-4_0 - INFO: 所有站点资源信息已经更新完毕。
```

**Comment by pofey** [comment]
你手动update成0时 当然不会触发种子删除，这符合预期啊

**Comment by pofey** [comment]
因为现在我会认为，种子记录如果因某些原因删除了，就不能删种子，怕有hr https://yee329.notion.site/c5ab6da4911746efa2ed557283d04fcd 
代码逻辑里有说明的

**Comment by pofey** [comment]
你未更新数据库前，遇到了什么问题？

**Comment by OLOrz996** [comment]
> 你未更新数据库前，遇到了什么问题？

我是因为发现免费的种子从未被删除过，所以尝试更新数据库复现问题。正常来说就不应该出现qb里还存在但是db里删除状态为1的情况。

**Comment by pofey** [comment]
`            if free.torrent_hash not in torrent_dict:
                # 确认一下如果下载器不存在，则标记为删除
                if not download_service.get_download_client().exists_hash(free.torrent_hash):
                    free.delete_status = 1
                    free.update()
                continue
            t = torrent_dict[free.torrent_hash]
            if DownloadUtils.rstrip_path(t.save_path) != DownloadUtils.rstrip_path(
                    base_config.free_download.get('save_path')):
                logging.info(f'{t.name} 保存目录已经和免费保存路径不符，将脱离免费任务监控，现保存路径：{t.save_path}')
                self.delete_free_download_record(t.hash)
                continue`

只有上述两种情况，会出现你说的只变更记录状态，但不操作下载器。除此之外，全部都是先调用下载器删除，再做记录删除标记。

**Comment by OLOrz996** [comment]
> 

请问如何能设置日志级别为info，我想排查一下是否为第二种情况

**Comment by pofey** [comment]
> > 
> 
> 请问如何能设置日志级别为info，我想排查一下是否为第二种情况

默认就是info，你是否变更了目录，你自己应该比较清楚吧

**Comment by OLOrz996** [comment]
> rstrip_path

日志里没有出现过上图的记录，我没有手动变更过目录，只是设置了qb的未完成文件单独保存
![image](https://user-images.githubusercontent.com/11268446/178269991-04f60c3f-a213-4103-8559-f72238e05eec.png)

**Comment by OLOrz996** [comment]
> 如果是第一的话，免费下载任务的表中，还有torrent hash的字段，你可以查看状态为删除，但是下载器还有的那些hash，在下载器中是否存在，检查是否走了第一个逻辑。 如果这一步没问题，那就只能加日志了。

这是我最开始查询问题时的截图，可以看见存在相同hash值的种子，db中标记已删除，但下载器中还存在。
![image](https://user-images.githubusercontent.com/11268446/178152046-c0980be3-ddc9-48e1-8249-d2409736070b.png)
![image](https://user-images.githubusercontent.com/11268446/178152020-ce210f65-b2fe-4142-b363-39f21b67641e.png)
感觉只能加日志看下到底逻辑走到哪儿去了……

**Comment by pofey** [comment]
> > 如果是第一的话，免费下载任务的表中，还有torrent hash的字段，你可以查看状态为删除，但是下载器还有的那些hash，在下载器中是否存在，检查是否走了第一个逻辑。 如果这一步没问题，那就只能加日志了。
> 
> 这是我最开始查询问题时的截图，可以看见存在相同hash值的种子，db中标记已删除，但下载器中还存在。 感觉只能加日志看下到底逻辑走到哪儿去了…… ![image](https://user-images.githubusercontent.com/11268446/178152046-c0980be3-ddc9-48e1-8249-d2409736070b.png) ![image](https://user-images.githubusercontent.com/11268446/178152020-ce210f65-b2fe-4142-b363-39f21b67641e.png)

嗯 下一版我补点关键状态变更日志吧

**Comment by OLOrz996** [comment]
> > > 如果是第一的话，免费下载任务的表中，还有torrent hash的字段，你可以查看状态为删除，但是下载器还有的那些hash，在下载器中是否存在，检查是否走了第一个逻辑。 如果这一步没问题，那就只能加日志了。
> > 
> > 
> > 这是我最开始查询问题时的截图，可以看见存在相同hash值的种子，db中标记已删除，但下载器中还存在。 感觉只能加日志看下到底逻辑走到哪儿去了…… ![image](https://user-images.githubusercontent.com/11268446/178152046-c0980be3-ddc9-48e1-8249-d2409736070b.png) ![image](https://user-images.githubusercontent.com/11268446/178152020-ce210f65-b2fe-4142-b363-39f21b67641e.png)
> 
> 嗯 下一版我补点关键状态变更日志吧

好的，多谢了

**Comment by pofey** [comment]
已经在每一处删除之前加了日志，等下一版发布吧

**Comment by OLOrz996** [comment]
后续来了，系统认为种子在下载器不存在，但看起来实际上是存在的
![image](https://user-images.githubusercontent.com/11268446/178794634-69fdaada-d2a9-4b36-b351-84b2e3fbce54.png)
![image](https://user-images.githubusercontent.com/11268446/178794748-ba3fcc0e-fa83-4468-b418-6b807c1cbead.png)

**Comment by pofey** [comment]
你配对下载器了吗，qbit版本是多少？
torrents: TorrentInfoList = self.qb.torrents_info(torrent_hashes=torrent_hash)

日志前查找的请求调用的qbit api，没什么出错的可能性了

**Comment by pofey** [comment]
qbittorrent-api==2022.3.29

**Comment by OLOrz996** [comment]
> 你配对下载器了吗，qbit版本是多少？ torrents: TorrentInfoList = self.qb.torrents_info(torrent_hashes=torrent_hash)
> 
> 日志前查找的请求调用的qbit api，没什么出错的可能性了

下载器是配对了的，因为我通过订阅是可以推送下载任务，并成功删除的。
目前qbit是FreeBSD自编译版本  qBittorrent v4.4.3.1 
![image](https://user-images.githubusercontent.com/11268446/178899059-0c0288b1-e3df-4362-ba5f-f25ba8134ae9.png)
![image](https://user-images.githubusercontent.com/11268446/178899148-fd82a150-38ec-404a-ab01-6abfe5a88fdc.png)

**Comment by pofey** [comment]
> > 你配对下载器了吗，qbit版本是多少？ torrents: TorrentInfoList = self.qb.torrents_info(torrent_hashes=torrent_hash)
> > 日志前查找的请求调用的qbit api，没什么出错的可能性了
> 
> 下载器是配对了的。 ![image](https://user-images.githubusercontent.com/11268446/178902317-2cd44ef2-2e77-4470-8847-40aa7a2559aa.png)
> 
> 同时我通过订阅是也是可以推送下载任务，在movie robot的下载页面手动删除，下载器里面也可以成功。 ![image](https://user-images.githubusercontent.com/11268446/178905556-a25aff1d-c165-4428-8c73-c7eb9d4b927d.png)
> 
> 目前qbit是FreeBSD自编译版本 qBittorrent v4.4.3.1 ![image](https://user-images.githubusercontent.com/11268446/178899059-0c0288b1-e3df-4362-ba5f-f25ba8134ae9.png) ![image](https://user-images.githubusercontent.com/11268446/178899148-fd82a150-38ec-404a-ab01-6abfe5a88fdc.png)

看到你这图，恍然大悟。自支持多下载器后，如果定义了不同站点到不同下载器，刷流的淘汰就会出bug，已经修复掉了。稍晚98 beta5 将修复。

非常感谢大佬耐心排查了这么久啊，提供了非常全面的信息。

**Comment by OLOrz996** [comment]
不客气，主要着实挺好使的，也感谢能及时响应处理issue
