### ISSUE TITLE
[缺陷]: 剧情整理功能无法使用

### ISSUE THREAD

**Issue by jinfeng1985** [pofey/movie_robot#448]
### 当前程序版本

0.9.97

### 问题描述

资源整理中，剧集整理功能无法使用。TV文件夹中有很多剧集，但系统只显示tv一个文件夹，识别也失败了，只识别了第一个剧集的nfo，其他啥都没有。

### 重现步骤

1、选择识别目录和整理后的目录，下面只显示一个TV文件夹
2、点击识别后，目标文件夹看了下，只有第一个剧集的nfo信息，其他啥都没有
3、识别就卡那儿不动了

### 发生问题时系统日志

```shell
2022/07/11 10:31:58 - Thread-72 - INFO: 完成剧集 季 1(2022) 第1季的NFO文件生成，路径：/video/link/tv/欧美/Moon Knig
Exception in thread Thread-72:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "yee/controller/thread/medialinkthread.py", line 80, in yee.controller.thread.medialinkthread.MediaLinkThread.run
File "yee/service/filemanagerservice.py", line 104, in yee.service.filemanagerservice.FileManagerService.link
  File "yee/media/link/medialink.py", line 156, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/tvlink.py", line 124, in yee.media.link.tvlink.TvLink.__walk__
  File "yee/media/link/tvlink.py", line 293, in yee.media.link.tvlink.TvLink.__handle__
File "yee/media/link/tvlink.py", line 90, in yee.media.link.tvlink.TvLink.link_tv_season_folder
  File "yee/media/link/tvlink.py", line 196, in yee.media.link.tvlink.TvLink.__create_episode_nfo__
  File "/usr/local/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/local/lib/python3.8/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'int'
```

**Comment by jinfeng1985** [comment]
![E421FCB6-3948-46F7-B3E8-E849E7815DB0](https://user-images.githubusercontent.com/22148953/178179126-e0592bf7-8e69-4d0b-9a9a-1c09acebda5c.jpeg)
![22C8FCFF-1A7B-4F19-A90D-FC478AD5BD55](https://user-images.githubusercontent.com/22148953/178179132-4bfbe0cd-9919-4973-b023-41f8bf7665a3.jpeg)

**Comment by OLOrz996** [comment]
我在识别电影时也有类似问题

**Comment by jinfeng1985** [comment]
> 我在识别电影的时候有类似的问题，显示异常也只有一部分，但实际上正在整理的功能是正常的 ![图片](https://user-images.githubusercontent.com/11268446/178195779-7f0a993c-81b7-4075-8dd8-be118f60a995.png)

我存量剧集已经卡在那边了，不进行硬链接了，新下的剧集正常硬链接分类。

**Comment by jinfeng1985** [comment]
好像被我删了几个剧集以后正常了。。。。

**Comment by pofey** [comment]
读不到文件夹详细内容的，必须把文件夹里实际内容截图发出来，要看实际文件截图，不然没法分析

**Comment by xwh4git** [comment]
![微信图片_20220711200143](https://user-images.githubusercontent.com/26497752/178259749-90aa88c8-f1eb-4baf-85e9-91c4b2b9beae.png)

**Comment by zzj6666** [comment]
![image](https://user-images.githubusercontent.com/101039599/178263889-023449e9-af41-4f17-8de5-e36c94c2891c.png)
这样的动漫命名方式识别不了，识别不了就会卡在无法识别报错，一直反复，后面订阅的都不无法硬链接，把这个源文件删除后，就开始识别动漫之后订阅的电影什么的，就恢复正常了

**Comment by OLOrz996** [comment]
![image](https://user-images.githubusercontent.com/11268446/178268846-82a1b143-9e5b-4353-9f09-f0c4639d4755.png)
用脚本把bd里最大的文件做了硬链接

**Comment by pofey** [comment]
> ![微信图片_20220711200143](https://user-images.githubusercontent.com/26497752/178259749-90aa88c8-f1eb-4baf-85e9-91c4b2b9beae.png)

这个是因为此目录混杂了几个单集文件，被程序认为你这个目录就是一个电视剧了。这块分析算法改了下，下一版发布

**Comment by pofey** [comment]
> ![image](https://user-images.githubusercontent.com/11268446/178268846-82a1b143-9e5b-4353-9f09-f0c4639d4755.png) 用脚本把bd里最大的文件做了硬链接

选中这个父路径，应该可以加载出来呀，看起来就是一个正常合集大目录，你截图资源整理页面结果我看看

**Comment by OLOrz996** [comment]
> > ![image](https://user-images.githubusercontent.com/11268446/178268846-82a1b143-9e5b-4353-9f09-f0c4639d4755.png) 用脚本把bd里最大的文件做了硬链接
> 
> 选中这个父路径，应该可以加载出来呀，看起来就是一个正常合集大目录，你截图资源整理页面结果我看看

就只有一条记录
![image](https://user-images.githubusercontent.com/11268446/178399642-b0193cc0-e81b-45b4-88c4-b7549a04c18d.png)

**Comment by pofey** [comment]
> > > ![image](https://user-images.githubusercontent.com/11268446/178268846-82a1b143-9e5b-4353-9f09-f0c4639d4755.png) 用脚本把bd里最大的文件做了硬链接
> > 
> > 
> > 选中这个父路径，应该可以加载出来呀，看起来就是一个正常合集大目录，你截图资源整理页面结果我看看
> 
> 就只有一条记录 ![image](https://user-images.githubusercontent.com/11268446/178399642-b0193cc0-e81b-45b4-88c4-b7549a04c18d.png)

这很像是被缓存了，等着开放清缓存功能吧

**Comment by pofey** [comment]
beta修复了一版这块的bug 可以试试
