### ISSUE TITLE
[缺陷]: 识别到同名其他剧

### ISSUE THREAD

**Issue by AAlexDing** [pofey/movie_robot#449]
### 当前程序版本

beta-0.9.97

### 问题描述

在豆瓣订阅未开播的国产剧“狂飙”时，下载下来的是英美剧   狂飙 (2017) [tmdbid=71693] ，而且简介居然是国产剧的简介
![image](https://user-images.githubusercontent.com/30212143/178187693-2f2d5fc0-2f8b-4e99-ae6e-fbd6dbd78798.png)

### 重现步骤

1.豆瓣订阅  狂飙(2022) 豆瓣id:35465232
2.movierobot下载入库

### 发生问题时系统日志

 2022/07/10 16:01:00 - ThreadPoolExecutor-4_3 - INFO: 开始获取sf***8(wish) 365天内的电影
 2022/07/10 16:01:01 - ThreadPoolExecutor-4_3 - INFO: 豆瓣用户sf1128的想看列表开始同步到订阅记录。 
 2022/07/10 16:01:11 - ThreadPoolExecutor-4_3 - INFO: 血路狂飙(2017) 选用过滤器：（默认）新国外剧中文字幕（自动洗版） 排序规则：compress
 2022/07/10 16:01:12 - ThreadPoolExecutor-4_3 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
 2022/07/10 16:01:43 - ThreadPoolExecutor-4_0 - INFO: 开始同步站点资源信息...
 2022/07/10 16:01:52 - ThreadPoolExecutor-4_0 - INFO: 瓷器最新种子同步完成。
 2022/07/10 16:02:08 - ThreadPoolExecutor-4_0 - INFO: 馒头最新种子同步完成。
 2022/07/10 16:02:11 - ThreadPoolExecutor-4_0 - INFO: 听听歌最新种子同步完成。
 2022/07/10 16:02:11 - ThreadPoolExecutor-4_0 - INFO: 所有站点资源信息已经更新完毕。
 2022/07/10 16:02:11 - ThreadPoolExecutor-4_0 - INFO: 没有任何需要养护的站点，停止免费任务获取。
 2022/07/10 16:02:34 - SubConsumer - INFO: 向往的生活(2017) 没有搜索到缺失的[9, 11, 12]集
 2022/07/10 16:02:38 - SubConsumer - INFO: 夏娃(2022) 经过系统分析后，没有搜到有效结果。
 2022/07/10 16:02:43 - SubConsumer - INFO: 星汉灿烂(2022) 没有搜索到缺失的[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]集
 2022/07/10 16:02:44 - SubConsumer - INFO: 已经开始在站点: 瓷器,馒头,听听歌 搜索: 血路狂飙,Blood Drive,tt4898282
 2022/07/10 16:03:06 - SubConsumer - INFO: 共在3个站点搜索到11条结果，其中馒头最慢，耗费21.61秒
 2022/07/10 16:03:06 - SubConsumer - INFO: [mteam]Blood Drive S01 1080p WEB-DL DD5.1 H264-RARBG 血路狂飙 第一季 全13集（内含简英外挂字幕）是个全集种子，需要预分析可靠性...
 2022/07/10 16:03:09 - SubConsumer - INFO: 血路狂飙(2017) 第1季 全集 品质：WEB-DL 1080p H.264 资源: https://kp.m-team.cc/details.php?id=206291&hit=1 已经提交下载。
 2022/07/10 16:03:09 - mteam-downloader - INFO: 开始处理来自订阅的下载: [mteam]Blood Drive S01 1080p WEB-DL DD5.1 H264-RARBG
 2022/07/10 16:03:09 - SubConsumer - INFO: 血路狂飙(2017) 第1季 本次下载的种子中，包含有全集字样信息，将默认本剧完结，停止订阅不再智能下载。
 2022/07/10 16:03:10 - mteam-downloader - INFO: [mteam]Blood Drive S01 1080p WEB-DL DD5.1 H264-RARBG已经开始下载,路径：/mnt/movie/download/英美剧 分类：英美剧 

......

 2022/07/10 17:31:08 - ThreadPoolExecutor-4_0 - INFO: 豆瓣用户sf1128的想看列表开始同步到订阅记录。 
 2022/07/10 17:31:08 - ThreadPoolExecutor-4_0 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
 2022/07/10 17:40:00 - ThreadPoolExecutor-0_2 - INFO: Emby连接正常，AuxoUNRAID版本为4.7.1.0
 2022/07/10 17:40:11 - ThreadPoolExecutor-4_0 - INFO: 完成剧集 狂飙(2022) 的NFO文件生成，路径：/mnt/movie/英美剧/狂飙 (2017) [tmdbid=71693]/tvshow.nfo
 2022/07/10 17:40:13 - ThreadPoolExecutor-4_0 - INFO: 完成剧集 第 5 集(2017) 第1季第5集的NFO文件生成，路径：/mnt/movie/英美剧/狂飙 (2017) [tmdbid=71693]/Season 1/狂飙 S01E05 - 1080p H.264 DD5.1.nfo
 2022/07/10 17:40:18 - ThreadPoolExecutor-4_0 - INFO: 完成剧集 第 13 集(2017) 第1季第13集的NFO文件生成，路径：/mnt/movie/英美剧/狂飙 (2017) [tmdbid=71693]/Season 1/狂飙 S01E13 - 1080p H.264 DD5.1.nfo
 2022/07/10 17:40:23 - ThreadPoolExecutor-4_0 - INFO: 完成剧集 第 9 集(2017) 第1季第9集的NFO文件生成，路径：/mnt/movie/英美剧/狂飙 (2017) [tmdbid=71693]/Season 1/狂飙 S01E09 - 1080p H.264 DDP5.1 NTb.nfo
 2022/07/10 17:40:28 - ThreadPoolExecutor-4_0 - INFO: 完成剧集 第 8 集(2017) 第1季第8集的NFO文件生成，路径：/mnt/movie/英美剧/狂飙 (2017) [tmdbid=71693]/Season 1/狂飙 S01E08 - 1080p H.264 DD5.1.nfo
 2022/07/10 17:40:33 - ThreadPoolExecutor-4_0 - INFO: 完成剧集 第 6 集(2017) 第1季第6集的NFO文件生成，路径：/mnt/movie/英美剧/狂飙 (2017) [tmdbid=71693]/Season 1/狂飙 S01E06 - 1080p H.264 DD5.1.nfo
 2022/07/10 17:40:38 - ThreadPoolExecutor-4_0 - INFO: 完成剧集 第 1 集(2017) 第1季第1集的NFO文件生成，路径：/mnt/movie/英美剧/狂飙 (2017) [tmdbid=71693]/Season 1/狂飙 S01E01 - 1080p H.264 DD5.1.nfo
 2022/07/10 17:40:42 - ThreadPoolExecutor-4_0 - INFO: 完成剧集 第 7 集(2017) 第1季第7集的NFO文件生成，路径：/mnt/movie/英美剧/狂飙 (2017) [tmdbid=71693]/Season 1/狂飙 S01E07 - 1080p H.264 DD5.1.nfo
 2022/07/10 17:40:46 - ThreadPoolExecutor-4_0 - INFO: 完成剧集 第 4 集(2017) 第1季第4集的NFO文件生成，路径：/mnt/movie/英美剧/狂飙 (2017) [tmdbid=71693]/Season 1/狂飙 S01E04 - 1080p H.264 DD5.1.nfo
 2022/07/10 17:40:51 - ThreadPoolExecutor-4_0 - INFO: 完成剧集 第 2 集(2017) 第1季第2集的NFO文件生成，路径：/mnt/movie/英美剧/狂飙 (2017) [tmdbid=71693]/Season 1/狂飙 S01E02 - 1080p H.264 DD5.1.nfo
 2022/07/10 17:40:55 - ThreadPoolExecutor-4_0 - INFO: 完成剧集 第 10 集(2017) 第1季第10集的NFO文件生成，路径：/mnt/movie/英美剧/狂飙 (2017) [tmdbid=71693]/Season 1/狂飙 S01E10 - 1080p H.264 DD5.1.nfo
 2022/07/10 17:41:00 - ThreadPoolExecutor-4_0 - INFO: 完成剧集 第 11 集(2017) 第1季第11集的NFO文件生成，路径：/mnt/movie/英美剧/狂飙 (2017) [tmdbid=71693]/Season 1/狂飙 S01E11 - 1080p H.264 DD5.1.nfo
 2022/07/10 17:41:03 - ThreadPoolExecutor-4_0 - INFO: 完成剧集 第 12 集(2017) 第1季第12集的NFO文件生成，路径：/mnt/movie/英美剧/狂飙 (2017) [tmdbid=71693]/Season 1/狂飙 S01E12 - 1080p H.264 DD5.1.nfo
 2022/07/10 17:41:07 - ThreadPoolExecutor-4_0 - INFO: 完成剧集 第 3 集(2017) 第1季第3集的NFO文件生成，路径：/mnt/movie/英美剧/狂飙 (2017) [tmdbid=71693]/Season 1/狂飙 S01E03 - 1080p H.264 DD5.1.nfo
 2022/07/10 17:41:07 - ThreadPoolExecutor-4_0 - INFO: 血路狂飙 第1季(2022) 第1,2,3,4,5,6,7,8,9,10,11,12,13集字幕下载 任务已经创建。
 2022/07/10 17:41:08 - ThreadPoolExecutor-4_0 - INFO: Blood.Drive.S01.1080p.WEB-DL.DD5.1.H264-RARBG处理完毕。
 2022/07/10 17:43:00 - ThreadPoolExecutor-4_2 - INFO: 血路狂飙 第1季(2022) 第1,2,3,4,5,6,7,8,9,10,11,12,13集字幕下载已经提交启动。
 2022/07/10 17:43:00 - SubRequestConsumer - INFO: 血路狂飙 第1季(2022) 第1,2,3,4,5,6,7,8,9,10,11,12,13集字幕下载 任务已经结束。
 2022/07/10 17:45:53 - ThreadPoolExecutor-4_3 - INFO: 开始同步站点资源信息...
 2022/07/10 17:46:02 - ThreadPoolExecutor-4_3 - INFO: 瓷器最新种子同步完成。
 2022/07/10 17:46:20 - ThreadPoolExecutor-4_3 - INFO: 馒头最新种子同步完成。
 2022/07/10 17:46:22 - ThreadPoolExecutor-4_3 - INFO: 听听歌最新种子同步完成。

**Comment by pofey** [comment]
选择过程的日志呢

**Comment by AAlexDing** [comment]
日志是这些

**Comment by AAlexDing** [comment]
> 
对的
