### ISSUE TITLE
[缺陷]: 

### ISSUE THREAD

**Issue by ShakeChanDev** [pofey/movie_robot#450]
### 当前程序版本

0.9.97

### 问题描述

在「豆瓣想看与智能下载保存规则」页面，将某分类的电影和剧集保存在同一文件夹时提示「存在重复的下载保存路径」

### 重现步骤

个人使用时将 儿童电影 和 儿童剧集 都放在「儿童」文件夹，之前是正常的（如图），最新的版本不支持，查阅后发现可能是修复该issue引发的：https://github.com/pofey/movie_robot/issues/415

### 其他信息

<img width="708" alt="微信图片_20220711142258" src="https://user-images.githubusercontent.com/2718231/178202470-c1e2c400-573e-456d-b2f5-8d3626a71d95.png">

**Comment by pofey** [comment]
正常设计，剧集和电影就是不建议混杂，想跳验证，就自己改配置文件吧，但会有不可预测的风险
