### ISSUE TITLE
[优化]: 整理与识别：压制组、音频、动态范围优化建议

### ISSUE THREAD

**Issue by Alano-i** [pofey/movie_robot#451]
### 当前现状

压制组名称过于宽泛，不能知道是谁压制的，比如CHDWEB有很多发布者

 **目前制作组关键词匹配时去掉了`@` `空格` `.` `-`这几个特殊符号。**
所以如果有的制作组名称比较短，比如两个或3个字母的（`ADE` 、彩虹岛的 `nn` （nn@CHDbits））,识别时可能会识别失误，

1. 只能使用NN去匹配关键字进行整理与识别，若影片文件名为，xxxxnn sgnb@CHDbits，会错误的识别为 `NN` 不会识别为 `SGNB` 
2. 无法使用 NN@CHDBITS 作为关键字匹配识别，最好能通过 NN@CHDBITS 作为组关键字，更准确
3. 音频很多命名是 `TrueHD 7.1`而不是`TrueHD7.1`，因为匹配不能有空格，所以匹配`TrueHD 7.1`时不能正确的识别为TrueHD 7.1 而仅识别为 TrueHD 不是很准确。

另外目前绝大多数影片都有 动态范围 （`HDR` `杜比视界` `SDR`）的标识，希望能增加动态范围的程序变量

![image](https://user-images.githubusercontent.com/68833595/178260459-9c09e5d3-8306-48b4-8e79-97a8934ef8e2.png)

### 你的建议

1. 制作组和音频在识别时能支持对`@` `空格` `.` `-`这几个特殊符号的匹配
2. 增加 动态范围程序 变量，以能展示该片动态范围品质（`HDR` `杜比视界` `SDR`）

<img width="591" alt="image" src="https://user-images.githubusercontent.com/68833595/178253702-868b8490-521e-46ba-849c-822d0790599d.png">

### 优先级

较高

### 受众范围

很多人需要

**Comment by zoooo0** [comment]
复议！而且还缺少一些站点压制组命名 例如吐鲁番的压制组:TLF，柠檬的web压制组:LeagueWEB

**Comment by cuicuifeng** [comment]
建议可以出个自定义保留的类似白名单，毕竟压制组太多今后还会不停的有新组成立，音频编码很多也识别不出来

**Comment by iYIJUN** [comment]
非常需要
