### ISSUE TITLE
[缺陷]: 监控种子任务出错

### ISSUE THREAD

**Issue by xwh4git** [pofey/movie_robot#452]
### 当前程序版本

0.9.97

### 问题描述

![图片](https://user-images.githubusercontent.com/26497752/178268206-896b9c31-5bcd-45ea-a3df-fef72536da3a.png)
![图片](https://user-images.githubusercontent.com/26497752/178268821-80d3dc06-0ccb-4ee9-8ce5-86c1a439b9a0.png)

### 重现步骤

启动日志报错

**Comment by pofey** [comment]
这个已经修了还没发布
