### ISSUE TITLE
[缺陷]: 每次开始同步站点资源信息就报解析错误。

### ISSUE THREAD

**Issue by 1pondog** [pofey/movie_robot#453]
### 当前程序版本

0.9.97

### 问题描述

每次开始同步站点资源信息就报data解析错误，之前版本就有遇到，升级了还是报错。

### 重现步骤

![1657549490322](https://user-images.githubusercontent.com/106610517/178287215-3e7e9df0-b6d6-4317-a820-b5521873db85.jpg)

### 其他信息

![image](https://user-images.githubusercontent.com/106610517/178287405-9db8541d-d9ad-4e72-b6d3-084d07406da2.png)

**Comment by pofey** [comment]
这是站点适配不支持你的pt站点设置，程序没什么可改的。99%你的站点设置不是已去时间

**Comment by htnanako** [comment]
hdtime太老的种子时间没有带秒钟，被顶上来就会抓到。无视就行了。
<img width="937" alt="image" src="https://user-images.githubusercontent.com/68056603/178442340-f115ef9c-e20f-4f96-8394-56fd506ba020.png">
