### ISSUE TITLE
[缺陷]: 已经在资源库的还是提交了下载

### ISSUE THREAD

**Issue by GodD6366** [pofey/movie_robot#454]
### 当前程序版本

0.9.97

### 问题描述

![image](https://user-images.githubusercontent.com/17250383/178386880-3cf58acd-b344-4879-8a78-9e34e1e9307e.png)

### 重现步骤

已经存在的电影还是会下载

### 发生问题时系统日志

```shell
2022/07/11 20:56:52 - SubRequestConsumer - INFO: 解除好友2：暗网(2018) 已经在影视库，不再进行订阅！,
2022/07/11 20:57:41 - Thread-355 - INFO: 已经开始在站点: 馒头 搜索: 暗网,
2022/07/11 21:04:55 - SubConsumer - INFO: 已经开始在站点: 馒头 搜索: 解除好友2：暗网,Unfriended: Dark Web,
2022/07/11 21:05:11 - SubConsumer - INFO: 解除好友2：暗网(2018) 当前最佳选择: Blu-ray 1080p x264 资源：https://kp.m-team.cc/details.php?id=505343&hit=1 已经提交下载。
```

**Comment by pofey** [comment]
已经在影视库，不再进行订阅！ 提示这个就已经完成，不会再扫了。 你订阅里这部剧的截图我看看

**Comment by GodD6366** [comment]
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/17250383/178508950-48697814-4668-42e8-8d68-965630aabbe9.png">
<img width="209" alt="image" src="https://user-images.githubusercontent.com/17250383/178509017-2bbcd1a8-d6fc-48e2-9861-f363247c95b5.png">

**Comment by pofey** [comment]
> <img alt="image" width="1357" src="https://user-images.githubusercontent.com/17250383/178508950-48697814-4668-42e8-8d68-965630aabbe9.png">
> 
> <img alt="image" width="209" src="https://user-images.githubusercontent.com/17250383/178509017-2bbcd1a8-d6fc-48e2-9861-f363247c95b5.png">

这也已经是一个完成状态了，现在还会下吗

**Comment by GodD6366** [comment]
不会 就是日志里发现重复下了

**Comment by pofey** [comment]
那先关了

**Comment by pofey** [comment]
那先关了
