### ISSUE TITLE
[提问]: 硬链接不会带文件夹以及xjj不会硬链的问题。

### ISSUE THREAD

**Issue by 1pondog** [pofey/movie_robot#460]
### 当前程序版本

0.9.97与0.9.98-beta1

### 问题

我用qb自带的rss下载小姐姐，因为大部分小姐姐下载下来本身外面是不套文件夹的，直接就是mp4文件，所以我用qb给他套了一层文件夹（如图1，2），然后mr是监控到了这个文件，但是硬链的时候显示未识别就没做硬链（如图3），我手动整理链接过去，发现qb给他套的文件夹没了，只硬链了原来的mp4文件（如图4）
所以我现在想问一下qb套的文件夹是不支持硬链过去嘛？还是我哪里设置不对？还有这个未识别就不硬链是为什么？请指点一下，我昨天晚上排查了一晚上也不知道是我哪里设置有问题，还有图5我勾上和不勾都试了都不行，我现在只是想他能自动硬链过去套一个文件夹，然后文件夹带番号就够了，感谢。
![1657711543321](https://user-images.githubusercontent.com/106610517/178724268-55be31c7-05b7-4546-a0d9-9bdde6f1aa95.jpg)
![1657711835760](https://user-images.githubusercontent.com/106610517/178724291-7b47bbef-5cde-457e-9156-8075bdbc86ec.jpg)
![1657711763237](https://user-images.githubusercontent.com/106610517/178724309-174182c2-280c-47d8-9bc3-913cd6193625.jpg)
![1657711824904](https://user-images.githubusercontent.com/106610517/178724333-6a102d04-23c6-4cbb-b5c1-78663dcb99d0.jpg)
![1657712104071](https://user-images.githubusercontent.com/106610517/178724795-1a53d8d6-9d22-462d-936d-cb36fedc0797.jpg)

**Comment by 1pondog** [comment]
那这个硬连接的问题能不能给指个方向，我现在不知道是我哪里没设置好导致他未识别就不会硬链

**Comment by 1pondog** [comment]
> qb 自动套是不支持的，因为qb 给的实际内容，还是mp4那个文件

那这个硬连接的问题能不能给指个方向，我现在不知道是我哪里没设置好导致他未识别就不会硬链

**Comment by pofey** [comment]
> > qb 自动套是不支持的，因为qb 给的实际内容，还是mp4那个文件
> 
> 那这个硬连接的问题能不能给指个方向，我现在不知道是我哪里没设置好导致他未识别就不会硬链

你的描述不是提到，文件链接过去了

**Comment by 1pondog** [comment]
> > > qb 自动套是不支持的，因为qb 给的实际内容，还是mp4那个文件
> > 
> > 
> > 那这个硬连接的问题能不能给指个方向，我现在不知道是我哪里没设置好导致他未识别就不会硬链
> 
> 你的描述不是提到，文件链接过去了

看我那个日志的截图，他未识别就没做硬链，我是手动整理才链接过去的
