### ISSUE TITLE
[缺陷]: 资源整理中电影合集只显示第一个文件夹

### ISSUE THREAD

**Issue by 2651335411** [pofey/movie_robot#463]
### 当前程序版本

0.9.9.7

### 问题描述

资源整理中电影合集只显示第一个文件夹

### 重现步骤

![image](https://user-images.githubusercontent.com/54398550/178768973-caa359c1-5a01-47ec-b37c-7ff77f4c5418.png)
![image](https://user-images.githubusercontent.com/54398550/178769133-17f5951e-e5f6-4bed-89cd-5f7264ffaf49.png)

### 健康检查

![image](https://user-images.githubusercontent.com/54398550/178769345-3f2e25ca-3d8c-4a5a-89ef-ef1b5163176d.png)

**Comment by pofey** [comment]
重复问题了，升级到beta试试，beta已经修复了
