### ISSUE TITLE
[优化]: 中文演员刮削功能建议

### ISSUE THREAD

**Issue by elic6699** [pofey/movie_robot#467]
### 当前现状

0.9.98 beta5发布中文演员刮削新功能后，电影nfo写入信息演员这一栏只有doubanid

### 你的建议

是否能增加tmdbid以便nfo文件能通用其他媒体服务器

### 优先级

一般

### 受众范围

一般

**Comment by pofey** [comment]
> ### 当前现状
> 0.9.98 beta5发布中文演员刮削新功能后，电影nfo写入信息演员这一栏只有doubanid
> 
> ### 你的建议
> 是否能增加tmdbid以便nfo文件能通用其他媒体服务器
> 
> ### 优先级
> 一般
> 
> ### 受众范围
> 一般

给了tmdb，中文就失效了，你可以试试，会被覆盖成tmdb上的英文信息

**Comment by elic6699** [comment]
好的
