### ISSUE TITLE
[优化]: 养站任务默认开启「强制继续」来做种

### ISSUE THREAD

**Issue by ShakeChanDev** [pofey/movie_robot#469]
### 当前现状

qb设置了完成任务后做种时间达到10分钟自动停止做种
根据qb设置，导致养站任务在种子下载后10分钟后自动停止做种

### 你的建议

养站任务强制继续做种，不受qb自动停止做种的设置限制影响

### 优先级

一般

### 受众范围

一般

**Comment by pofey** [comment]
没理解

**Comment by ShakeChanDev** [comment]
@pofey 更新了描述

**Comment by pofey** [comment]
冷汗😓 你关了这个设置或者独立一个下载器不就可以了
