### ISSUE TITLE
[缺陷]: 中文演员刮削不显示图片

### ISSUE THREAD

**Issue by happyhaha1** [pofey/movie_robot#470]
### 当前程序版本

0.9.98-Beta7

### 问题描述

中文刮削后头像不显示

### 重现步骤

该版本刮削的时候刮削名字是按照姓氏分开的。
如演员罗晋 /emby_person/罗/罗晋/person.nfo；/emby_person/罗/罗晋/folder.jpg
但是emby 4.7.40版本读取的是/emby_person/罗晋 不会按照姓氏分开。将/emby_person/罗/罗晋/folder.jpg 移动到/emby_person/罗晋/folder.jpg 时就会显示头像。

### 健康检查

![image](https://user-images.githubusercontent.com/10184254/179227350-6839f0e8-ff6d-4ace-b9dc-7430e7286543.png)

**Comment by pofey** [comment]
https://emby.media/community/index.php?/topic/101002-people-folder-issues/
