### ISSUE TITLE
[提问]: windows能用不  没看到哪里有windows的教程  如果能用的话 想支持一下 

### ISSUE THREAD

**Issue by 522654518** [pofey/movie_robot#472]
### 当前程序版本

0.99

### 问题

各位大佬好  我用的是windows nas，现在 plex qitorrent 等应用都直接用的exe版，不知道如果用windocker安装后，各个软件之间的联动会不会有问题，可有适用版本借我研究两天看看能不能实现。

**Comment by pofey** [comment]
docker 全平台都是一样的

**Comment by 522654518** [comment]
> 



> docker 全平台都是一样的

我试了nas-tools windows docker感觉不得行  ，有试用账号么 我装个试试 ，最好出个一个月的试用账号啊。不然买了软件不能用太难受了

**Comment by pofey** [comment]
> > docker 全平台都是一样的
> 
> 我试了nas-tools windows docker感觉不得行 ，有试用账号么 我装个试试 ，最好出个一个月的试用账号啊。不然买了软件不能用太难受了

看tg win用户挺多的
