### ISSUE TITLE
[缺陷]: 下载音乐资源时，识别到资源中thumb_image_url值为None，与download_record表中的该字段的非空限制冲突

### ISSUE THREAD

**Issue by WarriorsYou** [pofey/movie_robot#473]
### 当前程序版本

0.9.98-Beta8

### 问题描述

通过Movie Robot的网页搜索“最伟大的作品”，选择北洋园站点的资源（种子id：305969）进行手动下载，下载到预先设置的音乐媒体文件夹中，对应的音乐媒体文件夹路径见下图：
<img width="706" alt="image" src="https://user-images.githubusercontent.com/26532837/179362781-51a112ba-de96-4803-aa29-794263bae77b.png">
页面提示开始处理下载后，在qb里面已成功添加下载任务，但近期下载页面没有显示该任务的记录，如下图：
<img width="980" alt="image" src="https://user-images.githubusercontent.com/26532837/179362911-ab2f6204-b2fe-4f0b-bb33-ddc18dab5eb4.png">
<img width="609" alt="image" src="https://user-images.githubusercontent.com/26532837/179362922-10e2f438-ff5d-4736-b985-6f5baa765e48.png">
查看日志发现，在添加下载记录到download_record表中时，由于解析到的资源的thumb_image_url值为None，在执行insert语句时，与download_record表thumb_image_url字段的非空限制冲突，导致插入语句执行失败，处理下载任务失败。

### 重现步骤

1.在网页中搜索“最伟大的作品”；
2.选择北洋园站点的资源（种子id：305969）手动下载到音乐媒体文件夹路径中（/downloads/音乐）；
3.qb中任务添加成功，下载记录页面中的近期下载没有显示任务。

### 健康检查

![image](https://user-images.githubusercontent.com/26532837/179363228-951ef739-5246-4447-af9d-c1cebc935a3c.png)
前面Plex和qb健康度为白色的部分是因为nas停电重启后，相关服务没有重启配置好，后面发现问题配置好后，已正常，与本issue当中的问题无关。

**Comment by pofey** [comment]
现在还能下音乐呢 把种子地址发出来我看看

**Comment by WarriorsYou** [comment]
> 

https://tjupt.org/details.php?id=305969&hit=1

**Comment by WarriorsYou** [comment]
刚刚看问题描述的时候突然留意到，印象中添加到描述里面的日志截图不见了[可能也是当时截了图忘记添加]，补上当时的日志截图：
<img width="705" alt="mmexport1658061795740" src="https://user-images.githubusercontent.com/26532837/179398938-0e9c519d-a7c2-430b-a625-98e6fecb895c.png">

**Comment by pofey** [comment]
音乐现在没测试过，我估计会有一些奇怪的问题
