### ISSUE TITLE
[提问]: 有没有大佬能赠个试用激活码，不胜感谢！试用觉得适合自己再入手

### ISSUE THREAD

**Issue by Jockio** [pofey/movie_robot#474]
### 当前程序版本

0.99

### 问题

各位大佬好，刚接触到movie robot，有没有大佬能赠个试用激活码，不胜感谢！
身边还没有使用过ms的朋友，所以这里看能不能求一个。如果适合自己再入手永久，多谢多谢！
邮箱： 2641878408@qq.com

**Comment by pofey** [comment]
这求不到的，用户很少来看github
