### ISSUE TITLE
[缺陷]: 

### ISSUE THREAD

**Issue by BruceSuen720** [pofey/movie_robot#475]
### 当前程序版本

0.9.99

### 问题描述

豆瓣下载想看与智能保存规则中，想将不同标签的内容下载到同一个路径中（例如：动画、儿童两个标签，同时都想保存到动漫的下载路径，分别设置的时候会出现错误），会提示存在重复的下载保存路径

### 重现步骤

1.打开设置中的豆瓣下载想看与智能保存规则
2.添加分类 标签动画 下载路径到动漫的保存路径
3.添加分类 标签儿童 下载路径到动漫的保存路径
4.保存
5.报错
![1658067196892](https://user-images.githubusercontent.com/85166199/179402587-3097d819-8eaa-466d-8127-d45a49ef8fda.png)

### 发生问题时系统日志

```shell
无日志
```

### 健康检查

![image](https://user-images.githubusercontent.com/85166199/179402592-04f507b3-f9b8-475f-abae-8a26e6d4b69b.png)

**Comment by pofey** [comment]
这个是之前特别加的逻辑

**Comment by pofey** [comment]
不过多分类到一个目录 倒也是合理，我后面看看吧
