### ISSUE TITLE
[缺陷]: 能识别 却整理错误

### ISSUE THREAD

**Issue by Turbo6666** [pofey/movie_robot#477]
### 当前程序版本

0.9.99

### 问题描述

多次整理信息通知界面显示正确 整理下来的硬链接数据却是错误的！完全对照tmdb页面显示的信息输入也无法正确整理！
![IMG_20220718_021659](https://user-images.githubusercontent.com/105849652/179420186-6a79753e-9ece-41ef-8b3d-8519cc9d7ce4.jpg)
![IMG_20220718_022230](https://user-images.githubusercontent.com/105849652/179420194-82d5e217-2da8-49a5-a4d5-7ca8669a66b0.jpg)

### 重现步骤

.

### 健康检查

![Screenshot_20220718_024245_com qihoo contents](https://user-images.githubusercontent.com/105849652/179420292-f11b29dc-7f86-4739-a750-73b6ad29ad5f.jpg)

**Comment by pofey** [comment]
sp02 是日本动漫常见集数命名？现在不支持的

**Comment by Turbo6666** [comment]
> 



> sp02 是日本动漫常见集数命名？现在不支持的

sp02是原资源里面的文件 他的文件构造我给你上个图
![微信图片编辑_20220718135703](https://user-images.githubusercontent.com/105849652/179452588-b8fcf352-a8f6-4478-a6fc-73dbf6f32b29.jpg)
其实在识别第一季的时候已经是无法识别到正确的集数信息的(此时版本是97)升级到99后第一季识别正常了 于是我就没去提问题了 当时日志是有报错的!
然后等这个第二季下载完之后自动整理就出现现在这情况了 两季的文件内容均是上面图片的样式!都混有 sp之类的压缩包和视频文件!

**Comment by pofey** [comment]
> > sp02 是日本动漫常见集数命名？现在不支持的
> 
> sp02是原资源里面的文件 他的文件构造我给你上个图 ![微信图片编辑_20220718135703](https://user-images.githubusercontent.com/105849652/179452588-b8fcf352-a8f6-4478-a6fc-73dbf6f32b29.jpg) 其实在识别第一季的时候已经是无法识别到正确的集数信息的(此时版本是97)升级到99后第一季识别正常了 于是我就没去提问题了 当时日志是有报错的! 然后等这个第二季下载完之后自动整理就出现现在这情况了 两季的文件内容均是上面图片的样式!都混有 sp之类的压缩包和视频文件!

这个目录里volxx集肯定是识别不了上面[数字]这种应该是认识的

**Comment by Turbo6666** [comment]
> > > sp02 是日本动漫常见集数命名？现在不支持的
> > 
> > 
> > sp02是原资源里面的文件 他的文件构造我给你上个图 ![微信图片编辑_20220718135703](https://user-images.githubusercontent.com/105849652/179452588-b8fcf352-a8f6-4478-a6fc-73dbf6f32b29.jpg) 其实在识别第一季的时候已经是无法识别到正确的集数信息的(此时版本是97)升级到99后第一季识别正常了 于是我就没去提问题了 当时日志是有报错的! 然后等这个第二季下载完之后自动整理就出现现在这情况了 两季的文件内容均是上面图片的样式!都混有 sp之类的压缩包和视频文件!
> 
> 这个目录里volxx集肯定是识别不了上面[数字]这种应该是认识的

现在问题就是应该混杂了这些vol在里面以至于他不能正常识别了 动漫这块的资源依旧是很复杂 找不到WEB-DL的资源只能将就下这种包含sp之类的资源

**Comment by pofey** [comment]
这个vol数字是代表集号么 如果是 可以把这个完善下，其他也没什么可做的了

**Comment by Turbo6666** [comment]
> 这个vol数字是代表集号么 如果是 可以把这个完善下，其他也没什么可做的了

VOL不是集号 感谢衣总的在线解答!后续这类型的资源我自行处理!
