### ISSUE TITLE
[缺陷]: 资源整理能成功进行，但状态会变为识别失败

### ISSUE THREAD

**Issue by Kev1nT** [pofey/movie_robot#478]
### 当前程序版本

0.9.99

### 问题描述

更新0.9.99后，重新整理存量资源，人员信息能正常识别，也提示整理成功，但整理完成后会显示识别失败，电影与剧集都会，鼠标移入也没有提示错误信息
Emby设置同教程，关闭了元数据刮削，保留了图像刮削
![屏幕截图 2022-07-18 114034](https://user-images.githubusercontent.com/49979564/179442149-303d7f09-a2e0-4821-b676-1a40444c6e4a.png)
![屏幕截图 2022-07-18 114430](https://user-images.githubusercontent.com/49979564/179442246-f1a9cac5-345b-4f92-be32-ea1444a04cbe.png)

### 重现步骤

资源整理-》选中资源-》识别整理

### 发生问题时系统日志

![屏幕截图 2022-07-18 113719](https://user-images.githubusercontent.com/49979564/179442277-8bd318d3-62b4-4850-b00d-8362fd2b242c.png)

### 健康检查

![屏幕截图 2022-07-18 114756](https://user-images.githubusercontent.com/49979564/179442560-e3b4aa04-df45-4ccb-8ca5-4a6103129231.png)

**Comment by pofey** [comment]
已经修复了，等更新下一版吧
