### ISSUE TITLE
[缺陷]: 订阅中剧集对站点中“包含媒体库中已存在的部分集数”的小包无法识别

### ISSUE THREAD

**Issue by haha6311** [pofey/movie_robot#479]
### 当前程序版本

0.9.99

### 问题描述

订阅中的剧集 **幸福到万家**

媒体库已存在集数1-33

但是站点没有34-35的小包，仅有33-35的小包

此时无法识别并上报“未识别到34,35,...对应资源”

### 重现步骤

之前某个站点更新了33，另一个站点没有更新，订阅自动下载33入库

![image](https://user-images.githubusercontent.com/36618980/179444423-7e30c579-cd7d-4a51-8c27-f6eb93d42e69.png)

另一个站点后来居上，一下子发了个33-35的小包

![image](https://user-images.githubusercontent.com/36618980/179444462-ea5bb6d4-fdf9-44f4-9c68-c4c67aeb8443.png)

然后就出现了上述问题

### 发生问题时系统日志

```shell
2022/07/18 00:01:50 - ThreadPoolExecutor-5_2 - INFO: XX岛最新种子同步完成。
....省略其他站点（就是这个站发布了33-35）

2022/07/18 12:02:18 - ThreadPoolExecutor-5_3 - INFO: 所有站点资源信息已经更新完毕。
2022/07/18 12:02:21 - ThreadPoolExecutor-5_3 - INFO: 没有任何需要养护的站点，停止免费任务获取。
2022/07/18 12:02:30 - SubConsumer - INFO: 幸福到万家(2022) 没有搜索到缺失的[34, 35, 36, 37, 38, 39, 40]集
```

### 健康检查

![image](https://user-images.githubusercontent.com/36618980/179444288-6cb2e6ba-4d09-47c6-95ac-3df1a6702f91.png)

**Comment by pofey** [comment]
这应该不是33-35合集导致的，你把这个种子链接发出来我看看

**Comment by haha6311** [comment]
> 这应该不是33-35合集导致的，你把这个种子链接发出来我看看

https://chdbits.co/details.php?id=195498

**Comment by haha6311** [comment]
> 这应该不是33-35合集导致的，你把这个种子链接发出来我看看

我重新提交过滤器，MR搜到了只包含34-35的包并完成了下载。
`2022/07/18 17:09:31 - SubConsumer - INFO: 幸福到万家(2022) 没有搜索到缺失的[36, 37, 38, 39, 40]集
,2022/07/18 17:09:26 - ThreadPoolExecutor-5_0 - INFO: 开始同步站点资源信息...
,2022/07/18 17:02:43 - ThreadPoolExecutor-5_3 - INFO: 幸福到万家(2022) 发行地区为['中国大陆']，不需要下载字幕。
,2022/07/18 17:02:43 - ThreadPoolExecutor-5_3 - INFO: 通知媒体库刷新完成，tmdb_id: 131485 save_path: /video/剧集 item_id: 6:幸福到万家
,2022/07/18 17:02:43 - ThreadPoolExecutor-5_3 - INFO: The.Story.of.Xing.Fu.S01.2022.1080p.WEB-DL.H264.AAC-TJUPT处理完毕。
,2022/07/18 17:02:43 - ThreadPoolExecutor-5_3 - INFO: 已经通知plex重新扫描媒体库：电视剧
,2022/07/18 17:02:43 - ThreadPoolExecutor-5_3 - INFO: /video/Downloads/Drama/The.Story.of.Xing.Fu.S01.2022.1080p.WEB-DL.H264.AAC-TJUPT/The.Story.of.Xing.Fu.S01E11.2022.1080p.WEB-DL.H264.AAC-TJUPT.mp4 集号不属于所需的[34, 35] 跳过处理
,2022/07/18 17:02:39 - ThreadPoolExecutor-5_3 - INFO: 完成剧集 第 34 集(2022) 第1季第34集的NFO文件生成，路径：/video/剧集/幸福到万家 (2022) [tmdbid=131485]/Season 1/幸福到万家 S01E34 - 1080p H.264 TJUPT.nfo
,2022/07/18 17:02:33 - ThreadPoolExecutor-5_3 - INFO: 完成剧集 第 35 集(2022) 第1季第35集的NFO文件生成，路径：/video/剧集/幸福到万家 (2022) [tmdbid=131485]/Season 1/幸福到万家 S01E35 - 1080p H.264 TJUPT.nfo
,2022/07/18 17:02:26 - ThreadPoolExecutor-5_3 - INFO: /video/Downloads/Drama/The.Story.of.Xing.Fu.S01.2022.1080p.WEB-DL.H264.AAC-TJUPT/The.Story.of.Xing.Fu.S01E10.2022.1080p.WEB-DL.H264.AAC-TJUPT.mp4 集号不属于所需的[34, 35] 跳过处理
,2022/07/18 17:02:26 - ThreadPoolExecutor-5_3 - INFO: 完成剧集 第1季 季 1 的NFO文件生成，路径：/video/剧集/幸福到万家 (2022) [tmdbid=131485]/Season 1/season.nfo
,2022/07/18 17:02:26 - ThreadPoolExecutor-5_3 - INFO: 完成剧集 幸福到万家 的NFO文件生成，路径：/video/剧集/幸福到万家 (2022) [tmdbid=131485]/tvshow.nfo
,2022/07/18 17:00:46 - lemonhd-downloader - INFO: [lemonhd]The Story of Xing Fu S01E34-35 2022 1080p WEB-DL H.264 AAC-TJUPT已经开始下载,路径：/media/sda1/Downloads/Drama 分类：未设置 
,2022/07/18 17:00:43 - lemonhd-downloader - INFO: 开始处理来自订阅的下载: [lemonhd]The Story of Xing Fu S01E34-35 2022 1080p WEB-DL H.264 AAC-TJUPT
,2022/07/18 17:00:43 - SubConsumer - INFO: 幸福到万家(2022) 第1季 第[34]集 品质：WEB-DL 1080p H.264 资源: https://lemonhd.org/details_tv.php?id=315471 已经提交下载。
,2022/07/18 17:00:42 - SubConsumer - INFO: 共在16个站点搜索到155条结果，其中北洋园最慢，耗费625.05秒
,2022/07/18 17:00:42 - ThreadPoolExecutor-2_2 - ERROR: 从北洋园搜索['幸福到万家', 'The Story of Xing Fu']失败了 错误：RetryError[<Future at 0x7ed665c580 state=finished raised LoginRequired>]
,2022/07/18 17:00:42 - ThreadPoolExecutor-2_2 - ERROR: 从北洋园搜索 ['幸福到万家', 'The Story of Xing Fu'] 失败了，错误信息: 北洋园登陆失败！
`

**Comment by pofey** [comment]
这个问题的原因是，现在剧集分析优先解析种子名
The Story of Xing Fu S01E33-35 2022 2160p 60fps WEB-DL H264 AAC-CHDWEB
程序之前只认识E33-E35，这种子名少了个E，所以没认出来，只当成33集了。
下一版修复，等着更新吧
