### ISSUE TITLE
[提问]: 资源整理路径无法选择

### ISSUE THREAD

**Issue by tianjian110** [pofey/movie_robot#480]
### 当前程序版本

0.9.99

### 问题

资源整理路径无法选择
![Uploading 89F6F792-354A-4B2C-8B5C-1B817374B4EE.png…]()

**Comment by pofey** [comment]
什么也看不到 没图 没文字

**Comment by tianjian110** [comment]
![Uploading ABDE14D1-D232-40CF-ACC6-A5A5A55FED50.png…]()

**Comment by tianjian110** [comment]
![E0AC812E-9D73-4F69-ABC5-F8512344BAFC](https://user-images.githubusercontent.com/94738666/179638068-12ebf7d0-1aa9-40e7-9a4f-9d04d8098337.png)

**Comment by tianjian110** [comment]
只能选到media，下面的文件夹无法选择

**Comment by pofey** [comment]
看看日志吧 检查权限啥的吧 这个地方难以出bug
