### ISSUE TITLE
[缺陷]: 站点订阅不显示站点，重装好几次也没用，想请教一下

### ISSUE THREAD

**Issue by hjj18020233699** [pofey/movie_robot#481]
### 当前程序版本

0.9.99

### 问题描述

订阅站点的时候，不能选择站点，选择站点那一块啥也没有

### 重现步骤

1.站点管理
2.新增站点
3.选择站点空白

### 健康检查

一开始添加下载工具的时候，也不能添加站点

**Comment by MouLv** [comment]
这个问题看wiki可以解决：https://yee329.notion.site/4-28702cf23a834c2380eb8ff34de68ea5

**Comment by hjj18020233699** [comment]
![image](https://user-images.githubusercontent.com/36735244/179507522-7e576a89-70cd-4755-83c2-4278ef9177dd.png)
是这个没有，右侧下拉已经下拉了，结果没有站点显示

**Comment by MouLv** [comment]
想问下您看我发的链接里面wiki内容了吗？
![image](https://user-images.githubusercontent.com/16574475/179533114-18dc43d8-63cd-4f03-966b-f75fc291e89b.png)

**Comment by pofey** [comment]
对的 还是好好看wiki吧 楼上说的很清楚了
