### ISSUE TITLE
[缺陷]: web页面搜索资源，任意关键字+数字返回结果异常

### ISSUE THREAD

**Issue by MouLv** [pofey/movie_robot#482]
### 当前程序版本

0.9.99

### 问题描述

通过web页面搜索比如魔女2，教父2。返回结果的部分，emby媒体库的内容会全部返回。
![image](https://user-images.githubusercontent.com/16574475/179466292-0a724109-8729-4fb8-a783-c3d4c0ba6607.png)
![image](https://user-images.githubusercontent.com/16574475/179466308-2a30b680-6c7b-4b14-80c2-3ef93ced9d72.png)

### 重现步骤

通过web页面搜索魔女2

### 健康检查

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/16574475/179466041-8b159a62-3a1b-4123-ad9b-87b5077e2cec.png">

**Comment by pofey** [comment]
之前针对欢乐颂2 欢乐颂3 大江大河2 这种国产剧命名做了一次优化，搜索的时候拆词把教父2 这种也当成季度剧集了
做了点调整，下一版发
