### ISSUE TITLE
[提问]: 无法识别动漫

### ISSUE THREAD

**Issue by zzj6666** [pofey/movie_robot#483]
### 当前程序版本

0.9.99

### 问题

![image](https://user-images.githubusercontent.com/101039599/179478822-f1695127-eb18-4c68-a9a1-75d1ef469b76.png)
![1d5547628fe80a324f46b25a8ebca56](https://user-images.githubusercontent.com/101039599/179478880-2bc66faf-c49f-4db1-b98c-0d3b340a9553.png)
![image](https://user-images.githubusercontent.com/101039599/179478972-de053037-14b2-4577-8e52-e4ae930b9c8c.png)
过滤规则基本没限制，但是就是无法自动订阅，只能手动下载

### 发生问题时系统日志

```shell
2022/07/18 17:00:33 - SubConsumer - INFO: 共在8个站点搜索到8条结果，其中观众最慢，耗费355.74秒
2022/07/18 17:00:33 - SubConsumer - INFO: 斗破苍穹 缘起(2022) 经过系统分析后，没有搜到有效结果。
```

**Comment by pofey** [comment]
需要截图你认为应该下载的截图

**Comment by zzj6666** [comment]
![微信图片_20220719135640](https://user-images.githubusercontent.com/101039599/179675946-5f1ca9da-7614-4a36-841a-5958a740e16c.png)
这两个都是可以下载订阅的

**Comment by zzj6666** [comment]
![image](https://user-images.githubusercontent.com/101039599/179679888-21b7ff97-1911-4583-9b97-15eb06fba779.png)
这部动漫有两季，第一季已经更新完毕可以正常订阅，自动下载，第二部还在更新，我点击订阅后，说我已经订阅过了，应该是软件把两部动漫识别为同一个了。

**Comment by pofey** [comment]
> ```shell
> 斗破苍穹 缘起
> ```

我看了下这个，智能分析种子名称是非常严格的，为了避免下错，这个动漫tmdb中文名斗破苍穹 缘起 有个空格，pt站解析出来名字没空格，所以被智能分析pass掉了。。
目前唯一解法，是tmdb上把中文名的空格去掉。
