### ISSUE TITLE
[优化]: 请求加入纯自定义资源整理

### ISSUE THREAD

**Issue by qzbeta** [pofey/movie_robot#485]
### 当前现状

目前资源整理必须依托tmdb或豆瓣元数据信息。
因此目前整理功能对某些冷门资源或综艺不够友好。
会出现无法准确改名的情况。

### 你的建议

希望加入纯自定义整理选项。
脱离tmdb或豆瓣。
整理时通过纯自定义媒体信息（名称、年份、季数、集数等）来进行重命名整理。
功能如果能实现。
除了电影&剧集这些媒体可以更随心整理。
还能整理一些私人媒体。
比如一组周末外出游玩的视频，也可以通过该功能整理成标准电影&连续剧命名（钓鱼岛三日游 S01E01）。

### 优先级

非常高

### 受众范围

很多人需要

**Comment by ShakeChanDev** [comment]
我也遇到了这类问题，特别是在综艺，例如《脱口秀大会》等等，每一集都分上下，机器人完全无解

抛砖引玉提下可能的解决方案
1.自定义订阅增加选项是否「删除媒体库旧版」
2.增加选项「识别失败仍然硬链」

这两个基本能够解决问题，综艺类对信息准确性需求是低的，对时效性需求是高的，只要保证有的看即可

**Comment by ShakeChanDev** [comment]
头疼了，发现这个需求7月份就发了

**Comment by pofey** [comment]
自定义订阅已经到beta了
