### ISSUE TITLE
[优化]: 影片自动按制片区域分类可以自定义~

### ISSUE THREAD

**Issue by CiaoBye** [pofey/movie_robot#486]
### 当前现状

目前是大陆、港台、日韩、欧美、其他这五个区域

### 你的建议

个人是希望能把日本和韩国单独分开，所以提出能够自定义~
当然我也相信会有更多爱好者会有更细分的区域选择~

### 优先级

一般

### 受众范围

一般

**Comment by cuicuifeng** [comment]
希望可以自定义，每个人需求不同，我目前都是单独建立很多路径来实现分类。

**Comment by pofey** [comment]
这个区域 自定义空间其实非常小，理论上区域的分类最佳组合是有限的
