### ISSUE TITLE
[缺陷]: 整理完成，但是还是有很多显示识别错误和待识别。

### ISSUE THREAD

**Issue by phantasy36** [pofey/movie_robot#488]
### 当前程序版本

0.9.99

### 问题描述

1、电影整理完成了，但是还是有很多显示识别错误和待识别；识别纠错后仍然如此显示，但是emby中已经有相关资源显示了。
2、识别错误和待识别的主要为自己从其他硬盘拷贝过来的原盘；还有下载的合集电影、剧集均存在此类问题。

### 重现步骤

选择电影文件夹，然后选择识别整理，很多显示待识别或者无法识别。

### 健康检查

<img width="1280" alt="01" src="https://user-images.githubusercontent.com/46774023/179620799-10ede0f2-3339-4a90-8bfc-dd5acf2c93ef.png">
<img width="1280" alt="02" src="https://user-images.githubusercontent.com/46774023/179620784-6d348b44-edbf-448f-9fab-a94d635df611.png">
<img width="1280" alt="03" src="https://user-images.githubusercontent.com/46774023/179620794-97d8c09b-7932-4147-a6de-3fe48a23d751.png">
<img width="1280" alt="04" src="https://user-images.githubusercontent.com/46774023/179620797-180f896c-b12f-4e25-9065-30fd70643f8d.png">

**Comment by pofey** [comment]
#478 重复问题 下一版修
