### ISSUE TITLE
[缺陷]: 添加的站点未开启功能也会去检索种子

### ISSUE THREAD

**Issue by qiuwei0209** [pofey/movie_robot#489]
### 当前程序版本

0.9.99

### 问题描述

已经添加到机器人的站点，因为站点有点多，我就关闭了一些站点的“web搜索、智能下载、流量管理”，按正常理解，该站点应该是临时禁用了，但看到日志里面还是有相关站点的种子拉取。

就像之前您（作者）讲的，不管有没有开启订阅，对站点的请求始终是50多次/天，这里是否需要屏蔽没有添加功能的站点，也可以减少对站点的请求？现在的话只能删除站点。

### 重现步骤

依据问题描述

### 健康检查

![image](https://user-images.githubusercontent.com/28587136/179628312-b7130b51-2bd5-4e03-b4fa-c2cbb439bb2d.png)

**Comment by pofey** [comment]
是的，关闭web搜索只是主动不搜他了，关闭智能下载，只是订阅时不拉他了，但全站订阅，一直都会去跑，不会关的，这是现在既定的逻辑
