### ISSUE TITLE
[缺陷]: 站点数据不显示今日上传

### ISSUE THREAD

**Issue by tianjian110** [pofey/movie_robot#490]
### 当前程序版本

0.9.99

### 问题描述

![904FCC95-4994-4E64-9EFC-67006B1013CA](https://user-images.githubusercontent.com/94738666/179638340-6575eacc-b07c-4a12-a83e-9ec78c4dc2b4.png)
![99E8ABAD-C228-48A6-8CDB-875A56621455](https://user-images.githubusercontent.com/94738666/179638347-dff2ac9c-a4e4-4bf0-b54d-e431c0985617.png)

### 重现步骤

打开站点管理

### 健康检查

![FFE0902C-5A75-4125-A6A6-47DA3CB8E137](https://user-images.githubusercontent.com/94738666/179638419-e7c0c399-add7-47a3-9195-b413eb2d4f23.png)

**Comment by pofey** [comment]
新添加的站点吧？因为升级diff机制，隔一天才能算出来

**Comment by tianjian110** [comment]
不是新添加站点，每次进入都是无法显示

**Comment by pofey** [comment]
> 不是新添加站点，每次进入都是无法显示

是有异常么 有异常站点会这样 右上角强制刷新能好
