### ISSUE TITLE
[缺陷]: tmdb和豆瓣的中文名不一致。 机器人搜索的是tmdb中文名。片源用的豆瓣中文名。实际有片源但拉取不到。

### ISSUE THREAD

**Issue by zxq321zxq** [pofey/movie_robot#492]
### 当前程序版本

0.9.99

### 问题描述
tmdb和豆瓣的中文名不一致。 机器人搜索的是tmdb中文名。片源用的豆瓣中文名。实际有片源但拉取不到。
tmdb：欢迎来到实力至上主义的教室
豆瓣：欢迎来到实力至上主义教室

![64a84d40bc5f4626425bb69f4e9fa31](https://user-images.githubusercontent.com/50660883/179704595-d4e74c7e-d0d9-4782-8594-813cc305953c.png)
![4b8d669d820cca092a68c28954eaa9b](https://user-images.githubusercontent.com/50660883/179704609-50bee9db-b581-4aa8-a4e9-3c1e700b3b1c.png)
![5b2cedd8389697a5b17826a86f697ba](https://user-images.githubusercontent.com/50660883/179704622-c3dd9fb9-9c01-40c5-9ff4-48949940cce2.png)
![02346aba9422206e121b922ee023862](https://user-images.githubusercontent.com/50660883/179704637-86b00348-15cf-4abe-a771-577cb454c55a.png)
![02b217667018d33ce17b7734c65b5c6](https://user-images.githubusercontent.com/50660883/179704692-1aa3fea2-5a24-4070-aff3-a943fd14cec7.png)
![2df576ebc6dfa42cf9c6f4ef9fe2f49](https://user-images.githubusercontent.com/50660883/179704711-579def04-3250-4084-9085-39df919836d8.png)

### 重现步骤

tmdb和豆瓣的中文名不一致的情况下。  机器人搜的是tmdb中文名，片源用的是豆瓣中文名。应该就会出现同样问题。

### 发生问题时系统日志

```shell
2022/07/19 16:22:28 - SubConsumer - INFO: 已经开始在站点: 馒头,阿童木,RARBG,高清视界,观众,红豆饭 搜索: 欢迎来到实力至上主义的教室,Classroom of the Elite,tt7263328
2022/07/19 16:22:44 - SubConsumer - INFO: 共在6个站点搜索到10条结果，其中高清视界最慢，耗费15.8秒
2022/07/19 16:22:44 - SubConsumer - INFO: 欢迎来到实力至上主义的教室(2017) 已经有搜索结果，但经过你设定的过滤器后，无任何结果。
```

### 健康检查

![image](https://user-images.githubusercontent.com/50660883/179705127-66a2c68b-f6f6-49b5-8cc8-3a81265335f0.png)

**Comment by pofey** [comment]
这也没什么优化能做啊

**Comment by zxq321zxq** [comment]
如果 tmdb和豆瓣的中文名不一样，可以订阅时搜索2次不同的中文名吗。这样应该就能订阅上了。

**Comment by zxq321zxq** [comment]
应该算优化不是机器人错误。 我选错了
