### ISSUE TITLE
[优化]: 用户管理是否可以设置个删除按钮

### ISSUE THREAD

**Issue by zzj6666** [pofey/movie_robot#497]
### 当前现状

![image](https://user-images.githubusercontent.com/101039599/179957520-12873630-c851-40c1-afff-3c8e7ad7f2ed.png)
目前自己添加了一个用户，想删除，不怎么如何删除

### 你的建议

希望能有个删除键

### 优先级

非常高

### 受众范围

不确定

**Comment by CiaoBye** [comment]
目前的话可以自己去db删除~

**Comment by pofey** [comment]
改完了，下个版本见
