### ISSUE TITLE
[优化]: 中文刮削后emby剧集中的即将上映消失

### ISSUE THREAD

**Issue by jinfeng1985** [pofey/movie_robot#498]
### 当前现状

目前用机器人的中文刮削后，原来用TheTVDB,TheMovieDb数据源刮的电视剧，在emby剧集“即将上映”的剧集下集上映时间的内容没有了。

### 你的建议

是否使用中文刮削后，即将上映中仍然会有这个功能在。

### 优先级

一般

### 受众范围

一般

**Comment by pofey** [comment]
这跟刮nfo有关系吗？是什么影响的
