### ISSUE TITLE
帮忙看看这部剧的评分，还有TR卡UI的一个问题

### ISSUE THREAD

**Issue by mjyhj** [pofey/movie_robot#5]
下的琅琊榜2015，用的compress规则

结果给我下了这个
Nirvana.in.Fire.Complete.2015.1080p.WEB-DL.H264.AAC-BYRHD  86.72G
个人搜出，应该是这个更符合
Nirvana in Fire 2015 2160p WEB-DL H.265 AAC-FLTTH  82.30G

还有可能是因为TR下载大种的问题，导致UI偶尔会卡几秒转圈圈，检测种子状态没返回。robot直接挂掉了，日志报错最后停留在12：46分就没了
![1](https://user-images.githubusercontent.com/22577418/153739830-760640a3-6352-48b5-87c8-4674f52831b7.png)
[robot.log](https://github.com/pofey/movie_robot/files/8055016/robot.log)

**Comment by pofey** [comment]
h265和h264的分差现在并不高，如果其他维度满分，很大概率被超

**Comment by pofey** [comment]
tr卡死时机器人已经加了报错兼容
