### ISSUE TITLE
[缺陷]: 剧集所有集数被识别成第八集

### ISSUE THREAD

**Issue by zoooo0** [pofey/movie_robot#501]
### 当前程序版本

0.9.99.0720

### 问题描述

剧集所有集数被识别成第八集

### 重现步骤

下载frds的超感猎杀全2季
或者手动整理frds的超感猎杀全2季

### 发生问题时系统日志

```shell
2022/07/21 23:06:41 - Thread-31 - INFO: 完成剧集 勇气(2015) 第1季第8集的NFO文件生成，路径：/home/pess/inss/updata/serial/超感猎杀 (2015)/Season 1/超感猎杀 S01E08 - 1080p x265 FRDS.nfo
这段日志不断重复
```

### 健康检查

![image](https://user-images.githubusercontent.com/62314432/180248368-16a2ea89-81d0-4003-8817-0859f452af07.png)
种子文件名
感觉大概率命名问题导致失败

**Comment by pofey** [comment]
已知问题了，给你记一个有效bug，但是当前处理模式不打算针对这个去修复了😂
