### ISSUE TITLE
[缺陷]: 识别错误

### ISSUE THREAD

**Issue by zsgcgrs** [pofey/movie_robot#505]
### 当前程序版本

0.9.99 0722

### 问题描述

Keep.Running.S06E11.2022.1080p.WEB-DL.H264.AAC-TJUPT识别为S01E11了，之前是可以识别的

### 重现步骤

之前是可以识别的

### 健康检查

之前是可以识别的

**Comment by pofey** [comment]
种子名呢 得看下种子名
