### ISSUE TITLE
[缺陷]: 星汉灿烂被识别成了电影

### ISSUE THREAD

**Issue by tianjian110** [pofey/movie_robot#506]
### 当前程序版本

0.9.99.0720

### 问题描述

星汉灿烂电视剧
![3F2C2C48-1675-42DE-93F5-5DB6952F908D](https://user-images.githubusercontent.com/94738666/180496268-6d972880-138f-4d49-8f25-2c713ebcb61c.png)
被识别成了电影

### 重现步骤

无

### 健康检查

正常

**Comment by pofey** [comment]
![DE0B9242-871F-42C6-8C2D-CF94216EA0A9](https://user-images.githubusercontent.com/1396975/180513384-513f8d4a-9b58-4d7b-b735-c7574049fca8.png)

无法重现，没什么问题

**Comment by tianjian110** [comment]
不是立即变成电影，而是过一段时间被识别成2011年的电影
