### ISSUE TITLE
[缺陷]: 星汉灿烂只下载了20集，就显示完成

### ISSUE THREAD

**Issue by tianjian110** [pofey/movie_robot#507]
### 当前程序版本

0.9.99.0720

### 问题描述

星汉灿烂一共出了24集，只下载了20集，就显示完成，没有继续订阅
![4B8482A7-2616-4D5D-90F0-9328AF7C4BDC](https://user-images.githubusercontent.com/94738666/180496755-42839edc-7d7f-409f-8976-851138406760.png)

### 重现步骤

无

### 健康检查

正常

**Comment by pofey** [comment]
缺少日志、重现步骤，预期下载种子信息，无法进行问题排查，无效反馈关闭了

**Comment by pofey** [comment]
![Uploading A18ABAA5-6F1E-44ED-9B50-ED567C2CD890.jpeg…]()

**Comment by pofey** [comment]
![C80A3C20-98CC-4207-A223-47F6583CE5B6](https://user-images.githubusercontent.com/1396975/180513876-08a34c78-8a17-4cd2-a73e-49023d3a87aa.jpeg)
一切正常

**Comment by lzl20110** [comment]
这个剧我遇到过几次毫无征兆的识别成2011年 然后就变成订阅完成了 
![1](https://user-images.githubusercontent.com/25917398/180609138-651356e9-bb49-4c80-ad4d-9c3c63d18080.png)
![2](https://user-images.githubusercontent.com/25917398/180609140-0e83730d-95f3-4e3f-971b-4a8409c57c30.png)

**Comment by pofey** [comment]
> 这个剧我遇到过几次毫无征兆的识别成2011年 然后就变成订阅完成了
> ![1](https://user-images.githubusercontent.com/25917398/180609138-651356e9-bb49-4c80-ad4d-9c3c63d18080.png)
> ![2](https://user-images.githubusercontent.com/25917398/180609140-0e83730d-95f3-4e3f-971b-4a8409c57c30.png)

上面应该还有日志吧

**Comment by lzl20110** [comment]
> > 这个剧我遇到过几次毫无征兆的识别成2011年 然后就变成订阅完成了
> > ![1](https://user-images.githubusercontent.com/25917398/180609138-651356e9-bb49-4c80-ad4d-9c3c63d18080.png)
> > ![2](https://user-images.githubusercontent.com/25917398/180609140-0e83730d-95f3-4e3f-971b-4a8409c57c30.png)
> 
> 上面应该还有日志吧

![3](https://user-images.githubusercontent.com/25917398/180610932-903756f6-fe2f-46a7-b3e0-7bfa48447e26.png)
这一段有用吗

**Comment by pofey** [comment]
> > > 这个剧我遇到过几次毫无征兆的识别成2011年 然后就变成订阅完成了
> > > ![1](https://user-images.githubusercontent.com/25917398/180609138-651356e9-bb49-4c80-ad4d-9c3c63d18080.png)
> > > ![2](https://user-images.githubusercontent.com/25917398/180609140-0e83730d-95f3-4e3f-971b-4a8409c57c30.png)
> > 
> > 
> > 上面应该还有日志吧
> 
> ![3](https://user-images.githubusercontent.com/25917398/180610932-903756f6-fe2f-46a7-b3e0-7bfa48447e26.png) 这一段有用吗

你把这剧删了 重订 看看明早还会不会错

**Comment by lzl20110** [comment]
> 

前天就重订了,到现在正常

**Comment by tianjian110** [comment]
删除重新订阅正常，现在又出现问题，自动识别成2011年的电影，然后自动完成
