### ISSUE TITLE
[缺陷]: 监控下载器手动种子部分情况会报错

### ISSUE THREAD

**Issue by zoooo0** [pofey/movie_robot#508]
### 当前程序版本

0.9.99.0722

### 问题描述

夏日重现最新一集不断重复订阅并失败

### 重现步骤

订阅夏日重现下载到15集

### 发生问题时系统日志

```shell
2022/07/23 10:18:25 - SubConsumer - INFO: 夏日重现(2022) 第1季 第[15]集 品质：WEB-DL None None 资源: https://lemonhd.org/details_animate.php?id=316427 已经提交下载。
2022/07/23 10:18:25 - lemonhd-downloader - INFO: 开始处理来自订阅的下载: [lemonhd][夏日重现][Summer Time Rendering][2022][WEB-DL][1080][TV Series][第15话][Nekomoe kissaten]
2022/07/23 10:18:25 - lemonhd-downloader - INFO: 夏日重现(2022)在媒体服务已经存在，但未正确刮削，当前名称为：[Nekomoe kissaten][Summer Time Rendering][15][1080p][JPSC].mp4
2022/07/23 10:18:25 - lemonhd-downloader - INFO: [lemonhd][夏日重现][Summer Time Rendering][2022][WEB-DL][1080][TV Series][第15话][Nekomoe kissaten]提交下载失败
```

### 健康检查

尝试手动时也会进行报错

2022/07/23 10:33:00 - DownlaodCommander - INFO: 开始处理来自下载器的手动下载记录: [Nekomoe kissaten][Summer Time Rendering][15][1080p][JPSC].mp4
2022/07/23 10:33:00 - DownlaodCommander - ERROR: 处理下载任务失败：'NoneType' object has no attribute 'tv_series'
Traceback (most recent call last):
  File "yee/task/consumer/downloadcommanderconsumer.py", line 30, in yee.task.consumer.downloadcommanderconsumer.DownloadCommanderConsumer.run
  File "yee/service/downloadservice.py", line 257, in yee.service.downloadservice.DownloadService.new_download_record
  File "yee/service/downloadservice.py", line 292, in yee.service.downloadservice.DownloadService.analyze_and_setmodel
AttributeError: 'NoneType' object has no attribute 'tv_series'

**Comment by pofey** [comment]
健康检查的图呢，以及媒体服务器到底刮好了么

**Comment by zoooo0** [comment]
![image](https://user-images.githubusercontent.com/62314432/180603405-cb2d776c-970e-4263-9940-13b0867b4fd9.png)
最后一直没有提交到qbittorrent，所以完全没下好，导致一大早醒来看到十几条订阅夏日重现15集的日志都是这个报错

**Comment by zoooo0** [comment]
导致现在不知道触发什么bug，所有手动提交的到qb的剧集全部会报错
2022/07/23 19:42:00 - DownlaodCommander - INFO: 开始处理来自下载器的手动下载记录: 脱罪大师.The.Escape.Artist.E01-E03.2013.1080p.Blu-ray.x265.AC3￡cXcY@FRDS
2022/07/23 19:42:00 - DownlaodCommander - ERROR: 处理下载任务失败：'NoneType' object has no attribute 'tv_series'
Traceback (most recent call last):
  File "yee/task/consumer/downloadcommanderconsumer.py", line 30, in yee.task.consumer.downloadcommanderconsumer.DownloadCommanderConsumer.run
  File "yee/service/downloadservice.py", line 257, in yee.service.downloadservice.DownloadService.new_download_record
  File "yee/service/downloadservice.py", line 292, in yee.service.downloadservice.DownloadService.analyze_and_setmodel
AttributeError: 'NoneType' object has no attribute 'tv_series'

**Comment by pofey** [comment]
> ![image](https://user-images.githubusercontent.com/62314432/180603405-cb2d776c-970e-4263-9940-13b0867b4fd9.png)
> 最后一直没有提交到qbittorrent，所以完全没下好，导致一大早醒来看到十几条订阅夏日重现15集的日志都是这个报错

先让自己的qbit访问稳定了再说吧

**Comment by zoooo0** [comment]
明显不是稳定的问题吧，我专门是在qb能正常访问的时候提交的脱罪大师.The.Escape.Artist.E01-E03.2013.1080p.Blu-ray.x265.AC3￡cXcY@FRDS这个种子结果一样报错，中途而且在此之前手动提交的电影完全没问题

**Comment by pofey** [comment]
> 明显不是稳定的问题吧，我专门是在qb能正常访问的时候提交的脱罪大师.The.Escape.Artist.E01-E03.2013.1080p.Blu-ray.x265.AC3￡cXcY@FRDS这个种子结果一样报错，中途而且在此之前手动提交的电影完全没问题

正常访问的时候、提交报错的日志是？

**Comment by zoooo0** [comment]
![image](https://user-images.githubusercontent.com/62314432/180607698-2c1ee3ee-bcea-4497-87d0-6fe5feb3db57.png)

2022/07/23 21:44:00 - DownlaodCommander - INFO: 开始处理来自下载器的手动下载记录: [Nekomoe kissaten][Summer Time Rendering][15][1080p][JPSC].mp4
2022/07/23 21:44:00 - DownlaodCommander - ERROR: 处理下载任务失败：'NoneType' object has no attribute 'tv_series'
Traceback (most recent call last):
  File "yee/task/consumer/downloadcommanderconsumer.py", line 30, in yee.task.consumer.downloadcommanderconsumer.DownloadCommanderConsumer.run
  File "yee/service/downloadservice.py", line 257, in yee.service.downloadservice.DownloadService.new_download_record
  File "yee/service/downloadservice.py", line 292, in yee.service.downloadservice.DownloadService.analyze_and_setmodel
AttributeError: 'NoneType' object has no attribute 'tv_series'

**Comment by pofey** [comment]
> ![image](https://user-images.githubusercontent.com/62314432/180607698-2c1ee3ee-bcea-4497-87d0-6fe5feb3db57.png)
> 
> 2022/07/23 21:44:00 - DownlaodCommander - INFO: 开始处理来自下载器的手动下载记录: [Nekomoe kissaten][Summer Time Rendering][15][1080p][JPSC].mp4 2022/07/23 21:44:00 - DownlaodCommander - ERROR: 处理下载任务失败：'NoneType' object has no attribute 'tv_series' Traceback (most recent call last): File "yee/task/consumer/downloadcommanderconsumer.py", line 30, in yee.task.consumer.downloadcommanderconsumer.DownloadCommanderConsumer.run File "yee/service/downloadservice.py", line 257, in yee.service.downloadservice.DownloadService.new_download_record File "yee/service/downloadservice.py", line 292, in yee.service.downloadservice.DownloadService.analyze_and_setmodel AttributeError: 'NoneType' object has no attribute 'tv_series'

如果这是一个手动提交到下载器的种子，通过监听进机器人。那这就是一个bug

**Comment by pofey** [comment]
已经修复
