### ISSUE TITLE
[优化]: 搜索xx希望多一个用户权限配置

### ISSUE THREAD

**Issue by ciweiyoushang** [pofey/movie_robot#509]
### 当前现状

其他用户，也可以搜索xx资源。

### 你的建议

搜索xx希望多一个用户权限配置。

### 优先级

非常高

### 受众范围

很多人需要

**Comment by arho14** [comment]
是的，我也需要这个功能，或者至少给一个开关，像以前搜索设置里面那样在base_config.yml 设置就好。现在MR 连我小孩都在用来看动画片了，所以希望至少能给个开关哈。

**Comment by pofey** [comment]
> 是的，我也需要这个功能，或者至少给一个开关，像以前搜索设置里面那样在base_config.yml 设置就好。现在MR 连我小孩都在用来看动画片了，所以希望至少能给个开关哈。

哈哈哈。会有用户权限控制的

**Comment by arho14** [comment]
> > 是的，我也需要这个功能，或者至少给一个开关，像以前搜索设置里面那样在base_config.yml 设置就好。现在MR 连我小孩都在用来看动画片了，所以希望至少能给个开关哈。
> 
> 哈哈哈。会有用户权限控制的

都正式版了，大佬先加个开关吧，为了其他人搜不到xx 一直用老版本呢....

**Comment by pofey** [comment]
上线了

**Comment by arho14** [comment]
> 上线了

感谢哈～
