### ISSUE TITLE
[优化]: 搜索增加自定义配置选项

### ISSUE THREAD

**Issue by CiaoBye** [pofey/movie_robot#510]
### 当前现状

![搜索](https://user-images.githubusercontent.com/32627953/180589013-14a1fbfb-82be-4420-b9c8-97d3b0b4dbbb.png)

目前搜索仅支持单次自定义，如有特殊需求，每次都需要重新勾选。

### 你的建议

![image](https://user-images.githubusercontent.com/32627953/180589035-b5e83af7-6af8-4a1e-a356-de8f8238a05e.png)
搜索可以自定义配置，如电影，电视剧等选项，支持快速切换，提高搜索效率。

### 优先级

非常高

### 受众范围

很多人需要

**Comment by pofey** [comment]
下一版上线
