### ISSUE TITLE
[缺陷]: 手机端“搜索资源站”按钮问题

### ISSUE THREAD

**Issue by htnanako** [pofey/movie_robot#511]
### 当前程序版本

0.9.99.0723

### 问题描述

手机端safari保存到桌面书签，搜索界面勾选“搜索资源站”选项无效，依旧不搜索资源站，需要取消勾选重新勾上才能生效；”全选“按钮也无法操作“搜索资源站”按钮的选中状态。删除书签重新添加问题依旧。
电脑端及手机safari直接打开网页正常。

### 重现步骤

手机端safari保存到桌面后打开搜索
![RPReplay_Final1658551473](https://user-images.githubusercontent.com/68056603/180591370-313fd2a5-2185-4093-90a4-7865afa9ea34.gif)

### 健康检查

<img width="348" alt="image" src="https://user-images.githubusercontent.com/68056603/180591444-8aa81434-755a-4e09-8b2d-01d8b06f38b0.png">

**Comment by pofey** [comment]
已经修复
