### ISSUE TITLE
[缺陷]: mr搜索馒头xx，出现大海报，建议限制大小

### ISSUE THREAD

**Issue by Howardnm** [pofey/movie_robot#513]
### 当前程序版本

0.9.99.0723

### 问题描述

- mr搜索馒头xx，出现大海报，建议限制大小
- 差点把笔记本屏幕盖烂。

### 重现步骤

![image](https://user-images.githubusercontent.com/55622355/180612428-81bf8ee9-36e8-460c-8a8a-e50d521354b6.png)

### 健康检查

目前功能没问题

**Comment by pofey** [comment]
这算什么bug？
