### ISSUE TITLE
[优化]: 建立验证vip缓存机制

### ISSUE THREAD

**Issue by E4s0N** [pofey/movie_robot#514]
### 当前现状

部分地区用户网络环境不稳定，有时无法连接至 http://mbot.vip/ 进行vip验证，造成MR占用大量内存，
![7debeb6fb3289a7382d02a26e1f4cc1](https://user-images.githubusercontent.com/109868048/180613907-d206b665-9a5c-41b0-b697-cc18ff25e48b.jpg)
![493505c4be2fa70d3626aea3759136e](https://user-images.githubusercontent.com/109868048/180613920-667e7b60-d973-46ff-9ea0-52aeda1d2c85.jpg)
![image](https://user-images.githubusercontent.com/109868048/180614010-5b8016f9-9a1f-400e-ac41-ec520e54f1b0.png)

### 你的建议

请问能否像emby验证手机app中的Premiere会员那样，有一个缓存机制，验证成功后可以维持一段时间之后再次验证？

### 优先级

非常高

### 受众范围

一般

**Comment by pofey** [comment]
这不是解决问题的方法。现在可不止验证需要用服务，中文影人数据也需要，未来还有比如更新，插件，规则分享机制都需要用。
还是需要自身分析清楚，到底是因为什么导致了访问失败再说。
