### ISSUE TITLE
[缺陷]: 自动整理失败

### ISSUE THREAD

**Issue by qzbeta** [pofey/movie_robot#515]
### 当前程序版本

0.9.99.0723

### 问题描述

杜鹃的婚约。
第13集整理失败。
下载完成后自动整理失败。报：整理失败：[Errno 104] Connection reset by peer
尝试手动整理也失败。报：请求出错：'NoneType' object has no attribute 'tv_series'
![Shell_20220724-032650-823](https://user-images.githubusercontent.com/48495382/180620378-722339d8-8157-4153-b19d-f6c75cae45d8.png)
![Shell_20220724-032943-751](https://user-images.githubusercontent.com/48495382/180620384-3660b728-d01a-42de-b37c-d2ee038084ca.png)
![Shell_20220724-032855-303](https://user-images.githubusercontent.com/48495382/180620387-0946afc1-7c11-4a64-b3c1-c0ef9b4fa723.png)

### 重现步骤

下杜鹃的婚约第13集。100%重现。

### 发生问题时系统日志

```shell
2022/07/24 02:34:24 - ThreadPoolExecutor-5_0 - ERROR: 整理失败：[Errno 104] Connection reset by peer
 2022/07/24 02:34:24 - ThreadPoolExecutor-5_0 - INFO: 通知媒体库刷新完成，tmdb_id: 122587 save_path: /WD 14T1/NFS item_id: 7014
 2022/07/24 02:34:24 - ThreadPoolExecutor-5_0 - INFO: 通知媒体库刷新完成，tmdb_id: 122587 save_path: /WD 14T1/NFS item_id: 7101
 2022/07/24 02:34:24 - ThreadPoolExecutor-5_0 - INFO: 通知媒体库刷新完成，tmdb_id: 122587 save_path: /WD 14T1/NFS item_id: 7933
 2022/07/24 02:34:24 - ThreadPoolExecutor-5_0 - INFO: 杜鹃的婚约 第1季(2022) 第13集字幕下载 任务已经创建。
 2022/07/24 02:34:25 - ThreadPoolExecutor-5_0 - INFO: Kakkou.no.Iinazuke.S01.2022.1080p.CR.WEB-DL.x264.AAC-ADWeb处理完毕。



 2022/07/24 03:26:58 - Thread-121 - ERROR: 请求出错：'NoneType' object has no attribute 'tv_series'
Traceback (most recent call last):
  File "yee/register/bp_register.py", line 34, in yee.register.bp_register.login_required.wrapper.decorator
  File "yee/controller/downloadcontroller.py", line 243, in yee.controller.downloadcontroller.reanalyse
  File "yee/service/downloadservice.py", line 292, in yee.service.downloadservice.DownloadService.analyze_and_setmodel
AttributeError: 'NoneType' object has no attribute 'tv_series'
```

### 健康检查

![Shell_20220724-033427-259](https://user-images.githubusercontent.com/48495382/180620366-5703ab71-d003-4016-9872-71a231c3333c.png)

**Comment by pofey** [comment]
#508 异常报错和这个相同 确认是问题。
整理失败：[Errno 104] Connection reset by peer
这上面还有没有报错 这是访问tmdb 下载器 之类 报错了

**Comment by qzbeta** [comment]
没有其他报错
![Shell_20220724-103300-550](https://user-images.githubusercontent.com/48495382/180629706-13e9db1a-e21f-4e9b-b386-ce2ae31a30a4.png)

**Comment by pofey** [comment]
已经修复
