### ISSUE TITLE
关于tmdb数据不一致，导致剧集订阅提前自动结束

### ISSUE THREAD

**Issue by 52popojie** [pofey/movie_robot#517]
### 当前程序版本

0.99.0723

### 问题描述

https://www.themoviedb.org/tv/88939
https://www.themoviedb.org/tv/202042
同一个综艺，目前还会有s06e13，但是因为tmdb数据不一致，导致mr提前订阅结束了
![Screenshot_20220724_090655_mark via](https://user-images.githubusercontent.com/76438601/180627941-15ed7c2e-5731-4291-8583-e3ed4a63d791.jpg)

### 重现步骤

在mr搜索并订阅后，只会订阅12集，然后自动关闭订阅了，第十三集是有的

### 健康检查

![Screenshot_20220724_090559_mark via](https://user-images.githubusercontent.com/76438601/180627923-65004c85-a380-4b01-aaa7-d3b8c7da7e18.jpg)

**Comment by pofey** [comment]
这个问题程序上无法优化，去把只有12集那个改成更多集吧，纠正一下tmdb

**Comment by pofey** [comment]
要么我们一起投诉把下面那个错的删了
