### ISSUE TITLE
[缺陷]: 普通用户首页api/movie/douban_suggestion无权限

### ISSUE THREAD

**Issue by Ignatius-Ye** [pofey/movie_robot#522]
### 当前程序版本

0.9.99.0723

### 问题描述

![Screenshot_20220724_205553](https://user-images.githubusercontent.com/37823715/180648211-7c8acfeb-4e68-4f7b-bacb-b4daba0d1f22.jpg)

### 重现步骤

使用普通用户登录mr 点击首页

### 健康检查

![Screenshot_20220724_210338](https://user-images.githubusercontent.com/37823715/180648262-c9faeea3-7c5e-481e-9326-8a2a8f87719d.jpg)

**Comment by pofey** [comment]
已经修复
