### ISSUE TITLE
[缺陷]: 整理超时空富豪出错

### ISSUE THREAD

**Issue by happyhaha1** [pofey/movie_robot#523]
### 当前程序版本

0.9.99.0723

### 问题描述

显示unsupported operand type(s) for +: 'NoneType' and 'list'

### 重现步骤

订阅超时空富豪，下载完成后无法整理。
整理时，报错。

### 发生问题时系统日志

```shell
2022/07/24 22:43:38 - MainThread - INFO: 当前版本: 0.9.99.0723
2022/07/24 22:44:09 - Thread-74 - INFO: 开始自动用TMDB数据搜索豆瓣数据
2022/07/24 22:44:09 - Thread-74 - INFO: 搜索豆瓣: 超时空富豪 年份：2022 季度：None 季度发行年份：None
2022/07/24 22:44:16 - Thread-74 - INFO: 内容：/mnt/user/media/download/movie/超时空富豪. I.Will.Be.Rich.Man.2022.2160p.WEB-DL.H265.AAC-ADWeb/超时空富豪. I.Will.Be.Rich.Man.2022.2160p.WEB-DL.H265.AAC-ADWeb.mp4 识别为：超时空富豪 2022-07-10
2022/07/24 22:44:16 - Thread-74 - ERROR: 整理失败：unsupported operand type(s) for +: 'NoneType' and 'list'
```

### 健康检查

![Uploading image.png…]()

**Comment by pofey** [comment]
日志不全 等下一版补充日志再看

**Comment by happyhaha1** [comment]
内容：/mnt/user/media/download/movie/超时空富豪. I.Will.Be.Rich.Man.2022.2160p.WEB-DL.H265.AAC-ADWeb/超时空富豪. I.Will.Be.Rich.Man.2022.2160p.WEB-DL.H265.AAC-ADWeb.mp4 识别为：超时空富豪 2022-07-10
2022/07/25 09:04:22 - Thread-98 - ERROR: 整理失败：unsupported operand type(s) for +: 'NoneType' and 'list'
Traceback (most recent call last):
  File "yee/media/link/medialink.py", line 186, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/movielink.py", line 153, in yee.media.link.movielink.MovieLink.__handle__
  File "yee/media/link/movielink.py", line 92, in yee.media.link.movielink.MovieLink.__create_nfo__
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
2022/07/25 09:04:22 - Thread-98 - INFO: 通知媒体库刷新完成，tmdb_id: 999310 save_path: /mnt/user/media/server/电影 item_id: 3227ce1e069754c594af25ea66d69fc7
2022/07/25 09:04:22 - Thread-98 - INFO: 超时空富豪(2022) 发行地区为['中国大陆']，不需要下载字幕。
2022/07/25 09:04:23 - Thread-98 - INFO: 超时空富豪. I.Will.Be.Rich.Man.2022.2160p.WEB-DL.H265.AAC-ADWeb处理完毕。
2022/07/25 09:04:27 - Thread-102 - INFO: 内容：/mnt/user/media/download/movie/超时空富豪. I.Will.Be.Rich.Man.2022.2160p.WEB-DL.H265.AAC-ADWeb/超时空富豪. I.Will.Be.Rich.Man.2022.2160p.WEB-DL.H265.AAC-ADWeb.mp4 识别为：超时空富豪 2022-07-10
2022/07/25 09:04:27 - Thread-102 - ERROR: 整理失败：unsupported operand type(s) for +: 'NoneType' and 'list'
Traceback (most recent call last):
  File "yee/media/link/medialink.py", line 186, in yee.media.link.medialink.MediaLink.link
  File "yee/media/link/movielink.py", line 153, in yee.media.link.movielink.MovieLink.__handle__
  File "yee/media/link/movielink.py", line 92, in yee.media.link.movielink.MovieLink.__create_nfo__
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
2022/07/25 09:04:28 - Thread-102 - INFO: 通知媒体库刷新完成，tmdb_id: 999310 save_path: /mnt/user/media/server/电影 item_id: 3227ce1e069754c594af25ea66d69fc7
2022/07/25 09:04:28 - Thread-102 - INFO: 超时空富豪(2022) 发行地区为['中国大陆']，不需要下载字幕。
2022/07/25 09:04:28 - Thread-102 - INFO: 超时空富豪. I.Will.Be.Rich.Man.2022.2160p.WEB-DL.H265.AAC-ADWeb处理完毕。

**Comment by happyhaha1** [comment]
更新完的日志

**Comment by pofey** [comment]
新版应该是不会有这个问题，忘记在哪个版本修了
