### ISSUE TITLE
[缺陷]: 机器人接收消息的接口地址无法访问

### ISSUE THREAD

**Issue by owenlz** [pofey/movie_robot#525]
### 当前程序版本

0.9.99.0724

### 问题描述

按照http://域名:外网端口/api/qywx/receive填写地址手机无法访问

### 重现步骤

1、使用“http://域名:外网端口/”可以用手机正常访问到机器人的页面（ipv6，已添加支持ipv6的代码）。
2、增加/api/qywx/receive后无法访问。

### 发生问题时系统日志

```shell
2022/07/25 11:54:44 - Thread-198 - ERROR: '<' not supported between instances of 'NoneType' and 'str'
2022/07/25 11:54:44 - Thread-198 - ERROR: ERR: VerifyURL ret: -40003
```

### 健康检查

![image](https://user-images.githubusercontent.com/109936651/180697491-0aa4b3c1-f0bd-453a-b4d5-524d2003ec4e.png)

**Comment by pofey** [comment]
这个接口是给腾讯访问的，你要直接访问干什么

**Comment by owenlz** [comment]
因为我发现在微信里发送电影名称，不会反馈搜索结果了，排查的时候

**Comment by owenlz** [comment]
以前我的微信发送电影名称，是可以收到反馈的，现在不行了，日志里面也没有任何反馈，所以我猜测是不是机器人没有收到消息

**Comment by pofey** [comment]
> 以前我的微信发送电影名称，是可以收到反馈的，现在不行了，日志里面也没有任何反馈，所以我猜测是不是机器人没有收到消息

放到腾讯里 点保存 看看腾讯访问时提示什么

**Comment by owenlz** [comment]
企业微信的应用管理界面提示：企业微信openapi回调地址请求不通过

**Comment by owenlz** [comment]
> > 企业微信的应用管理界面提示：企业微信openapi回调地址请求不通过
> 
> 此时此刻日志是什么呢

完全没有日志，没有反应

**Comment by pofey** [comment]
> > > 企业微信的应用管理界面提示：企业微信openapi回调地址请求不通过
> > 
> > 
> > 此时此刻日志是什么呢
> 
> 完全没有日志，没有反应

那就是腾讯的机房访问不到你家

**Comment by Decade1993** [comment]
我发现貌似是腾讯的那个消息回调不支持ipv6？
我做了如下操作可以了：
1.套了cf，指向原来的ipv6的域名，cf是支持Ipv4地址访问的
2.修改机器人网络设置中的站点访问地址为cf的地址，不改的话验证url和腾讯那边的会对不上
3.将cf地址配置到腾讯接受消息那里

希望有所帮助~
