### ISSUE TITLE
[优化]: 建议支持.tp媒体格式

### ISSUE THREAD

**Issue by tcmdtc** [pofey/movie_robot#526]
### 当前现状

后缀名为.tp的格式
<img width="887" alt="image" src="https://user-images.githubusercontent.com/7284030/180721104-f9561091-ad5f-49b6-b3da-f84f3f4794d7.png">

在本地资源整理时不识别
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/7284030/180720662-e1b61798-6470-4fd3-80d5-e111850dcf9f.png">

### 你的建议
支持.tp的识别
后来我发现Emby和Infuse也不支持.tp，是否可以在硬连接的同时把视频后缀改为.ts 这样就可以播放了。

### 优先级

一般

### 受众范围

一般

**Comment by pofey** [comment]
你试过吗，tp 改ts

**Comment by tcmdtc** [comment]
![image](https://user-images.githubusercontent.com/7284030/182377923-a0b4f991-ad56-4718-9e3a-b7aad51b49e6.png)
![89d86234f57fec56d91fddc1dd32f97](https://user-images.githubusercontent.com/7284030/182378362-5c6c997e-b01f-42f1-bd31-0162f06856db.jpg)
改成ts以后Emby和Infuse都是可以识别并且正常播放的
