### ISSUE TITLE
[缺陷]: 海贼王只会硬链接第一季，第一季之后出的都无法识别

### ISSUE THREAD

**Issue by zzj6666** [pofey/movie_robot#527]
### 当前程序版本

0.9.99.0724

### 问题描述

![image](https://user-images.githubusercontent.com/101039599/180736585-1e39a459-dafb-455e-8a67-1fd60f7bdaa3.png)
![image](https://user-images.githubusercontent.com/101039599/180736669-62dee72f-c674-43c2-963c-7b9865c86844.png)

### 重现步骤

这个是我下载好别人已经整理好的合集，我想硬链接到我想要的目录，但在手动硬链接的时候，并且使用了识别纠错功能，机器人可以有效识别出第一季，但是第一季之后的都无法识别，我尝试了一个子目录一个的去识别并且TMDB的链接也换成了第二季的链接但是还是无法成功，好像机器人只能在TMDB上识别第一季的内容。

### 健康检查

![image](https://user-images.githubusercontent.com/101039599/180736305-72ee2bbf-fbf7-466f-9cb6-07885daf586c.png)

**Comment by zzj6666** [comment]
![image](https://user-images.githubusercontent.com/101039599/180746508-d6e2bfa5-d30a-41be-a190-f84124e2e182.png)
通过unkonw方式硬链接过去后，在点订阅，无法订阅了，说更新完了

**Comment by pofey** [comment]
这是tmdb的数据问题吧，tmdb数据是什么样

**Comment by zzj6666** [comment]
> 这是tmdb的数据问题吧，tmdb数据是什么样

![image](https://user-images.githubusercontent.com/101039599/180908150-94fa5b3d-35aa-405b-aed3-b93651320a55.png)
![image](https://user-images.githubusercontent.com/101039599/180908171-3442ec31-84dc-447c-a6bc-7076d4f72338.png)
https://www.themoviedb.org/tv/37854
这个海贼王的TMDB的链接

**Comment by pofey** [comment]
id都是一样的 我看看你媒体库目录配置 硬链接到海贼王这个目录的类型是剧集还是电影

**Comment by zzj6666** [comment]
> id都是一样的 我看看你媒体库目录配置 硬链接到海贼王这个目录的类型是剧集还是电影

![image](https://user-images.githubusercontent.com/101039599/180921448-fc06c203-8585-43d0-8517-5f77c76123a7.png)
是选的剧集

**Comment by pofey** [comment]
那这个动漫可能就还是不识别吧

**Comment by zzj6666** [comment]
> 那这个动漫可能就还是不识别吧

可以识别，但是只能识别出第一季的内容，现在这部动漫还没更新完，我也没办法继续订阅，一订阅就说影视库存在，不再订阅

**Comment by pofey** [comment]
> > 那这个动漫可能就还是不识别吧
> 
> 可以识别，但是只能识别出第一季的内容，现在这部动漫还没更新完，我也没办法继续订阅，一订阅就说影视库存在，不再订阅

这个动漫太特殊 好像群里有些人是靠自定义关键字订阅的，1.0之前我不打算改程序去专门优化这个动漫的识别问题
