### ISSUE TITLE
[缺陷]: 试用激活码到期 后台不停新建py进程 达到设备内存瓶颈

### ISSUE THREAD

**Issue by EndlessJY** [pofey/movie_robot#528]
### 当前程序版本

0.9.99.0723

### 问题描述

Ubuntu X64 激活码到期后重启服务  后台不停新建py进程(或许是 站点并发线程数+1 ？)，达到内存瓶颈，导致服务器失联
<img width="981" alt="image" src="https://user-images.githubusercontent.com/33413681/180817191-03ca23ea-b4bf-4806-b52e-447bb24851aa.png">

### 重现步骤

1.激活码到期
2.重启docker

### 发生问题时系统日志

2022/07/25 23:31:11 - MainThread - INFO: 站点并发线程数：1
 2022/07/25 23:31:11 - MainThread - INFO: 已开启企业微信接收消息配置
 2022/07/25 23:31:11 - MainThread - INFO: Plex连接正常，欢迎回来：xxxx
 2022/07/25 23:31:11 - MainThread - INFO: 新增任务：PT站点登陆有效性检查及分享数据更新任务
 2022/07/25 23:31:11 - MainThread - INFO: 新增任务：免费下载种子监测任务
 2022/07/25 23:31:11 - MainThread - INFO: 新增任务：站点资源同步任务
 2022/07/25 23:31:11 - MainThread - INFO: 新增任务：同步豆瓣想看到订阅列表
 2022/07/25 23:31:11 - MainThread - INFO: 新增任务：自定义任务调度
 2022/07/25 23:31:11 - MainThread - INFO: 开启监控下载器手动种子任务。
 2022/07/25 23:31:11 - MainThread - INFO: 开始监控保存目录为/home/Move/Film的所有下载任务
 2022/07/25 23:31:11 - MainThread - INFO: 开始监控保存目录为/home/Move/TV的所有下载任务
 2022/07/25 23:31:11 - MainThread - INFO: 开始监控保存目录为/home/Move/Ainme Film的所有下载任务
 2022/07/25 23:31:11 - MainThread - INFO: 开始监控保存目录为/home/Move/Ainme TV的所有下载任务
 2022/07/25 23:31:11 - MainThread - INFO: 开始监控保存目录为/home/Move/Chinese Film的所有下载任务
 2022/07/25 23:31:11 - MainThread - INFO: 开始监控保存目录为/home/Move/Chinese TV的所有下载任务
 2022/07/25 23:31:11 - MainThread - INFO: 开始监控保存目录为/home/Move/JP&KR Film的所有下载任务
 2022/07/25 23:31:11 - MainThread - INFO: 开始监控保存目录为/home/Move/JP&KR TV的所有下载任务
 2022/07/25 23:31:11 - MainThread - INFO: 开始监控保存目录为/home/Move/US&EU Film的所有下载任务
 2022/07/25 23:31:11 - MainThread - INFO: 开始监控保存目录为/home/Move/US&EU TV的所有下载任务
 2022/07/25 23:31:11 - MainThread - INFO: 开始监控保存目录为/home/Move/Other Film的所有下载任务
 2022/07/25 23:31:11 - MainThread - INFO: 开始监控保存目录为/home/Move/Other TV的所有下载任务
 2022/07/25 23:31:11 - MainThread - INFO: 新增任务：监听下载客户端下载状态
 2022/07/25 23:31:11 - MainThread - INFO: 新增任务：订阅元数据检查更新任务
 2022/07/25 23:31:11 - MainThread - INFO: 新增任务：健康检查任务
 2022/07/25 23:31:11 - MainThread - INFO: Plex连接正常，欢迎回来：xxxxx
 2022/07/25 23:31:11 - MainThread - INFO: 已经启动字幕下载处理任务。
 2022/07/25 23:31:11 - MainThread - INFO: 当前版本: 0.9.99.0723
 2022/07/25 23:31:11 - MainThread - ERROR: 验证失败，激活码已经过期！
 2022/07/25 23:31:17 - MainThread - INFO: 站点并发线程数：1
 2022/07/25 23:31:17 - MainThread - INFO: 已开启企业微信接收消息配置
 2022/07/25 23:31:17 - MainThread - INFO: Plex连接正常，欢迎回来：xxxxx
 2022/07/25 23:31:17 - MainThread - INFO: 新增任务：PT站点登陆有效性检查及分享数据更新任务
 2022/07/25 23:31:17 - MainThread - INFO: 新增任务：免费下载种子监测任务
 2022/07/25 23:31:17 - MainThread - INFO: 新增任务：站点资源同步任务
 2022/07/25 23:31:17 - MainThread - INFO: 新增任务：同步豆瓣想看到订阅列表
 2022/07/25 23:31:17 - MainThread - INFO: 新增任务：自定义任务调度
 2022/07/25 23:31:17 - MainThread - INFO: 开启监控下载器手动种子任务。
 2022/07/25 23:31:17 - MainThread - INFO: 开始监控保存目录为/home/Move/Film的所有下载任务
 2022/07/25 23:31:17 - MainThread - INFO: 开始监控保存目录为/home/Move/TV的所有下载任务
 2022/07/25 23:31:17 - MainThread - INFO: 开始监控保存目录为/home/Move/Ainme Film的所有下载任务
 2022/07/25 23:31:17 - MainThread - INFO: 开始监控保存目录为/home/Move/Ainme TV的所有下载任务
 2022/07/25 23:31:17 - MainThread - INFO: 开始监控保存目录为/home/Move/Chinese Film的所有下载任务
 2022/07/25 23:31:17 - MainThread - INFO: 开始监控保存目录为/home/Move/Chinese TV的所有下载任务
 2022/07/25 23:31:17 - MainThread - INFO: 开始监控保存目录为/home/Move/JP&KR Film的所有下载任务
 2022/07/25 23:31:17 - MainThread - INFO: 开始监控保存目录为/home/Move/JP&KR TV的所有下载任务
 2022/07/25 23:31:17 - MainThread - INFO: 开始监控保存目录为/home/Move/US&EU Film的所有下载任务
 2022/07/25 23:31:17 - MainThread - INFO: 开始监控保存目录为/home/Move/US&EU TV的所有下载任务
 2022/07/25 23:31:17 - MainThread - INFO: 开始监控保存目录为/home/Move/Other Film的所有下载任务
 2022/07/25 23:31:17 - MainThread - INFO: 开始监控保存目录为/home/Move/Other TV的所有下载任务
 2022/07/25 23:31:17 - MainThread - INFO: 新增任务：监听下载客户端下载状态
 2022/07/25 23:31:17 - MainThread - INFO: 新增任务：订阅元数据检查更新任务
 2022/07/25 23:31:17 - MainThread - INFO: 新增任务：健康检查任务
 2022/07/25 23:31:17 - MainThread - INFO: Plex连接正常，欢迎回来：xxxxx
 2022/07/25 23:31:17 - MainThread - INFO: 已经启动字幕下载处理任务。
 2022/07/25 23:31:17 - MainThread - INFO: 当前版本: 0.9.99.0723
 2022/07/25 23:31:18 - MainThread - ERROR: 验证失败，激活码已经过期！
 2022/07/25 23:31:23 - MainThread - INFO: 站点并发线程数：1
 2022/07/25 23:31:23 - MainThread - INFO: 已开启企业微信接收消息配置
 2022/07/25 23:31:23 - MainThread - INFO: Plex连接正常，欢迎回来：xxxxx
 2022/07/25 23:31:23 - MainThread - INFO: 新增任务：PT站点登陆有效性检查及分享数据更新任务
 2022/07/25 23:31:23 - MainThread - INFO: 新增任务：免费下载种子监测任务
 2022/07/25 23:31:23 - MainThread - INFO: 新增任务：站点资源同步任务
 2022/07/25 23:31:23 - MainThread - INFO: 新增任务：同步豆瓣想看到订阅列表
 2022/07/25 23:31:23 - MainThread - INFO: 新增任务：自定义任务调度
 2022/07/25 23:31:23 - MainThread - INFO: 开启监控下载器手动种子任务。
 2022/07/25 23:31:23 - MainThread - INFO: 开始监控保存目录为/home/Move/Film的所有下载任务
 2022/07/25 23:31:23 - MainThread - INFO: 开始监控保存目录为/home/Move/TV的所有下载任务
 2022/07/25 23:31:23 - MainThread - INFO: 开始监控保存目录为/home/Move/Ainme Film的所有下载任务
 2022/07/25 23:31:23 - MainThread - INFO: 开始监控保存目录为/home/Move/Ainme TV的所有下载任务
 2022/07/25 23:31:23 - MainThread - INFO: 开始监控保存目录为/home/Move/Chinese Film的所有下载任务
 2022/07/25 23:31:23 - MainThread - INFO: 开始监控保存目录为/home/Move/Chinese TV的所有下载任务
 2022/07/25 23:31:23 - MainThread - INFO: 开始监控保存目录为/home/Move/JP&KR Film的所有下载任务
 2022/07/25 23:31:23 - MainThread - INFO: 开始监控保存目录为/home/Move/JP&KR TV的所有下载任务
 2022/07/25 23:31:23 - MainThread - INFO: 开始监控保存目录为/home/Move/US&EU Film的所有下载任务
 2022/07/25 23:31:23 - MainThread - INFO: 开始监控保存目录为/home/Move/US&EU TV的所有下载任务
 2022/07/25 23:31:23 - MainThread - INFO: 开始监控保存目录为/home/Move/Other Film的所有下载任务
 2022/07/25 23:31:23 - MainThread - INFO: 开始监控保存目录为/home/Move/Other TV的所有下载任务
 2022/07/25 23:31:23 - MainThread - INFO: 新增任务：监听下载客户端下载状态
 2022/07/25 23:31:23 - MainThread - INFO: 新增任务：订阅元数据检查更新任务
 2022/07/25 23:31:23 - MainThread - INFO: 新增任务：健康检查任务
 2022/07/25 23:31:23 - MainThread - INFO: Plex连接正常，欢迎回来：xxxxx
 2022/07/25 23:31:23 - MainThread - INFO: 已经启动字幕下载处理任务。
 2022/07/25 23:31:23 - MainThread - INFO: 当前版本: 0.9.99.0723
 2022/07/25 23:31:24 - MainThread - ERROR: 验证失败，激活码已经过期！
 2022/07/25 23:31:29 - MainThread - INFO: 站点并发线程数：1
 2022/07/25 23:31:29 - MainThread - INFO: 已开启企业微信接收消息配置
 2022/07/25 23:31:29 - MainThread - INFO: Plex连接正常，欢迎回来：xxxxx
 2022/07/25 23:31:29 - MainThread - INFO: 新增任务：PT站点登陆有效性检查及分享数据更新任务
 2022/07/25 23:31:29 - MainThread - INFO: 新增任务：免费下载种子监测任务
 2022/07/25 23:31:29 - MainThread - INFO: 新增任务：站点资源同步任务
 2022/07/25 23:31:29 - MainThread - INFO: 新增任务：同步豆瓣想看到订阅列表
 2022/07/25 23:31:29 - MainThread - INFO: 新增任务：自定义任务调度
 2022/07/25 23:31:29 - MainThread - INFO: 开启监控下载器手动种子任务。
 2022/07/25 23:31:29 - MainThread - INFO: 开始监控保存目录为/home/Move/Film的所有下载任务
 2022/07/25 23:31:29 - MainThread - INFO: 开始监控保存目录为/home/Move/TV的所有下载任务
 2022/07/25 23:31:29 - MainThread - INFO: 开始监控保存目录为/home/Move/Ainme Film的所有下载任务
 2022/07/25 23:31:29 - MainThread - INFO: 开始监控保存目录为/home/Move/Ainme TV的所有下载任务
 2022/07/25 23:31:29 - MainThread - INFO: 开始监控保存目录为/home/Move/Chinese Film的所有下载任务
 2022/07/25 23:31:29 - MainThread - INFO: 开始监控保存目录为/home/Move/Chinese TV的所有下载任务
 2022/07/25 23:31:29 - MainThread - INFO: 开始监控保存目录为/home/Move/JP&KR Film的所有下载任务
 2022/07/25 23:31:29 - MainThread - INFO: 开始监控保存目录为/home/Move/JP&KR TV的所有下载任务
 2022/07/25 23:31:29 - MainThread - INFO: 开始监控保存目录为/home/Move/US&EU Film的所有下载任务
 2022/07/25 23:31:29 - MainThread - INFO: 开始监控保存目录为/home/Move/US&EU TV的所有下载任务
 2022/07/25 23:31:29 - MainThread - INFO: 开始监控保存目录为/home/Move/Other Film的所有下载任务
 2022/07/25 23:31:29 - MainThread - INFO: 开始监控保存目录为/home/Move/Other TV的所有下载任务
 2022/07/25 23:31:29 - MainThread - INFO: 新增任务：监听下载客户端下载状态
 2022/07/25 23:31:29 - MainThread - INFO: 新增任务：订阅元数据检查更新任务
 2022/07/25 23:31:29 - MainThread - INFO: 新增任务：健康检查任务
 2022/07/25 23:31:29 - MainThread - INFO: Plex连接正常，欢迎回来：xxxxx
 2022/07/25 23:31:29 - MainThread - INFO: 已经启动字幕下载处理任务。
 2022/07/25 23:31:29 - MainThread - INFO: 当前版本: 0.9.99.0723
 2022/07/25 23:31:30 - MainThread - ERROR: 验证失败，激活码已经过期！
 2022/07/25 23:31:35 - MainThread - INFO: 站点并发线程数：1
 2022/07/25 23:31:35 - MainThread - INFO: 已开启企业微信接收消息配置
 2022/07/25 23:31:35 - MainThread - INFO: Plex连接正常，欢迎回来：xxxxx
 2022/07/25 23:31:35 - MainThread - INFO: 新增任务：PT站点登陆有效性检查及分享数据更新任务
 2022/07/25 23:31:36 - MainThread - INFO: 新增任务：免费下载种子监测任务
 2022/07/25 23:31:36 - MainThread - INFO: 新增任务：站点资源同步任务
 2022/07/25 23:31:36 - MainThread - INFO: 新增任务：同步豆瓣想看到订阅列表
 2022/07/25 23:31:36 - MainThread - INFO: 新增任务：自定义任务调度
 2022/07/25 23:31:36 - MainThread - INFO: 开启监控下载器手动种子任务。
 2022/07/25 23:31:36 - MainThread - INFO: 开始监控保存目录为/home/Move/Film的所有下载任务
 2022/07/25 23:31:36 - MainThread - INFO: 开始监控保存目录为/home/Move/TV的所有下载任务
 2022/07/25 23:31:36 - MainThread - INFO: 开始监控保存目录为/home/Move/Ainme Film的所有下载任务
 2022/07/25 23:31:36 - MainThread - INFO: 开始监控保存目录为/home/Move/Ainme TV的所有下载任务
 2022/07/25 23:31:36 - MainThread - INFO: 开始监控保存目录为/home/Move/Chinese Film的所有下载任务
 2022/07/25 23:31:36 - MainThread - INFO: 开始监控保存目录为/home/Move/Chinese TV的所有下载任务
 2022/07/25 23:31:36 - MainThread - INFO: 开始监控保存目录为/home/Move/JP&KR Film的所有下载任务
 2022/07/25 23:31:36 - MainThread - INFO: 开始监控保存目录为/home/Move/JP&KR TV的所有下载任务
 2022/07/25 23:31:36 - MainThread - INFO: 开始监控保存目录为/home/Move/US&EU Film的所有下载任务
 2022/07/25 23:31:36 - MainThread - INFO: 开始监控保存目录为/home/Move/US&EU TV的所有下载任务
 2022/07/25 23:31:36 - MainThread - INFO: 开始监控保存目录为/home/Move/Other Film的所有下载任务
 2022/07/25 23:31:36 - MainThread - INFO: 开始监控保存目录为/home/Move/Other TV的所有下载任务
 2022/07/25 23:31:36 - MainThread - INFO: 新增任务：监听下载客户端下载状态
 2022/07/25 23:31:36 - MainThread - INFO: 新增任务：订阅元数据检查更新任务
 2022/07/25 23:31:36 - MainThread - INFO: 新增任务：健康检查任务
 2022/07/25 23:31:36 - MainThread - INFO: Plex连接正常，欢迎回来：xxxxx
 2022/07/25 23:31:36 - MainThread - INFO: 已经启动字幕下载处理任务。
 2022/07/25 23:31:36 - MainThread - INFO: 当前版本: 0.9.99.0723
 2022/07/25 23:31:36 - MainThread - ERROR: 验证失败，激活码已经过期！
 2022/07/25 23:31:43 - MainThread - INFO: 站点并发线程数：1
 2022/07/25 23:31:43 - MainThread - INFO: 已开启企业微信接收消息配置
 2022/07/25 23:31:43 - MainThread - INFO: Plex连接正常，欢迎回来：xxxxx
 2022/07/25 23:31:43 - MainThread - INFO: 新增任务：PT站点登陆有效性检查及分享数据更新任务
 2022/07/25 23:31:43 - MainThread - INFO: 新增任务：免费下载种子监测任务
 2022/07/25 23:31:43 - MainThread - INFO: 新增任务：站点资源同步任务
 2022/07/25 23:31:43 - MainThread - INFO: 新增任务：同步豆瓣想看到订阅列表
 2022/07/25 23:31:43 - MainThread - INFO: 新增任务：自定义任务调度
 2022/07/25 23:31:43 - MainThread - INFO: 开启监控下载器手动种子任务。
 2022/07/25 23:31:43 - MainThread - INFO: 开始监控保存目录为/home/Move/Film的所有下载任务
 2022/07/25 23:31:43 - MainThread - INFO: 开始监控保存目录为/home/Move/TV的所有下载任务
 2022/07/25 23:31:43 - MainThread - INFO: 开始监控保存目录为/home/Move/Ainme Film的所有下载任务
 2022/07/25 23:31:43 - MainThread - INFO: 开始监控保存目录为/home/Move/Ainme TV的所有下载任务
 2022/07/25 23:31:43 - MainThread - INFO: 开始监控保存目录为/home/Move/Chinese Film的所有下载任务
 2022/07/25 23:31:43 - MainThread - INFO: 开始监控保存目录为/home/Move/Chinese TV的所有下载任务
 2022/07/25 23:31:43 - MainThread - INFO: 开始监控保存目录为/home/Move/JP&KR Film的所有下载任务
 2022/07/25 23:31:43 - MainThread - INFO: 开始监控保存目录为/home/Move/JP&KR TV的所有下载任务
 2022/07/25 23:31:43 - MainThread - INFO: 开始监控保存目录为/home/Move/US&EU Film的所有下载任务
 2022/07/25 23:31:43 - MainThread - INFO: 开始监控保存目录为/home/Move/US&EU TV的所有下载任务
 2022/07/25 23:31:43 - MainThread - INFO: 开始监控保存目录为/home/Move/Other Film的所有下载任务
 2022/07/25 23:31:43 - MainThread - INFO: 开始监控保存目录为/home/Move/Other TV的所有下载任务
 2022/07/25 23:31:43 - MainThread - INFO: 新增任务：监听下载客户端下载状态
 2022/07/25 23:31:43 - MainThread - INFO: 新增任务：订阅元数据检查更新任务
 2022/07/25 23:31:44 - MainThread - INFO: 新增任务：健康检查任务
 2022/07/25 23:31:44 - MainThread - INFO: Plex连接正常，欢迎回来：xxxxx
 2022/07/25 23:31:44 - MainThread - INFO: 已经启动字幕下载处理任务。
 2022/07/25 23:31:44 - MainThread - INFO: 当前版本: 0.9.99.0723
 2022/07/25 23:31:44 - MainThread - ERROR: 验证失败，激活码已经过期！
 2022/07/25 23:31:50 - MainThread - INFO: 站点并发线程数：1
 2022/07/25 23:31:50 - MainThread - INFO: 已开启企业微信接收消息配置
 2022/07/25 23:31:50 - MainThread - INFO: Plex连接正常，欢迎回来：xxxxxx
 2022/07/25 23:31:51 - MainThread - INFO: 新增任务：PT站点登陆有效性检查及分享数据更新任务
 2022/07/25 23:31:51 - MainThread - INFO: 新增任务：免费下载种子监测任务
 2022/07/25 23:31:51 - MainThread - INFO: 新增任务：站点资源同步任务
 2022/07/25 23:31:51 - MainThread - INFO: 新增任务：同步豆瓣想看到订阅列表
 2022/07/25 23:31:51 - MainThread - INFO: 新增任务：自定义任务调度
 2022/07/25 23:31:51 - MainThread - INFO: 开启监控下载器手动种子任务。
 2022/07/25 23:31:51 - MainThread - INFO: 开始监控保存目录为/home/Move/Film的所有下载任务
 2022/07/25 23:31:51 - MainThread - INFO: 开始监控保存目录为/home/Move/TV的所有下载任务
 2022/07/25 23:31:51 - MainThread - INFO: 开始监控保存目录为/home/Move/Ainme Film的所有下载任务
 2022/07/25 23:31:51 - MainThread - INFO: 开始监控保存目录为/home/Move/Ainme TV的所有下载任务
 2022/07/25 23:31:51 - MainThread - INFO: 开始监控保存目录为/home/Move/Chinese Film的所有下载任务
 2022/07/25 23:31:51 - MainThread - INFO: 开始监控保存目录为/home/Move/Chinese TV的所有下载任务
 2022/07/25 23:31:51 - MainThread - INFO: 开始监控保存目录为/home/Move/JP&KR Film的所有下载任务
 2022/07/25 23:31:51 - MainThread - INFO: 开始监控保存目录为/home/Move/JP&KR TV的所有下载任务
 2022/07/25 23:31:51 - MainThread - INFO: 开始监控保存目录为/home/Move/US&EU Film的所有下载任务
 2022/07/25 23:31:51 - MainThread - INFO: 开始监控保存目录为/home/Move/US&EU TV的所有下载任务
 2022/07/25 23:31:51 - MainThread - INFO: 开始监控保存目录为/home/Move/Other Film的所有下载任务
 2022/07/25 23:31:51 - MainThread - INFO: 开始监控保存目录为/home/Move/Other TV的所有下载任务
 2022/07/25 23:31:51 - MainThread - INFO: 新增任务：监听下载客户端下载状态
 2022/07/25 23:31:51 - MainThread - INFO: 新增任务：订阅元数据检查更新任务
 2022/07/25 23:31:51 - MainThread - INFO: 新增任务：健康检查任务
 2022/07/25 23:31:51 - MainThread - INFO: Plex连接正常，欢迎回来：xxxxx
 2022/07/25 23:31:51 - MainThread - INFO: 已经启动字幕下载处理任务。
 2022/07/25 23:31:51 - MainThread - INFO: 当前版本: 0.9.99.0723
 2022/07/25 23:31:51 - MainThread - ERROR: 验证失败，激活码已经过期！
 2022/07/25 23:31:57 - MainThread - INFO: 站点并发线程数：1
 2022/07/25 23:31:57 - MainThread - INFO: 已开启企业微信接收消息配置
 2022/07/25 23:31:57 - MainThread - INFO: Plex连接正常，欢迎回来：xxxxx
 2022/07/25 23:31:57 - MainThread - INFO: 新增任务：PT站点登陆有效性检查及分享数据更新任务

### 健康检查

无法进入系统

**Comment by pofey** [comment]
下一版改成了直接杀守护进程
