### ISSUE TITLE
[需求]: 本地资源整理-点击选择媒体路径中不支持带.的隐藏文件夹

### ISSUE THREAD

**Issue by suwill** [pofey/movie_robot#530]
### 当前程序版本

Version: 0.9.99.0723

### 问题描述

<img width="333" alt="微信截图_20220726132813" src="https://user-images.githubusercontent.com/14219945/180930214-f2413ee9-92f4-4015-a927-78f340b55130.png">

由于本人还有局域网smb共享播放之需要，故使用了.m和.t存放qb下载器下载完成后的混乱资源，使用movie和tv存放经过MR整理过之后的资源，这样在TV上只显示movie和tv两个文件夹（试过unraid使用不同share名会导致硬链CrossDevice失败）

现在存量影片只能通过MR容器运行命令整理，请在web端给个“是否显示隐藏文件”的选项，感激不尽。
<img width="964" alt="微信截图_20220726131940" src="https://user-images.githubusercontent.com/14219945/180929709-f568596c-ea87-4bf2-925c-7eb11c12e81a.png">

### 重现步骤

1，进入容器内部
2，cd进资源目录
3，mkdir -p .test
4，开web看下，选不到那个带点的文件夹

### 发生问题时系统日志

```shell
好似不需要
```

### 健康检查

<img width="823" alt="微信截图_20220726132652" src="https://user-images.githubusercontent.com/14219945/180930074-43160089-491a-4b03-9e46-8f319beb2b6c.png">

选择不到资源目录，TMDB能否访问不重要..还没到那一步

**Comment by pofey** [comment]
这不是什么缺陷，过滤隐藏文件符合现在的逻辑，不过滤造成的后果也无法评估
