### ISSUE TITLE
[提问]: 关于流量管理-最大活跃刷流种子数的疑问

### ISSUE THREAD

**Issue by WWWWM03** [pofey/movie_robot#531]
### 当前程序版本

0.9.99.0725

### 问题

衣总您好，我在MR**流量管理**里把**最大活跃刷流种子数**设置成了**2**，但是qb依然持续进行免费种子的抓取，目前已经同时存在了15个任务，其中有10个下载任务。日志显示**最大活跃刷流种子数**一直为0，想请教下这个功能按照目前我的这个设置，是说刷流任务最大同时存在两个下载任务进行刷流直到被淘汰对嘛。感谢！

![1658842143861](https://user-images.githubusercontent.com/74545085/181017759-0b68f9cf-979d-403b-8334-c2b25e318b7c.png)
**fig1.qb任务界面**

![1658842190306](https://user-images.githubusercontent.com/74545085/181017945-b4b5e456-c016-412a-aba9-f421325a55de.png)
**fig2.log**

### 发生问题时系统日志
 2022/07/26 20:01:09 - ThreadPoolExecutor-5_1 - INFO: 馒头最新种子同步完成。
 2022/07/26 20:01:20 - ThreadPoolExecutor-5_1 - INFO: 马杀鸡最新种子同步完成。
 2022/07/26 20:01:43 - ThreadPoolExecutor-5_1 - INFO: 瓷器最新种子同步完成。
 2022/07/26 20:01:54 - ThreadPoolExecutor-5_1 - INFO: 红豆饭最新种子同步完成。
 2022/07/26 20:01:54 - ThreadPoolExecutor-5_1 - INFO: 所有站点资源信息已经更新完毕。
 2022/07/26 20:02:02 - SubConsumer - INFO: 山海情(2021) 经过系统分析后，没有搜到有效结果。
 2022/07/26 20:02:28 - ThreadPoolExecutor-5_1 - INFO: 当前在下载中刷流任务0个，上限2个
 2022/07/26 20:02:28 - ThreadPoolExecutor-5_1 - INFO: 开始筛选免费种子，未筛选前共283个。
 2022/07/26 20:02:28 - ThreadPoolExecutor-5_1 - INFO: 经过筛选后没有需要下载的免费任务。
 2022/07/26 20:10:01 - ThreadPoolExecutor-0_2 - INFO: Emby连接正常，Emby版本为4.7.5.0
 2022/07/26 20:18:56 - ThreadPoolExecutor-5_4 - INFO: 开始同步站点资源信息...
 2022/07/26 20:19:42 - ThreadPoolExecutor-5_4 - INFO: 高清杜比最新种子同步完成。
 2022/07/26 20:20:00 - ThreadPoolExecutor-0_2 - INFO: Emby连接正常，Emby版本为4.7.5.0
 2022/07/26 20:20:14 - ThreadPoolExecutor-5_4 - INFO: 高清视界最新种子同步完成。
 2022/07/26 20:20:29 - ThreadPoolExecutor-5_4 - INFO: 阿童木最新种子同步完成。
 2022/07/26 20:21:55 - ThreadPoolExecutor-5_4 - INFO: 馒头最新种子同步完成。
 2022/07/26 20:22:09 - ThreadPoolExecutor-5_4 - INFO: 马杀鸡最新种子同步完成。
 2022/07/26 20:22:35 - ThreadPoolExecutor-5_4 - INFO: 瓷器最新种子同步完成。
 2022/07/26 20:22:52 - ThreadPoolExecutor-5_4 - INFO: 红豆饭最新种子同步完成。
 2022/07/26 20:22:52 - ThreadPoolExecutor-5_4 - INFO: 所有站点资源信息已经更新完毕。
 2022/07/26 20:23:00 - SubConsumer - INFO: 山海情(2021) 经过系统分析后，没有搜到有效结果。
 2022/07/26 20:23:34 - ThreadPoolExecutor-5_4 - INFO: 当前在下载中刷流任务0个，上限2个
 2022/07/26 20:23:34 - ThreadPoolExecutor-5_4 - INFO: 开始筛选免费种子，未筛选前共283个。
 2022/07/26 20:23:34 - ThreadPoolExecutor-5_4 - INFO: 经过筛选后，还剩1个种子，按上传质量打分排序后提交上传，还可以再提交2个种子到下载器。
 2022/07/26 20:23:34 - ThreadPoolExecutor-5_4 - INFO: 有1个免费种子需要下载，开始提交到下载器。
 2022/07/26 20:23:34 - ThreadPoolExecutor-5_4 - INFO: 免费种子提交下载队列完成，本轮共提交1个免费种子
 2022/07/26 20:23:34 - hdchina-downloader - INFO: 开始处理免费种子下载任务: [hdchina]2022.Tour.de.France.1080p.WEB-DL.AAC2.0.H.264-FINFUNGUS

**Comment by pofey** [comment]
挑一个种子看下保存路径，保存路径是否和你配置的刷流提交路径一致

**Comment by WWWWM03** [comment]
是一致的，并且在本地文件夹中也能找到相对应的目录。

![1658846473036](https://user-images.githubusercontent.com/74545085/181036279-23a7da93-b571-4840-b233-90600e0c8341.png)


![1658846464683](https://user-images.githubusercontent.com/74545085/181036306-9833d0c4-7666-4bab-8acc-3b045a62adf1.png)

**Comment by pofey** [comment]
> 是一致的，并且在本地文件夹中也能找到相对应的目录。
> 
> ![1658846473036](https://user-images.githubusercontent.com/74545085/181036279-23a7da93-b571-4840-b233-90600e0c8341.png)
> 
> ![1658846464683](https://user-images.githubusercontent.com/74545085/181036306-9833d0c4-7666-4bab-8acc-3b045a62adf1.png)

在你的配置目录尾巴加一个/吧 这个算一个bug吧，后面优化下，现在比较过于严格了

**Comment by WWWWM03** [comment]
果然是这个问题，谢谢衣总解答~

**Comment by pofey** [comment]
已经修复了，下一版本好
