### ISSUE TITLE
[缺陷]: 瓷器 天才基本法不更新

### ISSUE THREAD

**Issue by vctory-xia** [pofey/movie_robot#534]
### 当前程序版本

0.9.99.0725

### 问题描述

和这个问题类似https://github.com/pofey/movie_robot/issues/487
仅设置过滤器为从瓷器下载，无结果。
日志显示的是有搜索结果，但经过你设定的过滤器后，无任何结果。

### 重现步骤

删除订阅后重新添加订阅，过滤器只添加瓷器如下图
![QQ截图20220727212744](https://user-images.githubusercontent.com/67232053/181260222-afdc3e26-6177-465a-b098-6da779d5c627.png)
![QQ截图20220727212803](https://user-images.githubusercontent.com/67232053/181260168-6f2360f5-16ce-4af7-9e9b-c0ab7283ec19.png)
但实际上是更新了的瓷器，搜索也能搜到
![QQ截图20220727213554](https://user-images.githubusercontent.com/67232053/181260571-a5055069-c83c-4f89-8298-fd29be999a33.png)
plex也是正常的
![QQ截图20220727214118](https://user-images.githubusercontent.com/67232053/181261839-03f54b04-f8b7-4b3a-9db3-cfdebf526107.png)

### 发生问题时系统日志

```shell
2022/07/27 21:21:17 - SubRequestConsumer - INFO: 天才基本法(2022)$ 设置了独立的过滤规则，可以在我的订阅中查看和修改。
 2022/07/27 21:21:17 - SubRequestConsumer - INFO: 新增来自的订阅: 天才基本法(2022) 设置了独立的过滤规则，可以在我的订阅中查看和修改。
 2022/07/27 21:21:17 - SubConsumer - INFO: 已经开始在站点: 瓷器,朋友,不可说,猫站,天空,观众,柠檬 搜索: 天才基本法,The Heart of Genius,tt14792320
 2022/07/27 21:21:36 - SubConsumer - INFO: 共在7个站点搜索到44条结果，其中猫站最慢，耗费18.27秒
 2022/07/27 21:21:36 - SubConsumer - INFO: 天才基本法(2022) 已经有搜索结果，但经过你设定的过滤器后，无任何结果。
 2022/07/27 21:30:00 - ThreadPoolExecutor-4_0 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
 2022/07/27 21:30:29 - ThreadPoolExecutor-4_1 - INFO: 开始同步站点资源信息...
 2022/07/27 21:30:48 - ThreadPoolExecutor-4_1 - INFO: 瓷器最新种子同步完成。
 2022/07/27 21:30:52 - ThreadPoolExecutor-4_1 - INFO: 朋友最新种子同步完成。
 2022/07/27 21:30:58 - ThreadPoolExecutor-4_1 - INFO: 不可说最新种子同步完成。
 2022/07/27 21:31:05 - ThreadPoolExecutor-4_1 - INFO: 猫站最新种子同步完成。
 2022/07/27 21:31:12 - ThreadPoolExecutor-4_1 - INFO: 天空最新种子同步完成。
 2022/07/27 21:31:18 - ThreadPoolExecutor-4_1 - INFO: 观众最新种子同步完成。
 2022/07/27 21:31:24 - ThreadPoolExecutor-4_1 - INFO: 柠檬最新种子同步完成。
 2022/07/27 21:31:24 - ThreadPoolExecutor-4_1 - INFO: 所有站点资源信息已经更新完毕。
 2022/07/27 21:31:24 - ThreadPoolExecutor-4_1 - INFO: 没有配置或开启流量管理设置，不会开始运行：{'avg_statistics_period': 5, 'enable': False}
 2022/07/27 21:31:26 - SubConsumer - INFO: 天才基本法(2022) 已经有搜索结果，但经过你设定的过滤器后，无任何结果。
```

### 健康检查

![QQ截图20220727213800](https://user-images.githubusercontent.com/67232053/181260956-e27c68b6-8bfd-45d5-9ccd-2cafe454a0e4.png)

**Comment by pofey** [comment]
#532 跟这个是同一个问题，我一起回复，那个先提，我标重复了
