### ISSUE TITLE
[缺陷]: 字幕下载完成后不能正常地触发元数据刷新

### ISSUE THREAD

**Issue by kolicime** [pofey/movie_robot#535]
### 当前程序版本

0.9.99.0725

### 问题描述

相同的问题在之前也有人提过：#149
在字幕下载任务完成后，plex库中看不到字幕，在日志中看到说是已经通知了plex进行元数据刷新，但在plex的日志中，只有扫描库的操作是正常执行了，并没有进行元数据刷新。plex日志截图和正常元数据刷新的图示如下。
![](https://img.u8.pw/2022/07/27/f5605328dad8e.png)
![](https://img.u8.pw/2022/07/27/7924548b55d6d.png)
plex中还是没有字幕
![](https://img.u8.pw/2022/07/27/7400fd025c650.png)
plex正常刷新元数据的日志
![](https://img.u8.pw/2022/07/27/5c0c87c379377.png)
手动刷新元数据之后字幕可以显示
![](https://img.u8.pw/2022/07/27/cac10059b0799.png)

### 重现步骤

正常搜索影片，手动下载字幕。

### 发生问题时系统日志

```shell
2022/07/27 22:16:47 - Thread-998 - INFO: 月球陨落(2022)字幕下载 任务已经创建。
2022/07/27 22:18:00 - ThreadPoolExecutor-5_2 - INFO: 月球陨落(2022)字幕下载已经提交启动。
2022/07/27 22:19:04 - MainThread - INFO: this log will be written to /data/logs/ffsubsync.log
2022/07/27 22:19:04 - MainThread - INFO: extracting speech segments from reference '/plex/temp/电影-mr/月球陨落 (2022) [tmdbid=406759]/月球陨落 (2022) [tmdbid=406759] - 1080p DDP5.1.mkv'...
2022/07/27 22:19:04 - MainThread - INFO: Checking video for subtitles stream...
2022/07/27 22:19:05 - MainThread - INFO: Video file appears to lack subtitle stream
100%|██████████| 7816.928/7816.928 [01:27<00:00, 89.48it/s] 
2022/07/27 22:20:32 - MainThread - INFO: ...done
2022/07/27 22:20:32 - MainThread - INFO: extracting speech segments from subtitles file(s) ['/data/subtitle/[zmk.pw]月球陨落（校对版）.srt']...
2022/07/27 22:20:32 - MainThread - INFO: detected encoding: UTF-8-SIG
2022/07/27 22:20:33 - MainThread - INFO: computing alignments...
2022/07/27 22:20:36 - MainThread - INFO: ...done
2022/07/27 22:20:36 - MainThread - INFO: score: 61290.000
2022/07/27 22:20:36 - MainThread - INFO: offset seconds: 0.020
2022/07/27 22:20:36 - MainThread - INFO: framerate scale factor: 1.000
2022/07/27 22:20:36 - MainThread - INFO: writing output to /plex/temp/电影-mr/月球陨落 (2022) [tmdbid=406759]/月球陨落 (2022) [tmdbid=406759] - 1080p DDP5.1.zh-cn.default.srt
2022/07/27 22:20:36 - MainThread - INFO: Skipped subtitle at index 496: No content
2022/07/27 22:20:36 - MainThread - INFO: Skipped subtitle at index 499: No content
2022/07/27 22:20:36 - MainThread - INFO: Skipped subtitle at index 501: No content
2022/07/27 22:20:36 - MainThread - INFO: Skipped subtitle at index 503: No content
2022/07/27 22:20:36 - SubRequestConsumer - INFO: 已经通知plex重新扫描媒体库：电影
2022/07/27 22:20:36 - SubRequestConsumer - INFO: 已经通知plex刷新媒体库元数据：电影
2022/07/27 22:20:36 - SubRequestConsumer - INFO: 通知媒体库刷新完成，tmdb_id: 406759 save_path: /plex/temp/电影-mr item_id: 4
2022/07/27 22:20:38 - SubRequestConsumer - INFO: 月球陨落(2022)字幕下载 任务已经结束。
```

### 健康检查

![](https://img.u8.pw/2022/07/27/6ce2cf6d9d10a.png)

**Comment by pofey** [comment]
实际上字幕写到正确的文件夹去了么

**Comment by kolicime** [comment]
> 实际上字幕写到正确的文件夹去了么

有的

**Comment by kolicime** [comment]
> 实际上字幕写到正确的文件夹去了么
看修改时间也是对的上的
![](https://img.u8.pw/2022/07/27/2f21c498d44ab.png)

**Comment by pofey** [comment]
那两个通知日志完成，是调用了plex接口的。你手扫能扫出来么？？

**Comment by kolicime** [comment]
> 那两个通知日志完成，是调用了plex接口的。你手扫能扫出来么？？

手动扫库扫不出字幕，手动刷新元数据之后才能看到

**Comment by kolicime** [comment]
> > > 那两个通知日志完成，是调用了plex接口的。你手扫能扫出来么？？
> > 
> > 
> > 手动扫库扫不出字幕，手动刷新元数据之后才能看到
> 
> 跑完字幕也通知plex刷新了啊

不清楚是不是扫库和刷新同时进行的原因
如果是从plex的接口处得到扫库完成的通知的话，是否可以考虑扫库完成后再进行刷新元数据？从日志来看，目前两个操作可能是同步进行的

**Comment by kolicime** [comment]
> > > > > 那两个通知日志完成，是调用了plex接口的。你手扫能扫出来么？？
> > > > 
> > > > 
> > > > 手动扫库扫不出字幕，手动刷新元数据之后才能看到
> > > 
> > > 
> > > 跑完字幕也通知plex刷新了啊
> > 
> > 
> > 不清楚是不是扫库和刷新同时进行的原因 如果是从plex的接口处得到扫库完成的通知的话，是否可以考虑扫库完成后再进行刷新元数据？从日志来看，目前两个操作可能是同步进行的
> 
> plex那个操作应该是异步进行的 发起后很难得到上一个状态

或许可以考虑下载字幕后仅进行刷新元数据操作？因为实际上扫库这个操作是无效的

**Comment by kolicime** [comment]
> 下一个版本变成 字幕至刷元数据试试吧

实测已经解决
不过顺带提一个可以考虑优化的点。现在的扫库和刷新元数据似乎都是针对整个库的，这样在库比较大的情况下会比较耗时，是否会考虑做单独刷新或者扫描呢？（emby似乎很早之前就已经是局部扫库了）
提供一个或许可以参考的项目：https://github.com/Cloudbox/autoscan

**Comment by kolicime** [comment]
plex的官网似乎没有提供对单个影片刷新元数据的API，但我找到了一个Tautulli开发者提供的API：https://www.reddit.com/r/PleX/comments/pwi9jg/use_api_to_refresh_metadata_for_a_single_artist/

**Comment by pofey** [comment]
> plex的官网似乎没有提供对单个影片刷新元数据的API，但我找到了一个Tautulli开发者提供的API：https://www.reddit.com/r/PleX/comments/pwi9jg/use_api_to_refresh_metadata_for_a_single_artist/

剧集应该就是精准刷单剧的。电影一直以来不管啥媒体服务器，都是刷电影所在库
