### ISSUE TITLE
[优化]: 希望增加discord推送功能

### ISSUE THREAD

**Issue by kvtong93** [pofey/movie_robot#536]
### 当前现状

你好，因为我在海外的，所有的server相关都用discord看推送信息。

### 你的建议

希望能够添加discord推送功能。这样整合在一起能够方便很多谢谢。

### 优先级

一般

### 受众范围

比较小众

**Comment by pofey** [comment]
这有点太小众了，你可以关注等待后续的订阅事件，靠自己订阅结束状态 封装脚本实现推送
