### ISSUE TITLE
提交订阅《少年派2》时订阅错误的影视

### ISSUE THREAD

**Issue by BruceSuen720** [pofey/movie_robot#538]
### 当前程序版本

0.9.99.0729

### 问题描述

提交订阅《少年派2》时会错误的订阅成《少年派的奇幻漂流(2012)》

### 重现步骤

每次提交订阅都是这样的结果

### 发生问题时系统日志

![IMG_20220730_104004](https://user-images.githubusercontent.com/85166199/181867123-2d81b6af-2a3f-4d21-886c-41975c389d5a.jpg)

### 健康检查

![Screenshot_2022-07-30-10-41-23-407_com microsoft emmx](https://user-images.githubusercontent.com/85166199/181867099-19496dbe-e944-453e-9729-9bef0c3e7446.jpg)

**Comment by BruceSuen720** [comment]
微信订阅也是同样的情况

**Comment by pofey** [comment]
<img width="1277" alt="截屏2022-08-02 07 51 24" src="https://user-images.githubusercontent.com/1396975/182263812-237e5eb2-df77-4403-9dc6-28fd1d3022f9.png">
无法复现呢 我订阅正常
