### ISSUE TITLE
硬链接不支持跨盘操作，/download1和/movie-robot不在一个存储区

### ISSUE THREAD

**Issue by seafood678** [pofey/movie_robot#54]
全新安装，nas多盘分布式存储，配置时出现：硬链接不支持跨盘操作，/download1和/movie-robot不在一个存储区。

要映射绝对路径？如果映射绝对路径，那单盘爆满怎么办？

**Comment by pofey** [comment]
理解不了你的问题到底是什么。要么清晰描述需求，要么了解下硬链接原理。
