### ISSUE TITLE
[优化]: 整理时，增加保留原文件名选项

### ISSUE THREAD

**Issue by cyetstar** [pofey/movie_robot#540]
### 当前现状

当前整理时，对原先的文件名会做修改，希望能保留原文件名。

### 你的建议

整理文件格式设置中，内置变量中增加原文件名，或者能够支持视频文件名不做更改

### 优先级

非常高

### 受众范围

一般

**Comment by pofey** [comment]
为什么会有这样的需求？

**Comment by cyetstar** [comment]
> 为什么会有这样的需求？

类似tinymediamanager那样，如果不设置模版，就忽略重命名，从而最大限度的保留视频文件的相关信息。

**Comment by pofey** [comment]
> > 为什么会有这样的需求？
> 
> 类似tinymediamanager那样，如果不设置模版，就忽略重命名，从而最大限度的保留视频文件的相关信息。

保留原名原结构的意义是？

**Comment by cyetstar** [comment]
文件夹按模版设置，而文件名可以保留下载后的文件名，既做到整理又能保留文件信息。如果有补种需求，就比较方便找到原文件。

**Comment by pofey** [comment]
> 文件夹按模版设置，而文件名可以保留下载后的文件名，既做到整理又能保留文件信息。如果有补种需求，就比较方便找到原文件。

你还是没说清楚你的痛点到底是什么

**Comment by cyetstar** [comment]
保留文件名称，即方便补种又减少因为模版引起的信息丢失。
比如：
原文件名：Swan.Song.2021.WebRip.1080p.x265.10bit.EAC3.iNT-TLF.mkv
整理后文件名：天鹅挽歌 (2021) [tmdbid=765245] - 1080p x265.mkv

**Comment by pofey** [comment]
> 保留文件名称，即方便补种又减少因为模版引起的信息丢失。
> 比如：
> 原文件名：Swan.Song.2021.WebRip.1080p.x265.10bit.EAC3.iNT-TLF.mkv
> 整理后文件名：天鹅挽歌 (2021) [tmdbid=765245] - 1080p x265.mkv

梳理下来，你就讲清楚了一个目标，就是所谓“方便补种” 那么问题来了，为什么保留原文件名就方便补种了呢？只有保留文件名一种形式方便补种？
