### ISSUE TITLE
[缺陷]: 健康管理页面多余下载器BUG

### ISSUE THREAD

**Issue by haha6311** [pofey/movie_robot#543]
### 当前程序版本

0.9.99.0729

### 问题描述

前提：MR的**下载工具**只配置了一个QB命名为“下载机”.一个TR命名为“保种机”
某一天突发奇想，QB webUI 改了下登录用户名和密码，没有解除多次登陆失败自动封IP限制，MR忘记修改对应QB的登录密码了 
很长一段时间后发现MR报错 进入WEBUI修改对应信息 但此时MR对应IP已经被封，无法保存更改
重启MR，**下载工具**里QB的按钮消失，大概是这个样子（当时忘截图了）
![image](https://user-images.githubusercontent.com/36618980/181876244-b8d7062e-da17-4447-bb8c-7efdcdad42e4.png)
无奈重新添加之前的QB，命名为“下载机2”，此时健康页面出现了两个下载机（之前消失的，和后建的）
![image](https://user-images.githubusercontent.com/36618980/181876152-9cc86077-1156-4d2c-ad03-dd4189f2adf3.png)
而之前一直无法修改设置的“下载机”又出现了，且只有他一个

现在我想把下载机2删除，但是下载工具里就不显示，几次重启都不行。
所以判定为BUG

### 重现步骤

1.QB webUI 改了下登录用户名和密码，没有解除多次登陆失败自动封IP限制 MR忘记改对应信息了 
2.发现MR报错 进入WEBUI修改对应信息 但此时已经被封，无法保存更改
3.重启MR，**下载工具**里"下载机”按钮消失
4.修改QB封IP限制，重新添加之前的QB，命名为“下载机2”，设置生效
5.此时健康页面出现了两个下载机（“下载机”和“下载机2”）
而**下载工具**里只有一个（“下载机”）

### 发生问题时系统日志

```shell
(各种 监控种子任务出错 * N)
……
qbittorrentapi.exceptions.Forbidden403Error: 身份认证失败次数过多，您的 IP 地址已被封禁。
……
```

### 健康检查

![image](https://user-images.githubusercontent.com/36618980/181876157-78931435-4276-46ad-ba04-e16928a9dca1.png)

**Comment by pofey** [comment]
健康检查的历史数据 过24小时就自动淘汰掉了
