### ISSUE TITLE
[提问]: zimuku.org无法访问

### ISSUE THREAD

**Issue by zzj6666** [pofey/movie_robot#544]
### 当前程序版本

0.9.99.0729

### 问题

上一个月还能自动下载字幕，后来再也没下载成功过，会不会是字幕库网址被屏蔽了，我这是江苏无锡电信，zimuku.org这个地址不挂代理会被江苏反诈拦截，zmk.pw这个网址不挂代理可以正常访问

**Comment by pofey** [comment]
有些地方还封它域名呀

**Comment by zzj6666** [comment]
> 地方还封它域名呀

是的
![image](https://user-images.githubusercontent.com/101039599/182064068-80b91dc6-dcd7-4406-a980-223b11f4bc7d.png)

**Comment by pofey** [comment]
目前还没看到其他人遇到这个问题
