### ISSUE TITLE
[优化]: 希望能够增加基于【原文件名/识别记录】的整理结果筛选功能

### ISSUE THREAD

**Issue by haha6311** [pofey/movie_robot#547]
### 当前现状

![image](https://user-images.githubusercontent.com/36618980/181909265-5c05a9af-66ea-422f-9aef-5e5872a09fd8.png)
在文件夹里有很多电影时，有个别文件提示识别整理完成，但识别结果仍有问题时，比如这种情况。

![image](https://user-images.githubusercontent.com/36618980/181909432-d6eea13a-461d-44b4-8feb-71c065c0eabb.png)

![image](https://user-images.githubusercontent.com/36618980/181909475-2c2bcf80-9ace-4193-8851-7e2b2233f723.png)

要排查这种结果，需要一页一页翻找，很麻烦。

### 你的建议

希望在这个界面添加检索栏，方便快速筛选出列表中需要修正的资源。

![image](https://user-images.githubusercontent.com/36618980/181909572-965f9c2e-315e-431e-b68b-60b9bf70e416.png)

### 优先级

非常高

### 受众范围

很多人需要

**Comment by haha6311** [comment]
另附种子文件链接：
https://avistaz.to/torrent/55957-samurai-kids-1993-directed-by-nobuhiko-obayashi

**Comment by pofey** [comment]
自定义订阅已经到beta了
