### ISSUE TITLE
[优化]: 自动区域分类会多建一级区域文件夹，可以取消影片内区域目录不，只是强迫症哈

### ISSUE THREAD

**Issue by hexiao5688** [pofey/movie_robot#551]
### 当前程序版本

Version: 0.9.99.0729

### 问题描述

![屏幕截图 2022-07-31 184724](https://user-images.githubusercontent.com/74167588/182023123-114513fc-e1fd-4ce9-b66e-cf80c36ff002.jpg)
![屏幕截图 2022-07-31 185640](https://user-images.githubusercontent.com/74167588/182023125-37ad9446-82a5-44dc-b7cd-92c0f79ffdf9.jpg)
![屏幕截图 2022-07-31 185715](https://user-images.githubusercontent.com/74167588/182023127-7c8713b3-7845-4a83-b99d-f349ab4b0bc7.jpg)
![屏幕截图 2022-07-31 184700](https://user-images.githubusercontent.com/74167588/182023656-6f7d7a73-2f22-416d-99bd-fe5f187edc97.jpg)

### 重现步骤

整理存量发现影片内也有区域文件夹，欧美》影片名》欧美》影片，

### 健康检查

UNRAID系统

**Comment by pofey** [comment]
这和你存量整理选择的原目录和目标目录有关系
