### ISSUE TITLE
[缺陷]: 版本更新后无法删除字幕来源SUBHD选项

### ISSUE THREAD

**Issue by Zayia** [pofey/movie_robot#553]
### 当前程序版本

0.9.99.0729

### 问题描述

之前使用字幕下载，同时打开了subhd和zimuku
得知最新版本已经弃用了subhd，所以打算在字幕来源下载那里将subhd取消勾选
但是发现无法取消勾选，选项里面只有一个zimuku，只能选择或者取消选择zimuku，subhd依然在来源下载的输入框内
![image](https://user-images.githubusercontent.com/35530837/182125174-33ffa5af-7347-4063-beed-539fec25f800.png)

### 重现步骤

取消勾选zimuku后如图
![image](https://user-images.githubusercontent.com/35530837/182125322-39b3bd1c-76e1-4419-939d-bf7c5e11acac.png)
勾选zimuku后如图
![image](https://user-images.githubusercontent.com/35530837/182125174-33ffa5af-7347-4063-beed-539fec25f800.png)

### 健康检查

![image](https://user-images.githubusercontent.com/35530837/182125420-5400d6a3-4bf8-484e-8461-6247ee4db0fd.png)

**Comment by pofey** [comment]
是有这个问题 因为本地有脏数据，打开baseconfig删了吧 不删 也不会用强制禁用
