### ISSUE TITLE
[缺陷]: 豆瓣想看与智能下载保存规则中，匹配多个条目时无法正确识别

### ISSUE THREAD

**Issue by anschein** [pofey/movie_robot#554]
### 当前程序版本

0.9.99.0729

### 问题描述

![image](https://user-images.githubusercontent.com/49552476/182164949-a98e8f8c-f3cd-4fd0-9b68-ad683bd2704c.png)
电影和纪录片分为两个文件夹，所以分类时规则1选择了除纪录片以外的所有，规则2选择了纪录片，测试保存规则时，带有双条目的例如灰影人 豆瓣ID：7051806，类型为动作 / 惊悚，测试结果如下：
![image](https://user-images.githubusercontent.com/49552476/182165459-9fc5a5f5-537b-4830-a958-722657054f0e.png)
单独条目的纪录片如美国工厂 豆瓣ID：30390700，识别正常

### 重现步骤

如上述设置

### 健康检查

![image](https://user-images.githubusercontent.com/49552476/182165996-e53fa8a5-f003-4696-8349-65f04c8f9537.png)

**Comment by pofey** [comment]
分类是并且 and的关系
