### ISSUE TITLE
[缺陷]: 少年派多季豆瓣数据导致硬链目录错误

### ISSUE THREAD

**Issue by htnanako** [pofey/movie_robot#556]
### 当前程序版本

0.9.99.0802

### 问题描述

少年派两季在豆瓣上分别名为"少年派（2019）"，"少年派2（2022）"
<img width="625" alt="image" src="https://user-images.githubusercontent.com/68056603/182318942-c06d9de0-4633-46ee-bce2-b26871ae0fef.png">

订阅下载后硬链的目录如下
<img width="231" alt="image" src="https://user-images.githubusercontent.com/68056603/182318979-1ff9cfca-022b-45a8-86c5-33b0e1c25b05.png">

### 重现步骤

web搜索订阅少年派及少年派2

### 健康检查

不相关 就不截图了

**Comment by haha6311** [comment]
我也出现了这个问题

**Comment by pofey** [comment]
我也遇到了这个问题 豆瓣的国产剧number没有去掉

**Comment by pofey** [comment]
修完了，下个版本发布
