### ISSUE TITLE
[缺陷]: 开启翻译中文演员，只翻译第一个人员，后面还是英文名

### ISSUE THREAD

**Issue by axunrun** [pofey/movie_robot#559]
### 当前程序版本

0.9.99.0802

### 问题描述

在“资源整理”中，电影演职员中文化异常，只翻译了第一个人员，进豆瓣查看后，确认其他人员在豆瓣中都有中文名。

### 重现步骤

1、修改好配置文件的采集中文演员名，并重启。2、通过资源整理重新刮削电影。3、出现演员翻译异常，有的电影可以都翻译，有的电影只翻译第一个人员。
<movie>
<lockdata>False</lockdata>
<id>tt13651628</id>
<imdbid>tt13651628</imdbid>
<tmdbid>776305</tmdbid>
<doubanid>35287908</doubanid>
<dateadded>2022-08-04 03:40:54</dateadded>
<title>龙和雀斑公主</title>
<year>2021</year>
<releasedate>2022-01-01</releasedate>
<premiered>2022-01-01</premiered>
<sorttitle>龙和雀斑公主</sorttitle>
<originaltitle>竜とそばかすの姫</originaltitle>
<plot>
...
</plot>
<rating>6.1</rating>
<runtime>122</runtime>
<uniqueid type="tmdb">776305</uniqueid>
<genre>冒险</genre>
<country>日本</country>
<director doubanid="1274299">细田守</director>
<actor>
<name>Kaho Nakamura</name>
<role>Suzu Naitō / Belle (voice)</role>
<type>Actor</type>
<tmdbid>3112441</tmdbid>
</actor>
<actor>
<name>Ryo Narita</name>
<role>Shinobu Hisatake (voice)</role>
<type>Actor</type>
<tmdbid>1668610</tmdbid>
</actor>
<actor>
<name>Shota Sometani</name>
<role>Shinjirō 'Kamishin' Chikami (voice)</role>
<type>Actor</type>
<tmdbid>1018944</tmdbid>
</actor>
<actor>
<name>Tina Tamashiro</name>
<role>Ruka Watanabe (voice)</role>
<type>Actor</type>
<tmdbid>1615061</tmdbid>
</actor>
<actor>

### 发生问题时系统日志

```shell
2022/08/04 03:40:49 - Thread-292 - INFO: 开始自动用TMDB数据搜索豆瓣数据
2022/08/04 03:40:49 - Thread-292 - INFO: 搜索豆瓣: 龙与雀斑公主 年份：2021 季度：None 季度发行年份：None
2022/08/04 03:40:53 - Thread-292 - INFO: 内容：/video/disk2/media/115/FILM/动漫电影/龙和雀斑公主 (2021) [tmdbid=776305]/龙和雀斑公主 (2021) [tmdbid=776305].mkv 识别为：龙和雀斑公主 2021-07-16
2022/08/04 03:40:54 - Thread-292 - INFO: 完成人物细田守的NFO信息写入，路径：/emby_person/细/细田守/person.nfo
2022/08/04 03:40:54 - Thread-292 - INFO: 完成人物细田守的图片下载，路径：/emby_person/细/细田守/folder.jpg
2022/08/04 03:41:04 - Thread-292 - INFO: 完成电影 龙和雀斑公主(2021) 的NFO文件生成，路径：/video/disk2/media/115/FILM/dmdy/龙和雀斑公主 (2021)/龙和雀斑公主 (2021).nfo
```

### 健康检查

![image](https://user-images.githubusercontent.com/97007105/182696002-1012856d-4f67-470a-b1d3-9aee24ce808f.png)

**Comment by pofey** [comment]
不太可能出现这样的逻辑情况。如果有，请把日志贴出来，以及影视的演员信息，nfo信息。

**Comment by axunrun** [comment]
这是操作的时候系统日志，只翻译了导演，演员部分都没有翻译
