### ISSUE TITLE
关于无法连接qbittorrent（获取下载器任务失败，请检查下载器是否能够链接）

### ISSUE THREAD

**Issue by ChanningHe** [pofey/movie_robot#56]
在刚刚配置完qbittorrent下载工具时没有问题，过了一段时间会出现无法连接
![image](https://user-images.githubusercontent.com/52875777/163702997-7b171e81-2953-4046-85e4-ff015f5c8b78.png)

**Comment by pofey** [comment]
qbit api的问题
