### ISSUE TITLE
[优化]: 希望能建一个交流群

### ISSUE THREAD

**Issue by 1455757504** [pofey/movie_robot#561]
### 当前现状

目前反馈建议，需求只能通过github。对于一些小问题效率较低

### 你的建议

希望可以建一个用户群。这样有些小问题就可以用户之间自行解决了，而不是通过github去提问作者。毕竟有些问题的出现可能只是操作上的问题，而非程序问题。这样也可以减轻作者的负担。而提交需求反馈缺陷这些依旧通过github。

### 优先级

一般

### 受众范围

很多人需要

**Comment by 1455757504** [comment]
如果作者不方便，也可以我们自行组建一个群

**Comment by pofey** [comment]
小问题非程序bug，目标一定是看wiki，解决，我后面会持续完善文档
