### ISSUE TITLE
[优化]: 演职员中文化的功能无法对动画配音演员起作用

### ISSUE THREAD

**Issue by axunrun** [pofey/movie_robot#563]
### 当前现状

动画类导演可以刮削为中文，但是演员都是声优，在豆瓣是voice，都无法变成中文。另外还有一个问题，当一个电影在豆瓣上的年份和TMDB不同时，也无法正常刮削演员中文名，比如“吉祥如意“，在豆瓣是2020年，在TMDB是2021年，就算设置豆瓣刮削，依然是从TMDB识别的演员名为英文。

### 你的建议

期望可以改善动画演职员汉化问题。并且希望能够文件在原地重新识别刷NFO，而不是一定需要指定一个新的目录，这样搬来搬去容易让EMBY丢库。

### 优先级

一般

### 受众范围

很多人需要

**Comment by pofey** [comment]
下一版应该可以修复这个问题
