### ISSUE TITLE
[优化]: 可否增加小姐姐文件整理功能

### ISSUE THREAD

**Issue by axunrun** [pofey/movie_robot#565]
### 当前现状

只要有下载后文件整理功能都行，干净的重命名和各自放目录，其他的功能自有各种流媒体端插件可以代劳

### 你的建议

下载后复制或则移动，文件重命名为车牌号，建立和车牌号一样的目录名，当然如果可以根据小姐姐家庭住址移动到各自家里更好。。。

### 优先级

一般

### 受众范围

很多人需要

**Comment by pofey** [comment]
现在有啊 不是原样转移么
