### ISSUE TITLE
[优化]:希望能够自主选择影片下载后是否刮削图片 

### ISSUE THREAD

**Issue by axunrun** [pofey/movie_robot#566]
### 当前现状

希望能够有开关管理是否刮削图片，有部分同学是把图片存在EMBY里的，下载后还需要删除

### 你的建议

有个开关就行了

### 优先级

一般

### 受众范围

一般

**Comment by arho14** [comment]
我也喜欢存再emby 里

**Comment by Decade1993** [comment]
同想要个开关

**Comment by LeeHK1989** [comment]
同想要个开关，我是用PLEX刮削了，感觉PLEX自带刮削很完美了。不需要MR来刮削图片和info

**Comment by cuicuifeng** [comment]
强烈要求带开关，使用PLEX完全不需要图片和nfo，每次下完还要删除。

**Comment by pofey** [comment]
scraper:
  generate_nfo: False

这配置一直存在，刮削还是个测试功能，暂时不开放到界面设置。
