### ISSUE TITLE
[提问]: 这个只能PT吗？

### ISSUE THREAD

**Issue by cszs1986** [pofey/movie_robot#567]
### 当前程序版本

1.0

### 问题

这个只能pt吗？现在只有一个pt账号，这个pt站资源都不怎么样，更新又慢。暂时又没有其他的pt

能不能自己加个公共资源的站点之类的功能？

**Comment by 1455757504** [comment]
倒数第二个是bt站，不过里面有好几个很容易获得的。像阿童木和pttime去贴吧到处有人发💊

**Comment by cszs1986** [comment]
> 倒数第二个是bt站，不过里面有好几个很容易获得的。像阿童木和pttime去贴吧到处有人发💊

谢谢
