### ISSUE TITLE
tg群 怎么不能用了？？

### ISSUE THREAD

**Issue by lalasou** [pofey/movie_robot#57]
突然发现 tg不能用了

**Comment by pofey** [comment]
维护成本较高，没有存在的必要性，选择解散掉了

**Comment by lalasou** [comment]
确实 有些乱

只是手册还不完善
我看 配置流量管理上面的说明链接打不开了

**Comment by pofey** [comment]
> 

可以看一下github首页的新wiki，换位置了

**Comment by lalasou** [comment]
> > 
> 
> 
> 
> 可以看一下github首页的新wiki，换位置了

![image](https://user-images.githubusercontent.com/7440313/164428695-c08bc66e-6503-4714-a796-b300d90b6659.png)


没有 wiki里面内容很少....

**Comment by lalasou** [comment]
@pofey

**Comment by pofey** [comment]
wiki的补充需要时间

**Comment by lalasou** [comment]
> wiki的补充需要时间

开放式  大家一起编辑

**Comment by pofey** [comment]
> > wiki的补充需要时间
> 
> 开放式 大家一起编辑

notion wiki 除了开发计划 和更新日志 都开发编辑了
