### ISSUE TITLE
[优化]: 关于剧集是否完结的判定

### ISSUE THREAD

**Issue by Xxx00xxX33** [pofey/movie_robot#570]
### 当前现状

当前对于国外剧集是否完结的判定是取决于TMDB的数据，一旦TMDB没有人更新集数信息就容易让机器人误判为完结（有时候很难判断这部剧将会有多少集，特别是日剧，8集、10集、11集、12集、13集完结的情况都有。）

拿当下还在播的日剧举例[[竞争的守护者](https://www.themoviedb.org/tv/203795?language=zh-CN)]举例，本周更新到第五集，TMDB也只有到第五集，所以机器人的订阅到了第五集就判定完结了，但实际上根据豆瓣这部剧有11集，需要人工干预编辑tmdb重新订阅才行...因为我看日韩剧比较多，所以深受这个问题困扰...没记错的话有些冷门一点的欧美剧也存在这个情况。

### 你的建议

- 希望优化判定逻辑，比如交叉对比豆瓣信息（有时候豆瓣也不一定准，拿刚才举例的日剧来说，豆瓣说有11集，tvdb说有8集）或者其他数据库比如tvdb

- 对于判定完结的订阅可以推迟几天（7天？3天？）等确定tmdb没有更新再标记为‘完结’

- 通常一部剧完结后站点会出打包合集，结合上一条建议，在延迟的这几天里机器人可以尝试搜索是否有合集，如果有可以提前标记为‘完结‘

### 优先级

非常高

### 受众范围

很多人需要

**Comment by pofey** [comment]
现在是可以考虑考虑策略升级一下了。现在是中国地区出品的剧，以豆瓣为准，其他圈tmdb，当时这么做是考虑到tmdb可以编辑，看到不全给编辑一下就好了，每天凌晨还会拉一下最新数据保证本地在变化。现在看大家不愿意去编辑啊。

**Comment by pofey** [comment]
后面这个地方，开自建数据就好了
