### ISSUE TITLE
[缺陷]: 下载文件自动整理时通过tmdb的信息没有找到豆瓣信息

### ISSUE THREAD

**Issue by happyhaha1** [pofey/movie_robot#571]
### 当前程序版本

1.0.5

### 问题描述

正常下载种子的时候，自动刮削硬连接时日志会报通过tmdb的信息没有找到豆瓣信息。但是手动整理的时候，勾选上了自动搜索豆瓣元数据就会正常找到豆瓣信息。这就导致每次新下一集电视的时候，中文人民会重新变为英文人名。

### 重现步骤

1.先订阅一个剧集。
2.剧集下载完成后自动整理的时候，会报通过tmdb的信息没有找到豆瓣信息。
3.然后改剧集就会重新变成英文人民。

### 发生问题时系统日志

```shell
2022/08/10 05:04:00 - ThreadPoolExecutor-5_2 - INFO: 搜索豆瓣: 正义的算法 年份：2022 季度：1 季度发行年份：None
 2022/08/10 05:04:01 - ThreadPoolExecutor-5_2 - INFO: 通过tmdb的信息没有找到豆瓣信息 正义的算法(2022)
 2022/08/10 05:04:01 - ThreadPoolExecutor-5_2 - INFO: 完成剧集 正义的算法 的NFO文件生成，路径：/mnt/user/media/server/剧集/正义的算法 (2022) [tmdbid=202018]/tvshow.nfo
 2022/08/10 05:04:02 - ThreadPoolExecutor-5_2 - INFO: 完成剧集 刘浪爸爸(2022) 第1季第24集的NFO文件生成，路径：/mnt/user/media/server/剧集/正义的算法 (2022) [tmdbid=202018]/Season 1/正义的算法 S01E24 - 2160p H.265 PTer.nfo
 2022/08/10 05:04:04 - ThreadPoolExecutor-5_2 - INFO: 开始自动用TMDB数据搜索豆瓣数据
 2022/08/10 05:04:04 - ThreadPoolExecutor-5_2 - INFO: 搜索豆瓣: 正义的算法 年份：2022 季度：1 季度发行年份：None
 2022/08/10 05:04:04 - ThreadPoolExecutor-5_2 - INFO: 通过tmdb的信息没有找到豆瓣信息 正义的算法(2022)
```

### 健康检查

正常的。

**Comment by happyhaha1** [comment]
`2022/08/10 07:27:20 - Thread-759 - INFO: 开始自动用TMDB数据搜索豆瓣数据
 2022/08/10 07:27:20 - Thread-759 - INFO: 搜索豆瓣: 正义的算法 年份：2022 季度：1 季度发行年份：2022
 2022/08/10 07:27:20 - Thread-759 - INFO: 搜到豆瓣编号:35633638
 2022/08/10 07:27:23 - Thread-759 - INFO: 完成剧集 正义的算法 的NFO文件生成，路径：/mnt/user/media/server/剧集/正义的算法 (2022) [tmdbid=202018]/tvshow.nfo
 2022/08/10 07:27:25 - Thread-759 - INFO: 完成剧集 刘浪爸爸(2022) 第1季第24集的NFO文件生成，路径：/mnt/user/media/server/剧集/正义的算法 (2022) [tmdbid=202018]/Season 1/正义的算法 S01E24 - 2160p H.265 PTer.nfo
 2022/08/10 07:27:26 - Thread-759 - INFO: 开始自动用TMDB数据搜索豆瓣数据
 2022/08/10 07:27:26 - Thread-759 - INFO: 搜索豆瓣: 正义的算法 年份：2022 季度：1 季度发行年份：2022
 2022/08/10 07:27:26 - Thread-759 - INFO: 搜到豆瓣编号:35633638
 2022/08/10 07:27:26 - Thread-759 - INFO: 完成剧集 大义灭亲(2022) 第1季第21集的NFO文件生成，路径：/mnt/user/media/server/剧集/正义的算法 (2022) [tmdbid=202018]/Season 1/正义的算法 S01E21 - 2160p H.265 PTer.nfo
`
手动整理时候的日志

**Comment by pofey** [comment]
正常订阅根本不会走这个逻辑啊，直接就有doubanid

**Comment by happyhaha1** [comment]
可能是我订阅的时候，手动下载了这个剧集，然后手动下载后下载完成不是自动整理嘛，会提示通过tmdb的信息没有找到豆瓣信息

**Comment by pofey** [comment]
> 可能是我订阅的时候，手动下载了这个剧集，然后手动下载后下载完成不是自动整理嘛，会提示通过tmdb的信息没有找到豆瓣信息

还能不能复现，非订阅现在识别豆瓣的能力应该是需要配置打开的，没开，肯定不会去查，本身就在实验中

**Comment by happyhaha1** [comment]
![image](https://user-images.githubusercontent.com/10184254/184055011-04107f3f-9043-45c6-ba5a-39bea2100959.png)
已经配置了，我在试一下
