### ISSUE TITLE
[优化]: 存量整理卡在半道不动的时候，希望有个按钮中断处理进程

### ISSUE THREAD

**Issue by haha6311** [pofey/movie_robot#573]
### 当前现状

如题
有时候点选了比较大的包，跑整理任务要跑很久，查看详细情况只能通过日志，也不知道去设置里重启会不会发生什么错误，等，就硬等。

### 你的建议

希望在界面上有一个按钮让用户可以随时中断处理，谢谢。

### 优先级

一般

### 受众范围

不确定

**Comment by pofey** [comment]
为什么会卡住呢？

**Comment by Dapong** [comment]
遇到同样情况，在整理一个365个电影文件的时候，卡在了58个停止状态，日志并没有显示报错

**Comment by pofey** [comment]
我估计很大原因是卡豆瓣，等吧
