### ISSUE TITLE
[优化]: 智能下载应该排除断种

### ISSUE THREAD

**Issue by AdoShan** [pofey/movie_robot#576]
### 当前现状

智能下载下载老片子的时候选中了一个断种进行下载。

### 你的建议

1. 智能下载选种的时候排除断种。
2. 并且对`订阅中`再细分一个`下载中`的状态(建议仍然处于`订阅中`列表)，而不是提交之后就直接设置为`已完成`。
3. 另外当迟迟没有下载成功的时候是否可以考虑进行一定的逻辑判定来决定是否重新筛选种子进行下载呢。这样也可以有效避免因为设置了最低做种人数而导致有种子但是设置不当而没有符合要求种子的问题

### 优先级

不着急

### 受众范围

一般

**Comment by pofey** [comment]
用最小做种数去控制
