### ISSUE TITLE
[优化]: 感谢大佬，试用过后已决定购买，特来提几点建议

### ISSUE THREAD

**Issue by 522654518** [pofey/movie_robot#577]
### 当前现状

大佬您好，最近我试过了很多类似软件，自动化的overseerr，jackett，sonarr，raddar四件套还有另一个nastools，刷流的pt小助手，flexget，art，下字幕的chinesesubfind，等等等等。
试用过mr之后感觉mr用起来最舒服，已决定购买，想发几个想法。

### 你的建议

1.我在用arr四件套时，他们的媒体库我觉着很好，希望MR加入媒体库，并且添加本地导入功能，有时候我忘记了我已经在arr里边订阅过了，会在MR里边重新订阅一下。这个媒体库功能我觉着很重要，或者加一个本地资源导入订阅也可以啊
2.搜索种子排序功能，没有偏好设置，希望可以设置一个自定义偏好，我喜欢frds，wiki等小组的片子，希望有些关键词可以为排序的时候加分，我看到了设置conf文件里边有排序文件，不知道自己添加关键词可否
3.现在的推荐影片，和热门影片基本已豆瓣为主，希望添加一下tmdb的热门推荐，就像overseerr
4.刷流任务希望有个优先级，不然最想刷的站没刷到，上传带宽已经被小站的种子占满了
1和2我觉着对我个人来讲还是挺有用的

### 优先级

一般

### 受众范围

不确定

**Comment by 522654518** [comment]
存量资源很难搞啊

**Comment by pofey** [comment]
存量不都在媒体库里么？媒体库如果有了，也就不会去下了。

**Comment by pofey** [comment]
第二条看wiki，高手可以自己改配置文件，新手暂不开放

**Comment by 522654518** [comment]
> 存量不都在媒体库里么？媒体库如果有了，也就不会去下了。

有一些电影或者电视剧下的264的 ，还是要洗版的。没有导入的话，只能手动弄了

**Comment by 522654518** [comment]
> 



> 存量不都在媒体库里么？媒体库如果有了，也就不会去下了。

而且有媒体剧的话我可以看到现在电视剧都有哪些集，缺哪些集，便于管理，有些电视剧我不想一集一集的下载，想等合集出来再下

**Comment by 522654518** [comment]
> 第二条看wiki，高手可以自己改配置文件，新手暂不开放

我看到json文件了，去改个试试

**Comment by 522654518** [comment]
> 存量不都在媒体库里么？媒体库如果有了，也就不会去下了。

overseerr的系列电影，和剧集的全部订阅有点爽，点一下就可以下载所有季，我们有批量订阅的计划么

**Comment by pofey** [comment]
关注后续更新计划 现在还不是终点

**Comment by 522654518** [comment]
> 关注后续更新计划 现在还不是终点

媒体库问题已经通过overseerr变相解决，如果只通过over订阅至少不会重复下载资源了，不过我个人还是觉着媒体库管理，下载管理，刷流任务管理好一点，等您慢慢更新

**Comment by pofey** [comment]
> > 关注后续更新计划 现在还不是终点
> 
> 媒体库问题已经通过overseerr变相解决，如果只通过over订阅至少不会重复下载资源了，不过我个人还是觉着媒体库管理，下载管理，刷流任务管理好一点，等您慢慢更新

？？ 你先用用吧 我觉得你可能还没理解逻辑
