### ISSUE TITLE
[缺陷]: 手动下载字幕失败

### ISSUE THREAD

**Issue by Zayia** [pofey/movie_robot#578]
### 当前程序版本

1.1.0

### 问题描述

下载一部电影，程序提示如下
分手的决心(2022)字幕下载到达限制，已经终止。启动至今：65分钟 运行次数：9
然后手动在搜索里面搜索这个电影，然后点击下载字幕
提示
![Uploading FF813544-9894-4825-9B4F-2FD03741DE51.png…]()

### 重现步骤

手动搜索已经下载过的电影，然后点击下载字幕，就会有提示

### 健康检查

![Uploading BF378304-17A3-4233-B19B-AC05069622C4.png…]()

**Comment by Zayia** [comment]
![Uploading 7F1A7E66-FD78-417F-A2E4-4FEB0FB6F81F.png…]()

**Comment by Zayia** [comment]
![FEB5DF84-075C-49B8-ADDB-D24298037CC0](https://user-images.githubusercontent.com/35530837/184454942-3a0683ec-9286-4fb2-bcca-c1e323230f06.png)

**Comment by Zayia** [comment]
![B16E07A0-14F1-4848-A066-F4F06C9B8125](https://user-images.githubusercontent.com/35530837/184455010-8e2c19da-72f7-474a-8da1-cd971ce4651c.png)

**Comment by pofey** [comment]
看不到日志，这部电影我字幕下载正常
