### ISSUE TITLE
[提问]:日志提示找不到tmdb的资源 id: None type: Movie

### ISSUE THREAD

**Issue by Zayia** [pofey/movie_robot#579]
### 当前程序版本

1.1.0

### 问题

手动搜索已经下载过的资源，日志提示如下

2022/08/13 18:59:45 - Thread-96 - ERROR: 找不到tmdb的资源 id: None type: Movie

导致的结果是无法自动下载字幕，怀疑就是因为匹配不到TMBD资源，另外手动下载字幕的时候提示必须提供TMDB编号！如图：
![1](https://user-images.githubusercontent.com/35530837/184480735-089186ca-05ab-4f1b-8048-f05df9b6c2f6.png)
然而TMBD连接却正常

![2](https://user-images.githubusercontent.com/35530837/184480750-0d340266-3f65-4bdb-bb4d-dc977deccb9b.png)

### 发生问题时系统日志

```shell
2022-08-13 18:54:06,038 INFO exited: mbots (terminated by SIGKILL; not expected)

2022-08-13 18:54:07,147 INFO spawned: 'mbots' with pid 1408

2022-08-13 18:54:12,153 INFO success: mbots entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)

2022/08/13 18:54:23 - MainThread - INFO: 站点并发线程数：6

2022/08/13 18:54:23 - MainThread - INFO: 已开启企业微信接收消息配置

2022/08/13 18:54:23 - MainThread - INFO: Plex连接正常，欢迎回来：366436708@qq.com

2022/08/13 18:54:26 - MainThread - INFO: 新增任务：PT站点登陆有效性检查及分享数据更新任务

2022/08/13 18:54:27 - MainThread - INFO: 新增任务：免费下载种子监测任务

2022/08/13 18:54:27 - MainThread - INFO: 新增任务：站点资源同步任务

2022/08/13 18:54:27 - Thread-12 - INFO: 同步豆瓣想看数据的任务已经启动

2022/08/13 18:54:27 - MainThread - INFO: 新增任务：自定义任务调度

2022/08/13 18:54:27 - MainThread - INFO: 新增任务：监听下载客户端下载状态

2022/08/13 18:54:27 - MainThread - INFO: 新增任务：订阅元数据检查更新任务

2022/08/13 18:54:27 - MainThread - INFO: 新增任务：新版本检测任务

2022/08/13 18:54:27 - Thread-13 - INFO: 开始更新媒体趋势榜单数据

2022/08/13 18:54:27 - MainThread - INFO: 新增任务：媒体趋势榜单任务

2022/08/13 18:54:27 - MainThread - INFO: 新增任务：健康检查任务

2022/08/13 18:54:27 - MainThread - INFO: Plex连接正常，欢迎回来：366436708@qq.com

2022/08/13 18:54:27 - MainThread - INFO: 已经启动字幕下载处理任务。

2022/08/13 18:54:27 - MainThread - INFO: 当前版本: 1.1.0

2022/08/13 18:54:31 - Thread-36 - INFO: 已经开始在站点: 家园,柠檬,馒头,我堡,猫站,铂金家,听听歌,聆音 搜索: 露西亚的情人

2022/08/13 18:54:38 - Thread-36 - INFO: 共在8个站点搜索到47条结果，其中猫站最慢，耗费6.62秒

2022/08/13 18:54:46 - Thread-13 - INFO: 媒体趋势榜单更新完毕

2022/08/13 18:54:53 - Thread-50 - INFO: 已经开始在站点: 家园,柠檬,馒头,我堡,猫站,铂金家,听听歌,聆音 搜索: 我的一级兄弟

2022/08/13 18:54:53 - Thread-49 - ERROR: 找不到tmdb的资源 id: None type: Movie

2022/08/13 18:54:58 - Thread-50 - INFO: 共在8个站点搜索到5条结果，其中听听歌最慢，耗费4.51秒

2022/08/13 18:59:45 - Thread-100 - INFO: 我的一级兄弟 资源搜索命中缓存结果。

2022/08/13 18:59:45 - Thread-96 - ERROR: 找不到tmdb的资源 id: None type: Movie

2022/08/13 19:01:59 - Thread-136 - INFO: 我的一级兄弟 资源搜索命中缓存结果。

2022/08/13 19:01:59 - Thread-134 - ERROR: 找不到tmdb的资源 id: None type: Movie
```

**Comment by Zayia** [comment]
重新安装MB，然后订阅一个电影，提示如下
2022/08/13 20:36:11 - SubRequestConsumer - INFO: 成功从CMDB取得豆瓣编号35073886对应的ID映射关系：{'mediaType': 'Movie', 'doubanId': 35073886, 'doubanSeasonNumber': None, 'tmdbId': 705996, 'imdbId': 'tt12477480', 'tvdbId': None}

2022/08/13 20:36:13 - SubRequestConsumer - INFO: 分手的决心(2022) 选用过滤器：通用 排序规则：compact

2022/08/13 20:36:14 - SubRequestConsumer - INFO: 新增来自zuomu的订阅: 分手的决心(2022) 选用过滤器：通用 排序规则：compact

2022/08/13 20:36:35 - Thread-472 - INFO: 已经开始在站点: 家园,柠檬,馒头,我堡,猫站,铂金家,听听歌,聆音 搜索: 分手的决心

2022/08/13 20:36:35 - Thread-468 - ERROR: 找不到tmdb的资源 id: None type: Movie

然后在搜索界面手动下载字幕，依然提示2022/08/13 20:36:11 - SubRequestConsumer - INFO: 成功从CMDB取得豆瓣编号35073886对应的ID映射关系：{'mediaType': 'Movie', 'doubanId': 35073886, 'doubanSeasonNumber': None, 'tmdbId': 705996, 'imdbId': 'tt12477480', 'tvdbId': None}

2022/08/13 20:36:13 - SubRequestConsumer - INFO: 分手的决心(2022) 选用过滤器：通用 排序规则：compact

2022/08/13 20:36:14 - SubRequestConsumer - INFO: 新增来自zuomu的订阅: 分手的决心(2022) 选用过滤器：通用 排序规则：compact

2022/08/13 20:36:35 - Thread-472 - INFO: 已经开始在站点: 家园,柠檬,馒头,我堡,猫站,铂金家,听听歌,聆音 搜索: 分手的决心

2022/08/13 20:36:35 - Thread-468 - ERROR: 找不到tmdb的资源 id: None type: Movie

**Comment by pofey** [comment]
无法重现 这部电影我订阅没什么问题 继续观察吧

**Comment by Zayia** [comment]
不是这一部电影这样，是所有电影都会出现这个情况





------------------ 原始邮件 ------------------
发件人: yipengfei ***@***.***&gt;
发送时间: 2022年8月16日 01:32
收件人: pofey/movie_robot ***@***.***&gt;
抄送: Zayia ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [pofey/movie_robot] [提问]:日志提示找不到tmdb的资源 id: None type: Movie (Issue #579)






Closed #579 as not planned.

**Comment by pofey** [comment]
> 不是这一部电影这样，是所有电影都会出现这个情况
> […](#)

那就按wiki检查检查配置吧

**Comment by Zayia** [comment]
> 

手动下载字幕的时候提示必须提供TMDB编号
这个提供TMDB编号在哪里提供
是自动整理后的文件名中必须含有TMDB编号还是在哪里手动填写一下TMDB编号？

**Comment by pofey** [comment]
> 手动下载字幕的时候提示必须提供TMDB编号
> 这个提供TMDB编号在哪里提供
> 是自动整理后的文件名中必须含有TMDB编号还是在哪里手动填写一下TMDB编号？

自动的 正常情况下一定有

**Comment by Zayia** [comment]
> 

发现电视剧无论是搜索还是手动下载字幕都没一点问题
就电影搜索的时候日志会提示`找不到tmdb的资源 id: None type: Movie`
然后手动下载字幕的时候会提示`必须提供TMDB编号`

**Comment by pofey** [comment]
> 发现电视剧无论是搜索还是手动下载字幕都没一点问题
> 就电影搜索的时候日志会提示`找不到tmdb的资源 id: None type: Movie`
> 然后手动下载字幕的时候会提示`必须提供TMDB编号`

那这就是有问题 但描述太宽泛了，也无法确定是哪里没配置好

**Comment by Zayia** [comment]
问题找到了
是因为PLEX使用的是豆瓣的刮削器，未使用MB自动生成的NFO文件
PLEX改用自动生成的NFO文件后就可以搜索字幕了

**Comment by pofey** [comment]
> 问题找到了
> 是因为PLEX使用的是豆瓣的刮削器，未使用MB自动生成的NFO文件
> PLEX改用自动生成的NFO文件后就可以搜索字幕了

是啥原理呢 因为plex 读不到这些id？

**Comment by Zayia** [comment]
这就不清楚了，我的排查过程是查看字幕下载日志
发现日志里面提示在媒体库还不存在，等一会再下。
于是猜测使用plex的豆瓣刮削插件刮削出来的媒体文件MR识别不出来
于是用MR生成的NFO文件刮削一下，发现问题就解决了。





------------------ 原始邮件 ------------------
发件人: yipengfei ***@***.***&gt;
发送时间: 2022年8月16日 12:39
收件人: pofey/movie_robot ***@***.***&gt;
抄送: Zayia ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [pofey/movie_robot] [提问]:日志提示找不到tmdb的资源 id: None type: Movie (Issue #579)






问题找到了
是因为PLEX使用的是豆瓣的刮削器，未使用MB自动生成的NFO文件
PLEX改用自动生成的NFO文件后就可以搜索字幕了

是啥原理呢 因为plex 读不到这些id？
