### ISSUE TITLE
[缺陷]: 经常提交下载之后下载器并没有下载

### ISSUE THREAD

**Issue by nikkzy** [pofey/movie_robot#581]
### 当前程序版本

1.1.1

### 问题描述

无法正常完成下载,一般3个想看里只有下载1-2个

### 重现步骤

点想看后,扫描到然后添加种子 ,然后提交给下载器,并没有开始下载,机器人里就提示洗版中,也没有下载记录,而且洗版刷新了也没有反应

### 发生问题时系统日志

```shell
2022/08/14 15:35:17
SubConsumerINF0：共在16个站点搜奏到50条结果，其中瓷器最慢，耗费34.25秒
2022/08/14 15:43:56
Thread-45INF0：豆越用户nikkpt的想看的情书已经提交订阅
2022/08/14 15:44:01
Thread-45
INFO：成功从CHDB敦得豆我编号1292220对应的工D映射关系：{"mediaType"："Movie', "douband' :
1292220，
"doubanSeasonNumber': None,
"tmdbId':
47002
•imdbId" :
"tto113703
'tvdbId': None}
2022/08/14 15:44:05
Thread-45
INFO:
情书(1995） 选用过浦器：电影 排序规则：collection
2022/08/14 15:44:05
Thread-45
INFO:
豆幾用户nikkpt的想看的大独裁者已经提交订阅
2022/08/14 15:44:05
SubConsumer
INF0：已经开始在站点：幼儿园，彩江岛，三免，瓷器，高清杜比，红豆饭，天空，朋友,柠檬，我堡，猫站，他吹吹风，
北洋园，听听歌，聆音，很头 搜索：情书,Love Letter.tt0113703
2022/08/14 15:44:10
Thread-45
INFO:
1295646,
" doubanseasonNumber •: None,
• tmdbId’: 914.
"imdbId": •ttoo32553"，
2022/08/14 15:44:14
Thread-45
INF0：大独裁者（1940） 选用过浦器：电影 排序规则：collection
2022/08/14 15:44:14
Thread-45
INFO:
豆我用户nikkpt的想看的星月童话已经提交订阅
2022/08/14 15:44:14
Thread-45
INF0：大独裁者（1940） 选用过滤器：电影 排序规则：collection
2022/08/14 15:44:14
Thread-45
INFO:
豆然用户nikkpt的想看的星月童话已经提交订兒
2022/08/14 15:44:28
Thread-45
INF0：星月童活(1999） 选用过浦器：电影 排序规则：collection
2022/08/14 15:45:28
SubConsumer
INFO：共在16个站点搜索到808条结果，其中瓷器最慢，耗费82.99秒
2022/08/14 15:45:28
SubConsumer
INF0：情书(1995） 没有找到符合过活结果的资源，先下Blu-ray 1080p AVC 等到重好的资源会言动下裁。
2022/08/14 15:45:28
SubConsumer
INF0：情书(1995)当前最佳选择：Blu-ray 1080p AVC 资源：https://kp.m.
team.cc/detaiis.php?id=215919Ghit=1己经提交下载
2022/08/14 15:45:28
mteam-downloader
• INFO：开始处理来自汀阅的下乾：[mteam] Love Letter 1995 Blu-Ray 1080p AVC TrueHD
5.1-Fantasymao@OurBits
2022/08/14 15:45:28
- SubConsumer
•INFO：已经开始在站点：幼儿园，彩工马，三免，瓷路，高清杜比，红豆饭，天空，朋友,柠檬，我壓，猫站，他吹吹风，
北洋园，听听歌，聆音，湿头 搜素：大独裁者,The Great Dictator, tte032553
2022/08/14 15:45:32
•mteam-downloader - INFO: [mteam]Love Letter 1995 Blu-Ray 108op AVC TrueHD 5.1-FantasymaogourBitse
经开始下裁，路径：/video/movie 分类：末设置
2022/08/14 15:46:13
SubConsumer
INFO：共在16个站点搜索到89条结果，其中侵头最慢，耗费36.7秒
2022/08/14 15:46:13
- SubConsumer
INF0：大独裁者(194日） 没有找到符合过汽结果的资源，先下Blu-ray 1080p AVC 等到更好的资源会三动下
2022/98/14 15:46:13 - SubConsumer - INF0：大独裁者(1940） 当前最佳远择：Blu-rav 1080p AVC 资源：https://hdsky.me/details.php?
id=48079ahit=1 已经提交下裁。
2022/08/14 15:46:13
3833p°3l-A55 Aee fparregt- gaiasegter- EhE0：手給处理來合河同的下露： thdsky/ The oreat Dictator 1940 criterion coilection
2022/08/14 15:46:13 - Subconsumer - INFO：已经开始在站点：幼儿园，彩江岛，三免，瓷器，高清杜比，红豆饭，天空，朋友,柠檬，我堡，猫站，他吹吹风，
北洋园，听听歌，段音，设头 搜索：星月童话,Moonlight Express, tt0202478
2022/08/14 15:46:17
• hdsky -downloader - INFO： 大独裁者(1940）在煤体股务已经存在，但未正确刮削，当前名称为：The Great Dictator
1940 Criterion Collection 10gop Blu-Ray AVC LPCN1 O-DIY@HDSky
2022/08/14 15:46:17
hdsky-downloader
- INFO: [hdsky]The Great Dictator 1940 Criterion Collection 1080p Blu-Rav AVC
LPCM1 O-DIYOHDSKy
2022/08/14 15:46:35
ThreadPoolExecutor-4 4 - INFO：开始同步站点资源信息，
2022/08/14 15:46:54
SubConsumer
INFO：共在16个站点搜索到49条结果，其中他吹吹风聂慢，耗费30.08秒
2022/08/14 15:46:54
- SubConsumer
- INF0：星月童话(1999） 没有找到符合过汽结果的资源，先下Blu-ray 1080p AVC 等到更好的资源会三动下
#.
2022/08/14 15:46:54
• Subconsumer - INF0：星月童洁(1999） 兰前聂佳选择：Blu-ray 1086p AVC 资源：https://kp.m•
team.cc/detaiis.php?id=284962chit=1己经提交下载
2022/08/14 15:46:54 - mteam-downloader.
TrueD 5.1-doraemon
- INFO：开始处理未自订阅的下载：[mteam]Moonlight Express 199g HKG Blu-ray 1080P AVC
2022/08/14 15:46:54
2022/08/14 15:46:54
SubConsumer
SubConsumer
INFO：共在16个站点搜索到49条结果，其中他吹吹风最慢，耗麦30.08秒
INFO：星月童话(1999）没有找到符合过洁结果的资源，
先下Blu-ray 1080p AVC 等到西好的资源会三动下
..
2022/08/14 15:46:54
SubConsumer
INF0：星月童洁(1999） 当前最佳远择：Blu-ray 1080p AVC 资源：https://kp.m.
team.cc/details.php?id=284962chit=1 EE*R#
2022/08/14 15:46:54
mteam-downloader
INF0：开始处理未自订阅的下裁：Imteam jMoonlight Express 1999 HKG Blu-ray 1086P AVC
TrueD 5.1-doraemon
2022/08/14 15:46:58
mteam-downloader
•INF0：星月童诺(1999)在滨体服务已经存在，但未正确刮削，当前名称为：Moonlight Express 1999
HKG Blu-ray 1080P AVC TrueHD 5.1-doraemon
2022/08/14 15:46:58
• mteam-downloader
INF0: [mteam JHoonl ight Express 199g HKG Blu-ray 1080P AVC TrueHD 5.1-do raemon提
交下哉失败
```

### 健康检查

![image](https://user-images.githubusercontent.com/56377576/184527058-da7f3e4d-225d-4257-afeb-e73609d52dfb.png)
![image](https://user-images.githubusercontent.com/56377576/184527543-f09340d3-e835-4729-ba96-e5fdbb3b8f3b.png)
![image](https://user-images.githubusercontent.com/56377576/184527633-406beabe-48d8-4898-a11c-a3cc4f85fb64.png)
![image](https://user-images.githubusercontent.com/56377576/184527660-b13436b8-21f2-4fea-89c9-7cc438a186fc.png)
![image](https://user-images.githubusercontent.com/56377576/184527665-2320c2b5-d14d-4cb1-8158-dde58f59a7b3.png)

**Comment by appalled2022** [comment]
遇到了同样的问题，并且有时候手动搜索下载亦会出现，显示已提交给下载器，但是并没有下载

**Comment by pofey** [comment]
INF0: [mteam JHoonl ight Express 199g HKG Blu-ray 1080P AVC TrueHD 5.1-do raemon提
交下哉失败

**Comment by nikkzy** [comment]
> INF0: [mteam JHoonl ight Express 199g HKG Blu-ray 1080P AVC TrueHD 5.1-do raemon提 交下哉失败

有时候是已经推送了种子的链接,已经推送成功了,但是也没下载

**Comment by nikkzy** [comment]
![image](https://user-images.githubusercontent.com/56377576/184531850-259450db-a575-4947-b115-88637cc44f65.png)

**Comment by nikkzy** [comment]
显示已经提交下载,但是应该不是站点的问题,mt的种子有的也可以成功,这样下载失败后无法解决看片的需求了

**Comment by pofey** [comment]
你的环境有问题 按wiki说明排查 程序没问题

**Comment by Dapong** [comment]
临时解决办法 ： 【*/diff/dependencies/qbittorrentapi/torrents.py】将文件中的
`            "paused": (None, is_paused),
`
替换为（重启容器）
`             "paused": ("false", "false"),
`
[https://github.com/pofey/movie_robot/issues/584](url)

**Comment by pofey** [comment]
> 临时解决办法 ： 【*/diff/dependencies/qbittorrentapi/torrents.py】将文件中的
> ` "paused": (None, is_paused),`
> 替换为（重启容器）
> ` "paused": ("false", "false"),`
> [https://github.com/pofey/movie_robot/issues/584](url)

另外一个问题中也提及到这个问题了 可能是新版qbit 不兼容老板api了 下一版修

**Comment by nikkzy** [comment]
> 临时解决办法 ： 【*/diff/dependencies/qbittorrentapi/torrents.py】将文件中的 ` "paused": (None, is_paused),` 替换为（重启容器） ` "paused": ("false", "false"),` [https://github.com/pofey/movie_robot/issues/584](url)

我跟你说的两个问题,我是种子压根没加到下载器里去

**Comment by pofey** [comment]
> > 临时解决办法 ： 【*/diff/dependencies/qbittorrentapi/torrents.py】将文件中的 ` "paused": (None, is_paused),` 替换为（重启容器） ` "paused": ("false", "false"),` [https://github.com/pofey/movie_robot/issues/584](url)
> 
> 我跟你说的两个问题,我是种子压根没加到下载器里去

那你的问题 就还是自己在好好检查检查环境吧，太宽泛了只能自己分析

**Comment by nikkzy** [comment]
![image](https://user-images.githubusercontent.com/56377576/184806429-6b6cb493-e7f6-421a-ac06-b292f043007e.png)
![image](https://user-images.githubusercontent.com/56377576/184806721-c8a7be1b-28fb-4e91-8474-7e271fc4d471.png)
衣总你看，一样的路径一样的配置一样的站点，就是有一个种子没有添加下载，然后默认跑到洗版那里去了

**Comment by pofey** [comment]
> ![image](https://user-images.githubusercontent.com/56377576/184806429-6b6cb493-e7f6-421a-ac06-b292f043007e.png)
> ![image](https://user-images.githubusercontent.com/56377576/184806721-c8a7be1b-28fb-4e91-8474-7e271fc4d471.png)
> 衣总你看，一样的路径一样的配置一样的站点，就是有一个种子没有添加下载，然后默认跑到洗版那里去了

提交下载器失败 就是你下载器的响应结果

**Comment by nikkzy** [comment]
所以是我下载器不稳定的缘故
