### ISSUE TITLE
[优化]: 在订阅新的剧集时，忽略指定的已更新集数

### ISSUE THREAD

**Issue by Dapong** [pofey/movie_robot#583]
### 当前现状

在订阅新的剧集时，无法忽略之前的集数，例如我想订阅柯南，但是我不想订阅1000集以前的，只想追更，如何忽略1000以前的集数？

### 你的建议

希望可以手动添加忽略规则：“集数忽略”

### 优先级

非常高

### 受众范围

一般

**Comment by pofey** [comment]
你的媒体库里如果有会忽略的

**Comment by Dapong** [comment]
> 你的媒体库里如果有会忽略的

媒体库里面没有的，只需要追新出来的剧集，不然还需要把之前的1000集下载下来吗？

**Comment by pofey** [comment]
> > 你的媒体库里如果有会忽略的
> 
> 媒体库里面没有的，只需要追新出来的剧集，不然还需要把之前的1000集下载下来吗？

是的
