### ISSUE TITLE
[缺陷]: 种子成功提交到Qbittorrent下载器后，是暂停状态

### ISSUE THREAD

**Issue by Dapong** [pofey/movie_robot#584]
### 当前程序版本

1.1.0

### 问题描述

种子成功提交到Qbittorrent下载器后，是暂停状态，不会自动开始下载，没看到movie-robot webui内有设置相关参数，是否是后台程序提交种子到下载器时未能正确附带自动下载参数，或者参数类型冲突，麻烦大佬查看一下

### 重现步骤

订阅成功>>提交下载>>日志显示“已经开始下载”>>qbitorrent内种子为暂停状态

### 发生问题时系统日志

```shell
2022/08/15 19:37:07 - SubConsumer - INFO: 玫瑰之战(2022) 没有搜索到缺失的[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]集
 2022/08/15 19:37:07 - SubConsumer - INFO: 苍兰诀(2022) 没有搜索到缺失的[21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]集
 2022/08/15 19:37:07 - SubConsumer - INFO: 胆小鬼(2022) 没有搜索到缺失的[8, 9, 10, 11, 12, 13, 14, 15, 16]集
 2022/08/15 19:52:06 - ThreadPoolExecutor-4_1 - INFO: 开始同步站点资源信息...
 2022/08/15 19:52:32 - ThreadPoolExecutor-4_1 - INFO: 所有站点资源信息已经更新完毕。
 2022/08/15 19:52:32 - ThreadPoolExecutor-4_1 - INFO: 没有配置或开启流量管理设置，不会开始运行：{'avg_statistics_period': 5, 'enable': False}
 2022/08/15 19:57:33 - SubConsumer - INFO: 玫瑰之战(2022) 第1季 第[17, 18]集 品质：WEB-DL 2160p H.265 资源: https://audiences.me/details.php?id=55531&hit=1 已经提交下载。
 2022/08/15 19:57:34 - audiences-downloader - INFO: 开始处理来自订阅的下载: [audiences]Rose War S01E17-E18 2022 2160p WEB-DL H265 AAC-ADWeb
 2022/08/15 19:57:34 - SubConsumer - INFO: 苍兰诀(2022) 没有搜索到缺失的[21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]集
 2022/08/15 19:57:34 - SubConsumer - INFO: 胆小鬼(2022) 没有搜索到缺失的[8, 9, 10, 11, 12, 13, 14, 15, 16]集
 2022/08/15 19:57:59 - audiences-downloader - INFO: [audiences]Rose War S01E17-E18 2022 2160p WEB-DL H265 AAC-ADWeb已经开始下载,路径：/share/CACHEDEV3_DATA/Public3/PT/剧集刮削分类/ 分类：未设置 
 2022/08/15 20:12:50 - ThreadPoolExecutor-4_0 - INFO: 开始同步站点资源信息...
 2022/08/15 20:13:49 - ThreadPoolExecutor-4_0 - INFO: 所有站点资源信息已经更新完毕。
 2022/08/15 20:13:50 - ThreadPoolExecutor-4_0 - INFO: 没有配置或开启流量管理设置，不会开始运行：{'avg_statistics_period': 5, 'enable': False}
 2022/08/15 20:20:48 - SubConsumer - INFO: 玫瑰之战(2022) 没有搜索到缺失的[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]集
 2022/08/15 20:20:48 - SubConsumer - INFO: 苍兰诀(2022) 没有搜索到缺失的[21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]集
 2022/08/15 20:20:48 - SubConsumer - INFO: 胆小鬼(2022) 没有搜索到缺失的[8, 9, 10, 11, 12, 13, 14, 15, 16]集
```

### 健康检查

![image](https://user-images.githubusercontent.com/16550877/184635575-6e78e3cf-646e-4ab6-b167-a3e435099422.png)

**Comment by pofey** [comment]
那我为啥不是呢？

**Comment by Dapong** [comment]
> 仔细研究研究手册，这个问题绝对是你设置的问题

感谢大佬回复，我现在使用的是威联通的Docker版的【docker pull linuxserver/qbittorrent:latest】，v4.4.3 ，现在更新到最新版仍然有问题存在；
在利用微薄的编程知识排查后发现是 【*/diff/dependencies/qbittorrentapi/torrents.py】 参数问题，现在文件内使用的 paused = None ，虽然官方api说明 paused 参数默认为 false ，但linuxserver/qbittorrent新版本会出现默认paused = true (疑似bug)，所以只能明确定义 paused = "false" ，才可以解决新版本qb所带来的问题；
不知道其他版本是否会出现这个问题，但是为了避免相关问题的存在，建议把参数值明确。

![image](https://user-images.githubusercontent.com/16550877/184733590-ee26962d-67d3-45e2-8947-ede16c43c071.png)

![image](https://user-images.githubusercontent.com/16550877/184735728-cc37215c-5f47-4957-a594-6a0b493f6957.png)

**Comment by Dapong** [comment]
> 那我为啥不是呢？

感谢大佬回复，我现在使用的是威联通的Docker版的【docker pull linuxserver/qbittorrent:latest】，v4.4.3 ，现在更新到最新版仍然有问题存在；
在利用微薄的编程知识排查后发现是 【*/diff/dependencies/qbittorrentapi/torrents.py】 参数问题，现在文件内使用的 paused = None ，虽然官方api说明 paused 参数默认为 false ，但linuxserver/qbittorrent新版本会出现默认paused = true (疑似bug)，所以只能明确定义 paused = "false" ，才可以解决新版本qb所带来的问题；
不知道其他版本是否会出现这个问题，但是为了避免相关问题的存在，建议把参数值明确。

![image](https://user-images.githubusercontent.com/16550877/184735943-70e141e0-de40-4270-ba45-c0da91c65430.png)

![image](https://user-images.githubusercontent.com/16550877/184735952-0fa8d9c6-6335-419b-9abe-0f839d44e500.png)

**Comment by pofey** [comment]
> > 那我为啥不是呢？
> 
> 感谢大佬回复，我现在使用的是威联通的Docker版的【docker pull linuxserver/qbittorrent:latest】，v4.4.3 ，现在更新到最新版仍然有问题存在； 在利用微薄的编程知识排查后发现是 【*/diff/dependencies/qbittorrentapi/torrents.py】 参数问题，现在文件内使用的 paused = None ，虽然官方api说明 paused 参数默认为 false ，但linuxserver/qbittorrent新版本会出现默认paused = true (疑似bug)，所以只能明确定义 paused = "false" ，才可以解决新版本qb所带来的问题； 不知道其他版本是否会出现这个问题，但是为了避免相关问题的存在，建议把参数值明确。
> 
> ![image](https://user-images.githubusercontent.com/16550877/184735943-70e141e0-de40-4270-ba45-c0da91c65430.png)
> 
> ![image](https://user-images.githubusercontent.com/16550877/184735952-0fa8d9c6-6335-419b-9abe-0f839d44e500.png)

下个版本加一下 试试
