### ISSUE TITLE
[缺陷]: 初始化配置，下载记录和添加下载器这两个页面，web加载不出来，一直loading，控制台报错

### ISSUE THREAD

**Issue by zjc1994** [pofey/movie_robot#586]
### 当前程序版本

1.1.1

### 问题描述

其他页面正常，日志也没有其他错误信息
![image](https://user-images.githubusercontent.com/24852256/184655366-4e555d3c-a173-4547-9233-f9a628b6a158.png)

### 重现步骤

初始化配置时，打开这两个页面

### 健康检查

初始化配置

**Comment by pofey** [comment]
这都是加密页面啥也看不出来
