### ISSUE TITLE
Plex媒体数量过多时，订阅相关功能失效

### ISSUE THREAD

**Issue by EndlessJY** [pofey/movie_robot#589]
### 当前程序版本

all

### 问题描述

环境：Linux、GD盘+Rclone挂载、Robot：1.1.1
Plex媒体数量过多(5000+)，Web订阅相关功能失效(订阅无法增 删)，微信订阅后无返回
1.1.1及1.0以下版本均可复现；仅测试Plex，暂无法确定Jellyfin、Emby是否会有此问题
![image](https://user-images.githubusercontent.com/33413681/184811302-6b7fa810-4016-4d2b-8674-716b8e19e0dc.png)

### 重现步骤

Plex媒体数量>5000+(无法确定具体数值)
Robot绑定Plex
重启Robot
订阅功能失效

Plex媒体数量<5000(无法确定具体数值)
Robot绑定Plex
重启Robot
订阅功能正常

### 发生问题时系统日志

```shell
2022/08/16 14:00:42 - MainThread - INFO: 新增任务：监听下载客户端下载状态
2022/08/16 14:00:42 - MainThread - INFO: 新增任务：订阅元数据检查更新任务
2022/08/16 14:00:42 - MainThread - INFO: 新增任务：新版本检测任务
2022/08/16 14:00:42 - Thread-10 - INFO: 开始更新媒体趋势榜单数据
2022/08/16 14:00:42 - MainThread - INFO: 新增任务：媒体趋势榜单任务
2022/08/16 14:00:42 - MainThread - INFO: 新增任务：健康检查任务
2022/08/16 14:00:42 - MainThread - INFO: Plex连接正常，欢迎回来：xxxxx
2022/08/16 14:00:42 - MainThread - INFO: 已经启动字幕下载处理任务。
2022/08/16 14:00:42 - MainThread - INFO: 当前版本: 1.1.1
2022-08-16 14:00:43,439 INFO success: mbots entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2022/08/16 14:01:25 - qywx-search - INFO: 成功从CMDB取得豆瓣编号2158647对应的ID映射关系：{'mediaType': 'TV', 'doubanId': 2158647, 'doubanSeasonNumber': 1, 'tmdbId': 15364, 'imdbId': None, 'tvdbId': 96941}
2022/08/16 14:08:34 - Thread-10 - INFO: 媒体趋势榜单更新完毕
```

### 健康检查

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/33413681/184811143-bb87d69a-3ccd-4e6b-82a1-a232fc16fe67.png">

**Comment by pofey** [comment]
跟plex的媒体id查询机制有关系，但五千这个量，内网问题不大，云库就不好说了

**Comment by EndlessJY** [comment]
这个有什么优化机制么？我理解用云库的有很大一部分群体

**Comment by EndlessJY** [comment]
> 跟plex的媒体id查询机制有关系，但五千这个量，内网问题不大，云库就不好说了


这个有什么优化机制么？我理解用云库的有很大一部分群体

**Comment by pofey** [comment]
有但短时间不打算去优化

**Comment by EndlessJY** [comment]
> 有但短时间不去优化
衣总，啥时候有时间修修这个呀. 哈哈...
