### ISSUE TITLE
[缺陷]: 下载美剧识别错误

### ISSUE THREAD

**Issue by 522654518** [pofey/movie_robot#595]
### 当前程序版本

1.1.1

### 问题描述

搜索功能订阅美剧看见第一季，订阅其他剧集

### 重现步骤

1.
![image](https://user-images.githubusercontent.com/44149189/185021164-f790c212-af1d-46de-a5ce-1afef0c2e861.png)
2.
![image](https://user-images.githubusercontent.com/44149189/185021298-bd4fc9e1-5678-41ca-9c01-bc04ab54064e.png)
3.搜索看见 点击订阅然后订阅库里出现看见味道的你？  

### 健康检查

系统运行情况极好

**Comment by pofey** [comment]
应该订阅的tmdb信息发一下

**Comment by 522654518** [comment]
> 应该订阅的tmdb信息发一下

https://www.themoviedb.org/tv/80752-see

**Comment by pofey** [comment]
不用更新 重新订阅一下就好了
