### ISSUE TITLE
电视剧link反馈

### ISSUE THREAD

**Issue by mjyhj** [pofey/movie_robot#6]
1.多季度的，全部只能处理 第一季：
INFO: 已处理：半泽直树 (2013) 第1季 源路径: /download3/电视剧/半泽直树 (2013)/Season 1
ERROR: 识别不到影视信息，无法处理 查询词:['半泽直树', '半泽直树', '半泽直树'] src: /download3/电视剧/半泽直树 (2013)/Season 2
![1](https://user-images.githubusercontent.com/22577418/153740579-0c13d039-9ab5-4e26-8ff0-d083bbcf90bd.png)

INFO: 已处理：绝命毒师 (2008) 第1季 源路径: /download3/电视剧/绝命毒师 (2008)/Season 1
ERROR: 识别不到影视信息，无法处理 查询词:['绝命毒师', '绝命毒师', '绝命毒师'] src: /download3/电视剧/绝命毒师 (2008)/Season 2
ERROR: 识别不到影视信息，无法处理 查询词:['绝命毒师', '绝命毒师', '绝命毒师'] src: /download3/电视剧/绝命毒师 (2008)/Season 5
ERROR: 识别不到影视信息，无法处理 查询词:['绝命毒师', '绝命毒师', '绝命毒师'] src: /download3/电视剧/绝命毒师 (2008)/Season 3
ERROR: 识别不到影视信息，无法处理 查询词:['绝命毒师', '绝命毒师', '绝命毒师'] src: /download3/电视剧/绝命毒师 (2008)/Season 4

INFO: 已处理：权力的游戏 (2011) 第1季 源路径: /download3/电视剧/权力的游戏 (2011)/Season 1
ERROR: 识别不到影视信息，无法处理 查询词:['权力的游戏', '权力的游戏', '权力的游戏'] src: /download3/电视剧/权力的游戏 (2011)/Season 2
ERROR: 识别不到影视信息，无法处理 查询词:['权力的游戏', '权力的游戏', '权力的游戏'] src: /download3/电视剧/权力的游戏 (2011)/Season 5
ERROR: 识别不到影视信息，无法处理 查询词:['权力的游戏', '权力的游戏', '权力的游戏'] src: /download3/电视剧/权力的游戏 (2011)/Season 3
ERROR: 识别不到影视信息，无法处理 查询词:['权力的游戏', '权力的游戏', '权力的游戏'] src: /download3/电视剧/权力的游戏 (2011)/Season 4
ERROR: 识别不到影视信息，无法处理 查询词:['权力的游戏', '权力的游戏', '权力的游戏'] src: /download3/电视剧/权力的游戏 (2011)/Season 8
ERROR: 识别不到影视信息，无法处理 查询词:['权力的游戏', '权力的游戏', '权力的游戏'] src: /download3/电视剧/权力的游戏 (2011)/Season 6
ERROR: 识别不到影视信息，无法处理 查询词:['权力的游戏', '权力的游戏', '权力的游戏'] src: /download3/电视剧/权力的游戏 (2011)/Season 7

2. 识别错误的：
ERROR: 这是啥？/download3/电视剧/无证之罪 (2017)/Season 1
![2](https://user-images.githubusercontent.com/22577418/153740613-d53badf3-1f4a-4c64-8e14-0c181faa3ac7.png)
![4](https://user-images.githubusercontent.com/22577418/153740836-6e309fd2-ad45-4a68-8207-a351e6f78793.png)
![5](https://user-images.githubusercontent.com/22577418/153740840-587d0fd7-5507-44f7-9e0d-80d9ae77a8b9.png)

可过滤：片尾曲 宣传曲 主题曲 等等

ERROR: 识别不到影视信息，无法处理 查询词:['kimetsu no yaiba yuukaku-hen'] src: /download3/电视剧/Kimetsu.no.Yaiba.Yuukaku-hen.2021.Crunchyroll.WEB-DL.1080p.x264.AAC-HDCTV
![3](https://user-images.githubusercontent.com/22577418/153740629-0fdc8b11-19e9-4a4a-be10-d4cff557e1d8.png)

3. 直播源过滤处理吧，或者直接硬链过来或者不处理就好
ERROR: 未识别的文件类型：/download3/电视剧/gdtvlist-http.m3u

**Comment by pofey** [comment]
ERROR: 识别不到影视信息，无法处理 查询词:['kimetsu no yaiba yuukaku-hen'] src: /download3/电视剧/Kimetsu.no.Yaiba.Yuukaku-hen.2021.Crunchyroll.WEB-DL.1080p.x264.AAC-HDCTV
这个剧tmdb手也搜不到，其他bug，正在修复，下一个版本修复

**Comment by mjyhj** [comment]
> ERROR: 识别不到影视信息，无法处理 查询词:['kimetsu no yaiba yuukaku-hen'] src: /download3/电视剧/Kimetsu.no.Yaiba.Yuukaku-hen.2021.Crunchyroll.WEB-DL.1080p.x264.AAC-HDCTV 这个剧tmdb手也搜不到，其他bug，正在修复，下一个版本修复

因为关键词是kimetsu no yaiba， 后面的是篇章
https://www.themoviedb.org/tv/85937/season/3

**Comment by pofey** [comment]
新版已经全部修复
