### ISSUE TITLE
无法正常读取豆瓣数据

### ISSUE THREAD

**Issue by laobanbiefangcu** [pofey/movie_robot#60]
添加完cookie，查看日志发现无法获取豆瓣数据。换了一个浏览器登陆账号，或者是修改密码后重新登录，还是同样无法获取数据

使用其他nastool，vertex可以正常获取数据

<a href="https://imgtu.com/i/L2WOMR"><img src="https://s1.ax1x.com/2022/04/22/L2WOMR.png" alt="L2WOMR.png" border="0" /></a>

**Comment by laobanbiefangcu** [comment]
换了个账号，添加想看的电影后，会提示没有任何订阅记录
<a href="https://imgtu.com/i/LRETu4"><img src="https://s1.ax1x.com/2022/04/22/LRETu4.png" alt="LRETu4.png" border="0" /></a>

**Comment by pofey** [comment]
检查版本号，以及在你的ip下访问豆瓣，看是否被豆瓣ban了。可以通过换ip和浏览器换退出豆瓣重新登陆换ck的方式解决
