### ISSUE TITLE
[优化]: 希望提供对网盘的支持

### ISSUE THREAD

**Issue by JackieDark** [pofey/movie_robot#601]
### 你的建议

首先感谢作者提供这么方便的媒体工具。

我认识的很多人都是通过 Rclone 挂载 Google Driver这种模式自建的媒体库，但目前工具不支持 rclone copy模式。我目前的方案是整理好的文件都放在服务器本地，然后写了个定时脚本，定时通过命令 rclone copy 那个整理好的目录到谷歌盘。这种方式无法使用 robot 的自动更新媒体库机制。

我的建议是可以提供 rclone copy 和 rclone move 这两个整理文件移动模式，对应系统的 copy 和 mv

希望以后作者可以支持到这个方案哈。

### 优先级

非常高

### 受众范围

很多人需要

**Comment by htnanako** [comment]
你是不是不会rclone mount🤔

**Comment by htnanako** [comment]
> 肯定会呀，不然怎么挂载的，直接copy到挂载盘很慢，而且会导致偶尔播放不了

并不会 我用的非常稳 自己研究mount的参数吧

**Comment by pofey** [comment]
这本身应该不是什么难事，但我不认为这是程序层面该去解决的问题
