### ISSUE TITLE
[优化]: 增加订阅页面中订阅用户的增加/修改的设置

### ISSUE THREAD

**Issue by zwf19870623** [pofey/movie_robot#604]
### 当前现状

目前逻辑是微信绑定后谁订阅就推送给谁，网页是哪个用户就推送给谁。
但我有一个应用场景，比如我老婆/朋友比较懒，让我帮忙订阅，我只能登录他的账号去订阅，不然下载完他收不到推送。

### 你的建议

在订阅页面的订阅影片上可以有一个下拉菜单勾选推送的人，默认是订阅者，可以更改。如果勾选多人下载完成后可以进行多人推送。

### 优先级

一般

### 受众范围

一般

**Comment by zwf19870623** [comment]
![11111](https://user-images.githubusercontent.com/49951252/185398627-d5985e8e-b98d-4a2a-a875-964ff568f34f.jpg)

能力有限，做了一张图，大概是这个意思，小三角点一下是个下拉菜单可以点选。

**Comment by pofey** [comment]
在配置文件的server项目下，加一个push_to_everyone: True 就会不管谁订阅都推所有人
server:
  push_to_everyone: True
