### ISSUE TITLE
[缺陷]: 订阅报错

### ISSUE THREAD

**Issue by sinosofti** [pofey/movie_robot#609]
### 当前程序版本

beta

### 问题描述

首页点击订阅提示订阅失败

### 重现步骤

首页点击订阅提示订阅失败
![image](https://user-images.githubusercontent.com/38282416/185529834-d6911f16-773e-47f0-a219-05b8efda71de.png)
![image](https://user-images.githubusercontent.com/38282416/185529617-180ee318-7b0a-4d43-b829-01ee288a33c5.png)

### 健康检查

全部100%

**Comment by pofey** [comment]
你这个版本号是多少，我觉得肯定是旧版

**Comment by sinosofti** [comment]
1.1.4

**Comment by pofey** [comment]
我无法在我的最新代码重现这个问题
