### ISSUE TITLE
不知道为什么订阅下载失败附log

### ISSUE THREAD

**Issue by lalasou** [pofey/movie_robot#61]
2022/04/23 00:18:32 - Thread-4 - INFO: 开始获取17****875(do) 365天内的电影
172.17.0.1 - - [2022-04-23 00:18:32] "GET /api/task/run?name=smart_download_task HTTP/1.1" 200 184 0.004263
2022/04/23 00:18:33 - Thread-4 - INFO: 开始获取17****875(wish) 365天内的电影
2022/04/23 00:18:33 - Thread-4 - INFO: 豆瓣用户179219875的想看列表开始同步到订阅记录。
2022/04/23 00:18:41 - Thread-4 - ERROR: 青春变形记(2022 订阅失败，请查看日志分析原因。

Traceback (most recent call last):
File "yee/service/smartdownloadservice.py", line 281, in yee.service.smartdownloadservice.SmartDownloadService.sub_from_douban
File "yee/service/smartdownloadservice.py", line 34, in yee.service.smartdownloadservice.SmartDownloadService.exists
AttributeError: 'NoneType' object has no attribute 'search_by_id'
172.17.0.1 - - [2022-04-23 00:18:41] "GET /api/user/count_unread_sys_notify HTTP/1.1" 200 162 0.007047
172.17.0.1 - - [2022-04-23 00:18:51] "GET /api/user/count_unread_sys_notify HTTP/1.1" 200 162 0.005019
2022/04/23 00:19:00 - Thread-4 - ERROR: 国王排名(2021 订阅失败，请查看日志分析原因。

Traceback (most recent call last):
File "yee/service/smartdownloadservice.py", line 281, in yee.service.smartdownloadservice.SmartDownloadService.sub_from_douban
File "yee/service/smartdownloadservice.py", line 34, in yee.service.smartdownloadservice.SmartDownloadService.exists
AttributeError: 'NoneType' object has no attribute 'search_by_id'
2022/04/23 00:19:00 - Thread-4 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
2022/04/23 00:19:00 - Thread-4 - INFO: 没有任何订阅记录需要进行智能下载。
不知道qb 连接正常啊  我也搞不定了

**Comment by lalasou** [comment]
下载记录 也显示不出来....

**Comment by pofey** [comment]
> 2022/04/23 00:18:32 - Thread-4 - INFO: 开始获取17****875(do) 365天内的电影 172.17.0.1 - - [2022-04-23 00:18:32] "GET /api/task/run?name=smart_download_task HTTP/1.1" 200 184 0.004263 2022/04/23 00:18:33 - Thread-4 - INFO: 开始获取17****875(wish) 365天内的电影 2022/04/23 00:18:33 - Thread-4 - INFO: 豆瓣用户179219875的想看列表开始同步到订阅记录。 2022/04/23 00:18:41 - Thread-4 - ERROR: 青春变形记(2022 订阅失败，请查看日志分析原因。
> 
> Traceback (most recent call last): File "yee/service/smartdownloadservice.py", line 281, in yee.service.smartdownloadservice.SmartDownloadService.sub_from_douban File "yee/service/smartdownloadservice.py", line 34, in yee.service.smartdownloadservice.SmartDownloadService.exists AttributeError: 'NoneType' object has no attribute 'search_by_id' 172.17.0.1 - - [2022-04-23 00:18:41] "GET /api/user/count_unread_sys_notify HTTP/1.1" 200 162 0.007047 172.17.0.1 - - [2022-04-23 00:18:51] "GET /api/user/count_unread_sys_notify HTTP/1.1" 200 162 0.005019 2022/04/23 00:19:00 - Thread-4 - ERROR: 国王排名(2021 订阅失败，请查看日志分析原因。
> 
> Traceback (most recent call last): File "yee/service/smartdownloadservice.py", line 281, in yee.service.smartdownloadservice.SmartDownloadService.sub_from_douban File "yee/service/smartdownloadservice.py", line 34, in yee.service.smartdownloadservice.SmartDownloadService.exists AttributeError: 'NoneType' object has no attribute 'search_by_id' 2022/04/23 00:19:00 - Thread-4 - INFO: 本次豆瓣想看同步到订阅任务已经完成。 2022/04/23 00:19:00 - Thread-4 - INFO: 没有任何订阅记录需要进行智能下载。 不知道qb 连接正常啊 我也搞不定了

首先检查emby或plex是否正常，其次重启机器人。

你的问题是启动时没有正常加载媒体服务器，启动应该就报错了的。

**Comment by lalasou** [comment]
好了 


还有个问题 emby 新安装提供api了  是手动添加好媒体库 ？
添加的媒体库是硬链接之后的那个

**Comment by pofey** [comment]
> 好了
> 
> 还有个问题 emby 新安装提供api了 是手动添加好媒体库 ？ 添加的媒体库是硬链接之后的那个

没看懂

**Comment by lalasou** [comment]
..额  emby那边需要设置什么   除了提供apitoken

**Comment by pofey** [comment]
> ..额 emby那边需要设置什么 除了提供apitoken

没了
