### ISSUE TITLE
[缺陷]: 站点统计页面下无数据

### ISSUE THREAD

**Issue by NotwoJack** [pofey/movie_robot#610]
### 当前程序版本

1.0

### 问题描述

目前添加了，HDAtoms HDTime。可以获取到上传下载总量，但是无每日的统计数据。
初步怀疑为数据未持久化到本地内存。

### 重现步骤

![image](https://user-images.githubusercontent.com/38264629/185536726-41da4ca6-1ac3-4f52-acf4-92146ef3fa1c.png)

### 健康检查

![image](https://user-images.githubusercontent.com/38264629/185536999-27d1a608-33bb-4c45-89b0-3e4848f7535c.png)

**Comment by pofey** [comment]
T+1 次日更新
