### ISSUE TITLE
[优化]: 建议刮削的nfo信息中<sorttitle> </sorttitle>字段使用拼音首字母缩写以支持emby中拼音首字母排序

### ISSUE THREAD

**Issue by MagicCheshireMeow** [pofey/movie_robot#611]
### 当前现状

当前nfo信息中 sorttitle 字段使用的是完整影视名称，在emby中无法按照拼音首字母排序，而emby的汉字排序非常不方便。

### 你的建议

　　经过反复对比查看确认将nfo信息中的 sorttitle 字段内容修改为影视名称的拼音首字母缩写，在emby中即为对应修改了元数据信息的类名，然后emby就会以此作为首字母排序的依据，这样无论是视觉效果上还是使用便利性上都有极大的提升。

　　目前需要第三方工具批量修改或者手动逐个修改，希望MR后续能直接在刮削的时候就实现识别转换影视名称首字母缩写并写入 sorttitle 中，能进一步提升体验。

　　感谢阅读！

### 优先级

一般

### 受众范围

很多人需要

**Comment by pofey** [comment]
极端情况下的英文电影名呢？也取单词的首字母吗

**Comment by pofey** [comment]
先改一版试试吧，中文拼音首字母，英文不动
