### ISSUE TITLE
自建影视数据错误反馈贴

### ISSUE THREAD

**Issue by pofey** [pofey/movie_robot#612]
系统已经逐步开启自建的影片元数据库，因为初期的数据构建完全由自动化录入，豆瓣、themoviedb、imdb等关系也是自动识别的，难免会有错误或者缺失。比如自建的Netflix榜单，就是全自动识别的，我注意到有些订阅会缺季度。如果还有其他，比如订阅了A，显示和下载成了B，这种也算错误，请集中反馈到这里，我集中订正错误数据。
具体反馈的形式也比较简单，给出两个正确的豆瓣链接和TMDB链接即可
如：风骚律师第六季
豆瓣：https://movie.douban.com/subject/34951007/
TMDB：https://www.themoviedb.org/tv/60059-better-call-saul
如果有缺失的季，也是给出对应关系就可以

**Comment by tcmdtc** [comment]
龙族第一季
豆瓣：https://movie.douban.com/subject/35170003/
TMDB：https://www.themoviedb.org/tv/107255

**Comment by xmumeyu** [comment]
机器人大战  第一季、第二季（不识别）
豆瓣： https://movie.douban.com/subject/26564336/
           https://movie.douban.com/subject/26786973/

TMDB：https://www.themoviedb.org/tv/62959-battlebots

机器人大战 第四季、第五季（订阅后默认显示下载完成，影库内没内容，下载器没记录，删除订阅状态也不成功，深度删除操作还能会其他已下载的季删除了）
豆瓣：https://movie.douban.com/subject/33950324/
           https://movie.douban.com/subject/35271106/

**Comment by mjyhj** [comment]
一路向西
https://www.themoviedb.org/movie/134764


1.2.13以前，开启了中文演员，因为豆瓣删了这个片，自然就没有图片
但是升级1.2.13后，直接重新识别，和手动纠错，都识别成 一路向北
一路向北 (2012) [tmdbid=134764]，ID倒是对的，nfo也是错的

**Comment by mjyhj** [comment]
我是格鲁特 I Am Groot (2022)
豆瓣是剧集：https://movie.douban.com/subject/35284249/
TMDB是电影：https://www.themoviedb.org/movie/1010823-magnum-opus

**Comment by pofey** [comment]
> 
哪看出来不识别的，我查了下这部剧的数据关系是对的

**Comment by pofey** [comment]
> 机器人大战 第一季、第二季（不识别） 豆瓣： https://movie.douban.com/subject/26564336/ https://movie.douban.com/subject/26786973/
> 
> TMDB：https://www.themoviedb.org/tv/62959-battlebots
> 
> 机器人大战 第四季、第五季（订阅后默认显示下载完成，影库内没内容，下载器没记录，删除订阅状态也不成功，深度删除操作还能会其他已下载的季删除了） 豆瓣：https://movie.douban.com/subject/33950324/ https://movie.douban.com/subject/35271106/


哪看出来不识别的，我查了下这部剧的数据关系是对的

**Comment by HelIwalker** [comment]
消失的孩子

豆瓣：https://movie.douban.com/subject/35235616/

tmdb：https://www.themoviedb.org/tv/209133-the-disappearing-child

下载完不识别，手动识别后，会重复提交之前的下载

**Comment by mjyhj** [comment]
鬼灭之刃
豆瓣：   https://movie.douban.com/subject/35620761/ 无限列车篇
              https://movie.douban.com/subject/34813210/ 遊郭編 
TMDB：https://www.themoviedb.org/tv/85937/seasons


豆瓣里是直接把篇章分开作为独立的剧集，TMDB是一个剧集里不同的篇章作为多个不同的季

手动纠错导致识别成，文件夹按豆瓣那样分开。
里面的season则变成按TMDB排列

![1](https://user-images.githubusercontent.com/22577418/187973561-a3062fad-0167-40d6-86c6-0b61a03269fb.png)

**Comment by HelIwalker** [comment]
奉天白事铺

TMDB：https://www.themoviedb.org/movie/1019659
豆瓣：https://movie.douban.com/subject/36075494/

不识别，归类到了unknown

**Comment by pofey** [comment]
> 奉天白事铺
> 
> TMDB：https://www.themoviedb.org/movie/1019659 豆瓣：https://movie.douban.com/subject/36075494/
> 
> 不识别，归类到了unknown

反馈数据错误 不是识别问题

**Comment by zjxzhdbl** [comment]
鬼吹灯之九层妖塔
豆瓣：https://movie.douban.com/subject/24827406/?dt_dapp=1
tmdb：https://www.themoviedb.org/movie/364324
