### ISSUE TITLE
[提问]: 排序文件，怎么通过压制组排序

### ISSUE THREAD

**Issue by 522654518** [pofey/movie_robot#616]
### 当前程序版本

1.1.1

### 问题

自动排序文件里，只有存储介质-source，分辨率-resolution，编码-codec这三种规则进行评分排序，请问压制小组对应的英文key应该是什么呢？压制小组=？，我想优先下载wiki，frds的种子，谢谢大佬

**Comment by pofey** [comment]
还有个关键字优先 压制组不能打分

**Comment by 522654518** [comment]
> 还有个关键字优先 压制组不能打分

可是也没找到namekeyword的模板，不知道结构应该啥样

**Comment by pofey** [comment]
> > 还有个关键字优先 压制组不能打分
> 
> 可是也没找到namekeyword的模板，不知道结构应该啥样

群里疯子的分享 应该有吧，他好像用了关键字打分的结构

**Comment by 522654518** [comment]
> 

我啥群都没有啊，求个群号，我去里边学习一下
