### ISSUE TITLE
[缺陷]: 存量整理手动设定季数失效

### ISSUE THREAD

**Issue by haha6311** [pofey/movie_robot#617]
### 当前程序版本

1.1.4

### 问题描述

存量整理**剧集**《还珠格格》第二部（1999） 该季共48集【TMDB数据库里是《还珠格格》——>第2季】
https://www.themoviedb.org/tv/4285-princess-pearl

源文件夹及内部文件命名格式如下：
`Princess.Pearl.II.1999.WEB-DL.1080p.H265.AAC-HDCTV`
`Princess.Pearl.II.1999.E08.WEB-DL.1080p.H265.AAC-HDCTV.mkv`

走**自动纠错**设置如下：
![image](https://user-images.githubusercontent.com/36618980/185773535-e1a9fb6e-7d2f-4a8f-8374-e38461ab6950.png)
【走**自动纠错**的原因是：这个英文命名走**自动整理**识别不出来】

设定的季数无法生效，依然识别成第一部【第一部只有24集啊QAQ，干出来48集...】

### 重现步骤

如上

### 发生问题时系统日志

```shell
2022/08/21 11:08:48 - Thread-2657 - INFO: 完成剧集 还珠格格 的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/tvshow.nfo
2022/08/21 11:08:49 - Thread-2657 - INFO: 完成剧集 第48集(None) 第1季第48集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E48 - 1080p H.265.nfo
2022/08/21 11:08:52 - Thread-2657 - INFO: 完成剧集 第 5 集(1998) 第1季第5集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E05 - 1080p H.265.nfo
2022/08/21 11:08:56 - Thread-2657 - INFO: 完成剧集 第35集(None) 第1季第35集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E35 - 1080p H.265.nfo
2022/08/21 11:08:51 - Thread-2657 - INFO: 完成剧集 第 16 集(1998) 第1季第16集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E16 - 1080p H.265.nfo
2022/08/21 11:08:54 - Thread-2657 - INFO: 完成剧集 第 13 集(1998) 第1季第13集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E13 - 1080p H.265.nfo
2022/08/21 11:08:59 - Thread-2657 - INFO: 完成剧集 第 14 集(1998) 第1季第14集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E14 - 1080p H.265.nfo
2022/08/21 11:09:01 - Thread-2657 - INFO: 完成剧集 第42集(None) 第1季第42集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E42 - 1080p H.265.nfo
2022/08/21 11:09:04 - Thread-2657 - INFO: 完成剧集 第 2 集(1998) 第1季第2集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E02 - 1080p H.265.nfo
2022/08/21 11:09:05 - Thread-2657 - INFO: 完成剧集 第27集(None) 第1季第27集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E27 - 1080p H.265.nfo
2022/08/21 11:09:07 - Thread-2657 - INFO: 完成剧集 第40集(None) 第1季第40集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E40 - 1080p H.265.nfo
2022/08/21 11:09:10 - Thread-2657 - INFO: 完成剧集 第44集(None) 第1季第44集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E44 - 1080p H.265.nfo
2022/08/21 11:09:11 - Thread-2657 - INFO: 完成剧集 第 22 集(1998) 第1季第22集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E22 - 1080p H.265.nfo
2022/08/21 11:09:12 - Thread-2657 - INFO: 完成剧集 第 12 集(1998) 第1季第12集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E12 - 1080p H.265.nfo
2022/08/21 11:09:14 - Thread-2657 - INFO: 完成剧集 第25集(None) 第1季第25集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E25 - 1080p H.265.nfo
2022/08/21 11:09:16 - Thread-2657 - INFO: 完成剧集 第43集(None) 第1季第43集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E43 - 1080p H.265.nfo
2022/08/21 11:09:17 - Thread-2657 - INFO: 完成剧集 第46集(None) 第1季第46集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E46 - 1080p H.265.nfo
2022/08/21 11:09:19 - Thread-2657 - INFO: 完成剧集 第34集(None) 第1季第34集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E34 - 1080p H.265.nfo
2022/08/21 11:09:20 - Thread-2657 - INFO: 完成剧集 第39集(None) 第1季第39集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E39 - 1080p H.265.nfo
2022/08/21 11:09:22 - Thread-2657 - INFO: 完成剧集 第47集(None) 第1季第47集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E47 - 1080p H.265.nfo
2022/08/21 11:09:24 - Thread-2657 - INFO: 完成剧集 第41集(None) 第1季第41集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E41 - 1080p H.265.nfo
2022/08/21 11:09:26 - Thread-2657 - INFO: 完成剧集 第 1 集(1998) 第1季第1集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E01 - 1080p H.265.nfo
2022/08/21 11:09:26 - Thread-2657 - INFO: 完成剧集 第 8 集(1998) 第1季第8集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E08 - 1080p H.265.nfo
2022/08/21 11:09:28 - Thread-2657 - INFO: 完成剧集 第38集(None) 第1季第38集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E38 - 1080p H.265.nfo
2022/08/21 11:09:29 - Thread-2657 - INFO: 完成剧集 第 20 集(1998) 第1季第20集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E20 - 1080p H.265.nfo
2022/08/21 11:09:31 - Thread-2657 - INFO: 完成剧集 第28集(None) 第1季第28集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E28 - 1080p H.265.nfo
2022/08/21 11:09:32 - Thread-2657 - INFO: 完成剧集 第 9 集(1998) 第1季第9集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E09 - 1080p H.265.nfo
2022/08/21 11:09:34 - Thread-2657 - INFO: 完成剧集 第31集(None) 第1季第31集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E31 - 1080p H.265.nfo
2022/08/21 11:09:35 - Thread-2657 - INFO: 完成剧集 第 7 集(1998) 第1季第7集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E07 - 1080p H.265.nfo
2022/08/21 11:09:36 - Thread-2657 - INFO: 完成剧集 第 17 集(1998) 第1季第17集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E17 - 1080p H.265.nfo
2022/08/21 11:09:38 - Thread-2657 - INFO: 完成剧集 第 10 集(1998) 第1季第10集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E10 - 1080p H.265.nfo
2022/08/21 11:09:39 - Thread-2657 - INFO: 完成剧集 第45集(None) 第1季第45集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E45 - 1080p H.265.nfo
2022/08/21 11:09:40 - Thread-2657 - INFO: 完成剧集 第 4 集(1998) 第1季第4集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E04 - 1080p H.265.nfo
2022/08/21 11:09:42 - Thread-2657 - INFO: 完成剧集 第30集(None) 第1季第30集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E30 - 1080p H.265.nfo
2022/08/21 11:09:43 - Thread-2657 - INFO: 完成剧集 第 11 集(1998) 第1季第11集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E11 - 1080p H.265.nfo
2022/08/21 11:09:44 - Thread-2657 - INFO: 完成剧集 第29集(None) 第1季第29集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E29 - 1080p H.265.nfo
2022/08/21 11:09:46 - Thread-2657 - INFO: 完成剧集 第 15 集(1998) 第1季第15集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E15 - 1080p H.265.nfo
2022/08/21 11:09:47 - Thread-2657 - INFO: 完成剧集 第37集(None) 第1季第37集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E37 - 1080p H.265.nfo
2022/08/21 11:09:49 - Thread-2657 - INFO: 完成剧集 第36集(None) 第1季第36集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E36 - 1080p H.265.nfo
2022/08/21 11:09:50 - Thread-2657 - INFO: 完成剧集 第32集(None) 第1季第32集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E32 - 1080p H.265.nfo
2022/08/21 11:09:52 - Thread-2657 - INFO: 完成剧集 第 6 集(1998) 第1季第6集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E06 - 1080p H.265.nfo
2022/08/21 11:09:53 - Thread-2657 - INFO: 完成剧集 第26集(None) 第1季第26集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E26 - 1080p H.265.nfo
2022/08/21 11:09:56 - Thread-2657 - INFO: 完成剧集 第 21 集(1998) 第1季第21集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E21 - 1080p H.265.nfo
2022/08/21 11:09:57 - Thread-2657 - INFO: 完成剧集 第 23 集(1998) 第1季第23集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E23 - 1080p H.265.nfo
```

### 健康检查

![image](https://user-images.githubusercontent.com/36618980/185773663-192ebe0d-ef4e-4cb0-a22c-3f0189ffc9b8.png)

**Comment by haha6311** [comment]
附上一个可以自动识别的命名：
`还珠格格2.1999.48集全.国语.繁体中字￡CMCT小鱼`
`还珠格格2.E12.1999.DVDRip.x264.AC3-CMCT.mkv`

```
2022/08/21 11:15:09 - Thread-2790 - INFO: 完成剧集 第2季 季 2 的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 2/season.nfo
2022/08/21 11:15:09 - Thread-2790 - INFO: 完成剧集 还珠格格 的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/tvshow.nfo
2022/08/21 11:15:12 - Thread-2790 - INFO: 完成剧集 第 17 集(1999) 第2季第17集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 2/还珠格格 S02E17 - x264 CMCT.nfo
2022/08/21 11:15:14 - Thread-2790 - INFO: 完成剧集 第 3 集(1999) 第2季第3集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 2/还珠格格 S02E03 - x264 CMCT.nfo
2022/08/21 11:15:13 - Thread-2790 - INFO: 完成剧集 第 29 集(1999) 第2季第29集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 2/还珠格格 S02E29 - x264 CMCT.nfo
2022/08/21 11:15:15 - Thread-2790 - INFO: 完成剧集 第 2 集(1999) 第2季第2集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 2/还珠格格 S02E02 - x264 CMCT.nfo
2022/08/21 11:15:19 - Thread-2790 - INFO: 完成剧集 第 44 集(1999) 第2季第44集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 2/还珠格格 S02E44 - x264 CMCT.nfo
2022/08/21 11:15:18 - Thread-2790 - INFO: 完成剧集 第 11 集(1999) 第2季第11集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 2/还珠格格 S02E11 - x264 CMCT.nfo
2022/08/21 11:15:16 - Thread-2790 - INFO: 完成剧集 第 34 集(1999) 第2季第34集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 2/还珠格格 S02E34 - x264 CMCT.nfo
```

**Comment by pofey** [comment]
猜不出原因

**Comment by haha6311** [comment]
> 猜不出原因

会不会是罗马数字“II”妨碍了识别？

**Comment by haha6311** [comment]
如果之后的版本可以利用人工智能按‘.’分词识别的话，感觉这种命名就能应付的来了，期待那一天早日到来

**Comment by haha6311** [comment]
> > 猜不出原因
> 
> 会不会是罗马数字“II”妨碍了识别？

按理说我已经强制的告诉它，剧集及对应季数都不用管，只管给我对好集数就行，但还是识别出错了

**Comment by haha6311** [comment]
> ### 当前程序版本
> 1.1.9
> 
> ### 问题描述
> 存量整理**剧集**《还珠格格》第二部（1999） 该季共48集【TMDB数据库里是《还珠格格》——>第2季】 https://www.themoviedb.org/tv/4285-princess-pearl
> 
> 源文件夹及内部文件命名格式如下： `Princess.Pearl.II.1999.WEB-DL.1080p.H265.AAC-HDCTV` `Princess.Pearl.II.1999.E08.WEB-DL.1080p.H265.AAC-HDCTV.mkv`
> 
> 走**自动纠错**设置如下： ![image](https://user-images.githubusercontent.com/36618980/185773535-e1a9fb6e-7d2f-4a8f-8374-e38461ab6950.png) 【走**自动纠错**的原因是：这个英文命名走**自动整理**识别不出来】
> 
> 设定的季数无法生效，依然识别成第一部【第一部只有24集啊QAQ，干出来48集...】
> 
> ### 重现步骤
> 如上
> 
> ### 发生问题时系统日志
> ```shell
> 2022/08/21 11:08:48 - Thread-2657 - INFO: 完成剧集 还珠格格 的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/tvshow.nfo
> 2022/08/21 11:08:49 - Thread-2657 - INFO: 完成剧集 第48集(None) 第1季第48集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E48 - 1080p H.265.nfo
> 2022/08/21 11:08:52 - Thread-2657 - INFO: 完成剧集 第 5 集(1998) 第1季第5集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E05 - 1080p H.265.nfo
> 2022/08/21 11:08:56 - Thread-2657 - INFO: 完成剧集 第35集(None) 第1季第35集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E35 - 1080p H.265.nfo
> 2022/08/21 11:08:51 - Thread-2657 - INFO: 完成剧集 第 16 集(1998) 第1季第16集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E16 - 1080p H.265.nfo
> 2022/08/21 11:08:54 - Thread-2657 - INFO: 完成剧集 第 13 集(1998) 第1季第13集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E13 - 1080p H.265.nfo
> 2022/08/21 11:08:59 - Thread-2657 - INFO: 完成剧集 第 14 集(1998) 第1季第14集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E14 - 1080p H.265.nfo
> 2022/08/21 11:09:01 - Thread-2657 - INFO: 完成剧集 第42集(None) 第1季第42集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E42 - 1080p H.265.nfo
> 2022/08/21 11:09:04 - Thread-2657 - INFO: 完成剧集 第 2 集(1998) 第1季第2集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E02 - 1080p H.265.nfo
> 2022/08/21 11:09:05 - Thread-2657 - INFO: 完成剧集 第27集(None) 第1季第27集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E27 - 1080p H.265.nfo
> 2022/08/21 11:09:07 - Thread-2657 - INFO: 完成剧集 第40集(None) 第1季第40集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E40 - 1080p H.265.nfo
> 2022/08/21 11:09:10 - Thread-2657 - INFO: 完成剧集 第44集(None) 第1季第44集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E44 - 1080p H.265.nfo
> 2022/08/21 11:09:11 - Thread-2657 - INFO: 完成剧集 第 22 集(1998) 第1季第22集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E22 - 1080p H.265.nfo
> 2022/08/21 11:09:12 - Thread-2657 - INFO: 完成剧集 第 12 集(1998) 第1季第12集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E12 - 1080p H.265.nfo
> 2022/08/21 11:09:14 - Thread-2657 - INFO: 完成剧集 第25集(None) 第1季第25集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E25 - 1080p H.265.nfo
> 2022/08/21 11:09:16 - Thread-2657 - INFO: 完成剧集 第43集(None) 第1季第43集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E43 - 1080p H.265.nfo
> 2022/08/21 11:09:17 - Thread-2657 - INFO: 完成剧集 第46集(None) 第1季第46集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E46 - 1080p H.265.nfo
> 2022/08/21 11:09:19 - Thread-2657 - INFO: 完成剧集 第34集(None) 第1季第34集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E34 - 1080p H.265.nfo
> 2022/08/21 11:09:20 - Thread-2657 - INFO: 完成剧集 第39集(None) 第1季第39集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E39 - 1080p H.265.nfo
> 2022/08/21 11:09:22 - Thread-2657 - INFO: 完成剧集 第47集(None) 第1季第47集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E47 - 1080p H.265.nfo
> 2022/08/21 11:09:24 - Thread-2657 - INFO: 完成剧集 第41集(None) 第1季第41集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E41 - 1080p H.265.nfo
> 2022/08/21 11:09:26 - Thread-2657 - INFO: 完成剧集 第 1 集(1998) 第1季第1集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E01 - 1080p H.265.nfo
> 2022/08/21 11:09:26 - Thread-2657 - INFO: 完成剧集 第 8 集(1998) 第1季第8集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E08 - 1080p H.265.nfo
> 2022/08/21 11:09:28 - Thread-2657 - INFO: 完成剧集 第38集(None) 第1季第38集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E38 - 1080p H.265.nfo
> 2022/08/21 11:09:29 - Thread-2657 - INFO: 完成剧集 第 20 集(1998) 第1季第20集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E20 - 1080p H.265.nfo
> 2022/08/21 11:09:31 - Thread-2657 - INFO: 完成剧集 第28集(None) 第1季第28集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E28 - 1080p H.265.nfo
> 2022/08/21 11:09:32 - Thread-2657 - INFO: 完成剧集 第 9 集(1998) 第1季第9集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E09 - 1080p H.265.nfo
> 2022/08/21 11:09:34 - Thread-2657 - INFO: 完成剧集 第31集(None) 第1季第31集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E31 - 1080p H.265.nfo
> 2022/08/21 11:09:35 - Thread-2657 - INFO: 完成剧集 第 7 集(1998) 第1季第7集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E07 - 1080p H.265.nfo
> 2022/08/21 11:09:36 - Thread-2657 - INFO: 完成剧集 第 17 集(1998) 第1季第17集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E17 - 1080p H.265.nfo
> 2022/08/21 11:09:38 - Thread-2657 - INFO: 完成剧集 第 10 集(1998) 第1季第10集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E10 - 1080p H.265.nfo
> 2022/08/21 11:09:39 - Thread-2657 - INFO: 完成剧集 第45集(None) 第1季第45集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E45 - 1080p H.265.nfo
> 2022/08/21 11:09:40 - Thread-2657 - INFO: 完成剧集 第 4 集(1998) 第1季第4集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E04 - 1080p H.265.nfo
> 2022/08/21 11:09:42 - Thread-2657 - INFO: 完成剧集 第30集(None) 第1季第30集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E30 - 1080p H.265.nfo
> 2022/08/21 11:09:43 - Thread-2657 - INFO: 完成剧集 第 11 集(1998) 第1季第11集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E11 - 1080p H.265.nfo
> 2022/08/21 11:09:44 - Thread-2657 - INFO: 完成剧集 第29集(None) 第1季第29集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E29 - 1080p H.265.nfo
> 2022/08/21 11:09:46 - Thread-2657 - INFO: 完成剧集 第 15 集(1998) 第1季第15集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E15 - 1080p H.265.nfo
> 2022/08/21 11:09:47 - Thread-2657 - INFO: 完成剧集 第37集(None) 第1季第37集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E37 - 1080p H.265.nfo
> 2022/08/21 11:09:49 - Thread-2657 - INFO: 完成剧集 第36集(None) 第1季第36集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E36 - 1080p H.265.nfo
> 2022/08/21 11:09:50 - Thread-2657 - INFO: 完成剧集 第32集(None) 第1季第32集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E32 - 1080p H.265.nfo
> 2022/08/21 11:09:52 - Thread-2657 - INFO: 完成剧集 第 6 集(1998) 第1季第6集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E06 - 1080p H.265.nfo
> 2022/08/21 11:09:53 - Thread-2657 - INFO: 完成剧集 第26集(None) 第1季第26集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E26 - 1080p H.265.nfo
> 2022/08/21 11:09:56 - Thread-2657 - INFO: 完成剧集 第 21 集(1998) 第1季第21集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E21 - 1080p H.265.nfo
> 2022/08/21 11:09:57 - Thread-2657 - INFO: 完成剧集 第 23 集(1998) 第1季第23集的NFO文件生成，路径：/video/剧集/还珠格格 (1998) [tmdbid=4285]/Season 1/还珠格格 S01E23 - 1080p H.265.nfo
> ```
> 
> ### 健康检查
> ![image](https://user-images.githubusercontent.com/36618980/185773663-192ebe0d-ef4e-4cb0-a22c-3f0189ffc9b8.png)

程序版本写错了，更正一下
