### ISSUE TITLE
[缺陷]: 过滤器搜索不到正确的种子

### ISSUE THREAD

**Issue by 522654518** [pofey/movie_robot#619]
### 当前程序版本

1.1.1

### 问题描述

过滤器过滤掉了正确的种子

### 重现步骤

1.订阅美剧 夜魔侠 第三季 
2.日志2022/08/22 11:24:48 - SubConsumer - INFO: 已经开始在站点: 听听歌,观众,备胎,铂金家,RARBG 搜索: 夜魔侠,Marvel's Daredevil,tt5902120
2022/08/22 11:25:04 - ThreadPoolExecutor-3_1 - WARNING: Using 'https' instead of requested 'http' to communicate with qBittorrent
2022/08/22 11:25:07 - SubConsumer - INFO: 共在5个站点搜索到71条结果，其中铂金家最慢，耗费19.21秒
2022/08/22 11:25:07 - SubConsumer - INFO: 夜魔侠(2015) 已经有搜索结果，但经过你设定的过滤器后，无任何结果。
3.过滤器设置
![Uploading image.png…]()
4.通过web搜索可以看到是有符合要求的种子的
![Uploading image.png…]()

### 健康检查

状态极好

**Comment by 522654518** [comment]
图片挂了，补充过滤器设置
![image](https://user-images.githubusercontent.com/44149189/185833660-9d7f7cd2-a7dd-4b0e-9711-3036ba3eeea9.png)
补充web搜索
![image](https://user-images.githubusercontent.com/44149189/185833733-94e4bc58-95b9-480b-8b9e-dab3b7ec0884.png)
可以看到是有符合要求的种子

**Comment by 522654518** [comment]
web搜索 手动下载frds的夜魔侠第三季种子  
![image](https://user-images.githubusercontent.com/44149189/185836640-49f2e0f8-9aeb-4144-a22a-002f282cbd86.png)
在下载记录里，被识别成了另外一个美剧3-Day Dare
好像是刮削的问题，可能不是过滤器的问题

**Comment by pofey** [comment]
但经过你设定的过滤器后 没有结果
看到这个日志 就不查了，这种问题排查起来非常消耗时间，最终能找到一个符合逻辑的解释，但程序也没啥改动空间了
