### ISSUE TITLE
[提问]: 媒体路径设置修改无效

### ISSUE THREAD

**Issue by EasonGaoDevelop** [pofey/movie_robot#621]
### 当前程序版本

1.1.1

### 问题

媒体路径一开始设置的 /downloads/videos/Movie-collect/  后改成了 /downloads/Movie-collect/，重启过容器，日志报错

### 发生问题时系统日志

```shell
chdbits-downloader - ERROR: 找不到/downloads/videos/Movie-collect/对应的媒体路径设置，请检查基础设置-存储路径设置，以及思考你是否变更过设置。
```

**Comment by EasonGaoDevelop** [comment]
修改base config 文件可以修复

**Comment by pofey** [comment]
历史记录也有可能被记录到下载记录表里了 得删下载记录
