### ISSUE TITLE
[优化]: name_ignore_words.txt 文件更新建议

### ISSUE THREAD

**Issue by mymoonyue** [pofey/movie_robot#622]
### 当前现状

有些站点（如彩虹岛）的官种喜欢在剧名前加 “JADE”、“AOD”、“美剧：”、“韩剧：”、“日剧：”等前缀，导致mr识别不了

<img width="211" alt="image" src="https://user-images.githubusercontent.com/60549575/186063285-54ad4ab6-7447-44f7-ba7c-8e31ae056cb0.png">

比如这个 **“韩剧：黑话律师”** 识别成了 **“：黑话律师”** 多了个冒号，自然也不会被下载，即使手动下载也不会被正确识别整理。

### 你的建议

我自己更新了一下 name_ignore_words.txt 文件，更新后可以准确识别并正常使用了几天

![image](https://user-images.githubusercontent.com/60549575/186063752-5ec91d03-a354-43f4-bf79-c390c7d4d88e.png)

但是昨晚mr更新了版本，导致这个文件被默认的覆盖了。希望老板能更新一下，这样其他人也会受益。

文件附上：
[name_ignore_words.txt](https://github.com/pofey/movie_robot/files/9399151/name_ignore_words.txt)

### 优先级

非常高

### 受众范围

很多人需要

**Comment by pofey** [comment]
你能玩到这个文件了，还是厉害的

**Comment by mymoonyue** [comment]
> 你能玩到这个文件了，还是厉害的

衣总，求更新😃

**Comment by pofey** [comment]
你都在这里加了啥词？

**Comment by mymoonyue** [comment]
> 你都在这里加了啥词？

美剧：
英剧：
法剧：
俄剧：
港劇:
港劇：
港剧：
台剧：
日剧：
韩剧：
泰剧：
马来西亚剧集：
马来西亚剧集
AOD


主要参考了彩虹岛和馒头的，其中港劇中英文冒号都有，其他都是中文冒号。有些发布组还喜欢在港剧种子英文名前面加JADE和AOD，JADE我看有了，自己补了一个AOD。

上面有发过完整文件👆🏻👆🏻👆🏻

**Comment by mymoonyue** [comment]
> 你都在这里加了啥词？

还有个问题就是带冒号的一定要放在不带冒号的前面，我猜测这个是从上往下匹配的，如果先匹配到不带冒号的比如“港剧”，就会忽略港剧这个词导致匹配不到“港剧：”

**Comment by pofey** [comment]
： 这个符号我读美歌词的时候应该是补了的

**Comment by mymoonyue** [comment]
> ： 这个符号我读每个词的时候应该是补了的，你升级前是什么版本啊

发ISSUE时的最新beta版本1.1.9，我看了这个文件上次更新是8月5号，只加了JADE

**Comment by pofey** [comment]
> > ： 这个符号我读每个词的时候应该是补了的，你升级前是什么版本啊
> 
> 发ISSUE时的最新beta版本1.1.9，我看了这个文件上次更新是8月5号，只加了JADE

不是 是程序会自动补特殊标点符号 有点奇怪

**Comment by mymoonyue** [comment]
> > > ： 这个符号我读每个词的时候应该是补了的，你升级前是什么版本啊
> > 
> > 
> > 发ISSUE时的最新beta版本1.1.9，我看了这个文件上次更新是8月5号，只加了JADE
> 
> 不是 是程序会自动补特殊标点符号 有点奇怪

但是现在抓包结果显示确实多了冒号，在微信群里面讨论过，茶茶说改那个文件，我尝试改了以后完美解决并且正常使用了两天，只是每次更新mr以后都会被覆盖

![image](https://user-images.githubusercontent.com/60549575/186410777-ac945617-26d8-43b4-82d9-53fe9c4d448e.png)

**Comment by Alano-i** [comment]
我猜把`/data/conf/words/movie_words/name_ignore_words.txt`映射出来自定义就能解决这个问题
没测试，可以试试。
这样可能会衍生另一个问题：老板更新了这个文件后，你本地这个不会更新。除非重新做一遍。

**Comment by mymoonyue** [comment]
> 我猜把`/data/conf/words/movie_words/name_ignore_words.txt`映射出来自定义就能解决这个问题
> 没测试，可以试试。
> 这样可能会衍生另一个问题：老板更新了这个文件后，你本地这个不会更新。除非重新做一遍。

是映射出来的，也会被覆盖

**Comment by Alano-i** [comment]
你本地的文件也被覆盖了么？

**Comment by mymoonyue** [comment]
> 你本地的文件也被覆盖了么？

是啊

**Comment by Alano-i** [comment]
我映射了另一个文件，没被覆盖，你是怎么映射的

**Comment by mymoonyue** [comment]
你随便改一下这个文件，看下个版本会不会被覆盖就知道了。不可能映射出来的文件就不会被覆盖，那咋更新功能啊。

**Comment by Alano-i** [comment]
我这个文件映射出来很久了，一直更新都没被覆盖
