### ISSUE TITLE
[缺陷]: 推送测试正常，但手动任务完成推送失败。

### ISSUE THREAD

**Issue by xssviggo** [pofey/movie_robot#623]
### 当前程序版本

1.1.9

### 问题描述

![image](https://user-images.githubusercontent.com/61963810/186153022-a878f6d5-446c-491f-acc2-657ef2d77972.png)
![image](https://user-images.githubusercontent.com/61963810/186153787-e2214fc3-fedf-4352-87e0-db4c6afb51ac.png)
![image](https://user-images.githubusercontent.com/61963810/186155788-e47cc5af-e427-4651-a133-177e3a119255.png)
之所以手动下载，订阅出现订阅下载出错
手动测试微信推送正常，识别完成推送报错
图为剧集

### 重现步骤

手动下载的任务，提交到开启监控下载目录的下载器，正确识别并监控，出现推送失败。剧集和电影都出现。图为电影情况复现
![image](https://user-images.githubusercontent.com/61963810/186155253-d78aab81-971c-4b8c-a0a0-ce408bff19e6.png)

### 发生问题时系统日志

```shell
,2022/08/23 20:12:06 - ThreadPoolExecutor-5_1 - INFO: 通知媒体库刷新完成，tmdb_id: 23606 save_path: /download1/movieslink item_id: 3227ce1e069754c594af25ea66d69fc7
,2022/08/23 20:12:06 - ThreadPoolExecutor-5_1 - INFO: 那年夏天，宁静的海(1991)字幕下载 任务已经创建。
,2022/08/23 20:12:06 - ThreadPoolExecutor-5_1 - ERROR: on_event error: NotifyListener event: <mbot.event.events.Event object at 0x7faa4a97ed60>
,Traceback (most recent call last):
,  File "mbot/event/eventbus.py", line 44, in mbot.event.eventbus.EventBus.publish_event
,  File "/app/mbot/event/listener/notifylistener.py", line 107, in on_event
,    'country': MediaMetaUtils.get_country(tmdb_meta, douban_meta),
,  File "mbot/common/mediametautils.py", line 33, in mbot.common.mediametautils.MediaMetaUtils.get_country
,AttributeError: 'NoneType' object has no attribute 'area'
,2022/08/23 20:12:06 - ThreadPoolExecutor-5_1 - INFO: A.Scene.at.the.Sea.1991.BluRay.720p.DD2.0.x264-BMDru处理完毕。
,2022/08/23 20:14:00 - ThreadPoolExecutor-5_0 - INFO: 那年夏天，宁静的海(1991)字幕下载已经提交启动。
,2022/08/23 20:14:00 - SubRequestConsumer - INFO: 那年夏天，宁静的海(1991)字幕下载 任务已经结束。
```

### 健康检查

![image](https://user-images.githubusercontent.com/61963810/186155463-bb855e26-0cb7-4497-96d3-3d038a2a401a.png)

**Comment by pofey** [comment]
修复了 下一版上线
