### ISSUE TITLE
[优化]: 希望可以提供对于MR刮削的选择

### ISSUE THREAD

**Issue by henryl46** [pofey/movie_robot#624]
### 当前现状

目前 在资源下载完成后 mr会自动移动源文件至目标盘同时进行刮削
但是 刮削的海报、logo等差强人意 尤其是当用户需求希望能刮削原发行语言海报时 往往需要人工进行二次校对
如果能将这一步交给更高度自定义的媒体服务器 相信体验会更流畅

### 你的建议

或许是否可以添加一个选项 「是否让mr自动刮削元数据」来提升这个体验呢
感谢

### 优先级

一般

### 受众范围

不确定

**Comment by pofey** [comment]
差强人意是指？有对比细节么

**Comment by henryl46** [comment]
> 差强人意是指？有对比细节么

应该说基本上刮削的结果都挺不错的 但是例如我自己希望海报、logo等图片能刮成原语言的版本
就可能对于我来说 mr自动刮削出来的对比ellyfin/emby自动（有设置优先级和语言）刮削的来说 还是有点出入的 对于个人的影视库的构建
再者就是nfo的问题 比如mr自动生成的nfo是中文的 但是用户（我）希望做成英文的库
大概就是这样...

**Comment by pofey** [comment]
这本质不是开放刮削设置么。
另外你现在依然可以开媒体库刮削去覆盖原始的

**Comment by bqlh** [comment]
原语言？还有人强迫症喜欢英语海报？

**Comment by henryl46** [comment]
是的 现在我是这么操作的

不过或许不需要开放全部刮削选项？ 只要增加一个 是/否 通过mr进行刮削 的选项

不过不是什么必须的功能好像？毕竟我不太确定其他人的需求

**Comment by henryl46** [comment]
> 原语言？还有人强迫症喜欢英语海报？

是的 中文海报和nfo有时候有些...

**Comment by pofey** [comment]
配置中可以关的，tg频道里应该能翻到设置，这功能本身就在实验中，正式版配置会全开到页面设置的

**Comment by henryl46** [comment]
感谢
