### ISSUE TITLE
[缺陷]: 无法手动硬链接

### ISSUE THREAD

**Issue by zzj6666** [pofey/movie_robot#627]
### 当前程序版本

1.1.10

### 问题描述

![image](https://user-images.githubusercontent.com/101039599/186437308-d5598d16-6025-4fd6-a746-5fd86e454f5d.png)

### 重现步骤

正常手动纠错硬链接

### 健康检查

![image](https://user-images.githubusercontent.com/101039599/186437513-bc7cc830-9692-4bfd-b0d0-9490d9d5a55d.png)

**Comment by zzj6666** [comment]
![image](https://user-images.githubusercontent.com/101039599/186438729-f22a7f0b-7b2f-419c-bf5a-c16568564de9.png)
最后显示整理完成，但是硬链接里并没有文件

**Comment by zzj6666** [comment]
![image](https://user-images.githubusercontent.com/101039599/186441415-e99be069-7318-440b-943a-b341c63c4965.png)
再次手动尝试硬链接之后，文件出现了，但是都没有文件格式后缀了

**Comment by pofey** [comment]
beta可能已经好了
