### ISSUE TITLE
[缺陷]: 下载器监控不到位

### ISSUE THREAD

**Issue by lintreek** [pofey/movie_robot#629]
### 当前程序版本

最新稳定版

### 问题描述

下载器不在线的情况下还会不断的添加下载，然后取消订阅

### 重现步骤

1.下载器掉线 2.订阅还在不断下载 3.掉线期间添加下载的电影不会重新添加

### 健康检查

系统运行状态良好

**Comment by lintreek** [comment]
里面有全集两个字的会取消订阅，其他的不会

**Comment by pofey** [comment]
你都知道掉线了 还来提这个是要干什么

**Comment by lintreek** [comment]
掉线了不会马上知道，这期间已经丢了很多剧了，凡是带有全集字眼的全部被取消订阅了

**Comment by pofey** [comment]
还是要努力分析原因 别让下载器掉线 保证好依赖系统的稳定性
