### ISSUE TITLE
[缺陷]: 1.1.11版企业微信搜索失败，无返回结果

### ISSUE THREAD

**Issue by jayling1111** [pofey/movie_robot#635]
### 当前程序版本

1.1.11

### 问题描述

企业微信搜索影片失败，通知功能正常

### 重现步骤

1.微信搜索影片 一直显示搜索中，并且尝试多个影片名字都无法返回搜索结果
2.微信通知功能正常，排除接口问题
![photo_2022-08-26_02-11-56](https://user-images.githubusercontent.com/84979549/186739034-b6e287d9-9280-42b4-99be-0f15c9757102.jpg)

![屏幕截图 2022-08-26 021543](https://user-images.githubusercontent.com/84979549/186739957-e937e046-abd7-4aa6-9504-23891841a14f.jpg)

### 发生问题时系统日志

2022/08/25 22:05:19 - MainThread - INFO: 当前版本: 1.1.11
 2022/08/25 22:05:52 - Thread-69 - ERROR: 处理微信消息出错。
Traceback (most recent call last):
  File "mbot/controller/qywxcontroller.py", line 126, in mbot.controller.qywxcontroller.receive
AttributeError: 'NoneType' object has no attribute 'text'
 2022/08/25 22:05:52 - Thread-70 - ERROR: 处理微信消息出错。
Traceback (most recent call last):
  File "mbot/controller/qywxcontroller.py", line 126, in mbot.controller.qywxcontroller.receive
AttributeError: 'NoneType' object has no attribute 'text'
 2022/08/25 22:05:55 - qywx-search - ERROR: 企业微信搜索失败：'NoneType' object is not iterable
Traceback (most recent call last):
  File "mbot/controller/qywxcontroller.py", line 49, in mbot.controller.qywxcontroller.QywxSearchThread.run
TypeError: 'NoneType' object is not iterable
 2022/08/25 22:06:04 - qywx-search - ERROR: 企业微信搜索失败：'NoneType' object is not iterable
Traceback (most recent call last):
  File "mbot/controller/qywxcontroller.py", line 49, in mbot.controller.qywxcontroller.QywxSearchThread.run
TypeError: 'NoneType' object is not iterable
```


### 健康检查

![屏幕截图 2022-08-26 021543](https://user-images.githubusercontent.com/84979549/186739863-e3d2fcb7-7aab-42a0-a21d-0c21d8708317.jpg)

**Comment by jayling1111** [comment]
[https://user-images.githubusercontent.com/84979549/186739476-c0521cf2-f2fc-4141-944c-d055e51216d1.png)](url)

**Comment by Decade1993** [comment]
标题版本号写错了吧，是1.1.11，我也有这个问题

**Comment by gdyan2001** [comment]
> 

我今天也这样了

**Comment by jayling1111** [comment]
尝试更换豆瓣IP，然后个别影片能返回结果，大部分还是不行，应该是豆瓣那边出了问题
![Uploading Screenshot_20220826_113842_com.tencent.mm_edit_80742420274657.jpg…]()

**Comment by jayling1111** [comment]
![Screenshot_20220826_113842_com tencent mm_edit_80742420274657](https://user-images.githubusercontent.com/84979549/186812624-b582da01-1fd0-47b3-991e-eda3e7c7d2ce.jpg)

**Comment by Decade1993** [comment]
是的，有些可以，我搜独行月球可以，搜明日战记就报这个错

**Comment by jayling1111** [comment]
再补充一下，
已尝试更换豆瓣COOKIE，尝试豆瓣走节点，依然无法解决。

另外web界面首页正常显示豆瓣推荐榜单，搜索资源可以正常显示豆瓣资源海报，并且跳转豆瓣APP，唯独微信搜索出问题。

**Comment by pofey** [comment]
豆瓣接口升级，等下一版
