### ISSUE TITLE
[提问]: 日志有报错，看不懂

### ISSUE THREAD

**Issue by tianjian110** [pofey/movie_robot#638]
### 当前程序版本

1.1.1

### 问题

![342017C5-55E6-4D68-8BC9-AFDB23CCF3B8](https://user-images.githubusercontent.com/94738666/186828315-b80d016c-fef4-45f7-8624-2bb8f5d2371d.jpeg)

**Comment by pofey** [comment]
豆瓣接口升级，等下一版

**Comment by tianjian110** [comment]
会影响查找资源么，我少年派的订阅一直没有下载，但是看见馒头上有好多资源

**Comment by pofey** [comment]
不会

**Comment by tianjian110** [comment]
![5F43495A-1B0A-461F-BED4-17CBC8F24F56](https://user-images.githubusercontent.com/94738666/186898299-6b41c52a-7d45-4a3a-a72c-0b739ce5e2fe.png)

**Comment by tianjian110** [comment]
日志里看不见少年派的奇幻漂流的日志
