### ISSUE TITLE
[缺陷]: 提交下载失败: 'NoneType' object has no attribute 'info_hash'

### ISSUE THREAD

**Issue by luckyyyyy** [pofey/movie_robot#639]
### 当前程序版本

1.2.1

### 问题描述

2022/08/26 20:39:11 - mteam-downloader - INFO: [mteam]Lost and Found 2021 WEB-DL 4K H.265 DDP 2.0 & AAC-Dave提交下载失败: 'NoneType' object has no attribute 'info_hash'

### 重现步骤

订阅后提交下载失败 健康检查看不到qBittorrent 用户名密码正确 升级后出现这个问题

qBittorrent v4.4.3.1 Web UI (64-bit)

### 发生问题时系统日志

```shell
2022/08/26 20:38:46 - SubConsumer - INFO: 已经开始在站点: 馒头,52pt 搜索: 以年为单位的恋爱,Lost and Found,tt18266996
2022/08/26 20:39:08 - SubConsumer - INFO: 共在2个站点搜索到12条结果，其中馒头最慢，耗费22.47秒
2022/08/26 20:39:08 - SubConsumer - INFO: 以年为单位的恋爱(2021) 当前最佳选择: WEB-DL 4K H.265 资源：https://kp.m-team.cc/details.php?id=549261&hit=1 已经提交下载。
2022/08/26 20:39:08 - mteam-downloader - INFO: 开始处理来自订阅的下载: [mteam]Lost and Found 2021 WEB-DL 4K H.265 DDP 2.0 & AAC-Dave
2022/08/26 20:39:11 - mteam-downloader - INFO: [mteam]Lost and Found 2021 WEB-DL 4K H.265 DDP 2.0 & AAC-Dave提交下载失败: 'NoneType' object has no attribute 'info_hash'
```

### 健康检查

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/9210430/186906050-ceed8286-3753-40a1-aa36-daa2a30907bc.png">

**Comment by pofey** [comment]
看wiki 配置完了重启
