### ISSUE TITLE
导入原有数据命令  参数？

### ISSUE THREAD

**Issue by lalasou** [pofey/movie_robot#64]
python commandapp.py -w=/data -a=moviesmanager --source-type=movie --source-dir=/Downloads/Free --target-dir=/Downloads/link/embyMovie --file-mode=link

source-type 有什么参数
serials不识别啊

**Comment by pofey** [comment]
> python commandapp.py -w=/data -a=moviesmanager --source-type=movie --source-dir=/Downloads/Free --target-dir=/Downloads/link/embyMovie --file-mode=link
> 
> source-type 有什么参数 serials不识别啊

tv 而且命令行程序有 —help的
