### ISSUE TITLE
[提问]: 报错提示免费种子处理淘汰任务出错

### ISSUE THREAD

**Issue by tianjian110** [pofey/movie_robot#641]
### 当前程序版本

1.2.1

### 问题

2022/08/26 23:04:30 - ThreadPoolExecutor-4_3 - ERROR: 处理免费种子淘汰任务出错：(sqlite3.OperationalError) database is locked
[SQL: SELECT free_download_record.id AS free_download_record_id, free_download_record.gmt_create AS free_download_record_gmt_create, free_download_record.gmt_modified AS free_download_record_gmt_modified, free_download_record.site_id AS free_download_record_site_id, free_download_record.torrent_id AS free_download_record_torrent_id, free_download_record.name AS free_download_record_name, free_download_record.subject AS free_download_record_subject, free_download_record.size_mb AS free_download_record_size_mb, free_download_record.upload_count AS free_download_record_upload_count, free_download_record.downloading_count AS free_download_record_downloading_count, free_download_record.download_count AS free_download_record_download_count, free_download_record.download_volume_factor AS free_download_record_download_volume_factor, free_download_record.upload_volume_factor AS free_download_record_upload_volume_factor, free_download_record.minimum_ratio AS free_download_record_minimum_ratio, free_download_record.minimum_seed_time AS free_download_record_minimum_seed_time, free_download_record.free_deadline AS free_download_record_free_deadline, free_download_record.torrent_hash AS free_download_record_torrent_hash, free_download_record.delete_status AS free_download_record_delete_status 
FROM free_download_record 
WHERE free_download_record.torrent_hash = ? AND free_download_record.delete_status = ?
 LIMIT ? OFFSET ?]
[parameters: ('90509592ae00e88e7877d25039928436e197acf6', 0, 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/dependencies/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mbot/task/freedownloadmonitortask.py", line 192, in mbot.task.freedownloadmonitortask.FreeDownloadMonitor.run
  File "mbot/task/freedownloadmonitortask.py", line 130, in mbot.task.freedownloadmonitortask.FreeDownloadMonitor.can_delete
  File "mbot/models/freedownloadmodel.py", line 54, in mbot.models.freedownloadmodel.FreeDownloadModel.get_by_torrent_hash
  File "/dependencies/sqlalchemy/orm/query.py", line 2823, in first
    return self.limit(1)._iter().first()
  File "/dependencies/sqlalchemy/orm/query.py", line 2907, in _iter
    result = self.session.execute(
  File "/dependencies/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/dependencies/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/dependencies/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/dependencies/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/dependencies/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/dependencies/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/dependencies/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/dependencies/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/dependencies/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT free_download_record.id AS free_download_record_id, free_download_record.gmt_create AS free_download_record_gmt_create, free_download_record.gmt_modified AS free_download_record_gmt_modified, free_download_record.site_id AS free_download_record_site_id, free_download_record.torrent_id AS free_download_record_torrent_id, free_download_record.name AS free_download_record_name, free_download_record.subject AS free_download_record_subject, free_download_record.size_mb AS free_download_record_size_mb, free_download_record.upload_count AS free_download_record_upload_count, free_download_record.downloading_count AS free_download_record_downloading_count, free_download_record.download_count AS free_download_record_download_count, free_download_record.download_volume_factor AS free_download_record_download_volume_factor, free_download_record.upload_volume_factor AS free_download_record_upload_volume_factor, free_download_record.minimum_ratio AS free_download_record_minimum_ratio, free_download_record.minimum_seed_time AS free_download_record_minimum_seed_time, free_download_record.free_deadline AS free_download_record_free_deadline, free_download_record.torrent_hash AS free_download_record_torrent_hash, free_download_record.delete_status AS free_download_record_delete_status 
FROM free_download_record 
WHERE free_download_record.torrent_hash = ? AND free_download_record.delete_status = ?
 LIMIT ? OFFSET ?]
[parameters: ('90509592ae00e88e7877d25039928436e197acf6', 0, 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
 2022/08/26 23:04:46 - ThreadPoolExecutor-4_2 - INFO: 最近5秒上传速度持续超过最大上行 30Mbps 的85%，无需拉新种子。
 2022/08/26 23:05:21 - ThreadPoolExecutor-4_0 - INFO: [audiences]The Vampire Diarie

**Comment by htnanako** [comment]
> sqlite3.OperationalError: database is locked

你docker所在硬盘卡IO了
