### ISSUE TITLE
[提问]: 出现了很多错误的日志,不知道是什么意思

### ISSUE THREAD

**Issue by nikkzy** [pofey/movie_robot#645]
### 当前程序版本

1.2.1

### 问题

出现了很多错误的日志,看着很难受,使用是正常的,也没有下载日志里相关的电影,养站已经都关掉了
![image](https://user-images.githubusercontent.com/56377576/187018928-f6f3ee30-f99c-465c-86f8-87bd4d1a9a4b.png)

**Comment by pofey** [comment]
站点适配的问题吧 但我也不知道是什么站

**Comment by nikkzy** [comment]
ptsbao

**Comment by nikkzy** [comment]
> 站点适配的问题吧 但我也不知道是什么站

但是我没下载日志里的电影,也没开刷流,就挺奇怪的

**Comment by pofey** [comment]
> > 站点适配的问题吧 但我也不知道是什么站
> 
> 但是我没下载日志里的电影,也没开刷流,就挺奇怪的

看wiki
