### ISSUE TITLE
[提问]: 有些种子能搜到但是无法提交下载

### ISSUE THREAD

**Issue by nikkzy** [pofey/movie_robot#649]
### 当前程序版本

1.2.1

### 问题

![image](https://user-images.githubusercontent.com/56377576/187058833-ec1460d4-8f99-47fe-bad9-5edc4366d1fb.png)
![image](https://user-images.githubusercontent.com/56377576/187058848-f267ef0b-028f-4635-8c74-22e978c66627.png)
过滤器选择电影，其余全部为空，排序规则三个都试了

**Comment by pofey** [comment]
你没看出来pt站资源种子年份和电影年份全都不一样吗？

**Comment by nikkzy** [comment]
![image](https://user-images.githubusercontent.com/56377576/187065773-684f7c31-8fc0-4a40-bace-39b4b50e63a9.png)
![image](https://user-images.githubusercontent.com/56377576/187065780-08ed5780-da56-4ab5-baa4-f4ce7539e56e.png)
但是为什么年份是不对的呢

**Comment by nikkzy** [comment]
这样的资源就需要手动下载吧
