### ISSUE TITLE
[缺陷]: 1.ThreadPoolExecutor-5_2 - ERROR     2.激活码突然提示多台机器激活  3.python无端占用内存过大

### ISSUE THREAD

**Issue by chiron688** [pofey/movie_robot#651]
### 当前程序版本

latest

### 问题描述

1.更新媒体趋势榜单数据之后报错
2022/08/28 03:00:00 - ThreadPoolExecutor-5_6 - INFO: 开始更新媒体趋势榜单数据
2022/08/28 03:01:50    ThreadPoolExecutor-5_2 - ERROR
   后续贴上log

2. 使用过程一切正常，后19：10开始提示激活码被太多设备使用，但是本人确保这段日子都是在一台服务器上使用的，同一个ip，前面激活的都删除了，激活码接受邮箱：948502378@qq.com，激活ip地址皆为138.201.57.*，ip为同一个ip（以防被打隐去最后几位）
2022/08/28 19:00:03 - ThreadPoolExecutor-5_5 - INFO: 豆瓣用户232959597的想看列表开始同步到订阅记录。 
 2022/08/28 19:00:03 - ThreadPoolExecutor-5_5 - INFO: 本次豆瓣想看同步到订阅任务已经完成。
 2022/08/28 19:10:00 - ThreadPoolExecutor-5_0 - INFO: 天外来客 第1季(2022) 第1,2,3,4,5,6,7,8,9,10集字幕下载已经提交启动。
 2022/08/28 19:10:30 - ThreadPoolExecutor-5_6 - ERROR: 验证失败，此激活码已经被太多设备使用！
 2022/08/28 19:10:35 - MainThread - INFO: 添加事件(下载完成)监听器：NotifyListener
 2022/08/28 19:10:35 - MainThread - INFO: 添加事件(订阅影片)监听器：NotifyListener
 2022/08/28 19:10:35 - MainThread - INFO: 添加事件(开始下载)监听器：NotifyListener
 2022/08/28 19:10:35 - MainThread - INFO: 添加事件(站点异常)监听器：NotifyListener
 2022/08/28 19:10:35 - MainThread - INFO: 站点并发线程数：12

3.今日python运行占用突然爆炸，占用了运行内存64个g，暂时未知是什么原因，只知道python多线程并发把全部64个g占满了，从20：30左右开始，探针多次提示离线，重启后正常。第二张图将movie-robot卸载后正常（python多进程超过12进程）
![image](https://user-images.githubusercontent.com/63992772/187085912-8bbafbea-2934-4799-a018-1531607ea69e.png)
![image](https://user-images.githubusercontent.com/63992772/187085967-ef35fec3-a245-4bf3-bf84-ad783821022b.png)
第二张图将movie-robot卸载后正常（明显超过12线程）

### 重现步骤

完整log后续附上

### 发生问题时系统日志

```shell
完整log（谷歌云盘）
https://drive.google.com/file/d/1L1PNnt-UMMia7avH6SCEB_ox9fF43THP/view?usp=sharing
```

### 健康检查

暂无，movie-robot无法激活

**Comment by pofey** [comment]
内存爆就是因为你激活码出问题 启动自毁无限重启模式

**Comment by pofey** [comment]
我一会看看你激活码咋回事 先关了

**Comment by chiron688** [comment]
好的，麻烦您了

**Comment by pofey** [comment]
这个邮箱的激活码我确认了没问题的 948502378@qq.com
