### ISSUE TITLE
[优化]: 通知增加首播日期

### ISSUE THREAD

**Issue by Alano-i** [pofey/movie_robot#653]
### 当前现状

当前通知中没有 `电影/剧集 首播日期`，仅订阅通知中有 `release_date `

### 你的建议

希望能下载通知中也能添加`电影/剧集 首播日期`，以及`剧集单集 播出日期`

### 优先级

一般

### 受众范围

一般

**Comment by pofey** [comment]
下一版本，除了集，所有都带release_date

**Comment by Alano-i** [comment]
单集的 release_date 有机会么
