### ISSUE TITLE
[缺陷]: 电影标题出错，未上映影片上映日期错误

### ISSUE THREAD

**Issue by Alano-i** [pofey/movie_robot#654]
### 当前程序版本

1.2.6

### 问题描述

![image](https://user-images.githubusercontent.com/68833595/187144797-4e50beda-dc3e-4888-892c-baa3abacd23b.png)

1. 通知标题错误
2. 该电影未上映，但`is_aired`变量没起作用。
3. 上映日期错误，豆瓣该电影上映日期为`2022-09-09`，[该电影豆瓣链接](https://movie.douban.com/subject/27201437/)

设置的电影订阅标题为：
`🍿订阅：{{ cn_name }} {% if rating %}  ⭐️{{"%.1f"|format(rating)}}{% else %}{% if not is_aired %}  尚未上映{% endif %}{% endif %}`

设置的电影订阅内容为：
```
{{ release_date }}上映，由 {{ nickname }} 订阅
{{country|join(" · ")}}{% if genres %}   {{genres|join(" · ")}}{% else %}   分类未知{% endif %}
{% if intro -%}··········································
{{intro|replace('　','')|replace(' ','')|replace('\n','')}}{%- endif %}
```

### 重现步骤

订阅《梵天神器》
设置 订阅通知

### 健康检查

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/68833595/187145122-9e880c40-e85c-4fc2-8348-d8cf7851161d.png">

**Comment by pofey** [comment]
下一版本修
