### ISSUE TITLE
[缺陷]: 识别过程中，碰到不能识别的，会重启

### ISSUE THREAD

**Issue by Ignatius-Ye** [pofey/movie_robot#656]
### 当前程序版本

1.2.10

### 问题描述

识别过程中，碰到不能识别的，会重启
![5f8cb8f2149282955a776948d494527](https://user-images.githubusercontent.com/37823715/187355778-329d1120-37ce-4c21-9e37-0633cf33a59f.jpg)
![4cd0e66ad0bc8591a2a16cee95b67eb](https://user-images.githubusercontent.com/37823715/187355824-448504e8-699c-4445-b35a-045d80d3b5e5.jpg)

### 重现步骤

直接资源整理  识别整理

### 健康检查

![image](https://user-images.githubusercontent.com/37823715/187356045-38b4d287-5e65-49e1-a376-c39ebf08330d.png)

**Comment by pofey** [comment]
应该好了
