### ISSUE TITLE
[缺陷]: 自定义关键字订阅编辑保存返回404

### ISSUE THREAD

**Issue by mymoonyue** [pofey/movie_robot#658]
### 当前程序版本

1.2.11

### 问题描述

自定义关键字订阅编辑保存返回404，订阅归类以后一直以来的bug还没修复

### 重现步骤

自定义关键字订阅编辑保存返回404

### 发生问题时系统日志

<img width="253" alt="image" src="https://user-images.githubusercontent.com/60549575/187582133-0c6d90f6-1d8d-48cc-a267-7e4fd6779cdb.png">

### 健康检查

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/60549575/187581907-2afa70ad-9d32-49d3-949c-3e80be4568c3.png">

**Comment by pofey** [comment]
点什么地方404了 保存肯定不会

**Comment by mymoonyue** [comment]
> 点什么地方404了 保存肯定不会

我的订阅-关键字-添加-保存

**Comment by pofey** [comment]
还真是

**Comment by pofey** [comment]
下个版本上线
