### ISSUE TITLE
新增PT站支持

### ISSUE THREAD

**Issue by bobo0810** [pofey/movie_robot#66]
大佬好，是否考虑对百川PT、 PTtime等热门PT站支持呢?

**Comment by pofey** [comment]
没特色的小站不支持了，可以自己适配

**Comment by LeanFly** [comment]
尝试适配PTtime

`id: pttime
name: 时光
domain: https://www.pttime.org/
encoding: UTF-8

login:
  test:
    selector: a[href="logout.php"]

category_mappings:
  - { id: 401, cate_level1: Movie, cate_level2: "Movies(电影)", cate_level2_desc: "Movies(电影)" }
  - { id: 402, cate_level1: TV, cate_level2: "TV Series(电视剧)", cate_level2_desc: "TV Series(电视剧)" }
  - { id: 430, cate_level1: Anime, cate_level2: "Animate(3D动画、2.5次元)", cate_level2_desc: "Animate(3D动画、2.5次元)" }
  - { id: 404, cate_level1: Documentary, cate_level2: "Documentaries(纪录片)", cate_level2_desc: "Documentaries(纪录片)" }
  - { id: 403, cate_level1: TV, cate_level2: "TV Shows(综艺)", cate_level2_desc: "TV Shows(综艺)" }
  - { id: 451, cate_level1: Other, cate_level2: "Software(软件、系统、 程序、APP等)", cate_level2_desc: "Software(软件、系统、 程序、APP等)" }
  - { id: 450, cate_level1: Other, cate_level2: "Resource(资源、素材、模板)", cate_level2_desc: "Resource(资源、素材、模板)" }
  - { id: 406, cate_level1: Game, cate_level2: "Games(游戏及相关)", cate_level2_desc: "Games(游戏及相关)" }
  - { id: 408, cate_level1: Music, cate_level2: "Music(音乐、专辑、MV、演唱会)", cate_level2_desc: "Music(音乐、专辑、MV、演唱会)" }
  - { id: 405, cate_level1: other, cate_level2: "Sport(体育、竞技、武术及相关)", cate_level2_desc: "Sport(体育、竞技、武术及相关)" }
  - { id: 490, cate_level1: Other, cate_level2: "Other(其它)", cate_level2_desc: "Other(其它)" }
  - { id: 409, cate_level1: Other, cate_level2: "Art(舞蹈、歌剧、戏曲、相声、评书等)", cate_level2_desc: "Art(舞蹈、歌剧、戏曲、相声、评书等)" }
# 搜索时id映射
category_id_mapping:
  - { id: movie, mapping: 401 }
  - { id: tv, mapping: [ 402,403 ] }
  - { id: doc, mapping: [ 404 ] }
  - { id: animate, mapping: 430 }
  - { id: mv, mapping: 408 }
  - { id: music, mapping: 408 }
  - { id: other, mapping: [ 405,409,451,490 ] }

userinfo:
  path: https://pt.btschool.club/rules.php
  item:
    selector: table[id="info_block"]
  fields:
    uid:
      default_value: 0
      selector: a[href^="userdetails.php?id="]
      attribute: href
      filters:
        - name: re_search
          args: [ '\d+', 0 ]
    user_group:
      default_value: ''
      selector: a[href^="userdetails.php?id="]
      attribute: class
    username:
      default_value: '未知用户名'
      selector: a[href^="userdetails.php?id="]
    share_ratio:
      default_value: ''
      selector: font[class="color_ratio"]
      method: next_sibling
      filters:
        - name: replace
          args: [ '无限','inf' ]
    uploaded:
      default_value: 0
      selector: font[class="color_uploaded"]
      method: next_sibling
      filters:
        - name: replace
          args: [ '无限','inf' ]
    downloaded:
      default_value: 0
      selector: font[class="color_downloaded"]
      method: next_sibling
      filters:
        - name: replace
          args: [ '无限','inf' ]
    seeding:
      default_value: 0
      selector: img[alt="Torrents seeding"]
      method: next_sibling
    leeching:
      default_value: 0
      selector: img[alt="Torrents seeding"]
      method: next_sibling
    vip_group:
      case:
        a[class^="VIP"]: true
        "*": false
search:
  paths:
    - path: torrents.php
      method: get
  query:
    $raw: "{% for c in query.cates %}cat{{c}}=1&{% endfor %}"
    search: "{% if query.imdb_id %}{{query.imdb_id}}{%else%}{{query.keyword}}{% endif %}"
    # 0 incldead, 1 active, 2 dead
    incldead: 1
    # 0 all, 1 normal, 2 free, 3 2x, 4 2xfree, 5 50%, 6 2x50%, 7 30%
    spstate: "{% if query.free %}2{% else %}0{% endif %}"
    # 0 title, 1 descr, 3 uploader, 4 imdburl (searching imdburl does not work with tt1234567, but descr is good)
    search_area: "{% if query.imdb_id %}4{% else %}0{%endif%}"
    # 0 AND, 1 OR, 2 exact
    search_mode: 0
    sort: "{{ query.sort }}"
    type: "{{ query.type }}"
    page: "{{ query.page }}"

torrents:
  list:
    selector: table.torrents > tr:has(table.torrentname)
  fields:
    id:
      selector: a[href^="details.php?id="]
      attribute: href
      filters:
        - name: re_search
          args: [ '\d+', 0 ]
    title_default:
      selector: a[href^="details.php?id="]
    title_optional:
      optional: true
      selector: a[title][href^="details.php?id="]
      attribute: title
    title:
      text: "{% if fields['title_optional'] %}{{ fields['title_optional'] }}{% else %}{{ fields['title_default'] }}{% endif %}"
    category:
      selector: a[href^="?cat="]
      attribute: href
      filters:
        - name: replace
          args: [ "?", "" ]
        - name: querystring
          args: cat
    details:
      selector: a[href^="details.php?id="]
      attribute: href
    download:
      selector: a[href^="download.php?id="]
      attribute: href
    imdbid:
      selector: div.imdb_100 > a
      attribute: href
      filters:
        - name: re_search
          args: [ 'tt\d+',0 ]
    date_elapsed:
      # 站点设置，已去时间 (默认)
      selector: td:nth-child(5) > span[title]
      attribute: title
      optional: true
    date_added:
      # 站点设置，实际时间
      selector: td:nth-child(5):not(:has(span))
      optional: true
    date:
      text: "{% if fields['date_elapsed'] or fields['date_added'] %}{{ fields['date_elapsed'] if fields['date_elapsed'] else fields['date_added'] }}{% else %}now{% endif %}"
      filters:
        - name: dateparse
          args: "%Y-%m-%d %H:%M:%S"
    size:
      selector: td:nth-child(6)
    seeders:
      selector: td:nth-child(7)
    leechers:
      selector: td:nth-child(8)
    grabs:
      selector: td:nth-child(9)
    downloadvolumefactor:
      case:
        font.promotion.free: 0
        font.promotion.twoupfree: 0
        font.promotion.twouphalfdown: 0.5
        font.promotion.halfdown: 0.5
        font.promotion.thirtypercent: 0.3
        font.promotion.zeroupzerodown: 0.3
        "*": 1
    uploadvolumefactor:
      case:
        font.promotion.twoup: 2
        font.promotion.twouphalfdown: 2
        font.promotion.twoupfree: 2
        "*": 1
    free_deadline:
      default_value: "{% if fields['downloadvolumefactor']==0 %}{{max_time}}{% endif%}"
      default_value_format: '%Y-%m-%d %H:%M:%S.%f'
      selector: font.promotion.free,font.promotion.twoupfree
      attribute: onmouseover
      filters:
        - name: re_search
          args: [ '\d+-\d+-\d+ \d+:\d+:\d+', 0 ]
        - name: dateparse
          args: "%Y-%m-%d %H:%M:%S"
    description:
      selector: table.torrentname > tr > td.embedded
      remove: a, img, span, b, font
      contents: -2
    minimumratio:
      text: 1
    minimumseedtime:
      #做种21小时
      text: 75600`

**Comment by LeanFly** [comment]
> 尝试适配PTtime
> 
> `id: pttime name: 时光 domain: https://www.pttime.org/ encoding: UTF-8
> 
> login: test: selector: a[href="logout.php"]
> 
> category_mappings:
> 
> * { id: 401, cate_level1: Movie, cate_level2: "Movies(电影)", cate_level2_desc: "Movies(电影)" }
> * { id: 402, cate_level1: TV, cate_level2: "TV Series(电视剧)", cate_level2_desc: "TV Series(电视剧)" }
> * { id: 430, cate_level1: Anime, cate_level2: "Animate(3D动画、2.5次元)", cate_level2_desc: "Animate(3D动画、2.5次元)" }
> * { id: 404, cate_level1: Documentary, cate_level2: "Documentaries(纪录片)", cate_level2_desc: "Documentaries(纪录片)" }
> * { id: 403, cate_level1: TV, cate_level2: "TV Shows(综艺)", cate_level2_desc: "TV Shows(综艺)" }
> * { id: 451, cate_level1: Other, cate_level2: "Software(软件、系统、 程序、APP等)", cate_level2_desc: "Software(软件、系统、 程序、APP等)" }
> * { id: 450, cate_level1: Other, cate_level2: "Resource(资源、素材、模板)", cate_level2_desc: "Resource(资源、素材、模板)" }
> * { id: 406, cate_level1: Game, cate_level2: "Games(游戏及相关)", cate_level2_desc: "Games(游戏及相关)" }
> * { id: 408, cate_level1: Music, cate_level2: "Music(音乐、专辑、MV、演唱会)", cate_level2_desc: "Music(音乐、专辑、MV、演唱会)" }
> * { id: 405, cate_level1: other, cate_level2: "Sport(体育、竞技、武术及相关)", cate_level2_desc: "Sport(体育、竞技、武术及相关)" }
> * { id: 490, cate_level1: Other, cate_level2: "Other(其它)", cate_level2_desc: "Other(其它)" }
> * { id: 409, cate_level1: Other, cate_level2: "Art(舞蹈、歌剧、戏曲、相声、评书等)", cate_level2_desc: "Art(舞蹈、歌剧、戏曲、相声、评书等)" }
> 
> # 搜索时id映射
> category_id_mapping:
> 
> * { id: movie, mapping: 401 }
> * { id: tv, mapping: [ 402,403 ] }
> * { id: doc, mapping: [ 404 ] }
> * { id: animate, mapping: 430 }
> * { id: mv, mapping: 408 }
> * { id: music, mapping: 408 }
> * { id: other, mapping: [ 405,409,451,490 ] }
> 
> userinfo: path: https://pt.btschool.club/rules.php item: selector: table[id="info_block"] fields: uid: default_value: 0 selector: a[href^="userdetails.php?id="] attribute: href filters: - name: re_search args: [ '\d+', 0 ] user_group: default_value: '' selector: a[href^="userdetails.php?id="] attribute: class username: default_value: '未知用户名' selector: a[href^="userdetails.php?id="] share_ratio: default_value: '' selector: font[class="color_ratio"] method: next_sibling filters: - name: replace args: [ '无限','inf' ] uploaded: default_value: 0 selector: font[class="color_uploaded"] method: next_sibling filters: - name: replace args: [ '无限','inf' ] downloaded: default_value: 0 selector: font[class="color_downloaded"] method: next_sibling filters: - name: replace args: [ '无限','inf' ] seeding: default_value: 0 selector: img[alt="Torrents seeding"] method: next_sibling leeching: default_value: 0 selector: img[alt="Torrents seeding"] method: next_sibling vip_group: case: a[class^="VIP"]: true "*": false search: paths: - path: torrents.php method: get query: $raw: "{% for c in query.cates %}cat{{c}}=1&{% endfor %}" search: "{% if query.imdb_id %}{{query.imdb_id}}{%else%}{{query.keyword}}{% endif %}" # 0 incldead, 1 active, 2 dead incldead: 1 # 0 all, 1 normal, 2 free, 3 2x, 4 2xfree, 5 50%, 6 2x50%, 7 30% spstate: "{% if query.free %}2{% else %}0{% endif %}" # 0 title, 1 descr, 3 uploader, 4 imdburl (searching imdburl does not work with tt1234567, but descr is good) search_area: "{% if query.imdb_id %}4{% else %}0{%endif%}" # 0 AND, 1 OR, 2 exact search_mode: 0 sort: "{{ query.sort }}" type: "{{ query.type }}" page: "{{ query.page }}"
> 
> torrents: list: selector: table.torrents > tr:has(table.torrentname) fields: id: selector: a[href^="details.php?id="] attribute: href filters: - name: re_search args: [ '\d+', 0 ] title_default: selector: a[href^="details.php?id="] title_optional: optional: true selector: a[title][href^="details.php?id="] attribute: title title: text: "{% if fields['title_optional'] %}{{ fields['title_optional'] }}{% else %}{{ fields['title_default'] }}{% endif %}" category: selector: a[href^="?cat="] attribute: href filters: - name: replace args: [ "?", "" ] - name: querystring args: cat details: selector: a[href^="details.php?id="] attribute: href download: selector: a[href^="download.php?id="] attribute: href imdbid: selector: div.imdb_100 > a attribute: href filters: - name: re_search args: [ 'tt\d+',0 ] date_elapsed: # 站点设置，已去时间 (默认) selector: td:nth-child(5) > span[title] attribute: title optional: true date_added: # 站点设置，实际时间 selector: td:nth-child(5):not(:has(span)) optional: true date: text: "{% if fields['date_elapsed'] or fields['date_added'] %}{{ fields['date_elapsed'] if fields['date_elapsed'] else fields['date_added'] }}{% else %}now{% endif %}" filters: - name: dateparse args: "%Y-%m-%d %H:%M:%S" size: selector: td:nth-child(6) seeders: selector: td:nth-child(7) leechers: selector: td:nth-child(8) grabs: selector: td:nth-child(9) downloadvolumefactor: case: font.promotion.free: 0 font.promotion.twoupfree: 0 font.promotion.twouphalfdown: 0.5 font.promotion.halfdown: 0.5 font.promotion.thirtypercent: 0.3 font.promotion.zeroupzerodown: 0.3 "_": 1 uploadvolumefactor: case: font.promotion.twoup: 2 font.promotion.twouphalfdown: 2 font.promotion.twoupfree: 2 "_": 1 free_deadline: default_value: "{% if fields['downloadvolumefactor']==0 %}{{max_time}}{% endif%}" default_value_format: '%Y-%m-%d %H:%M:%S.%f' selector: font.promotion.free,font.promotion.twoupfree attribute: onmouseover filters: - name: re_search args: [ '\d+-\d+-\d+ \d+:\d+:\d+', 0 ] - name: dateparse args: "%Y-%m-%d %H:%M:%S" description: selector: table.torrentname > tr > td.embedded remove: a, img, span, b, font contents: -2 minimumratio: text: 1 minimumseedtime: #做种21小时 text: 75600`

![image](https://user-images.githubusercontent.com/18253047/165945557-52203d1c-ae5a-4e77-a6e8-81f97d5bcf05.png)
