### ISSUE TITLE
[优化]: MR识别刮削报错后，建议MR下载记录仍然显示，这样会员还可以手动识别

### ISSUE THREAD

**Issue by 563824978** [pofey/movie_robot#666]
### 当前现状

MR识别刮削报错后，MR下载记录不显示这不电影

### 你的建议

MR识别刮削报错后，建议MR下载记录里面仍然可以显示，这样会员还可以手动识别

### 优先级

非常高

### 受众范围

很多人需要

**Comment by pofey** [comment]
没看懂 有图来辅助说明吗

**Comment by pofey** [comment]
还有日志
