### ISSUE TITLE
[优化]: 建议订阅刷流能选择下载器

### ISSUE THREAD

**Issue by xwh4git** [pofey/movie_robot#669]
### 当前现状

安装了两个qb一个用来订阅追剧,一个用来刷流.mr下载只会用默认的下载器,mr可以配置多个却不能在不同的下载任务里面选对应的下载器.如果想用的话就得装两个mr,这样我觉得有点不合理.

### 你的建议

建议在有下载任务的地方可以增加选择下载器的选项,让有需要的人有更多的选择.

### 优先级

非常高

### 受众范围

一般

**Comment by htnanako** [comment]
多看看wiki吧
https://yee329.notion.site/e73e20b466104ca486ac37a26d81587d

**Comment by pofey** [comment]
不改非常合理 楼上贴wiki了
