### ISSUE TITLE
需求：订阅希望支持手动选择存储路径

### ISSUE THREAD

**Issue by ShakeChanDev** [pofey/movie_robot#67]
使用场景：
因为采用不同的存储路径去管理自己和家人的电影，希望在订阅时可以手动选择不同路径

需求功能描述：
类似「搜索资源」的点击「下载」，选择存储路径

**Comment by pofey** [comment]
你是指根据不同订阅人，决定下载路径？

**Comment by ShakeChanDev** [comment]
不同订阅人的话也可以实现该需求，但是貌似这样逻辑就变复杂多了，可能把这个功能设计在过滤器里可能更合理

**Comment by pofey** [comment]
如果你描述的不是这个，那就不懂你的意思了。

**Comment by ShakeChanDev** [comment]
描述是这个意思，没有理解错。

我的意思是可能出现A帮B下载电影或B帮A下载电影的场景，这种情况下根据订阅人来区分路径就无法满足了，但是主要需求场景已经能够满足了。

如果功能上直接支持手动选择存储路径，满足的场景会更丰富些。

**Comment by pofey** [comment]
我的判断这是个伪需求，实际上按类别把目录分好，用媒体服务器的目录设置不同媒体库，就能按用户分配媒体库了

**Comment by ShakeChanDev** [comment]
「用媒体服务器的目录设置不同媒体库，就能按用户分配媒体库」这步是没有问题


「按类别把目录分好」这步是无法满足需求的，在刚刚那个场景中，《哈利波特》属于「奇幻 / 冒险」，但并不代表所有「奇幻 / 冒险」的电影都要进入路径「/电影@妻子」

或者说，现在的功能需求可以满足通过「分类管理文件夹」的用户群，对于通过「以人为单位管理文件夹」的用户群无法满足

**Comment by pofey** [comment]
> 「用媒体服务器的目录设置不同媒体库，就能按用户分配媒体库」这步是没有问题
> 
> 「按类别把目录分好」这步是无法满足需求的，在刚刚那个场景中，《哈利波特》属于「奇幻 / 冒险」，但并不代表所有「奇幻 / 冒险」的电影都要进入路径「/电影@妻子」
> 
> 或者说，现在的功能需求可以满足通过「分类管理文件夹」的用户群，对于通过「以人为单位管理文件夹」的用户群无法满足

没错，我想说的就是，按人管理就是伪需求。你能讲清楚按人管理的逻辑与实际意义么？

**Comment by ShakeChanDev** [comment]
这个管理方式确实不够优雅，但是暂时没有找到更合适的策略。例如在以下场景，通过分类管理有一定的难度：

同属于动画，《国王排名》是成人向，《小猪佩奇》是儿童向，但是这两者在库的分类上是一起的

**Comment by pofey** [comment]
国王排名属于动画 小猪佩奇有独立分类动画

**Comment by ShakeChanDev** [comment]
OK
