### ISSUE TITLE
[缺陷]: 订阅了诛仙动画，下载的却是诛仙青云志

### ISSUE THREAD

**Issue by tianjian110** [pofey/movie_robot#682]
### 当前程序版本

1.3.1

### 问题描述

![Up
![9BC36BD5-07DD-472D-B06D-7D0A3D3B410C](https://user-images.githubusercontent.com/94738666/188251355-042ec24d-7704-471c-b96e-14288e2b2edb.png)
loading 6D929F49-88CA-4161-A428-1B860060BCD1.png…]()
种子链接：https://kp.m-team.cc//details.php?id=445922&hit=1

### 重现步骤

直接订阅诛仙动画

### 健康检查

100%

**Comment by pofey** [comment]
不支持动漫
