### ISSUE TITLE
[优化]: 增加字幕下载相关推送信息的开关

### ISSUE THREAD

**Issue by deyangchu** [pofey/movie_robot#688]
### 当前现状

字幕下载失败会在推送通道发送相关提示，大量下载时会非常频繁。下载资源还是希望都尝试自动下载一下字幕的，但字幕下载失败时即使推送提醒，一般也不会起到用户及时手动查找字幕的作用。

### 你的建议

推送相关设置中增加开关，可选是否推送字幕下载相关推送信息。

### 优先级

一般

### 受众范围

很多人需要

**Comment by pofey** [comment]
你可以把重试时间改长
