### ISSUE TITLE
[文档]: 如何自建微信代理

### ISSUE THREAD

**Issue by shenshangshang** [pofey/movie_robot#694]
### 当前程序版本

1.3.1

### 问题

作者自建的代理不能添加进企业微信的可信ip了，请问怎么自建一个代理呢

**Comment by pofey** [comment]
有自己的服务器吗？

**Comment by shenshangshang** [comment]
有

**Comment by shenshangshang** [comment]
一个本地群晖服务器一个阿里云服务器

**Comment by pofey** [comment]
> 一个本地群晖服务器一个阿里云服务器

有阿里云固定ip很好，等我有时间写个搭建教程吧

**Comment by roderickbao** [comment]
有固定ip，同样需要教程。

**Comment by pofey** [comment]
第一步，在你的主机上安装一个nginx，这个教程我就不贴了，网上找吧，用yum或者dnf安装成服务；
第二步：装好nginx后进入 /etc/nginx/conf.d 配置目录，vim一个名为qywx.conf 的文件，内容如下
server {
    server_name wx.xxx.com;

    location / {
		proxy_pass https://qyapi.weixin.qq.com/;
	}
    listen       80 ;
}

替换成你自己的域名
第三步：重启nginx让这个配置生效了就行了，如果你没乱改nginx默认的/etc/nginx/nginx.conf 文件，那conf.d 目录的配置文件应该是会自动加载的。
第四步：重启完去机器人微信推送的地方，把推送的那个腾讯官方域名，改成你自己自建的就可以了

**Comment by Howe-Huang** [comment]
简易版本:我vps上有一个博客 用宝塔搭建的  在宝塔界面 配置文件的添加 那段代码就行

**Comment by Alano-i** [comment]
可以用PHP建代理吗

**Comment by Howe-Huang** [comment]
这流程很有可能有人搞不懂  用宝塔还不会 那就真的很难了

**Comment by roderickbao** [comment]
> 配置之后还是不行（nginx内其他域名工作正常），推送API地址填入http://wx.xxx.com  （XXX已改成自己域名），去除{开启Movie Robot自建代理通过白名单验证}的勾选，日志报错

ERROR: 推送测试消息失败：RetryError[<Future at 0x7f384c132d90 state=finished raised JSONDecodeError>]

**Comment by roderickbao** [comment]
还是有问题，把proxy_pass改成https://www.baidu.com都能访问了，证明nginx工作正常，但是https://qyapi.weixin.qq.com/还是用不了。

**Comment by roderickbao** [comment]
> 第一步，在你的主机上安装一个nginx，这个教程我就不贴了，网上找吧，用yum或者dnf安装成服务； 第二步：装好nginx后进入 /etc/nginx/conf.d 配置目录，vim一个名为qywx.conf 的文件，内容如下 server { server_name wx.xxx.com;
> 
> ```
> location / {
> 	proxy_pass https://qyapi.weixin.qq.com/;
> }
> listen       80 ;
> ```
> 
> } 替换成你自己的域名 第三步：重启nginx让这个配置生效了就行了，如果你没乱改nginx默认的/etc/nginx/nginx.conf 文件，那conf.d 目录的配置文件应该是会自动加载的。 第四步：重启完去机器人微信推送的地方，把推送的那个腾讯官方域名，改成你自己自建的就可以了

还是有问题，把proxy_pass改成[https://www.baidu.com浏览器打开可以正常访问，证明nginx工作正常。但是qyapi仍旧不能正常工作。](https://www.baidu.xn--com%2Cnginx%2Chttps-c54xq7gjls07uqmbn74gbvai17gyl2ifh9btbaz42vc62a//qyapi.weixin.qq.com/%E8%BF%98%E6%98%AF%E7%94%A8%E4%B8%8D%E4%BA%86%E3%80%82)

**Comment by ruicky** [comment]
> 将作者的文档内容，编辑美化l一下，方便后来者，比较直观的看。

1. 在你的主机上安装一个nginx，这个教程我就不贴了，网上找吧，用yum或者dnf安装成服务；
2. 装好nginx后进入 /etc/nginx/conf.d 配置目录，vim一个名为qywx.conf 的文件，内容如下
```
server {
  server_name wx.xxx.com;

  location / {
	proxy_pass https://qyapi.weixin.qq.com/;
  }
  listen       80 ;
}
```
替换成你自己的域名
3. 重启nginx让这个配置生效了就行了，如果你没乱改nginx默认的/etc/nginx/nginx.conf 文件，那conf.d 目录的配置文件应该是会自动加载的。
4. 重启完去机器人微信推送的地方，把推送的那个腾讯官方域名，改成你自己自建的就可以了

**Comment by shenshangshang** [comment]
server {
  server_name wx.xxx.com;

  location / {
	proxy_pass https://qyapi.weixin.qq.com/;
  }
  listen       80 ;
}

**Comment by shenshangshang** [comment]
请问这里的域名是robot的域名还是另外的

**Comment by hyy34** [comment]
> > 一个本地群晖服务器一个阿里云服务器
> 
> 有阿里云固定ip很好，等我有时间写个搭建教程吧

请问搭建教程写了吗？

**Comment by pofey** [comment]
> > > 一个本地群晖服务器一个阿里云服务器
> > 
> > 
> > 有阿里云固定ip很好，等我有时间写个搭建教程吧
> 
> 请问搭建教程写了吗？

前面都已经给会员做好代理了还需要教程？

**Comment by hyy34** [comment]
> > > > 一个本地群晖服务器一个阿里云服务器
> > > 
> > > 
> > > 有阿里云固定ip很好，等我有时间写个搭建教程吧
> > 
> > 
> > 请问搭建教程写了吗？
> 
> 前面都已经给会员做好代理了还需要教程？

可能是来晚了，可信IP加不进去了。
