### ISSUE TITLE
[缺陷]: 过滤器中选择只从以下站点过滤时，订阅时无法下载最新剧集

### ISSUE THREAD

**Issue by happyhaha1** [pofey/movie_robot#697]
### 当前程序版本

1.3.2

### 问题描述

使用过滤器中选择只从柠檬站过滤时，柠檬站点已有该剧集新的集数时无法自动下载
![image](https://user-images.githubusercontent.com/10184254/189018430-524e2c8b-a2b3-41be-a2d4-4b5d9cc7318b.png)
搜索时可以搜索到
![image](https://user-images.githubusercontent.com/10184254/189018694-bad31b61-ad81-45ea-a05e-c96be522d874.png)
但是从订阅界面点击过滤重新提交可以触发自动下载。

该种子发布于1天前了
![image](https://user-images.githubusercontent.com/10184254/189018973-92320344-0651-4f13-b411-78946d416b40.png)

### 重现步骤

1、订阅消失的孩子，过滤器选择只从柠檬站过滤时
2、robot自动任务时显示但经过你设定的过滤器后，无任何结果。
3、但是从订阅界面点击过滤重新提交可以触发自动下载。

### 发生问题时系统日志

```shell
2022/09/08 10:02:56 - SubConsumer - INFO: 消失的孩子(2022) 已经有搜索结果，但经过你设定的过滤器后，无任何结果。


2022/09/08 10:08:07 - Thread-2978 - INFO: 共在16个站点搜索到41条结果，其中猫站最慢，耗费7.81秒
2022/09/08 10:08:55 - SubConsumer - INFO: 已经开始在站点: 阿童木,猫站,高清时间,红豆饭,观众,高清杜比,听听歌,丐帮,柠檬,海棠,天空,我堡,备胎,不可说,朋友,1pt,梓喵,馒头,聆音 搜索: 消失的孩子,The Disappearing Child
2022/09/08 10:09:18 - SubConsumer - INFO: 共在19个站点搜索到43条结果，其中馒头最慢，耗费22.52秒
2022/09/08 10:09:18 - SubConsumer - INFO: 消失的孩子(2022) 第1季 第[9, 10, 11, 12]集 品质：WEB-DL 1080p H.264 资源: https://lemonhd.org/details_tv.php?id=327211 已经提交下载。
2022/09/08 10:09:18 - lemonhd-downloader - INFO: 开始处理来自订阅的下载: [lemonhd]The Disappearing Child 2022 S01E09-E12 1080p LINETV WEB-DL H264 AAC-LeagueWEB
2022/09/08 10:09:20 - lemonhd-downloader - INFO: [lemonhd]The Disappearing Child 2022 S01E09-E12
```

### 健康检查

正常

**Comment by happyhaha1** [comment]
咋关闭了 。emm

**Comment by pofey** [comment]
没什么可分析的，这个地方也不会改。订阅成功率就不是100%
