### ISSUE TITLE
[提问]: 

### ISSUE THREAD

**Issue by HelIwalker** [pofey/movie_robot#699]
### 当前程序版本

1.3.1

### 问题

群晖DSM 6.2.3-25426系统

在1.3.1版本我删除了之前的docker全部重新配置了
现在想请教两个问题：

1.影库已有资源会重复下载，比如下面这两个(不是因为合集重复的，单集已有也会重复下载)：
消失的孩子：https://movie.douban.com/subject/35235616/
龙族：https://movie.douban.com/subject/35170003/

2.站点资源更新(最新集)两三天都不去自动下载，点击：我的订阅⋙剧集⋙过滤⋙提交，这样操作之后就会去搜索最新的剧集下载，比如：
莉可丽丝：https://movie.douban.com/subject/35722670/
不死者之王 第四季：https://movie.douban.com/subject/35460694/
异世界归来的舅舅：https://movie.douban.com/subject/35417872/

[log.zip](https://github.com/pofey/movie_robot/files/9524777/log.zip)

### 发生问题时系统日志

```shell
自镜像创建后几天的日志都传在上一对话框里了
```

**Comment by pofey** [comment]
自己分析吧，程序没问题
