### ISSUE TITLE
电视剧link反馈，问题有三

### ISSUE THREAD

**Issue by horseytr** [pofey/movie_robot#7]
1.在出现area:地区时，qb无法分配到指定分类，直接默认目录/downloads下载
<a href="https://sm.ms/image/XmpEUSZt5YwFA7f" target="_blank"><img src="https://s2.loli.net/2022/02/13/XmpEUSZt5YwFA7f.png" /></a>
2.下载时，出现不同版本的剧集同时下载，我们往往只需要一种版本
<a href="https://sm.ms/image/l7IV95BsudwNLqX" target="_blank"><img src="https://s2.loli.net/2022/02/13/l7IV95BsudwNLqX.png" /></a>
3.在出现多季的硬链接情况下，会出现剧集下的season2,season3，发送到.unknown文件夹下

**Comment by pofey** [comment]
1 2 3都已经修复，请升级到216v6
