### ISSUE TITLE
老大，虹猫蓝兔搜不到，我哪里设置错了？

### ISSUE THREAD

**Issue by leverule** [pofey/movie_robot#70]
![419f3b7fa8756956d325a71bcea2e8d](https://user-images.githubusercontent.com/57491211/165963958-5904141a-9456-401f-b10b-339a4c7963cf.png)
虹猫蓝兔七侠传也不行

**Comment by pofey** [comment]
前几天优化web搜索，改出一个bug，只搜了电影和剧集分类，忽略了动画，等3.9版本修复

**Comment by pofey** [comment]
0.3.9已经修复了
