### ISSUE TITLE
[缺陷]: 有些电影订阅后，无法正确匹配到资源。请考虑增加手动搜索选择资源的按钮？

### ISSUE THREAD

**Issue by CyEilo** [pofey/movie_robot#700]
### 当前程序版本

1.3.1

### 问题描述

巴黎墓穴 订阅后无法自动开始下载 （过滤器没有任何限制）手动搜索的话是可以搜到的

### 重现步骤

通过网页订阅或者通过douban 订阅后均无法开始下载

### 健康检查

手动搜索可以搜到合适的资源

**Comment by CyEilo** [comment]
补充 
2022/09/09 03:48:26 - SubRequestConsumer - INFO: 新增来自admin的订阅: 巴黎地下墓穴(2014) 选用过滤器：normal 排序规则：compress
stdout
19:50:27
2022/09/09 03:50:27 - SubConsumer - INFO: 共在3个站点搜索到4条结果，其中RARBG最慢，耗费136.17秒
stdout
19:50:27
2022/09/09 03:50:27 - SubConsumer - INFO: 巴黎地下墓穴(2014) 经过系统分析后，没有搜到有效结果。

我发现 tmdb的数据里电影名为“巴黎地下墓穴”
而大部分资源名字都是 “地下墓穴”

**Comment by pofey** [comment]
你已经知道原因了
