### ISSUE TITLE
[优化]: 纪录片订阅有的有问题

### ISSUE THREAD

**Issue by hexiao5688** [pofey/movie_robot#702]
### 当前现状

版本：1.3.1

纪录片订阅，下载分类识别错误，纪录片分类，进入了剧集目录  《华尔街》《鸟瞰地球》
![屏幕截图 2022-09-09 212932](https://user-images.githubusercontent.com/74167588/189362223-48066fdb-6ce8-431c-94c0-e75ebf2e0a1d.jpg)
![屏幕截图 2022-09-09 212835](https://user-images.githubusercontent.com/74167588/189362316-53e4526c-2217-482c-a997-95c63380043e.jpg)
![屏幕截图 2022-09-09 212819](https://user-images.githubusercontent.com/74167588/189362332-65fd77d4-3e81-4b16-b239-99ddd2632d74.jpg)
![屏幕截图 2022-09-09 212631](https://user-images.githubusercontent.com/74167588/189362377-9d44cd20-db9f-4282-87e5-277ddde749fc.jpg)
![屏幕截图 2022-09-09 212724](https://user-images.githubusercontent.com/74167588/189362392-1cdcbaa9-1cb5-4550-a55b-c04bf35b81e8.jpg)

### 你的建议

修复

### 优先级

一般

### 受众范围

不确定

**Comment by htnanako** [comment]
第一 好好去看wiki这块地方该怎么设置。
第二 分类以tmdb数据为准，确保tmdb上片子带了“纪录”分类。

**Comment by pofey** [comment]
图太多了 你先自己分析一下为什么
