### ISSUE TITLE
[提问]: 搜索模板无法保存

### ISSUE THREAD

**Issue by nicedc** [pofey/movie_robot#706]
### 当前程序版本

1.3.1

### 问题

程序首页搜索功能模版选项无法保存 也无法新建 持续两个版本，不太清楚是我自己配置问题还是什么原因
麻烦看一下。
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/94834977/189520075-c2e93c05-21e5-4ef4-a300-e9b62e5d1938.png">

### 发生问题时系统日志

```shell
create mbot(0): mbot(0)
启动升级脚本
完成系统默认配置初始化。
完成数据表升级。
2022-09-11 17:07:11,874 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-09-11 17:07:11,909 INFO supervisord started with pid 36
2022-09-11 17:07:12,913 INFO spawned: 'mbots' with pid 38
2022-09-11 17:07:17,918 INFO success: mbots entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2022/09/11 17:07:34 - MainThread - INFO: 添加事件(下载完成)监听器：NotifyListener
2022/09/11 17:07:34 - MainThread - INFO: 添加事件(订阅影片)监听器：NotifyListener
2022/09/11 17:07:34 - MainThread - INFO: 添加事件(开始下载)监听器：NotifyListener
2022/09/11 17:07:34 - MainThread - INFO: 添加事件(站点异常)监听器：NotifyListener
2022/09/11 17:07:34 - MainThread - INFO: 站点并发线程数：6
2022/09/11 17:07:34 - MainThread - INFO: 已开启企业微信接收消息配置
2022/09/11 17:07:34 - MainThread - INFO: Emby连接正常，DSM版本为4.7.6.0
2022/09/11 17:07:38 - MainThread - INFO: 新增任务：PT站点登陆有效性检查及分享数据更新任务
2022/09/11 17:07:39 - MainThread - INFO: 新增任务：免费下载种子监测任务
2022/09/11 17:07:39 - MainThread - INFO: 新增任务：站点资源同步任务
2022/09/11 17:07:39 - MainThread - INFO: 新增任务：同步豆瓣想看到订阅列表
2022/09/11 17:07:39 - MainThread - INFO: 新增任务：自定义任务调度
2022/09/11 17:07:39 - MainThread - INFO: 开启监控下载器手动种子任务。
2022/09/11 17:07:39 - MainThread - INFO: 开始监控保存目录为/downloads/Movie的所有下载任务
2022/09/11 17:07:39 - MainThread - INFO: 开始监控保存目录为/downloads/TV Series的所有下载任务
2022/09/11 17:07:39 - MainThread - INFO: 开始监控保存目录为/downloads/Documentaries的所有下载任务
2022/09/11 17:07:39 - MainThread - INFO: 开始监控保存目录为/downloads/Animes的所有下载任务
2022/09/11 17:07:39 - MainThread - INFO: 开始监控保存目录为/downloads/TV Shows的所有下载任务
2022/09/11 17:07:39 - MainThread - INFO: 新增任务：监听下载客户端下载状态
2022/09/11 17:07:39 - MainThread - INFO: 新增任务：订阅元数据检查更新任务
2022/09/11 17:07:39 - MainThread - INFO: 新增任务：新版本检测任务
2022/09/11 17:07:39 - Thread-7 - INFO: 开始更新媒体趋势榜单数据
2022/09/11 17:07:39 - MainThread - INFO: 新增任务：媒体趋势榜单任务
2022/09/11 17:07:39 - MainThread - INFO: 新增任务：健康检查任务
2022/09/11 17:07:39 - ThreadPoolExecutor-0_0 - INFO: Emby连接正常，DSM版本为4.7.6.0
2022/09/11 17:07:39 - MainThread - INFO: Emby连接正常，DSM版本为4.7.6.0
2022/09/11 17:07:39 - MainThread - INFO: 已经启动字幕下载处理任务。
2022/09/11 17:07:39 - MainThread - INFO: 当前版本: 1.3.1
2022/09/11 17:08:08 - Thread-7 - INFO: 媒体趋势榜单更新完毕
2022/09/11 17:08:14 - Thread-59 - ERROR: 请求出错：'name'
Traceback (most recent call last):
  File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
  File "mbot/controller/settingcontroller.py", line 664, in mbot.controller.settingcontroller.update_search_template.lambda2
  File "mbot/controller/settingcontroller.py", line 664, in mbot.controller.settingcontroller.update_search_template.lambda2
KeyError: 'name'
```

**Comment by nicedc** [comment]
补充：站点设置里面 web搜索 只能下载均已开启

**Comment by pofey** [comment]
把配置文件隐私信息删掉发出来才能判断

**Comment by nicedc** [comment]
#base_config.yml
download_client:
- host: 192.168.66.118
  is_default: false
  monitor_all_torrents: true
  name: Transmission
  need_login: true
  password: *
  port: 9091
  site_id: []
  status: 1
  type: transmission
  url: http://192.168.66.118:9091
  username: admin
- is_default: true
  monitor_all_torrents: false
  name: Qbittorrent
  need_login: false
  password: *
  site_id:
  - ssd
  - mteam
  status: 1
  type: qbittorrent
  url: http://192.168.66.118:8080
  username: admin
free_download:
  available_space: 512
  avg_statistics_period: 30
  enable: true
  maximum_active_torrent: 0
  save_path: /downloads/downloads
  upload_mbps_maximum: 30
frontend:
  search_template:
  - name: 默认
    option:
      category:
      - Movie
      - TV
      - Documentary
      - Anime
      searchContent:
      - searchDouban
      - searchMediaServer
      - searchSite
      site:
      - mteam
  - option:
      category:
      - Movie
      - TV
      - Documentary
      - Anime
      searchContent:
      - searchDouban
      - searchMediaServer
      - searchSite
      site:
      - mteam
      - ssd
media_path:
- download_path: /downloads/Movie
  file_process_mode: link
  qbit_cate: ''
  source_dir: /video/Movie
  target_dir: /video/Movie_p
  type: movie
  use_area_folder: true
- download_path: /downloads/TV Series
  file_process_mode: link
  qbit_cate: ''
  source_dir: /video/TV Series
  target_dir: /video/TV Series_p
  type: tv
  use_area_folder: true
- download_path: /downloads/Documentaries
  file_process_mode: link
  qbit_cate: ''
  source_dir: /video/Documentaries
  target_dir: /video/Documentaries_p
  type: tv
- download_path: /downloads/Animes
  file_process_mode: link
  qbit_cate: ''
  source_dir: /video/Animes
  target_dir: /video/Animes_p
  type: tv
  use_area_folder: false
- download_path: /downloads/Animes
  file_process_mode: link
  qbit_cate: ''
  source_dir: /video/Animes
  target_dir: /video/Animes_p
  type: movie
- download_path: /downloads/TV Shows
  file_process_mode: link
  qbit_cate: ''
  source_dir: /video/TV Shows
  target_dir: /video/TV Shows_p
  type: tv
media_server:
  default: emby
  emby:
    api_key: *
    host: 192.168.66.118
    https: false
    port: 8096
movie_metadata:
  douban:
    cookie: *
  fanart:
    api_key: *
    proxies: ''
  tmdb:
    api_key: *
    proxies: ''
notify_channel:
  bark:
    enable: true
    group: 电影机器人
    icon: https://yee-1254270141.cos.ap-beijing.myqcloud.com/movie_robot/icon.jpg
    push_url: *
    sound: birdsong
  qywx:
    aes_key: *
    agentid: '1000005'
    corpid: *
    corpsecret: *
    enable: true
    server_url: http://robot.xface.top/api/qywx/receive
    token: *
    touser: '@all'
    use_server_proxy: true
  telegram:
    enable: false
    proxy: socks5://mr:123456@192.168.66.2:7891
    server_url: https://api.telegram.org
    token: *
    user_id: '2090491137'
scraper: {}
server: {}
smart_download:
  douban:
    default_score_rule: compress
    download_paths:
    - area: []
      cate:
      - 纪录
      download_path: /downloads/Documentaries
      score_rule: compress
      type: tv
    - area: []
      cate:
      - 动画
      - 儿童
      download_path: /downloads/Movie
      score_rule: compress
      type: movie
    - area: []
      cate:
      - 儿童
      - 动画
      download_path: /downloads/Animes
      score_rule: compress
      type: tv
    - area: []
      cate:
      - 真人秀
      download_path: /downloads/TV Shows
      score_rule: compress
      type: tv
    - area: []
      cate: []
      download_path: /downloads/Movie
      score_rule: compress
      type: movie
    - area: []
      cate: []
      download_path: /downloads/TV Series
      score_rule: compress
      type: tv
    tags: []
    users:
    - id: '147537295'
      pull_time_range: 365
subtitle:
  enable: true
  exclude_area:
  - 中国大陆
  - 中国台湾
  file_name_template: '{{ name }}.{{ language[0] }}{% if language[0] == "zh-cn" and
    language | length == 2 %}.default{% endif%}{{ subtitle_ext }}'
  filter_type:
  - srt
  - ass
  finder_type:
  - zimuku
  - subhd
  not_found_stop_minutes: 4320
  sync_language:
  - zh-cn
  - zh-tw
web:
  host: '::'
  port: 1329
  server_url: http://
