### ISSUE TITLE
[优化]: 关键字订阅选择多站点，会重复下载

### ISSUE THREAD

**Issue by Alano-i** [pofey/movie_robot#707]
### 当前现状

关键字订阅若配置多个下载站点会从这几个站都下载一遍。
<img width="814" alt="image" src="https://user-images.githubusercontent.com/68833595/189559412-a912ce20-1dbb-495e-874a-d847d103127d.png">

### 你的建议

多个站点如果已经有一个站下载好了，就不在下载其他站点

### 优先级

非常高

### 受众范围

很多人需要

**Comment by pofey** [comment]
正常
