### ISSUE TITLE
TG推送失败

### ISSUE THREAD

**Issue by Macondo1224** [pofey/movie_robot#709]
### 当前程序版本

1.3.1

### 问题描述

tg推送在测试时是正常的，但是订阅下载及下载完成时就报错，无法推送

### 重现步骤

我是路由器科学上网的，之前tg推送一直是正常的，有一天突然就不可以了，但是点击推送测试是没问题，实际使用就不行，bark什么的都是正常

### 发生问题时系统日志

```shell
ERROR: telegram推送失败：Bad Request: failed to get HTTP URL content
ERROR: telegram推送失败：Bad Request: wrong file identifier/HTTP URL specified
```

### 健康检查

![E24FC1E3-2AD6-43B7-9087-B1CF5BB83918](https://user-images.githubusercontent.com/108214719/189615241-150192b1-a154-48a5-8da0-b66ac30232ed.png)

**Comment by zoooo0** [comment]
同样 1.3.2也是会报错

**Comment by pofey** [comment]
那就用bark

**Comment by wustyu** [comment]
bark只有ios版本吧 对安卓用户来说  现在推送就有点尴尬  telegram 有时候报错 企业微信现在也ip也绑定不了

**Comment by pofey** [comment]
> bark只有ios版本吧 对安卓用户来说 现在推送就有点尴尬 telegram 有时候报错 企业微信现在也ip也绑定不了

你有什么好办法
