### ISSUE TITLE
需求:养站希望可以增加远程访问功能!

### ISSUE THREAD

**Issue by WuhanSy** [pofey/movie_robot#71]
现实场景:我有两个nas,我希望一种是专门挂PT养站的.另一种日常使用,可是两个nas都需要安装qbittorren和movie-robot并进行维护.能不能在我日常机器中通过movie-robot访问另一个专门养站的qbittorrent?甚至是远程访问其他位置的qbittorrent呢?

**Comment by pofey** [comment]
目前没有限制用远程地址连接

**Comment by WuhanSy** [comment]
我的意思是movie-robot能否添加两个下载工具，一个日常影音播放下载使用(机器A)，一个是对应养站刷数据使用(机器B)。最大程度上实现资源的利用。

**Comment by pofey** [comment]
> 我的意思是movie-robot能否添加两个下载工具，一个日常影音播放下载使用(机器A)，一个是对应养站刷数据使用(机器B)。最大程度上实现资源的利用。

我个人目前的判断，多下载器都是伪需求，跟看电影无关。你可以通过起两个容器达到目的。
