### ISSUE TITLE
[提问]: 搜索模板无法保存

### ISSUE THREAD

**Issue by nicedc** [pofey/movie_robot#714]
### 当前程序版本

1.3.1

### 问题

程序首页搜索功能模版选项无法保存 也无法新建 持续两个版本，不太清楚是我自己配置问题还是什么原因
麻烦看一下。
![](https://user-images.githubusercontent.com/94834977/189520075-c2e93c05-21e5-4ef4-a300-e9b62e5d1938.png)

====配置文件======
`download_client:
- host: 192.168.66.118
  is_default: false
  monitor_all_torrents: true
  name: Transmission
  need_login: true
  password: *******
  port: 9091
  site_id: []
  status: 1
  type: transmission
  url: http://192.168.66.118:9091
  username: admin
- is_default: true
  monitor_all_torrents: false
  name: Qbittorrent
  need_login: false
  password: *******
  site_id:
  - ssd
  - mteam
  status: 1
  type: qbittorrent
  url: http://192.168.66.118:8080
  username: admin
free_download:
  available_space: 512
  avg_statistics_period: 30
  enable: true
  maximum_active_torrent: 0
  save_path: /downloads/downloads
  upload_mbps_maximum: 30
frontend:
  search_template:
  - name: 默认
    option:
      category:
      - Movie
      - TV
      - Documentary
      - Anime
      searchContent:
      - searchDouban
      - searchMediaServer
      - searchSite
      site:
      - mteam
  - option:
      category:
      - Movie
      - TV
      - Documentary
      - Anime
      searchContent:
      - searchDouban
      - searchMediaServer
      - searchSite
      site:
      - mteam
      - ssd
media_path:
- download_path: /downloads/Movie
  file_process_mode: link
  qbit_cate: ''
  source_dir: /video/Movie
  target_dir: /video/Movie_p
  type: movie
  use_area_folder: true
- download_path: /downloads/TV Series
  file_process_mode: link
  qbit_cate: ''
  source_dir: /video/TV Series
  target_dir: /video/TV Series_p
  type: tv
  use_area_folder: true
- download_path: /downloads/Documentaries
  file_process_mode: link
  qbit_cate: ''
  source_dir: /video/Documentaries
  target_dir: /video/Documentaries_p
  type: tv
- download_path: /downloads/Animes
  file_process_mode: link
  qbit_cate: ''
  source_dir: /video/Animes
  target_dir: /video/Animes_p
  type: tv
  use_area_folder: false
- download_path: /downloads/Animes
  file_process_mode: link
  qbit_cate: ''
  source_dir: /video/Animes
  target_dir: /video/Animes_p
  type: movie
- download_path: /downloads/TV Shows
  file_process_mode: link
  qbit_cate: ''
  source_dir: /video/TV Shows
  target_dir: /video/TV Shows_p
  type: tv
media_server:
  default: emby
  emby:
    api_key: *******
    host: 192.168.66.118
    https: false
    port: 8096
movie_metadata:
  douban:
    cookie: *******
  fanart:
    api_key: *******
    proxies: ''
  tmdb:
    api_key: *******
    proxies: ''
notify_channel:
  bark:
    enable: true
    group: 电影机器人
    icon: https://yee-1254270141.cos.ap-beijing.myqcloud.com/movie_robot/icon.jpg
    push_url: http://*******/*******/
    sound: birdsong
  qywx:
    aes_key: *******
    agentid: '*******'
    corpid: *******
    corpsecret: *******
    enable: true
    server_url: http://*******/api/qywx/receive
    token: *******
    touser: '@all'
    use_server_proxy: true
  telegram:
    enable: false
    proxy: socks5://mr:123456@192.168.66.2:7891
    server_url: https://api.telegram.org
    token: *******
    user_id: '*******'
scraper: {}
server: {}
smart_download:
  douban:
    default_score_rule: compress
    download_paths:
    - area: []
      cate:
      - 纪录
      download_path: /downloads/Documentaries
      score_rule: compress
      type: tv
    - area: []
      cate:
      - 动画
      - 儿童
      download_path: /downloads/Movie
      score_rule: compress
      type: movie
    - area: []
      cate:
      - 儿童
      - 动画
      download_path: /downloads/Animes
      score_rule: compress
      type: tv
    - area: []
      cate:
      - 真人秀
      download_path: /downloads/TV Shows
      score_rule: compress
      type: tv
    - area: []
      cate: []
      download_path: /downloads/Movie
      score_rule: compress
      type: movie
    - area: []
      cate: []
      download_path: /downloads/TV Series
      score_rule: compress
      type: tv
    tags: []
    users:
    - id: '*******'
      pull_time_range: 365
subtitle:
  enable: true
  exclude_area:
  - 中国大陆
  - 中国台湾
  file_name_template: '{{ name }}.{{ language[0] }}{% if language[0] == "zh-cn" and
    language | length == 2 %}.default{% endif%}{{ subtitle_ext }}'
  filter_type:
  - srt
  - ass
  finder_type:
  - zimuku
  - subhd
  not_found_stop_minutes: 4320
  sync_language:
  - zh-cn
  - zh-tw
web:
  host: '::'
  port: 1329
  server_url: http://
`

### 发生问题时系统日志

```shell
=======log=======
movie-robot    | 2022/09/15 10:42:04 - MainThread - INFO: 当前版本: 1.3.1
movie-robot    | 2022/09/15 10:42:20 - Thread-30 - ERROR: 请求出错：'name'
movie-robot    | Traceback (most recent call last):
movie-robot    |   File "mbot/register/bp_register.py", line 34, in mbot.register.bp_register.login_required.wrapper.decorator
movie-robot    |   File "mbot/controller/settingcontroller.py", line 664, in mbot.controller.settingcontroller.update_search_template.lambda2
movie-robot    |   File "mbot/controller/settingcontroller.py", line 664, in mbot.controller.settingcontroller.update_search_template.lambda2
movie-robot    | KeyError: 'name'
```

**Comment by pofey** [comment]
自己保存了一个不带名字的自己不知道吗？search_template 配置都干掉重新来吧
