### ISSUE TITLE
[提问]: 手动搜索站点电影很快，订阅电影自动搜索速度很慢

### ISSUE THREAD

**Issue by zzj6666** [pofey/movie_robot#715]
### 当前程序版本

1.3.36

### 问题

![image](https://user-images.githubusercontent.com/101039599/190303522-ad6abe6b-1ead-44ad-8225-f5ecb8337d79.png)
不知道是不是我的问题，还是机器人的问题

**Comment by pofey** [comment]
你自己搜一个，订阅要搜2-3个词，而且要保证绝对都成功，差别很大啊
