### ISSUE TITLE
[优化]: 支持以非root权限运行

### ISSUE THREAD

**Issue by Gccxeon** [pofey/movie_robot#716]
### 当前现状

使用环境：Ubuntu 20.04 + Docker CE

目前程序只支持以root方式启动，但是这会导致所映射的目录及文件所有者被更改为root。影响其他以非root用户读写该目录的程序运行。

### 你的建议

期望容器内部支持PGID和PUID环境变量，在初始入口处先创建用户，再该用户身份运行，同时修正映射目录权限。

### 优先级

非常高

### 受众范围

一般

**Comment by pofey** [comment]
有啊
