### ISSUE TITLE
[优化]: 订阅刚上映的电视剧（或已经有其中几集）能否自动屏蔽“全集”二字

### ISSUE THREAD

**Issue by zzj6666** [pofey/movie_robot#718]
### 当前现状

订阅了正在更新的电视剧，然后电视剧更新完了，因为PT站点直接全集打包了，因为只差最后一两集，导致机器人直接全集下载了，之前下载的都全部重复了

### 你的建议

要是机器人能先识别到已经有集数的剧集，然后自动略过“全集”这两个字，是不是就好了

### 优先级

非常高

### 受众范围

很多人需要

**Comment by pofey** [comment]
这个问题先不优化 只是多下载一点而已
