### ISSUE TITLE
[缺陷]: 搜索经常会有pt站显示报错 错误信息：Server disconnected without sending a response

### ISSUE THREAD

**Issue by wustyu** [pofey/movie_robot#720]
### 当前程序版本

1.3.37

### 问题描述

订阅影片后 经常会有pt站显示给不出回应报错，错误信息：Server disconnected without sending a response，电脑直连pt站没问题。

### 重现步骤

订阅影片，后台日志报错

### 发生问题时系统日志

```shell
2022/09/16 23:15:17 - SubConsumer - INFO: 已经开始在站点(13): 阿童木,馒头,carpt,红豆饭,pt时间,1pt,高清时间,备胎,观众,猪猪,开心,马杀鸡,filelist 搜索: 半个喜剧,Almost a Comedy,tt11273332
2022/09/16 23:16:19 - SubConsumer - INFO: 开心搜索半个喜剧出错，自动重试中，错误信息：Server disconnected without sending a response.
2022/09/16 23:16:32 - SubConsumer - INFO: 共在13个站点搜索到10条结果，其中猪猪最慢，耗费75.05秒
```

### 健康检查

![image](https://user-images.githubusercontent.com/9413400/190675962-74e4e4a9-6539-4aa3-a8d6-8969a2f94832.png)

**Comment by pofey** [comment]
网络问题太复杂了，订阅你别管他有多慢，最终保证都搜到就行。
