### ISSUE TITLE
[缺陷]: 重装后应用设置有问题

### ISSUE THREAD

**Issue by 2263075977** [pofey/movie_robot#728]
### 当前程序版本

1.3.39

### 问题描述

重新安装后
1.“设置媒体文件夹”会保存不了
2.“豆瓣想看与智能下载保存规则”设置选取不了
查看了base_config.yml文件 发现没有相关代码 需要自行写入 对新玩家可能不太友好
个人猜想：可能和wiki教程中，通过网页完成首次初始化时并没有弹出“媒体服务器设置”，“下载工具设置”，“存储路径(媒体文件夹)设置”有关

### 重现步骤

试过将base_config.yml删除 重启还是一样

### 发生问题时系统日志

```shell
无相关日志
```

### 健康检查

刚初始化 无健康检查

**Comment by wustyu** [comment]
这个问题我也出现了

**Comment by pofey** [comment]
媒体路径我看了下可以读，但是豆瓣那个页面确实bug 设置不了了

**Comment by pofey** [comment]
媒体路径也可以保存

**Comment by pofey** [comment]
修复了 新版正在推
