### ISSUE TITLE
[提问]:  MR在订阅 剧集时，触发过滤器后 无结果，但实际手动搜索是有的

### ISSUE THREAD

**Issue by PANGPANGDigital** [pofey/movie_robot#729]
### 当前程序版本

1.3.1

### 问题

在搜索 你安全吗？ 这部剧的时候，站点是有 2160P ADWeb 这个组压制的，于是在订阅时选择了这两个关键词，MR过滤器筛选后返回 “已经有搜索结果，但经过你设定的过滤器后，无任何结果。”

实际我是想要过滤器 命中 ADweb 这个组压制的 4k 你安全吗？ 这个剧
**过滤器只 设置了压制组为 “ADweb”，和 分辨率 “4k”、“2160P”**

### 发生问题时系统日志

```shell
2022/09/18 12:07:22 - SubConsumer - INFO: 共在7个站点搜索到8条结果，其中观众最慢，耗费13.05秒                                                           
2022/09/18 12:07:22 - SubConsumer - INFO: 你安全吗？(2022) 已经有搜索结果，但经过你设定的过滤器后，无任何结果。
```

**Comment by htnanako** [comment]
你自己已经回答了

**Comment by PANGPANGDigital** [comment]
> 你自己已经回答了

老哥，我的意思是 我只需要 ADWeb这个组的 4k版 你安全吗？ 这个剧集，但通过过滤器筛选的时候，把这个过滤掉了，没有命中

**Comment by htnanako** [comment]
> > 你自己已经回答了
> 
> 老哥，我的意思是 我只需要 ADWeb这个组的 4k版 你安全吗？ 这个剧集，但通过过滤器筛选的时候，把这个过滤掉了，没有命中

你这样提问是觉得我们会算命？

**Comment by htnanako** [comment]
> > 你自己已经回答了
> 
> 老哥，我的意思是 我只需要 ADWeb这个组的 4k版 你安全吗？ 这个剧集，但通过过滤器筛选的时候，把这个过滤掉了，没有命中

![2356121663479909_ pic](https://user-images.githubusercontent.com/68056603/190888778-9e247926-e723-4790-9090-e6e9f9335ee5.jpg)
