### ISSUE TITLE
[缺陷]: 手动整理资源的时候不识别tmdb部分季

### ISSUE THREAD

**Issue by q381151220** [pofey/movie_robot#730]
### 当前程序版本

1.3.1

### 问题描述

手动整理资源的时候，不识别tmdb的部分季，会直接识别为第一季然后覆盖。

### 重现步骤

![0a2d8fa4b252e6a0877d062868141fb](https://user-images.githubusercontent.com/52910011/190894603-e0aec858-43c0-4660-b6f1-612c69aba651.jpg)
![0cd10504fe07ef1a7fbd3e330b5e915](https://user-images.githubusercontent.com/52910011/190894607-e9f5db28-d8ba-4a95-b0f9-ddd1e0c87999.jpg)
手动识别报告老板这个剧集，如图填写内容，1.2季都可以正常识别出来，0季无法识别。会识别成第一季，然后覆盖第一季的内容。

### 健康检查

部分动漫也会有这种问题，手动识别第2季的时候，会错误识别成第一季，然后覆盖。

**Comment by pofey** [comment]
不支持动漫

**Comment by q381151220** [comment]
> 不支持动漫

您好 一开始是识别电视剧第0季错误 正好手头还有没有刮的动漫所以才试了一下

**Comment by pofey** [comment]
> > 不支持动漫
> 
> 您好 一开始是识别电视剧第0季错误 正好手头还有没有刮的动漫所以才试了一下

识别已经不做优化了，现在的架构实现，就这样不改了。95%以上用着都很好
