### ISSUE TITLE
[提问]: 刷流和订阅下载的下载器分开

### ISSUE THREAD

**Issue by wustyu** [pofey/movie_robot#731]
### 当前程序版本

1.3.39

### 问题

我现在有两台设备，一台是nas 一台是n5105小主机 专门买的固态是在5105主机上 ，想要正常的订阅推送给nas上的qb下载 ，刷流的任务推送到5105主机的qb上 可否专门为刷流设置一个下载器。

### 发生问题时系统日志

```shell
无
```

**Comment by htnanako** [comment]
https://yee329.notion.site/e73e20b466104ca486ac37a26d81587d
