### ISSUE TITLE
[提问]: 关于自动刷流 下载的hr种子 完成hr时间后如何处理请教

### ISSUE THREAD

**Issue by wustyu** [pofey/movie_robot#737]
### 当前程序版本

1.3.39

### 问题

我发现有的hr的种子是不会随便删除，但是当该种子已经达标后，上传已经没速度了，mr也不会处理这个种子，请问这种是需要用户手动删除吗

### 发生问题时系统日志

```shell
无日志
```

**Comment by pofey** [comment]
做种时间达标会自动删
