### ISSUE TITLE
[提问]: 过滤器订阅问题请教

### ISSUE THREAD

**Issue by PANGPANGDigital** [pofey/movie_robot#742]
### 当前程序版本

1.3.1

### 问题

衣总好，在通过过滤器下载 “你安全吗？”这部剧的时候，出现了手动搜索有资源，但经过过滤器后没有命中的情况，想咨询下哪里有配置不对的地方，感谢！
![配置1](https://user-images.githubusercontent.com/95346888/191284346-7979ff29-d96f-419e-a470-aafab6f4d918.png)
![配置2](https://user-images.githubusercontent.com/95346888/191284355-c1ba178e-d39b-4c71-89da-3990946cc4c7.png)
![手动搜索](https://user-images.githubusercontent.com/95346888/191284360-536ab8a0-70a4-4f1a-8089-0500d1ded522.png)

### 发生问题时系统日志

```shell
2022/09/20 22:22:41 - SubConsumer - INFO: 已经开始在站点: 观众,备胎,阿童木,馒头,家园 搜索: 你安全吗？,Are You Safe?                                     
2022/09/20 22:22:41 - Thread-27 - INFO: 共在7个站点搜索到14条结果，其中聆音最慢，耗费5.6秒                                                                                                                                                        
2022/09/20 22:22:54 - SubConsumer - INFO: 共在5个站点搜索到14条结果，其中观众最慢，耗费13.09秒                                                          
2022/09/20 22:22:54 - SubConsumer - INFO: 你安全吗？(2022) 已经有搜索结果，但经过你设定的过滤器后，无任何结果。
```

**Comment by pofey** [comment]
![BE71B5CB-B6EE-4DE4-A422-2434DA441B88](https://user-images.githubusercontent.com/1396975/191317030-50704208-dd4d-4724-9301-329c2b48728d.png)
看我的beta版就明白了，观众这几个影片名没拆对

**Comment by PANGPANGDigital** [comment]
谢谢衣总，明白了。换了个过滤器目前能正常拉取

**Comment by PANGPANGDigital** [comment]
![f6ca0c6e6ae57c5a9d3fdd739b20cf1](https://user-images.githubusercontent.com/95346888/191412138-0ab577c8-99fc-425a-82ba-9316981c2786.jpg)

通过机器人添加的订阅，第一次添加的时候会有结果，再之后的 监控中，会显示 没有匹配的资源。（当前为Beta 1.3.44）

**Comment by PANGPANGDigital** [comment]
![微信截图_20220921122819](https://user-images.githubusercontent.com/95346888/191414582-40ab54cb-6dd0-47fd-87b1-c122feb6ca37.png)
![微信截图_20220921122832](https://user-images.githubusercontent.com/95346888/191414585-384084ab-8687-4f66-bf0c-c8ebe1bffd76.png)

**Comment by pofey** [comment]
感觉命名会比较奇葩的剧就别用过滤器了 能下到就行
