### ISSUE TITLE
[优化]: 追更剧集，完结后下载全集大包问题

### ISSUE THREAD

**Issue by wustyu** [pofey/movie_robot#743]
### 当前现状

追更剧集，当剧集完结后  网站会发出全集大包，mr多次命中大包下载 造成重复下载。

### 你的建议

是否能**比对全集包中的内容和当前媒体库已有内容 ，只下载缺失的部分**，比如 罚罪有40集 ，媒体库中有38集，分析全集大包 只下载 39 40 两集。之前在群里提到过 剧集专门订阅某个网站，我订阅的是观众，还是发出了全集大包。

### 优先级

一般

### 受众范围

很多人需要

**Comment by ShakeChanDev** [comment]
观众我记得文件夹命名是一样的，在下载器看起来是大包，实际上之前下过的理论上会走校验，我猜测的没实践过

**Comment by wustyu** [comment]
你这么一说  好像我有印象，确实是有校验的

**Comment by hexiao5688** [comment]
我觉得追剧，最后应下合集大包，自动删除以前散装，最后上传都是合集，并免费

**Comment by wustyu** [comment]
。。。。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月2日(周日) 晚上10:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [pofey/movie_robot] [优化]: 追更剧集，完结后下载全集大包问题 (Issue #743)




 
我觉得追剧，最后应下合集大包，自动删除以前散装，最后上传都是合集，并免费
 
&mdash;

**Comment by hexiao5688** [comment]
我觉得追剧，最后应下合集大包，自动删除以前散装，最后上传都是合集，并免费
