### ISSUE TITLE
[缺陷]: 资源整理出现问题

### ISSUE THREAD

**Issue by vickychien0114** [pofey/movie_robot#744]
### 当前程序版本

1.3.44

### 问题描述

升级了 1.3.44后资源整理页面以前整理好的资源全变成待识别，重新整理后也是显示待识别，日志里显示已经完成整理
![未命名1663691318](https://user-images.githubusercontent.com/101592714/191313523-70bb9914-cdac-44b8-8d88-9623f4df64ce.png)
![未命名1663691336](https://user-images.githubusercontent.com/101592714/191313529-065cb081-c05a-4706-a6c2-606defd48493.png)

### 重现步骤

无

### 健康检查

        无

**Comment by pofey** [comment]
下一版修复
