### ISSUE TITLE
[优化]: 自定义关键字订阅 希望增加选项 是否「下载完成后自动替换掉媒体服务器的旧版」

### ISSUE THREAD

**Issue by ShakeChanDev** [pofey/movie_robot#746]
### 当前现状

现在是默认替换掉媒体服务器旧版

### 你的建议

解决的需求

1. 对命名混乱的剧集（例如综艺），在追更时可以保证基本的下载入库，后续再自行手动刮削
  - 例如：
> 综艺的命名：脱口秀大会第五季 第六期 tmdb是 [E05]，腾讯名叫[第2期上]，种子名叫[E02.part1]
剧集订阅：当新一期E02.part2出来后，如果是走剧集订阅，机器人会认为已经有E02了而不进行下载，所以需要用自定义来解决
如果是用自定义：自定义会把E02.part2下载下来，这时候会发现库里有E02，会将原来的E02替换

2. 想保留多版本的人群（例如4k和1080p）

### 优先级

一般

### 受众范围

追更综艺以及其他命名混乱的剧集的人群

**Comment by pofey** [comment]
新版超级自定义没这个问题了
