### ISSUE TITLE
[优化]: 希望能支持方糖

### ISSUE THREAD

**Issue by lingyizhuzhu** [pofey/movie_robot#747]
### 当前现状

1.微信企业微信又加强限制了，后期个人想添加企业微信推送基本上不行了。
2.微信企业微信需要“可信”的IP，没新限制之前的你买的阿里云服务器添加可信IP提示第三方也用不了。

### 你的建议

希望能支持方糖，这个可以在微信里面推送，也方便一些。

### 优先级

一般

### 受众范围

一般

**Comment by pofey** [comment]
用bark或者pushdeer

**Comment by lingyizhuzhu** [comment]
方糖能在微信里面通知，要方便不少。

**Comment by pofey** [comment]
他那两个渠道不是也要关了么

**Comment by lingyizhuzhu** [comment]
是嘛，腾讯真可恶
