### ISSUE TITLE
[优化]: 订阅的剧在过滤器里面添加一个默认的保存路径

### ISSUE THREAD

**Issue by lingyizhuzhu** [pofey/movie_robot#750]
### 当前现状

1.目前订阅的剧有一些会显示找不到下载路径。
2.我看了教程，但是，电视剧和动漫都是剧集。
3.设置剧集有多个路径是不是会有一些冲突，导致目标剧没有下载到我想要的路径里面。

### 你的建议

1.在过滤器里面增加目标订阅保存到指定路径，该指定路径对应媒体库的路径，如电影-电影，电视剧-电视剧，动漫-动漫。防止电视剧和动漫的路径串串。
2.比如苍兰诀就在2022年几乎同时出了电视剧和动漫，订阅里面就搞不定，显示已经有了，但是动漫其实还在更新，只是电视剧的更新完了。

### 优先级

非常高

### 受众范围

一般

**Comment by pofey** [comment]
这个和保存路径有啥关系呢，你的诉求再总结清楚一点
