### ISSUE TITLE
[缺陷]: mr资源整理功能，在识别整理中选择分类后移动到目标目录，然后整部电视剧就消失了，只剩空文件夹

### ISSUE THREAD

**Issue by zhouxingchiaiguanxiaodan** [pofey/movie_robot#752]
### 当前程序版本

1.4.3

### 问题描述

mr资源整理功能，在识别整理中选择分类后移动到目标目录，然后整部电视剧就消失了，只剩空文件夹

### 重现步骤

1.mr选择资源整理。
2.选择识别整理，之后选择分类后移动到目标目录。
3.点击确定之后，电视剧突然消失，只剩空文件夹。
4.在nas中的所有文件夹都找不到电视剧去了哪里，也没有到目标目录中，日志中无显示。

### 发生问题时系统日志

```shell
日志中什么都没有
```

### 健康检查

![批注 2022-09-23 191841](https://user-images.githubusercontent.com/97221178/191959513-7e00e53b-d613-4f85-a4f9-959e2f9b61ff.jpg)

**Comment by pofey** [comment]
你这个重现步骤太泛泛了，按你的说法是重现不了的
