### ISSUE TITLE
[提问]: 我unraid下，机器人找到资源，但是无法下载，说是下载失败，有谁遇到同样的问题吗？

### ISSUE THREAD

**Issue by cszs1986** [pofey/movie_robot#756]
### 当前程序版本

1.41

### 问题

![bf80b65981ed522dad36cdbc6ff5ded](https://user-images.githubusercontent.com/30801827/192225612-ecb47a2e-fe46-4e9f-b9c4-6b46113e1b02.jpg)

以找到资源，但是下载失败，其他的资源也是这样

**Comment by pofey** [comment]
就学校一个站点？

**Comment by cszs1986** [comment]
> 就学校一个站点？

是的，现在弄好了
这边是删除了容器和删除了所有配置文件后重新安装就好了

我感觉是升级后再又升级，是不是什么数据混乱了，才出现这样的？
因为只有升级后才出现这样的情况，之前没问题啊
