### ISSUE TITLE
订阅失败，不明原因

### ISSUE THREAD

**Issue by WuhanSy** [pofey/movie_robot#76]
2022/05/04 08:18:42 - SubRequestConsumer - INFO: 绝密543(2017) 选用过滤器：Emby过滤 排序规则：compress
2022/05/04 08:18:42 - SubConsumer - INFO: 已经开始在站点: 馒头 搜索: 绝密543
2022/05/04 08:18:42 - SubConsumer - INFO: 已开启网络异常重试机制，最多可能等待15分钟。
2022/05/04 08:18:42 - SubRequestConsumer - INFO: 新增来自WuhanSy的订阅: 绝密543(2017)
2022/05/04 08:18:45 - SubConsumer - INFO: 共在1个站点搜索到2条结果，其中馒头最慢，耗费3.38秒
2022/05/04 08:18:45 - SubConsumer - INFO: 绝密543(2017) 第1季 全集 品质：WEB-DL 1080p H.264 资源: https://kp.m-team.cc/details.php?id=543805&hit=1 已经提交下载。
2022/05/04 08:18:45 - DownloadConsumer - INFO: 开始处理来自订阅的下载: [mteam]Top Secret 2017 Complete WEB-DL 1080p H264 AAC-HDSWEB
2022/05/04 08:18:45 - SubConsumer - INFO: 绝密543(2017) 第1季 本次下载的种子中，包含有全集字样信息，将默认本剧完结，停止订阅不再智能下载。
2022/05/04 08:18:45 - DownloadConsumer - ERROR: 处理下载任务失败：error() missing 1 required positional argument: 'msg'

Traceback (most recent call last):
File "yee/consumer/downloadconsumer.py", line 32, in yee.consumer.downloadconsumer.DownloadConsumer.run
File "yee/service/downloadservice.py", line 353, in yee.service.downloadservice.DownloadService.download_from_sub
TypeError: error() missing 1 required positional argument: 'msg'

**Comment by pofey** [comment]
升级到最新版 然后看这个 https://yee329.notion.site/08fe4ef7e4914374a5c898e754616fc4
