### ISSUE TITLE
[缺陷]: 识别前带season的2级目录，整理完后没有文件后缀

### ISSUE THREAD

**Issue by mjyhj** [pofey/movie_robot#761]
### 当前程序版本

1.4.17

### 问题描述

硬链接整理完后，文件不带后缀
![1](https://user-images.githubusercontent.com/22577418/193242447-cd92bb0f-98b7-47c8-8c71-e78b48620a3c.jpg)

源目录路径：\\192.168.123.254\download3\电视剧\天才枪手 (2020)\Season 1\天才枪手 - S01E01 - 第 1 集.mkv
link目录路径：\\192.168.123.254\download3\电视剧link\天才枪手(剧版) (2020) [tmdbid=106868]\Season 1\天才枪手(剧版) S01E01

### 重现步骤

web上直接识别，从1.3的版本开始发现就这样了

### 发生问题时系统日志

关联https://github.com/pofey/movie_robot/issues/668

### 健康检查

正常

**Comment by pofey** [comment]
beta修了
