### ISSUE TITLE
[缺陷]: rarbg不识别集数导致不断重复下载

### ISSUE THREAD

**Issue by kriskwok** [pofey/movie_robot#764]
### 当前程序版本

1.5.3

### 问题描述

从rarbg下载的剧集经常不显示第几集，然后就开启不停的重复下载，大概是这么回事，这个问题困扰有半个多月了。
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/31760242/194692098-5ccc2e9c-9548-449a-9d63-3afd905d33b3.png">
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/31760242/194692114-3d681182-9f3e-4279-898a-e2aedc522c35.png">
<img width="619" alt="image" src="https://user-images.githubusercontent.com/31760242/194692148-46a4ba13-5a9b-4f57-b62b-184cd7d82d3e.png">

### 重现步骤

自动订阅下载，也尝试过重新订阅，问题重现。

### 健康检查

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/31760242/194692243-c1dc1fba-1ecf-41a2-a497-c61bd28ba1df.png">

**Comment by pofey** [comment]
这个线索给的好，下一版修复掉

**Comment by pofey** [comment]
beta已经上线了
