### ISSUE TITLE
自定义 流量管理 页面所采用的下载器

### ISSUE THREAD

**Issue by Gccxeon** [pofey/movie_robot#767]
### 当前现状

当前页面下流量管理不支持自定义下载器，会直接采用默认下载器

### 你的建议

期望在流量管理界面可以选择下载器，这样可以兼容seedbox部署在其他服务器的情况

### 优先级

一般

### 受众范围

一般

**Comment by pofey** [comment]
https://yee329.notion.site/e73e20b466104ca486ac37a26d81587d
