### ISSUE TITLE
[优化]: TG图文推送

### ISSUE THREAD

**Issue by zxcll** [pofey/movie_robot#769]
### 当前现状

目前TG推送由于sendPhoto接口请求方式的原因图片url会导致失败

### 你的建议

经过测试采用图片上传的方式去发送消息这个问题能得到很大改善，附件是修改过后的TG推送代码

[TG.zip](https://github.com/pofey/movie_robot/files/9750925/TG.zip)

### 优先级

非常高

### 受众范围

不确定

**Comment by pofey** [comment]
大佬可以直接提pr合并的

**Comment by Nolovenodie** [comment]
我也是最近推送失败很多

**Comment by Nolovenodie** [comment]
> 

闭源的 我也没办法

**Comment by pofey** [comment]
> > > 我也是最近推送失败很多
> > 
> > 
> > 牛子都不能解决？
> 
> 闭源的 我也没办法

一直刷discord忘了看这边。明天找个时间改下发图稳定性，先把beta和latest发一版

**Comment by pofey** [comment]
done
