### ISSUE TITLE
[优化]: 同一种子下优先选择免费或打折种子

### ISSUE THREAD

**Issue by ShakeChanDev** [pofey/movie_robot#777]
### 当前现状

部分优秀站点上传不容易养，这里举例**朋友**，例如搜索【顺流逆流】，第一选择是**朋友**的8.51GB种子，但是馒头有同一种子并且50%促销，同时馒头养站难度也更低

### 你的建议

在智能下载选中种子后，增加一步查找同一种子但处于促销状态 并 做种人数大于xx

### 优先级

一般

### 受众范围

很多人需要

**Comment by pofey** [comment]
https://yee329.notion.site/46b9ffafe17b4595b031b1b9f407344b
