### ISSUE TITLE
[缺陷]: 《流浪地球：飞跃2020特别版》下载后，洗版识别错误，并且手动纠正无效

### ISSUE THREAD

**Issue by tinymins** [pofey/movie_robot#779]
### 当前程序版本

1.6.20

### 问题描述

搜索“流浪地球”，下载《流浪地球：飞跃2020特别版》后，下载完成弹出洗版结果识别错误，手动修改也无效。

### 重现步骤

1. 搜搜索 “流浪地球：飞跃2020特别版”

  ![image](https://user-images.githubusercontent.com/1808990/198884664-2c1cfc2c-2af0-4786-a663-e0a773ff07e9.png)

2. 选择 “The Wandering Earth: Beyond 2020 Special Edition 2020 WEB-DL 2160p H265 DDP 5.1-Dave” 点击下载

  ![image](https://user-images.githubusercontent.com/1808990/198884715-6f7268e2-4d6f-45ca-83a0-0005837e0718.png)

3. 等待下载成功够，弹出“洗版”提示，内容错误

  ![F A{60X61V_5Q{}89LL9G 0](https://user-images.githubusercontent.com/1808990/198884916-c542a4fd-b8b3-4ae8-84f9-979302ab9443.png)
  ![image](https://user-images.githubusercontent.com/1808990/198885010-395239ad-79d7-4310-b455-507cd7b30acd.png)

4. 手动输入纠正信息，仍然识别错误

  ![image](https://user-images.githubusercontent.com/1808990/198885070-d6e728ca-3dba-44b9-a5c0-86c913bc71fc.png)
  ![image](https://user-images.githubusercontent.com/1808990/198885148-dd04dc60-533f-4597-a2b4-696da792fd4e.png)
  ![490T_Q`EC7YW8MVZ58J@(6O](https://user-images.githubusercontent.com/1808990/198885190-a146fcb8-ec81-418d-b5ad-e6a73b109962.jpg)

### 发生问题时系统日志

```shell
2022/10/30 22:40:32 - Thread-8696 - INFO: 已经开始在站点(1): 馒头 搜索: 流浪地球：飞跃2020特别版
2022/10/30 22:40:39 - Thread-8696 - INFO: 共在1个站点搜索到5条结果，其中馒头最慢，耗费7.35秒
2022/10/30 22:48:06 - ThreadPoolExecutor-3_0 - INFO: 开始同步站点资源信息...
2022/10/30 22:48:29 - ThreadPoolExecutor-3_0 - INFO: 所有站点资源信息已经更新完毕，耗时：23.03秒
2022/10/30 22:48:31 - ThreadPoolExecutor-3_0 - INFO: 开始筛选免费种子，未筛选前共158个。
2022/10/30 22:48:31 - ThreadPoolExecutor-3_0 - INFO: 经过筛选后没有需要下载的免费任务。
2022/10/30 22:49:58 - Thread-8958 - INFO: 开始自动用TMDB数据搜索豆瓣数据
2022/10/30 22:49:58 - Thread-8958 - INFO: 成功从CMDB取得TMDB编号797188对应的ID映射关系：{'mediaType': 'Movie', 'doubanId': 35177635, 'doubanSeasonNumber': None, 'tmdbId': 797188, 'imdbId': None, 'tvdbId': None}
2022/10/30 22:49:58 - Thread-8958 - INFO: 搜到豆瓣编号:35177635
2022/10/30 22:49:58 - Thread-8960 - INFO: 十三邀·夏日特别版(2020)下完更好的版本，开始删除媒体库旧版并替换为新版。
2022/10/30 22:49:59 - Thread-8960 - INFO: 开始自动用TMDB数据搜索豆瓣数据
2022/10/30 22:49:59 - Thread-8960 - INFO: 成功从CMDB取得TMDB编号797188对应的ID映射关系：{'mediaType': 'Movie', 'doubanId': 35177635, 'doubanSeasonNumber': None, 'tmdbId': 797188, 'imdbId': None, 'tvdbId': None}
2022/10/30 22:49:59 - Thread-8960 - INFO: 搜到豆瓣编号:35177635
2022/10/30 22:49:59 - Thread-8960 - INFO: 内容：/mnt/media/movie-robot/movie/The Wandering Earth Beyond 2020 Special Edition 2020 WEB-DL 2160p H265 DDP 5.1-Dave/The Wandering Earth Beyond 2020 Special Edition 2020 WEB-DL 2160p H265 DDP 5.1-Dave.mkv 识别为：十三邀·夏日特别版 2020-11-26
2022/10/30 22:49:59 - Thread-8960 - INFO: 完成电影 十三邀·夏日特别版(2020) 的NFO文件生成，路径：/mnt/media/movie/十三邀·夏日特别版 (2020)/十三邀·夏日特别版 (2020) - 2160p H.265.nfo
2022/10/30 22:49:59 - Thread-8960 - INFO: 开始刮削图片数据，影片信息：{'tmdb_id': None, 'imdb_id': None, 'douban_id': '35177635', 'media_type': 'Movie', 'content_path': '/mnt/media/movie/十三邀·夏日特别版 (2020)', 'season_index': None, 'episode_index': None, 'episode_filename': None, 'tvdb_id': None}
2022/10/30 22:49:59 - Thread-8960 - INFO: Movie图片下载完毕。
2022/10/30 22:49:59 - Thread-8960 - INFO: 已经通知plex重新扫描媒体库：Movies
2022/10/30 22:49:59 - Thread-8960 - INFO: 通知媒体库刷新完成，tmdb_id: 797188 save_path: /mnt/media/movie item_id: 4
2022/10/30 22:49:59 - Thread-8960 - INFO: 十三邀·夏日特别版(2020) 发行地区为['中国大陆']，不需要下载字幕。
2022/10/30 22:50:00 - Thread-8960 - INFO: The Wandering Earth Beyond 2020 Special Edition 2020 WEB-DL 2160p H265 DDP 5.1-Dave处理完毕。
```

### 健康检查

![image](https://user-images.githubusercontent.com/1808990/198885467-63451a2a-6648-4f41-95a0-837620de4b5d.png)

**Comment by pofey** [comment]
豆瓣上没有这个版本

**Comment by tinymins** [comment]
> 豆瓣上没有这个版本

tmdb 上是有的，豆瓣就是个社区，电影肯定是不全的呀，它没有很正常，好多电影动漫豆瓣都没有的，这个不影响咱们这个系统才对呀

**Comment by tinymins** [comment]
> 豆瓣上没有这个版本

请问下以后会做成专业级别的，支持全部影视资源数据库吗？还是打算就只做到玩具级别的，只采用豆瓣的不全的影视数据 😂 

如果能做到专业级别的，大家都非常愿意等您这边的新功能支持~ 感谢！

**Comment by pofey** [comment]
飞跃2020特别版 是电影公司特别发行的版本么？和原浏览地球的区别是什么？
