### ISSUE TITLE
[缺陷]: 移动端浏览器点击订阅信息无法正常跳转

### ISSUE THREAD

**Issue by tinymins** [pofey/movie_robot#781]
### 当前程序版本

1.7.1

### 问题描述

搜索订阅，无法正常打开影片信息

### 重现步骤

1. 搜索一个订阅
2. 点击影片图片
3. 显示地址不合法（怀疑写死了什么 scheme 而不是 https）

![BC990CBA-DAD2-4513-9808-D621577F3B7C](https://user-images.githubusercontent.com/1808990/199641318-f287ae48-fb4e-4237-9e6c-f18ac983c03c.jpeg)

### 发生问题时系统日志

```shell
无，纯前端问题
```

### 健康检查

![F94BB3CE-D82A-4F45-9F03-78D2A3910874](https://user-images.githubusercontent.com/1808990/199641302-46c46f1a-aec1-4ee6-bd7a-caad4f08f9d0.jpeg)

**Comment by pofey** [comment]
你手机没装豆瓣，装了直接打开app的

**Comment by tinymins** [comment]
> 你手机没装豆瓣，装了直接打开app的

请问可以出个选项跳 tmdb 吗～ 豆瓣好多番都没有，根本没法跳 😂

**Comment by pofey** [comment]
举个例子，哪个不能跳
