### ISSUE TITLE
[缺陷]: 下载完成后微信通知报错

### ISSUE THREAD

**Issue by happyhaha1** [pofey/movie_robot#786]
### 当前程序版本

1.7.19

### 问题描述

更新1.7.19后，微信通知不成功，没有收到一次

### 重现步骤

1.下载新的电影或电视的通知

### 发生问题时系统日志

```shell
2022/11/16 16:07:04 - ThreadPoolExecutor-6_0 - INFO: 超能使者.Ive.Got.The.Power.S01.2022.2160p.WEB-DL.H265.AAC.2Audio-ADWeb处理完毕。
2022/11/16 16:07:04 - ThreadPoolExecutor-6_0 - ERROR: on_event error: EventListener event: {'event_type': 'DownloadCompleted', 'data': {'x_meta': {'id': 125325, 'doubanId': 35080462, 'tmdbId': 213236, 'imdbId': None, 'tvdbId': None, 'gmtModified': '2022-10-30 19:05:14', 'needUpdate': False, 'mediaType': 'TV', 'title': '超能使者', 'enTitle': '超能使者', 'originalTitle': '超能使者', 'intro': '由香港电视广播有限公司制作出品，文伟鸿监制，吴超荣执导，陈展鹏、唐诗咏、陈山聪 、王君馨、刘佩玥、林子善、沈震轩、刘颖镟、欧瑞伟等主演的奇幻动作剧，于2022年9月5日在中国香港首播，该剧以异能英雄为主题，讲述了五位社会低下层人物作主角成为街头英雄拯救街坊的故事，一宗意外，改写人生，激发超能力，觉醒正义使者！五位社会低下层人物锺孝年（陈展鹏饰）、乔若岚（唐诗咏饰）、高勇（陈山聪饰）、韦瑞琦（王君馨饰）和柯翠屏（刘颖镟饰），www.liuse.cc/l/s152481/为对抗暗黑危机，组成正义同盟，成为《超能使者》。', 'rating': 0.0, 'releaseYear': 2022, 'premiereDate': 20221031, 'duration': None, 'posterUrl': 'https://image.tmdb.org/t/p/original/2HeKfb9o2jQJbUBbALPAPH2uHWb.jpg', 'backgroundUrl': 'https://image.tmdb.org/t/p/original/dBg7GCEBWHsUBE3p5LRwRFzBBAH.jpg', 'genres': ['科幻', '动作冒险'], 'country': ['中国香港'], 'seasonList': [{'name': '第1季', 'seasonNumber': 1, 'episodeCount': 30, 'intro': '由香港电视广播有限公司制作出品，文伟鸿监制，吴超荣执导，陈展鹏、唐诗咏、陈山聪 、王君馨、刘佩玥、林子善、沈震轩、刘颖镟、欧瑞伟等主演的奇幻动作剧，于2022年9月5日在中国香港首播，该剧以异能英雄为主题，讲述了五位社会低下层人物作主角成为街头英雄拯救街坊的故事，一宗意外，改写人生，激发超能力，觉醒正义使者！五位社会低下层人物锺孝年（陈展鹏饰）、乔若岚（唐诗咏饰）、高勇（陈山聪饰）、韦瑞琦（王君馨饰）和柯翠屏（刘颖镟饰），www.liuse.cc/l/s152481/为对抗暗黑危机，组成正义同盟，成为《超能使者》。', 'airDate': 20221031, 'posterUrl': None, 'doubanId': 35080462}]}, 'douban_id': None, 'tmdb_meta': None, 'douban_meta': None, 'target_path': '/mnt/user/media/server/剧集/超能使者 (2022)', 'sub_id': None, 'uid': '1', 'tmdb_id': '213236', 'media_type': 'TV', 'season_number': 1, 'season_year': 2022, 'year': 2022, 'episodes': [6], 'file_size': '2.3 GB', 'media_stream': {'resolution': '2160p', 'media_source': 'WEB-DL', 'media_codec': 'H.265', 'media_audio': ['2Audio', 'AAC'], 'release_team': 'ADWeb'}, 'source_path': '/mnt/user/media/download/vedio/超能使者.Ive.Got.The.Power.S01.2022.2160p.WEB-DL.H265.AAC.2Audio-ADWeb/超能使者.Ive.Got.The.Power.S01E06.2022.2160p.WEB-DL.H265.AAC.2Audio-ADWeb.mkv', 'torrent_name': '超能使者.Ive.Got.The.Power.S01.2022.2160p.WEB-DL.H265.AAC.2Audio-ADWeb', 'torrent_subject': '超���使者 第06集 | 类型: 动作 / 奇幻 主演: 陈展鹏 / 唐诗咏 / 陈山聪 / 王君馨 / 刘佩玥 *4K* *国粤双语*', 'torrent_id': 81063, 'torrent_hash': '41c2d8e365addca7a15b07210d4721c5e68edeae', 'torrent_url': 'https://audiences.me/details.php?id=81063&hit=1', 'site_id': 'audiences', 'site_name': '观众'}}
Traceback (most recent call last):
  File "mbot/core/event/eventbus.py", line 81, in mbot.core.event.eventbus.EventBus.publish_event
  File "mbot/core/event/eventlistener.py", line 21, in mbot.core.event.eventlistener.EventListener.__call__
  File "mbot/core/__init__.py", line 49, in mbot.core.__init__.MovieBot.on_event.decorator.wrap
  File "mbot/listener/notifylistener.py", line 153, in mbot.listener.notifylistener.on_sub_event
  File "mbot/listener/notifylistener.py", line 84, in mbot.listener.notifylistener.Notify.notify_by_event
  File "mbot/listener/notifylistener.py", line 66, in mbot.listener.notifylistener.Notify._get_tmdb_meta
AttributeError: 'NoneType' object has no attribute 'get'
```

### 健康检查

022/11/16 16:07:04 - ThreadPoolExecutor-6_0 - INFO: 超能使者.Ive.Got.The.Power.S01.2022.2160p.WEB-DL.H265.AAC.2Audio-ADWeb处理完毕。
2022/11/16 16:07:04 - ThreadPoolExecutor-6_0 - ERROR: on_event error: EventListener event: {'event_type': 'DownloadCompleted', 'data': {'x_meta': {'id': 125325, 'doubanId': 35080462, 'tmdbId': 213236, 'imdbId': None, 'tvdbId': None, 'gmtModified': '2022-10-30 19:05:14', 'needUpdate': False, 'mediaType': 'TV', 'title': '超能使者', 'enTitle': '超能使者', 'originalTitle': '超能使者', 'intro': '由香港电视广播有限公司制作出品，文伟鸿监制，吴超荣执导，陈展鹏、唐诗咏、陈山聪 、王君馨、刘佩玥、林子善、沈震轩、刘颖镟、欧瑞伟等主演的奇幻动作剧，于2022年9月5日在中国香港首播，该剧以异能英雄为主题，讲述了五位社会低下层人物作主角成为街头英雄拯救街坊的故事，一宗意外，改写人生，激发超能力，觉醒正义使者！五位社会低下层人物锺孝年（陈展鹏饰）、乔若岚（唐诗咏饰）、高勇（陈山聪饰）、韦瑞琦（王君馨饰）和柯翠屏（刘颖镟饰），www.liuse.cc/l/s152481/为对抗暗黑危机，组成正义同盟，成为《超能使者》。', 'rating': 0.0, 'releaseYear': 2022, 'premiereDate': 20221031, 'duration': None, 'posterUrl': 'https://image.tmdb.org/t/p/original/2HeKfb9o2jQJbUBbALPAPH2uHWb.jpg', 'backgroundUrl': 'https://image.tmdb.org/t/p/original/dBg7GCEBWHsUBE3p5LRwRFzBBAH.jpg', 'genres': ['科幻', '动作冒险'], 'country': ['中国香港'], 'seasonList': [{'name': '第1季', 'seasonNumber': 1, 'episodeCount': 30, 'intro': '由香港电视广播有限公司制作出品，文伟鸿监制，吴超荣执导，陈展鹏、唐诗咏、陈山聪 、王君馨、刘佩玥、林子善、沈震轩、刘颖镟、欧瑞伟等主演的奇幻动作剧，于2022年9月5日在中国香港首播，该剧以异能英雄为主题，讲述了五位社会低下层人物作主角成为街头英雄拯救街坊的故事，一宗意外，改写人生，激发超能力，觉醒正义使者！五位社会低下层人物锺孝年（陈展鹏饰）、乔若岚（唐诗咏饰）、高勇（陈山聪饰）、韦瑞琦（王君馨饰）和柯翠屏（刘颖镟饰），www.liuse.cc/l/s152481/为对抗暗黑危机，组成正义同盟，成为《超能使者》。', 'airDate': 20221031, 'posterUrl': None, 'doubanId': 35080462}]}, 'douban_id': None, 'tmdb_meta': None, 'douban_meta': None, 'target_path': '/mnt/user/media/server/剧集/超能使者 (2022)', 'sub_id': None, 'uid': '1', 'tmdb_id': '213236', 'media_type': 'TV', 'season_number': 1, 'season_year': 2022, 'year': 2022, 'episodes': [6], 'file_size': '2.3 GB', 'media_stream': {'resolution': '2160p', 'media_source': 'WEB-DL', 'media_codec': 'H.265', 'media_audio': ['2Audio', 'AAC'], 'release_team': 'ADWeb'}, 'source_path': '/mnt/user/media/download/vedio/超能使者.Ive.Got.The.Power.S01.2022.2160p.WEB-DL.H265.AAC.2Audio-ADWeb/超能使者.Ive.Got.The.Power.S01E06.2022.2160p.WEB-DL.H265.AAC.2Audio-ADWeb.mkv', 'torrent_name': '超能使者.Ive.Got.The.Power.S01.2022.2160p.WEB-DL.H265.AAC.2Audio-ADWeb', 'torrent_subject': '超���使者 第06集 | 类型: 动作 / 奇幻 主演: 陈展鹏 / 唐诗咏 / 陈山聪 / 王君馨 / 刘佩玥 *4K* *国粤双语*', 'torrent_id': 81063, 'torrent_hash': '41c2d8e365addca7a15b07210d4721c5e68edeae', 'torrent_url': 'https://audiences.me/details.php?id=81063&hit=1', 'site_id': 'audiences', 'site_name': '观众'}}
Traceback (most recent call last):
  File "mbot/core/event/eventbus.py", line 81, in mbot.core.event.eventbus.EventBus.publish_event
  File "mbot/core/event/eventlistener.py", line 21, in mbot.core.event.eventlistener.EventListener.__call__
  File "mbot/core/__init__.py", line 49, in mbot.core.__init__.MovieBot.on_event.decorator.wrap
  File "mbot/listener/notifylistener.py", line 153, in mbot.listener.notifylistener.on_sub_event
  File "mbot/listener/notifylistener.py", line 84, in mbot.listener.notifylistener.Notify.notify_by_event
  File "mbot/listener/notifylistener.py", line 66, in mbot.listener.notifylistener.Notify._get_tmdb_meta
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by happyhaha1** [comment]
ERROR: on_event error: EventListener event: {'event_type': 'DownloadCompleted', 'data': {'x_meta': {'id': 103241, 'doubanId': 26959697, 'tmdbId': 436270, 'imdbId': 'tt6443346', 'tvdbId': None, 'gmtModified': '2022-09-01 02:19:54', 'needUpdate': False, 'mediaType': 'Movie', 'title': '黑亚当', 'enTitle': 'Black Adam', 'originalTitle': 'Black Adam', 'intro': '黑亚当是DC漫画中的超级反派，他在许多世纪前曾受到老巫师沙赞赐予的力量，然而妻儿死亡的悲剧因素，使他转向反对他的恩人，成为沙赞的宿敌。\n电影版《黑亚当》由华纳旗下的新线影业与DC共同推进，“巨石”道恩·强森将领衔主演这位DC超级反派。', 'rating': 0.0, 'releaseYear': 2022, 'premiereDate': 20221019, 'duration': None, 'posterUrl': 'http://assets.fanart.tv/fanart/movies/436270/movieposter/black-adam-62547b806d5e9.jpg', 'backgroundUrl': 'http://assets.fanart.tv/fanart/movies/436270/moviebackground/black-adam-5ca57bcd1b1c5.jpg', 'genres': ['动作', '奇幻', '冒险'], 'country': ['美国']}, 'douban_id': None, 'tmdb_meta': None, 'douban_meta': None, 'target_path': '/mnt/user/media/server/电影/黑亚当 (2022)', 'sub_id': 122, 'uid': '1', 'tmdb_id': '436270', 'media_type': 'Movie', 'season_number': None, 'season_year': None, 'year': 2022, 'episodes': None, 'file_size': '10.62 GB', 'media_stream': {'resolution': '1080p', 'media_source': 'HDRip', 'media_codec': 'x264', 'media_audio': [], 'release_team': None}, 'source_path': '/mnt/user/media/download/movie/Black.Adam.2022.HC.1080p.HDRip.x264.AC3-EVO.mkv', 'torrent_name': 'Black.Adam.2022.HC.1080p.HDRip.x264.AC3-EVO.mkv', 'torrent_subject': '黑亚当/黑亞當(港/台)/霹雳亚当', 'torrent_id': 350562, 'torrent_hash': '190682c2899373f3528acb5d7295b0c9c2d75498', 'torrent_url': 'https://lemonhd.org/details_movie.php?id=350562', 'site_id': 'lemonhd', 'site_name': '柠檬'}}
Traceback (most recent call last):
  File "mbot/core/event/eventbus.py", line 81, in mbot.core.event.eventbus.EventBus.publish_event
  File "mbot/core/event/eventlistener.py", line 21, in mbot.core.event.eventlistener.EventListener.__call__
  File "mbot/core/__init__.py", line 49, in mbot.core.__init__.MovieBot.on_event.decorator.wrap
  File "mbot/listener/notifylistener.py", line 153, in mbot.listener.notifylistener.on_sub_event
  File "mbot/listener/notifylistener.py", line 84, in mbot.listener.notifylistener.Notify.notify_by_event
  File "mbot/listener/notifylistener.py", line 66, in mbot.listener.notifylistener.Notify._get_tmdb_meta
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by pofey** [comment]
应该都好了
