### ISSUE TITLE
订阅后，下载提示无法找到路径，但养站却没问题。

### ISSUE THREAD

**Issue by Dukkha97** [pofey/movie_robot#80]
![52251651769019_ pic](https://user-images.githubusercontent.com/93964813/166975694-0a823945-a5f8-4eee-b941-0058196b1eaa.jpg)
![52261651769019_ pic](https://user-images.githubusercontent.com/93964813/166975697-e16fd074-a60b-4d15-90db-738f6a9ec25f.jpg)
![52241651769019_ pic](https://user-images.githubusercontent.com/93964813/166975699-5998913d-77ac-4d84-948f-7f8a79249c80.jpg)
<img width="939" alt="LWScreenShot 2022-05-06 at 00 56 39" src="https://user-images.githubusercontent.com/93964813/166975708-87c31709-241e-4dd4-9be7-d40deee3e4ca.png">
<img width="1202" alt="LWScreenShot 2022-05-06 at 00 57 15" src="https://user-images.githubusercontent.com/93964813/166975712-116814f7-74bb-4a69-b572-c45fa330f42c.png">

<img width="1235" alt="LWScreenShot 2022-05-06 at 01 01 54" src="https://user-images.githubusercontent.com/93964813/166975679-d551713f-e52a-470c-bffc-a403b5d493d0.png">

**Comment by Dukkha97** [comment]
<img width="662" alt="LWScreenShot 2022-05-06 at 01 07 38" src="https://user-images.githubusercontent.com/93964813/166976051-d434972a-1b00-4e89-be60-211a947fb70c.png">

补充一张文件夹截图

**Comment by pofey** [comment]
还要看一下你智能下载-豆瓣想看，那块的下载保存路径设置

**Comment by Dukkha97** [comment]
![image](https://user-images.githubusercontent.com/93964813/167238938-4651a9dd-c03f-42f4-a67a-e0591bfe69a2.png)

**Comment by pofey** [comment]
看着没啥问题 报错前面怎么少了个/讷
