### ISSUE TITLE
ERROR: 处理免费种子淘汰任务出错

### ISSUE THREAD

**Issue by fengci** [pofey/movie_robot#82]
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/13860628/167196976-c6af190c-d6ca-460d-a2e3-dad4fbfedf33.png">

**Comment by pofey** [comment]
你的下载监控周期值配置了一个非数字 - ？

**Comment by fengci** [comment]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/13860628/167237589-04f2a908-5504-4620-b52e-5b484c2e5b2e.png">
是数字啊

**Comment by fengci** [comment]
我重新填了一个数字好像好了。

**Comment by fengci** [comment]
我重新填了一个数字好像好了。
