### ISSUE TITLE
[Bug Report] 下载路径修改后不生效

### ISSUE THREAD

**Issue by neroxps** [pofey/movie_robot#83]
之前设置错保存的路径了，修改完后重启过，下载保存路径依然是错误的。

容器内的 data 目录下找的到 

![image](https://user-images.githubusercontent.com/8503224/167242579-100efa63-7dba-4370-96d3-431200fbd6be.png)
![2 JDEL) R23X7~OCZGFTT$X](https://user-images.githubusercontent.com/8503224/167242587-18c4ede9-886c-4d87-8d5e-0842d5b0e4cf.png)

容器内的 data 目录下找的到  base_config.yml 配置是正确的。

![image](https://user-images.githubusercontent.com/8503224/167243200-a931ddc6-a0c9-4169-97e1-76efdd268d9c.png)

电影下载完毕后，由于路径和配置不符，导致电影无法硬链接。
```
movie-robot    | 2022/05/07 15:54:00 - ThreadPoolExecutor-0_0 - ERROR: 在存储路径设置的下载保存路径中，找不到此路径，请检查配置：/4T/cn 种子名: 白蛇2：青蛇劫起.White Snake.2021.4K.WEB-DL.HEVC.DDP5.1.2Audio-HaresWEB hash: eeea4490306b1cc3de2736ab2ff0c0078597403d
movie-robot    | 2022/05/07 15:54:00 - ThreadPoolExecutor-0_0 - INFO: 当前已配置的下载保存路径：dict_keys(['/4T/tmpTV', '/4T/movie/tmp-cn', '/4T/movie/tmp-hk', '/4T/movie/tmp-en'])
```

**Comment by pofey** [comment]
这个是你之前提交的种子就保存到这个路径了，你可以把这个种子保存路径在qbit改正确，或者删了重来

**Comment by 1960697431** [comment]
> 这个是你之前提交的种子就保存到这个路径了，你可以把这个种子保存路径在qbit改正确，或者删了重来

我也有这个问题，当我完成所有设置后测试豆瓣智能下载的时候，我按步骤搜寻了一部科幻电影会给保存到 剧集-动漫（/video/downloads/剧集）文件夹下而不是电影（/video/download/电影）文件夹下，这会导致错误的hard link，在plex削刮中会该测试电影会出现在动漫（/video/media/anime）资料库中

**Comment by pofey** [comment]
> > 这个是你之前提交的种子就保存到这个路径了，你可以把这个种子保存路径在qbit改正确，或者删了重来
> 
> 我也有这个问题，当我完成所有设置后测试豆瓣智能下载的时候，我按步骤搜寻了一部科幻电影会给保存到 剧集-动漫（/video/downloads/剧集）文件夹下而不是电影（/video/downloads/电影）文件夹下，这会导致错误的hard link

都是配置问题 看这个吧 https://yee329.notion.site/5-745da2776daa4fc7b5e2ddb3170aa11a

**Comment by neroxps** [comment]
> 这个是你之前提交的种子就保存到这个路径了，你可以把这个种子保存路径在qbit改正确，或者删了重来

不是的 新订阅的电影全部都是之前配置错的路径。但是配置文件是对的。现在新增订阅影片下载也是错误的路径，不知道为何。日志是否能输出更详细的内容？

**Comment by pofey** [comment]
> > 这个是你之前提交的种子就保存到这个路径了，你可以把这个种子保存路径在qbit改正确，或者删了重来
> 
> 不是的 新订阅的电影全部都是之前配置错的路径。但是配置文件是对的。现在新增订阅影片下载也是错误的路径，不知道为何。日志是否能输出更详细的内容？

看我上面wiki吧 仔细检查保存路径设置的逻辑，配置文件变更如果正常，程序里不可能加载到错误地址。除非qbit那边还有什么别的设置变更了路径。

**Comment by neroxps** [comment]
> 



> > > 这个是你之前提交的种子就保存到这个路径了，你可以把这个种子保存路径在qbit改正确，或者删了重来
> > 
> > 
> > 不是的 新订阅的电影全部都是之前配置错的路径。但是配置文件是对的。现在新增订阅影片下载也是错误的路径，不知道为何。日志是否能输出更详细的内容？
> 
> 看我上面wiki吧 仔细检查保存路径设置的逻辑，配置文件变更如果正常，程序里不可能加载到错误地址。除非qbit那边还有什么别的设置变更了路径。

抓包发现 POST 的确是配置正确的地址，不知道为何 qb 会把地址改了，难道是配置了分类？

![image](https://user-images.githubusercontent.com/8503224/167328287-0da56c1d-d3d0-43d0-91c3-0f5a94cc4dbb.png)

感觉和这里有关。

![image](https://user-images.githubusercontent.com/8503224/167328340-07fcaba1-01a6-42d9-ba3b-91ce9d56db40.png)

**Comment by neroxps** [comment]
![$~0E76SIQ `Z2_RSI(582XA](https://user-images.githubusercontent.com/8503224/167330223-46454742-d7d1-4a48-bcb5-d9b7ad0bfcf4.png)
把下载路径的分类删除即可。
