### ISSUE TITLE
【不知是否是bug】现有存量的硬链接问题

### ISSUE THREAD

**Issue by yzblonely** [pofey/movie_robot#84]
![1651941669(1)](https://user-images.githubusercontent.com/76820847/167263761-9c048173-8217-48d0-953c-de24684c5938.jpg)

现有存量的整理，本来一开始我有6个现有存量的资源没有整理， 粘贴的代码只会  ，只有一个成功生成硬链接，并且出现如上错误提示
如果突破不现实，请看下面
[~] # docker exec -it ec5d21d0c1fb /bin/bash
root@ec5d21d0c1fb:/app# python commandapp.py -w=/data -a=moviesmanager --source-type=tv --source-dir=/downloads/TV --target-dir=/downloads/rebot/TV --file-mode=link
2022/05/07 23:21:43 - MainThread - INFO: 开始处理剧集目录 /downloads/TV 目标目录：/downloads/rebot/TV
2022/05/07 23:21:44 - MainThread - ERROR: Uncaught exception
Traceback (most recent call last):
  File "commandapp.py", line 68, in <module>
    CommandActions.movies_manager(tmdb_config['api_key'],base_config.movie_metadata.get('proxies'), args.file_mode, args.use_country_folder,
  File "yee/commandactions.py", line 21, in yee.commandactions.CommandActions.movies_manager
  File "yee/core/moviefilemanager.py", line 111, in yee.core.moviefilemanager.MovieFileManager.walk_tv_folder
  File "yee/core/moviefilemanager.py", line 197, in yee.core.moviefilemanager.MovieFileManager.handle_tv
UnboundLocalError: local variable 'dst' referenced before assignment

我已经多次确认 TMDB的key没有错误   代理也是可以正常使用的 我拿浏览器和tgg都测试了  

希望作者百忙之中能抽空帮解答一下  谢谢 感激不尽

**Comment by pofey** [comment]
你的版本号是多少 这个看起来像老版本的问题

**Comment by yzblonely** [comment]
> 

右下角显示版本号 Version: 0.5.6

**Comment by pofey** [comment]
> > 
> 
> 右下角显示版本号 Version: 0.5.6

升级到最新版，有问题再来反馈。
