### ISSUE TITLE
电影识别错误，集中帖

### ISSUE THREAD

**Issue by mjyhj** [pofey/movie_robot#9]
请在大家此贴发各种各样的识别错误，而不是报错
例如：
片A识别成片B；
片A 第二部识别成片A 第一部；
同名片A（2001） 识别成 同名片A（2005）；
诸如此类

**Comment by mjyhj** [comment]
INFO: 已处理：扫黑英雄 (2021) 源路径: /download2/电影/扫黑·决战.Break.Through.the.Darkness.2021.2160p.WEB-DL.DD5.1.H265-HDSWEB.mkv

INFO: 已处理：三傻大闹宝莱坞 (2009) (2009) 源路径: /download2/电影/三傻大闹宝莱坞.3.Idiots.2009.BluRay.1080p.x265.10bit.2Audio.MNHD-FRDS/3.Idiots.2009.BluRay.1080p.x265.10bit.2Audio.MNHD-FRDS.mkv

**Comment by suwill** [comment]
2022/02/15 09:57:59 - MainThread - INFO: 首次上映：2013-06-27 名称：Tiny Times 中文名：小时代 相似度：1.7826086956521738
2022/02/15 09:58:01 - MainThread - INFO: 首次上映：2013-08-07 名称：Tiny Times 2 中文名：小时代2：青木时代 相似度：1.8
2022/02/15 09:58:04 - MainThread - INFO: 已处理：小时代2：青木时代 (2013) 源路径: /mnt/user/nfs/.ptUpload/movie/[故事片]小时代系列(第1～4).Tiny.Tim.1-4.1080p.WEB-DL.H264.AAC-HDSTV/Tiny.Time 1-4.1080p.WEB-DL.H264.AAC-HDSTV/**Tiny.Time 1.0.2013.**1080p.WEB-DL.H264.AAC-HDSTV.mkv
2022/02/15 09:58:05 - MainThread - INFO: 首次上映：2013-06-27 名称：Tiny Times 中文名：小时代 相似度：1.7826086956521738
2022/02/15 09:58:07 - MainThread - INFO: 首次上映：2013-08-07 名称：Tiny Times 2 中文名：小时代2：青木时代 相似度：1.88
2022/02/15 09:58:07 - MainThread - INFO: 已处理：小时代2：青木时代 (2013) 源路径: /mnt/user/nfs/.ptUpload/movie/[故事片]小时代系列(第1～4).Tiny.Tim.1-4.1080p.WEB-DL.H264.AAC-HDSTV/Tiny.Time 1-4.1080p.WEB-DL.H264.AAC-HDSTV/Tiny.Time 2.0.2013.1080p.WEB-DL.H264.AAC-HDSTV.mkv
2022/02/15 09:58:09 - MainThread - INFO: 已处理：小时代3：刺金时代 (2014) 源路径: /mnt/user/nfs/.ptUpload/movie/[故事片]小时代系列(第1～4).Tiny.Tim.1-4.1080p.WEB-DL.H264.AAC-HDSTV/Tiny.Time 1-4.1080p.WEB-DL.H264.AAC-HDSTV/Tiny.Time 3.0.2014.1080p.WEB-DL.H264.AAC-HDSTV.mkv
2022/02/15 09:58:10 - MainThread - INFO: 已处理：小时代4：灵魂尽头 (2015) 源路径: /mnt/user/nfs/.ptUpload/movie/[故事片]小时代系列(第1～4).Tiny.Tim.1-4.1080p.WEB-DL.H264.AAC-HDSTV/Tiny.Time 1-4.1080p.WEB-DL.H264.AAC-HDSTV/Tiny.Time 4.0.2015.1080p.WEB-DL.H264.AAC-HDSTV.mkv

**Comment by Skyline0503** [comment]
龙与魔女 第一季识别为第None季

2022/02/18 08:06:05 - ThreadPoolExecutor-0_0 - INFO: 开始为剧集 龙与魔女 (2020)做文件转移 源路径：/Media/Downloads/anim/Burn.the.Witch.2020.1080p.BluRay.Remux.AVC.FLAC2.0-PTer 链接路径：/Media/Store/anim
 2022/02/18 08:06:06 - ThreadPoolExecutor-0_0 - INFO: 已处理：龙与魔女 (2020) 第None季 源路径: /Media/Downloads/anim/Burn.the.Witch.2020.1080p.BluRay.Remux.AVC.FLAC2.0-PTer/Burn.the.Witch.2020.E02.1080p.BluRay.Remux.AVC.FLAC2.0-PTer.mkv
 2022/02/18 08:06:07 - ThreadPoolExecutor-0_0 - INFO: 已处理：龙与魔女 (2020) 第None季 源路径: /Media/Downloads/anim/Burn.the.Witch.2020.1080p.BluRay.Remux.AVC.FLAC2.0-PTer/Burn.the.Witch.2020.E03.1080p.BluRay.Remux.AVC.FLAC2.0-PTer.mkv
 2022/02/18 08:06:07 - ThreadPoolExecutor-0_0 - INFO: 已处理：龙与魔女 (2020) 第None季 源路径: /Media/Downloads/anim/Burn.the.Witch.2020.1080p.BluRay.Remux.AVC.FLAC2.0-PTer/Burn.the.Witch.2020.E01.1080p.BluRay.Remux.AVC.FLAC2.0-PTer.mkv
 2022/02/18 08:06:07 - ThreadPoolExecutor-0_0 - INFO: Burn the Witch 2020 1080p BluRay Remux AVC FLAC2.0-PTer下完啦！

**Comment by Skyline0503** [comment]
超能力女儿 日志显示mteam搜索不到，但实际可以搜到
版本:2022022V3
日志：
2022/02/21 21:00:58 - ThreadPoolExecutor-0_0 - INFO: 超能力女儿(2018)需要下载，需要在mteam寻找最佳种子
 2022/02/21 21:01:12 - ThreadPoolExecutor-0_0 - INFO: 超能力女儿(2018)使用compress策略选种
 2022/02/21 21:01:12 - ThreadPoolExecutor-0_0 - INFO: 超能力女儿(2018)在mteam搜索不到缺少的第[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]集资源
mteam可搜到的链接：https://kp.m-team.cc/details.php?id=505616&hit=1

**Comment by mjyhj** [comment]
2022/02/24 01:03:14 - MainThread - INFO: 已处理：好想去你的世界爱你 (2022) 源路径: /download2/电影/Anita.Directors.Cut.S01.2022.Disney+.WEB-DL.1080p.H264.DDP-AREY/Anita.Directors.Cut.S01E01.2022.Disney+.WEB-DL.1080p.H264.DDP-AREY.mkv

实际为：梅艳芳 导演剪辑版 / Anita 第1集 | 主演：王丹妮 古天乐 粤语 简繁英软字幕
