### ISSUE TITLE
【需求】增加通知模式设置，可以定向推，也可以全局推

### ISSUE THREAD

**Issue by MouLv** [pofey/movie_robot#90]
当前版本：0.6.1
在推送通知的企业微信里面touser是@all的情况下。下面两种场景都没有出发全员通知
一：用户A通过微信搜索影片，产生的订阅和下载完成的通知只会发送给用户A。用户B（同时也是管理员）收不到对应的通知

一：用户B通过在mr web端添加的订阅，下载完成之后，通知只会通知给用户B，用户A收不到对应通知
具体截图如下
推送通知配置
![image](https://user-images.githubusercontent.com/16574475/167335917-8bc04740-06ae-44b1-b8b0-f56469785721.png)

场景一用户A的截图
![image](https://user-images.githubusercontent.com/16574475/167336027-4367818a-950a-4911-8cfe-0140021d0f65.png)

场景二用户B截图
![image](https://user-images.githubusercontent.com/16574475/167336331-1b87d640-6894-4ca7-b617-75a5d0a2b1fc.png)

**Comment by HisingX** [comment]
订阅也有通知？？为啥我这只有下载成功才会通知呢？

**Comment by pofey** [comment]
多用户定向通知是专门设计的，所以你是想，任何人订阅，管理组都要收？

**Comment by Totobo** [comment]
> 多用户定向通知是专门设计的，所以你是想，任何人订阅，管理组都要收？

对，所有人能收到其他人的订阅通知，或者管理组能收的话都可以，目的是可以随时了解影音库的更新情况。比如我老婆想看个什么电影，我添加下载后她也能收到下载完成的通知。追剧的话也能及时知道追的剧更新了，并不是只有添加下载的人知道

另外还有个问题，就是通知里面企业微信的touser选项具体用法是什么，一开始以为是下载任务完成后需要接收通知的人，现在看来并不是的。

**Comment by pofey** [comment]
> > 多用户定向通知是专门设计的，所以你是想，任何人订阅，管理组都要收？
> 
> 对，所有人能收到其他人的订阅通知，或者管理组能收的话都可以，目的是可以随时了解影音库的更新情况。比如我老婆想看个什么电影，我添加下载后她也能收到下载完成的通知。追剧的话也能及时知道追的剧更新了，并不是只有添加下载的人知道
> 
> 另外还有个问题，就是通知里面企业微信的touser选项具体用法是什么，一开始以为是下载任务完成后需要接收通知的人，现在看来并不是的。

touser是不绑定用户时的默认通知选项，曾经确实是一个人下，全通知，后来慢慢发展成今天的样子了。

**Comment by Totobo** [comment]
> > > 多用户定向通知是专门设计的，所以你是想，任何人订阅，管理组都要收？
> > 
> > 
> > 对，所有人能收到其他人的订阅通知，或者管理组能收的话都可以，目的是可以随时了解影音库的更新情况。比如我老婆想看个什么电影，我添加下载后她也能收到下载完成的通知。追剧的话也能及时知道追的剧更新了，并不是只有添加下载的人知道
> > 另外还有个问题，就是通知里面企业微信的touser选项具体用法是什么，一开始以为是下载任务完成后需要接收通知的人，现在看来并不是的。
> 
> touser是不绑定用户时的默认通知选项，曾经确实是一个人下，全通知，后来慢慢发展成今天的样子了。

明白了。衣大看看这部分能否再优化下，目的是家庭场景下，对应相关资源感兴趣的人可以及时收到资源更新的通知。

**Comment by leiletter** [comment]
复议
