### ISSUE TITLE
剧集手动洗版后，没能自动删除qb内相关种子

### ISSUE THREAD

**Issue by leverule** [pofey/movie_robot#94]
硬链都删除替换掉了，但种子及文件都还在。种子是陆陆续续自动订阅到的分集。5月4号从4.4.2改用的qb4.2.5快检版，机器人0.6.1
[相关日志.txt](https://github.com/pofey/movie_robot/files/8648803/default.txt)
![Snipaste_2022-05-09_12-04-02](https://user-images.githubusercontent.com/57491211/167342095-a13a3edf-b798-4ca2-87c2-898176f96b1b.png)

**Comment by pofey** [comment]
> 硬链都删除替换掉了，但种子及文件都还在。种子是陆陆续续自动订阅到的分集。5月4号从4.4.2改用的qb4.2.5快检版，机器人0.6.1 [相关日志.txt](https://github.com/pofey/movie_robot/files/8648803/default.txt) ![Snipaste_2022-05-09_12-04-02](https://user-images.githubusercontent.com/57491211/167342095-a13a3edf-b798-4ca2-87c2-898176f96b1b.png)

种子和源文件删不掉就找找下载器的问题吧，现在的删除是调用qbit的删除接口
