### ISSUE TITLE
求助TMDB api无法连接！

### ISSUE THREAD

**Issue by huang-shaohua** [pofey/movie_robot#95]
问题：豆瓣编号: 30314848 无法关联TMDB，请检查你是否可以稳定连接TMDB API服务器，或TMDB是否有这部片子。
尝试多次订阅总是无法成功订阅，大概率是TMDB api无法正确连接。但已尝试过修改群晖hosts、搭建SmartDNS等方法都无法解决，还有其他办法吗？就差这最后一步了，谢谢！

**Comment by phinleyfei** [comment]
比较彻底的方法是根据域名来定策略，走科学上网。

**Comment by Howardnm** [comment]
路由器dns代理加上：
54.230.15.71 api.Themoviedb.org
54.230.15.76 api.Themoviedb.org
54.230.15.90 api.Themoviedb.org
54.230.15.119 api.Themoviedb.org
104.25.27.31 u2.dmhy.org
104.25.26.31 u2.dmhy.org
104.25.27.31 tracker.dmhy.org
104.25.26.31 tracker.dmhy.org
13.226.238.76 api.themoviedb.org
13.224.161.90 api.themoviedb.org
13.35.7.102 api.themoviedb.org
13.225.103.26 api.themoviedb.org
13.226.191.85 api.themoviedb.org
13.225.103.110 api.themoviedb.org
52.85.79.89 api.themoviedb.org
13.225.41.40 api.themoviedb.org
13.226.251.88 api.themoviedb.org
65.9.85.74 api.themoviedb.org
65.9.85.19 api.themoviedb.org
65.9.85.127 api.themoviedb.org
65.9.85.118 api.themoviedb.org
13.225.89.239 api.thetvdb.com
13.249.175.212 api.thetvdb.com
13.35.161.120 api.thetvdb.com
2606:4700:20::6819:1b1f u2.dmhy.org
2606:4700:20::6819:1a1f u2.dmhy.org
2606:4700:20::6819:1b1f tracker.dmhy.org
2606:4700:20::6819:1a1f tracker.dmhy.org
2600:9000:20e9:800:c:174a:c400:93a1 api.Themoviedb.org
2600:9000:20e9:4e00:c:174a:c400:93a1 api.Themoviedb.org
2600:9000:20e9:6800:c:174a:c400:93a1 api.Themoviedb.org
2600:9000:20e9:7200:c:174a:c400:93a1 api.Themoviedb.org
2600:9000:20e9:8800:c:174a:c400:93a1 api.Themoviedb.org
2600:9000:20e9:b400:c:174a:c400:93a1 api.Themoviedb.org
2600:9000:20e9:c000:c:174a:c400:93a1 api.Themoviedb.org
2600:9000:20e9:d200:c:174a:c400:93a1 api.Themoviedb.org
185.199.108.133 raw.githubusercontent.com
185.199.109.133 raw.githubusercontent.com
185.199.110.133 raw.githubusercontent.com
185.199.111.133 raw.githubusercontent.com
172.67.148.83 tracker.hdchina.org
104.25.26.31 u2.dmhy.org
104.25.26.31 tracker.dmhy.org
104.25.26.31 share.dmhy.org
45.35.17.203 kp.m-team.cc
104.26.13.50 tracker.m-team.cc
104.27.133.85 tracker.keepfrds.com
104.27.133.85 keepfrds.com
13.224.161.90 api.themoviedb.org
104.16.61.155 image.themoviedb.org
13.35.67.86 api.themoviedb.org
54.192.151.79 www.themoviedb.org
13.225.89.239 api.thetvdb.com
13.249.175.212 api.thetvdb.com
13.35.161.120 api.thetvdb.com
13.226.238.76 api.themoviedb.org
13.35.7.102 api.themoviedb.org
13.225.103.26 api.themoviedb.org
13.226.191.85 api.themoviedb.org
13.225.103.110 api.themoviedb.org
52.85.79.89 api.themoviedb.org
13.225.41.40 api.themoviedb.org
13.226.251.88 api.themoviedb.org
54.230.15.71 api.themoviedb.org
54.230.15.76 api.themoviedb.org
54.230.15.90 api.themoviedb.org
54.230.15.119 api.themoviedb.org

**Comment by huang-shaohua** [comment]
> 路由器dns代理加上：
> 54.230.15.71 api.Themoviedb.org
> 54.230.15.76 api.Themoviedb.org
> 54.230.15.90 api.Themoviedb.org
> 54.230.15.119 api.Themoviedb.org
> 104.25.27.31 u2.dmhy.org
> 104.25.26.31 u2.dmhy.org
> 104.25.27.31 tracker.dmhy.org
> 104.25.26.31 tracker.dmhy.org
> 13.226.238.76 api.themoviedb.org
> 13.224.161.90 api.themoviedb.org
> 13.35.7.102 api.themoviedb.org
> 13.225.103.26 api.themoviedb.org
> 13.226.191.85 api.themoviedb.org
> 13.225.103.110 api.themoviedb.org
> 52.85.79.89 api.themoviedb.org
> 13.225.41.40 api.themoviedb.org
> 13.226.251.88 api.themoviedb.org
> 65.9.85.74 api.themoviedb.org
> 65.9.85.19 api.themoviedb.org
> 65.9.85.127 api.themoviedb.org
> 65.9.85.118 api.themoviedb.org
> 13.225.89.239 api.thetvdb.com
> 13.249.175.212 api.thetvdb.com
> 13.35.161.120 api.thetvdb.com
> 2606:4700:20::6819:1b1f u2.dmhy.org
> 2606:4700:20::6819:1a1f u2.dmhy.org
> 2606:4700:20::6819:1b1f tracker.dmhy.org
> 2606:4700:20::6819:1a1f tracker.dmhy.org
> 2600:9000:20e9:800:c:174a:c400:93a1 api.Themoviedb.org
> 2600:9000:20e9:4e00:c:174a:c400:93a1 api.Themoviedb.org
> 2600:9000:20e9:6800:c:174a:c400:93a1 api.Themoviedb.org
> 2600:9000:20e9:7200:c:174a:c400:93a1 api.Themoviedb.org
> 2600:9000:20e9:8800:c:174a:c400:93a1 api.Themoviedb.org
> 2600:9000:20e9:b400:c:174a:c400:93a1 api.Themoviedb.org
> 2600:9000:20e9:c000:c:174a:c400:93a1 api.Themoviedb.org
> 2600:9000:20e9:d200:c:174a:c400:93a1 api.Themoviedb.org
> 185.199.108.133 raw.githubusercontent.com
> 185.199.109.133 raw.githubusercontent.com
> 185.199.110.133 raw.githubusercontent.com
> 185.199.111.133 raw.githubusercontent.com
> 172.67.148.83 tracker.hdchina.org
> 104.25.26.31 u2.dmhy.org
> 104.25.26.31 tracker.dmhy.org
> 104.25.26.31 share.dmhy.org
> 45.35.17.203 kp.m-team.cc
> 104.26.13.50 tracker.m-team.cc
> 104.27.133.85 tracker.keepfrds.com
> 104.27.133.85 keepfrds.com
> 13.224.161.90 api.themoviedb.org
> 104.16.61.155 image.themoviedb.org
> 13.35.67.86 api.themoviedb.org
> 54.192.151.79 [www.themoviedb.org](http://www.themoviedb.org)
> 13.225.89.239 api.thetvdb.com
> 13.249.175.212 api.thetvdb.com
> 13.35.161.120 api.thetvdb.com
> 13.226.238.76 api.themoviedb.org
> 13.35.7.102 api.themoviedb.org
> 13.225.103.26 api.themoviedb.org
> 13.226.191.85 api.themoviedb.org
> 13.225.103.110 api.themoviedb.org
> 52.85.79.89 api.themoviedb.org
> 13.225.41.40 api.themoviedb.org
> 13.226.251.88 api.themoviedb.org
> 54.230.15.71 api.themoviedb.org
> 54.230.15.76 api.themoviedb.org
> 54.230.15.90 api.themoviedb.org
> 54.230.15.119 api.themoviedb.org
不好意思，大佬，本人算是小白一个，我是华硕的路由器，具体怎么设置，能不能指教一下，谢谢

**Comment by huang-shaohua** [comment]
具体如何操作，能不能指导下？

**Comment by pofey** [comment]
tmdb的问题还是自己解决吧，别在这问了，这是基础网络类目的问题

**Comment by guimeiwangliang** [comment]
换成api.tmdb.org
