### ISSUE TITLE
问题：下载中的电影，在我的订阅点击删除无效

### ISSUE THREAD

**Issue by phinleyfei** [pofey/movie_robot#96]
下载中的电影，在我的订阅点击删除无效，不会删除qb内的任务，是否可以改一下？

**Comment by Howardnm** [comment]
能删，可能你的机器出问题了

**Comment by pofey** [comment]
> 下载中的电影，在我的订阅点击删除无效，不会删除qb内的任务，是否可以改一下？

反馈问题，要先自证自己的假设是真实有效的。自证最好的方式，就是贴日志，无日志可贴，贴操作截图。不然你一句话，分析啥？
