### ISSUE TITLE
【需求】手动管理存量电影支持字幕转移

### ISSUE THREAD

**Issue by xmumeyu** [pofey/movie_robot#99]
今天尝试手动管理存量电影

三千多个电影，识别错误数量20个左右，电视剧63个，识别错误2个。准确性很高。

但是转移完之后，元数据得重新搜刮，等了不少时间，换了一次IP才全部处理完

重点是，之前文件夹里的外挂字幕全部没带过来。这些字幕需要花不少时间去搜集回来，当前可能我需要分析转移日志写程序去恢复字幕了。

在此经验基础上提两点建议：

1、转移时顺道**把元数据和字幕文件一并带上**
2、转移后，电影**自动加入已订阅列表**，**状态为已完成**，方便后续洗版

希望肝帝能考虑一下此需求，感谢！

**Comment by pofey** [comment]
1、确实历史原因，不容易，我列入wiki中的开发计划，但暂时先不排期，有几件大事要搞。
2、订阅的核心意义我目前认为更多还是对订阅中和洗版中的状态观察，这不是存量洗版的入口，存量洗版，会有独立的页面，针对媒体库已有的影片进行精细洗版操作。

**Comment by xmumeyu** [comment]
ok，那我继续提下个需求。

**Comment by pofey** [comment]
这个事情短期还是先不做了，处理起来比想象的要复杂
